version: 2

build:
  os: "ubuntu-22.04"
  python:
    version: "3.8"

dependencies:
  override:
    - python -m pip install -r docs/requirements.txt
    - python -m pip install .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
