# ruff: noqa: E501, F401
"""Active-learning Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

ACTIVELEARNING_PLAN = Prerequisite(
    "activelearning-plan",
    "A train-fitted ActiveLearningPlan is attached to the Session.",
    check_hint="Session.activelearning_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_active_learner",
        OperationKind.MODEL,
        "Fit / initialize an active learner on labeled train rows only.",
        "Train a supervised classifier on currently labeled train rows; freeze pool + budget contract.",
        "Active-learning fit step.",
        (
            "Require a SplitPlan and a target role.",
            "Treat target NaNs (default) as the unlabeled train pool.",
            "Fit a base classifier on labeled train rows only.",
            "Never use validation/test as the query pool.",
            "Disclose that labels come from the user (no oracle in core).",
        ),
        parameters=(
            _p(
                "strategy",
                "least_confidence | margin | entropy | committee | expected_model_change_lite | "
                "core_set | qbc_kl | qbc_variation_ratios | bald | mc_dropout",
                "Default query strategy for suggest_query.",
                "margin",
            ),
            _p(
                "backend",
                "sklearn | industry | torch | None",
                "Query backend; None infers from strategy / installed extras.",
                None,
            ),
            _p(
                "base_estimator",
                "logistic_regression | hist_gradient_boosting",
                "Supervised classifier family.",
                "logistic_regression",
            ),
            _p("columns", "list[str] | None", "Optional explicit numeric columns."),
            _p("random_state", "int | None", "RNG seed where applicable.", 0),
            _p("batch_size", "int", "Default suggest_query batch size.", 5),
            _p(
                "label_budget",
                "int | None",
                "Cap on labels acquired via label_rows (None = unlimited).",
                50,
            ),
            _p(
                "unlabeled_marker",
                "Any | None",
                "Extra unlabeled sentinel; default None uses NaN missingness.",
            ),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer Session.reduce_dimensions component columns when available.",
                True,
            ),
            _p("committee_size", "int", "Bagging committee size for QBC.", 5),
            _p(
                "auto_refit",
                "bool",
                "Default refit behavior after label_rows.",
                True,
            ),
        ),
        inputs=("Split Session with numeric features and a partially labeled train target.",),
        outputs=("ActiveLearningFitResult; ActiveLearningPlan stored on the Session.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split and usually after impute/scale; blank some train targets first.",),
        alternatives=(
            "Session.fit_semisupervised when you want propagation without an oracle loop.",
            "Session.fit when the train set is already fully labeled.",
        ),
        rationale=(
            "Use when annotation budget is limited and a human can label suggested rows.",
        ),
        assumptions=(
            "At least two labeled train rows spanning ≥2 classes.",
            "Features are numeric and non-null.",
        ),
        failures=(
            "Missing split/target, <2 labeled rows, single class, null features, unknown strategy.",
        ),
        leakage=(
            "Using validation/test as the query pool.",
            "Fitting before split contaminates holdout metrics.",
        ),
        anti_patterns=(
            "Inventing oracle labels inside library core.",
            "Treating active learning as semi-supervised propagation.",
        ),
        state_changes=(
            "Stores activelearning_plan and fit result; clears prior query/label/eval slots.",
        ),
        result_reading=(
            "Read n_labeled_train, n_unlabeled_pool, strategy, label_budget, disclosures.",
        ),
        next_steps=(
            "suggest_query → label_rows → evaluate_active_learning; optionally save_active_learning_bundle.",
        ),
        concepts=(
            "activelearning-train-pool",
            "activelearning-human-labels",
            "activelearning-uncertainty",
            "leakage-boundary",
        ),
    ),
    _operation(
        "suggest_query",
        OperationKind.DIAGNOSTIC,
        "Suggest unlabeled train-pool indices for human labeling (no oracle).",
        "Rank the train pool by uncertainty / committee disagreement; return a batch.",
        "Active-learning query step.",
        (
            "Require an attached ActiveLearningPlan.",
            "Score only unlabeled train rows.",
            "Honor remaining label_budget.",
            "Return indices + scores; do not invent labels.",
        ),
        parameters=(
            _p("batch_size", "int | None", "Override default batch size from the plan."),
            _p(
                "strategy",
                "least_confidence | margin | entropy | committee | expected_model_change_lite | "
                "core_set | qbc_kl | qbc_variation_ratios | bald | mc_dropout | None",
                "Optional strategy override for this round.",
            ),
        ),
        inputs=("Active ActiveLearningPlan with a non-empty train pool (usually).",),
        outputs=("ActiveLearningQueryResult with indices and scores.",),
        prerequisites=(DATASET, ACTIVELEARNING_PLAN),
        ordering=("After fit_active_learner or load_active_learning_bundle.",),
        alternatives=("Random train sampling is not exposed — use uncertainty strategies.",),
        rationale=("Use to spend the annotation budget on informative train rows.",),
        assumptions=("Plan estimator supports the chosen strategy.",),
        failures=("No plan; committee strategy without committee_; budget exhausted.",),
        leakage=("Querying validation/test rows.",),
        anti_patterns=("Treating suggested indices as already-labeled truths.",),
        state_changes=("Stores activelearning_query_result.",),
        result_reading=("Read indices, scores, budget_remaining, disclosures.",),
        next_steps=("label_rows with human-provided labels for those indices.",),
        concepts=(
            "activelearning-train-pool",
            "activelearning-uncertainty",
            "activelearning-human-labels",
        ),
    ),
    _operation(
        "label_rows",
        OperationKind.TRANSFORM,
        "Incorporate user-provided labels on train-pool rows; optionally refit.",
        "Write human labels onto Session targets; enforce budget; refit by default.",
        "Active-learning label incorporation step.",
        (
            "Validate indices are train-pool (refuse validation/test).",
            "Enforce label_budget.",
            "Write labels onto the Session target role.",
            "Optionally refit the active learner on the expanded labeled set.",
        ),
        parameters=(
            _p("indices", "list | tuple", "Dataset indices to label.", required=True),
            _p("labels", "list | tuple", "User-provided labels aligned to indices.", required=True),
            _p(
                "refit",
                "bool | None",
                "Refit after labeling; None uses plan auto_refit (default True).",
            ),
        ),
        inputs=("Active ActiveLearningPlan and concrete user labels.",),
        outputs=("ActiveLearningLabelResult; mutated dataset targets; updated plan.",),
        prerequisites=(DATASET, ACTIVELEARNING_PLAN),
        ordering=("After suggest_query (typical) or with any valid train-pool indices.",),
        alternatives=("Manually editing the frame then calling fit_active_learner.",),
        rationale=("Use to close the human-in-the-loop labeling loop.",),
        assumptions=("Labels are real user values, not library-invented.",),
        failures=("Budget exceeded; null labels; validation/test indices.",),
        leakage=("Labeling holdout rows to improve reported scores.",),
        anti_patterns=("Silent oracle that fills labels from hidden test truths in core.",),
        state_changes=(
            "Updates dataset targets, activelearning_plan, label result; may update fit result.",
        ),
        result_reading=(
            "Read n_newly_labeled, n_labeled_now, n_queries_used, budget_remaining, refit.",
        ),
        next_steps=("suggest_query again, or evaluate_active_learning on labeled holdout.",),
        concepts=(
            "activelearning-human-labels",
            "activelearning-train-pool",
            "leakage-boundary",
        ),
    ),
    _operation(
        "evaluate_active_learning",
        OperationKind.DIAGNOSTIC,
        "Evaluate the active learner on labeled partition rows only.",
        "Score accuracy/F1 on ground-truth labels; disclose unlabeled holdout rows.",
        "Active-learning evaluation step.",
        (
            "Predict with the frozen/refitted learner.",
            "Exclude unlabeled rows from metrics.",
            "Report accuracy / macro and weighted F1 with query-budget disclosures.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation falls back to test if absent).",
                "validation",
            ),
            _p(
                "unlabeled_marker",
                "Any | None",
                "Optional unlabeled sentinel override for eval missingness.",
            ),
        ),
        inputs=("Active ActiveLearningPlan and a partition with some labeled targets.",),
        outputs=("ActiveLearningEvalResult.",),
        prerequisites=(DATASET, ACTIVELEARNING_PLAN),
        ordering=("After fit_active_learner / label_rows.",),
        alternatives=("Classical Session.evaluate when using a fully supervised FitResult.",),
        rationale=("Use to quantify holdout quality as the labeling budget is spent.",),
        assumptions=("Holdout has labeled rows for the metrics you care about.",),
        failures=("No plan; no labeled eval rows (empty metrics with warning).",),
        leakage=("Using unlabeled holdout rows as invented truths for selection.",),
        anti_patterns=("Reporting train accuracy after each query as holdout performance.",),
        state_changes=("Stores activelearning_eval_result.",),
        result_reading=(
            "Read n_labeled_eval, n_unlabeled_eval, n_queries_used, metrics, disclosures.",
        ),
        next_steps=("save_active_learning_bundle; or continue suggest_query / label_rows.",),
        concepts=(
            "activelearning-train-pool",
            "activelearning-human-labels",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "save_active_learning_bundle",
        OperationKind.PERSIST,
        "Persist the active ActiveLearningPlan as buildml.activelearning_bundle.v1.",
        "Write a domain bundle distinct from Session checkpoints.",
        "Active-learning bundle save.",
        ("Require an attached plan.", "Write meta.json + activelearning_plan.joblib."),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active ActiveLearningPlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(ACTIVELEARNING_PLAN,),
        ordering=("After a successful fit_active_learner / labeling round.",),
        alternatives=("Session.checkpoint_save for workflow resume without the learner.",),
        rationale=("Use when the learner + labeling ledger must travel separately from data.",),
        assumptions=("Destination is writable.",),
        failures=("No plan attached.",),
        leakage=("Bundles do not embed a fake oracle.",),
        anti_patterns=("Assuming a Session checkpoint embeds the ActiveLearningPlan.",),
        state_changes=("History records save_active_learning_bundle.",),
        result_reading=("Confirm meta.json format buildml.activelearning_bundle.v1.",),
        next_steps=("load_active_learning_bundle in another Session.",),
        concepts=("activelearning-bundle-boundary",),
    ),
    _operation(
        "load_active_learning_bundle",
        OperationKind.PERSIST,
        "Load a buildml.activelearning_bundle.v1 ActiveLearningPlan into the Session.",
        "Restore a train-fitted active learner + query history without refitting.",
        "Active-learning bundle load.",
        ("Validate bundle format.", "Attach ActiveLearningPlan; clear fit/query/label/eval slots."),
        parameters=(_p("path", "str | Path", "Bundle directory.", required=True),),
        inputs=("Bundle directory with meta.json + activelearning_plan.joblib.",),
        outputs=("Session with activelearning_plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest/roles/split aligned with the plan feature contract.",),
        alternatives=("fit_active_learner to learn a new plan.",),
        rationale=("Use to resume a human-in-the-loop labeling ledger.",),
        assumptions=("Feature columns and target role still match the plan contract.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Do not treat load as permission to query holdout rows.",),
        anti_patterns=("Loading into a Session whose features drifted from the plan.",),
        state_changes=("Sets activelearning_plan; clears fit/query/label/eval result slots.",),
        result_reading=("Inspect Session.activelearning_plan.to_dict().",),
        next_steps=("suggest_query / label_rows / evaluate_active_learning.",),
        concepts=("activelearning-bundle-boundary",),
    ),
)
