# ruff: noqa: E501, F401
"""AI operator Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    AI,
    AI_PROVIDER,
    DASHBOARD,
    DATASET,
    FIT,
    FIT_TORCH,
    RAG,
    RAG_CORPUS,
    RAG_INDEX,
    ROLES,
    SPLIT,
    TORCH,
    VIZ,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "ai_configure",
        OperationKind.CONFIGURE,
        "Configure an AI provider for LLM-assisted workflow guidance.",
        "Establish provider, model, and egress settings for AI operations.",
        "AI operator configuration entry point.",
        (
            "Create ProviderConfig from arguments and environment.",
            "Initialize provider (OpenAI-compatible or MockProvider).",
            "Set default egress level and transcript store.",
        ),
        parameters=(
            _p("provider", "str", "Provider name (openai, mock).", "openai"),
            _p("model", "str", "Model identifier.", "gpt-4o-mini"),
            _p("api_key", "str | None", "API key (reads from env if None)."),
            _p("api_key_env", "str", "Environment variable for API key.", "BUILDML_OPENAI_API_KEY"),
            _p("egress_level", "str", "Default egress: schema_only, stats_only (default), redacted_sample, full_sample.", "stats_only"),
            _p("max_iterations", "int", "Maximum tool iterations per call.", 10),
        ),
        inputs=("Provider configuration and optional API key from environment.",),
        outputs=("Session with configured AI provider and transcript store.",),
        prerequisites=(AI,),
        ordering=("Before any other ai_* methods.",),
        alternatives=("Use buildml.ai directly for standalone operation without Session.",),
        rationale=("BYO API key model keeps BuildML free of embedded secrets.",),
        assumptions=("API key is valid; provider endpoint is reachable.",),
        failures=("Missing API key, invalid provider name, or network unavailable.",),
        leakage=(
            "API keys must not be logged, persisted in transcripts, or echoed in errors.",
            "Provider sees whatever egress payload the user approves.",
        ),
        anti_patterns=(
            "Hardcoding API keys in code rather than environment variables.",
            "Using full_sample egress without reviewing what data leaves the machine.",
        ),
        state_changes=("Stores provider, egress config, and transcript; dataset unchanged.",),
        result_reading=("Confirm provider is configured via Session history or metadata.",),
        next_steps=("ai_egress_preview to verify data boundaries; ai_advisor for guidance.",),
        concepts=("ai-egress-privacy", "ai-tool-trust", "ai-prompt-injection"),
    ),
    _operation(
        "ai_egress_preview",
        OperationKind.INSPECT,
        "Preview what data will leave the machine before an LLM call.",
        "Show columns, row counts, and estimated tokens that would be sent to the provider.",
        "AI egress verification (read-only).",
        (
            "Build egress payload at the configured level.",
            "Apply column allow/deny lists.",
            "Return EgressManifest without calling the provider.",
        ),
        parameters=(
            _p("level", "str | None", "Override egress level for this preview."),
            _p("allow_columns", "sequence | None", "Explicit column allowlist."),
            _p("deny_columns", "sequence | None", "Explicit column denylist."),
        ),
        inputs=("Current dataset and egress configuration.",),
        outputs=("EgressManifest showing what would be sent.",),
        ordering=("After ai_configure; before ai_advisor or ai_plan.",),
        alternatives=("ai_dry_run for full prompt payload preview.",),
        rationale=("User must be able to verify data boundaries before any egress.",),
        assumptions=("Dataset is attached; egress config is initialized.",),
        failures=("No dataset returns an empty manifest with a warning.",),
        leakage=(
            "Preview does not send data; actual egress happens in ai_advisor/ai_plan.",
            "STATS_ONLY sends aggregates, not raw row values.",
            "FULL_SAMPLE sends raw rows and requires explicit opt-in.",
        ),
        anti_patterns=("Skipping preview when working with sensitive data.",),
        state_changes=("No state changes (read-only).",),
        result_reading=("Inspect columns_sent, columns_denied, rows_sent, and warnings.",),
        next_steps=("Adjust allow/deny columns if needed; proceed with ai_advisor.",),
        concepts=("ai-egress-privacy", "leakage-boundary"),
    ),
    _operation(
        "ai_dry_run",
        OperationKind.INSPECT,
        "Preview the full prompt payload without calling the provider.",
        "Return system prompt, user message, tools, and egress manifest.",
        "AI prompt inspection (read-only).",
        (
            "Build advisor context with current Session state.",
            "Apply egress configuration and column filters.",
            "Return payload without making an API call.",
        ),
        parameters=(
            _p("question", "str", "The question or goal to preview.", required=True),
            _p("level", "str | None", "Override egress level for this preview."),
        ),
        inputs=("Question text and current Session state.",),
        outputs=("Dict with messages, tools, egress_manifest, and state_digest.",),
        ordering=("After ai_configure; before ai_advisor for verification.",),
        alternatives=("ai_egress_preview for data-only manifest.",),
        rationale=("Users should see exactly what will be sent before any API call.",),
        assumptions=("Provider is configured; dataset may or may not be attached.",),
        failures=("None; always returns a payload dict.",),
        leakage=(
            "Dry run does not send data; inspect the payload locally.",
            "State digest includes column names which may be sensitive.",
        ),
        anti_patterns=("Sending FULL_SAMPLE without dry-run inspection first.",),
        state_changes=("No state changes (read-only).",),
        result_reading=("Review messages content, tool definitions, and egress manifest.",),
        next_steps=("Proceed with ai_advisor or ai_plan if payload is acceptable.",),
        concepts=("ai-egress-privacy", "ai-prompt-injection"),
    ),
    _operation(
        "ai_advisor",
        OperationKind.INSPECT,
        "Get advisory Q&A guidance about the current workflow (read-only).",
        "Describe data, explain operations, and suggest next steps without executing changes.",
        "AI advisory Q&A (read-only).",
        (
            "Build conversation context from Session state.",
            "Call provider with read-only tools.",
            "Return evidence-bound advice without state changes.",
        ),
        parameters=(
            _p("question", "str", "The question to ask about the workflow.", required=True),
            _p("level", "str | None", "Override egress level for this call."),
        ),
        inputs=("Question text, Session state, and configured provider.",),
        outputs=("AdvisorResult with answer, evidence, recommendations, and limitations.",),
        prerequisites=(AI_PROVIDER, AI),
        ordering=("After ai_configure; before ai_execute for state changes.",),
        alternatives=("explain for catalog-only operation info; ai_plan for structured planning.",),
        rationale=("Advisory Q&A provides evidence-bound guidance without side effects.",),
        assumptions=("Provider is configured and reachable; egress level is acceptable.",),
        failures=("No provider configured, API errors, or max iterations exceeded.",),
        leakage=(
            "STATS_ONLY egress sends aggregates and schema, not raw rows.",
            "Advisor cannot bypass Session leakage guards.",
            "AI advice is not infallible; verify recommendations before acting.",
        ),
        anti_patterns=(
            "Treating AI suggestions as authoritative without evidence review.",
            "Using FULL_SAMPLE egress for routine questions.",
        ),
        state_changes=("Stores ai_result and updates transcript; dataset unchanged.",),
        result_reading=("Inspect answer, evidence, recommendations, and limitations.",),
        next_steps=("Verify advice against Session state; use ai_execute for confirmed changes.",),
        concepts=("ai-egress-privacy", "ai-tool-trust", "ai-prompt-injection"),
    ),
    _operation(
        "ai_plan",
        OperationKind.INSPECT,
        "Generate a structured workflow plan for a goal (read-only).",
        "Return steps, prerequisites, and expected changes based on current state.",
        "AI structured planning (read-only).",
        (
            "Build state digest from Session.",
            "Request structured plan from provider.",
            "Parse steps with operations, rationale, and prerequisites.",
        ),
        parameters=(
            _p("goal", "str", "The workflow goal to plan for.", required=True),
            _p("level", "str | None", "Override egress level for this call."),
        ),
        inputs=("Goal text, Session state, and configured provider.",),
        outputs=("PlanResult with steps, assumptions, limitations, and alternatives.",),
        prerequisites=(AI_PROVIDER, AI),
        ordering=("After ai_configure; use to structure multi-step work before execution.",),
        alternatives=("ai_advisor for Q&A; workflow for catalog-based status.",),
        rationale=("Structured plans help organize complex workflows with clear prerequisites.",),
        assumptions=("Provider is configured; goal is achievable given current state.",),
        failures=("No provider, invalid response format, or max iterations exceeded.",),
        leakage=(
            "Plan generation sends state summary, not raw data (at STATS_ONLY level).",
            "Plans are AI-generated suggestions, not guaranteed correct sequences.",
        ),
        anti_patterns=(
            "Executing all plan steps without reviewing each operation.",
            "Treating plan as authoritative without checking Session prerequisites.",
        ),
        state_changes=("Stores ai_result and updates transcript; dataset unchanged.",),
        result_reading=("Review each step's operation, rationale, prerequisites, and warnings.",),
        next_steps=("Use ai_execute for individual steps with confirmation.",),
        concepts=("ai-egress-privacy", "ai-tool-trust"),
    ),
    _operation(
        "ai_execute",
        OperationKind.MODEL,
        "Execute a single tool with propose-confirm-execute flow.",
        "Propose tool execution and require explicit confirmation for write operations.",
        "AI confirmed tool execution.",
        (
            "Validate tool is in allowed registry.",
            "Create ExecutorProposal with expected changes.",
            "Execute only if confirmed (or auto-confirm for read-only).",
        ),
        parameters=(
            _p("tool", "str", "Name of the tool to execute.", required=True),
            _p("params", "dict | None", "Tool arguments as a dictionary."),
            _p("confirm", "bool", "If True, confirms and executes.", False),
        ),
        inputs=("Tool name, arguments, and confirmation status.",),
        outputs=("ExecutorProposal (if not confirmed) or ExecutorResult (if confirmed).",),
        prerequisites=(AI_PROVIDER, AI),
        ordering=("After ai_advisor or ai_plan; use for individual confirmed operations.",),
        alternatives=("Call Session methods directly for immediate execution.",),
        rationale=("Propose-confirm-execute prevents accidental state changes from AI suggestions.",),
        assumptions=("Tool is in the allowed registry; Session state supports the operation.",),
        failures=("Tool not in registry, confirmation refused, or operation errors.",),
        leakage=(
            "Executor calls real Session methods which enforce leakage guards.",
            "Destructive operations always require explicit confirmation.",
            "AI cannot bypass confirmation requirements for write operations.",
        ),
        anti_patterns=(
            "Auto-confirming destructive operations without review.",
            "Bypassing the tool registry with direct eval/exec.",
        ),
        state_changes=("Executes Session method if confirmed; updates transcript.",),
        result_reading=("Check confirmed, executed, result_summary, and error fields.",),
        next_steps=("Review state changes; continue with next planned operation.",),
        concepts=("ai-tool-trust", "ai-prompt-injection", "leakage-boundary"),
    ),
    _operation(
        "save_ai_transcript",
        OperationKind.PERSIST,
        "Save the AI transcript to a JSON file with secrets redacted.",
        "Record conversation history, tool calls, and egress manifests for audit.",
        "AI transcript persistence.",
        (
            "Collect all transcript entries.",
            "Redact API keys and potential secrets.",
            "Write JSON to destination path.",
        ),
        parameters=(
            _p("path", "str | Path", "Output file path.", required=True),
            _p("redact", "bool", "Redact potential secrets before saving.", True),
        ),
        inputs=("Active transcript store and destination path.",),
        outputs=("Resolved output Path.",),
        ordering=("After ai_advisor/ai_plan/ai_execute; at session boundaries.",),
        alternatives=("Inspect transcript entries directly for debugging.",),
        rationale=("Transcripts enable audit without persisting sensitive keys or data.",),
        assumptions=("Transcript store exists; destination is writable.",),
        failures=("Unwritable path or empty transcript.",),
        leakage=(
            "Redaction removes API key patterns but cannot guarantee all secrets removed.",
            "Transcripts record egress manifests, not raw data (unless FULL_SAMPLE).",
            "Transcript schema is buildml.ai_transcript.v1, distinct from checkpoints.",
        ),
        anti_patterns=(
            "Saving transcripts without redaction in shared environments.",
            "Treating transcript as a Session checkpoint (use checkpoint_save for data).",
        ),
        state_changes=("Writes file and appends to history; transcript content unchanged.",),
        result_reading=("Verify the returned path exists and schema_id is correct.",),
        next_steps=("load_ai_transcript in a new session for resume or audit.",),
        concepts=("ai-egress-privacy", "reproducibility"),
    ),
    _operation(
        "load_ai_transcript",
        OperationKind.PERSIST,
        "Load an AI transcript for resume or audit.",
        "Restore conversation history without restoring provider or data state.",
        "AI transcript restoration.",
        (
            "Read JSON from path.",
            "Validate schema buildml.ai_transcript.v1.",
            "Attach TranscriptStore to Session.",
        ),
        parameters=(
            _p("path", "str | Path", "Input file path.", required=True),
        ),
        inputs=("Trusted transcript file path.",),
        outputs=("Session with restored ai_transcript.",),
        prerequisites=(AI,),
        ordering=("Before ai_advisor/ai_execute to continue a prior conversation.",),
        alternatives=("Start fresh with ai_configure for a new conversation.",),
        rationale=("Resume or audit prior AI conversations without re-running operations.",),
        assumptions=("File is trusted and schema-compatible.",),
        failures=("Wrong schema (checkpoint/bundle), corrupt file, or missing path.",),
        leakage=(
            "Transcripts may reference column names from prior sessions.",
            "Load does not restore provider config or dataset; call ai_configure separately.",
        ),
        anti_patterns=(
            "Loading transcripts from untrusted sources.",
            "Expecting load_ai_transcript to restore dataset or fit state.",
        ),
        state_changes=("Replaces ai_transcript; provider and dataset unchanged.",),
        result_reading=("Inspect transcript.entries for prior conversation context.",),
        next_steps=("ai_configure if provider needed; ai_advisor to continue.",),
        concepts=("ai-egress-privacy", "reproducibility"),
    ),
    _operation(
        "ai_run_plan",
        OperationKind.MODEL,
        "Execute a multi-step plan with confirmation gating.",
        "Run plan steps sequentially, pausing for confirmation on write operations.",
        "AI multi-step execution.",
        (
            "Retrieve plan from prior ai_plan or argument.",
            "Map each step to a tool in the registry.",
            "Execute steps with confirmation gating; stop on error or unconfirmed.",
        ),
        parameters=(
            _p("plan", "PlanResult | None", "Plan to execute (uses last ai_plan if None)."),
            _p("confirmations", "dict[int, bool] | None", "Per-step confirmation overrides."),
            _p("auto_confirm_read_only", "bool", "Auto-confirm read-only steps.", True),
            _p("stop_on_error", "bool", "Stop execution on first error.", True),
            _p("stop_on_unconfirmed", "bool", "Stop at unconfirmed write steps.", True),
            _p("max_steps", "int | None", "Maximum steps to execute."),
        ),
        inputs=("PlanResult from ai_plan and optional confirmation overrides.",),
        outputs=("PlanExecutionResult with per-step execution details.",),
        prerequisites=(AI_PROVIDER, AI),
        ordering=("After ai_plan; use to execute approved multi-step workflows.",),
        alternatives=("ai_execute for single-step execution.",),
        rationale=("Multi-step execution with confirmation gates prevents runaway AI actions.",),
        assumptions=("Plan steps map to tools in the registry; prerequisites are met.",),
        failures=("Step not in registry, unconfirmed write operation, or execution error.",),
        leakage=(
            "Executes real Session methods which enforce leakage guards.",
            "Write operations pause for confirmation; destructive operations always require confirm.",
            "Max steps limit prevents runaway loops.",
        ),
        anti_patterns=(
            "Confirming all steps without reviewing each operation.",
            "Ignoring stop_reason when execution halts.",
        ),
        state_changes=("Executes confirmed plan steps; updates transcript and history.",),
        result_reading=("Check completed_steps, stopped_at_step, and per-step results.",),
        next_steps=("Review results; resume with confirmations if stopped early.",),
        concepts=("ai-tool-trust", "ai-egress-privacy"),
    ),
    _operation(
        "ai_run_autonomous",
        OperationKind.MODEL,
        "Explicit autonomy mode: plan-and-execute allowlisted tools under hard caps.",
        "Opt-in operator automation with max steps, allowlist, blocked sample egress, and audit.",
        "AI autonomy boundary (not default).",
        (
            "Require confirm_autonomy=True explicit opt-in.",
            "Refuse sample/raw egress levels.",
            "Plan (optional) then auto-confirm only allowlisted non-destructive tools.",
            "Record every step in the transcript with residual-risk disclosures.",
        ),
        parameters=(
            _p("goal", "str", "Operator goal string.", required=True),
            _p("plan", "PlanResult | None", "Optional precomputed plan."),
            _p("confirm_autonomy", "bool", "Required True opt-in (default False refuses).", False),
            _p("max_steps", "int", "Hard step cap.", 8),
            _p("tool_allowlist", "Sequence[str] | None", "Subset of registry tools to permit."),
            _p("allow_destructive", "bool", "Permit destructive tools (default False).", False),
            _p("provider_plan", "bool", "Call planner when plan is omitted.", True),
        ),
        inputs=("Configured AI provider (or an explicit PlanResult) and Session state.",),
        outputs=("AutonomyResult with step audit, disclosures, limitations, residual_risks.",),
        prerequisites=(AI_PROVIDER, AI),
        ordering=("After ai_configure; alternative to per-step ai_run_plan confirmations.",),
        alternatives=("ai_run_plan with explicit confirmations (default safer path).",),
        rationale=(
            "Use only when an operator intentionally wants allowlisted automation with audit."
        ,),
        assumptions=("Allowlist is tight; workspace is not production-irreplaceable.",),
        failures=("confirm_autonomy missing, sample egress configured, or empty allowlist.",),
        leakage=(
            "Auto-confirmed write tools still mutate Session state; review transcripts.",
            "Injection filters are best-effort: not a formal sandbox.",
        ),
        anti_patterns=(
            "Treating autonomy as unconstrained agency or production autopilot.",
            "Widening the allowlist to include destructive tools without review.",
        ),
        state_changes=("Executes allowlisted steps; stores ai_autonomy_result and transcript entries.",),
        result_reading=("Read completed_steps, stop_reason, residual_risks, and step audit.",),
        next_steps=("save_ai_transcript; tighten allowlist; prefer confirm path for prod.",),
        concepts=("ai-tool-trust", "ai-egress-privacy"),
    ),
    _operation(
        "ai_status",
        OperationKind.INSPECT,
        "Get AI operator status including provider, egress, budget, and autonomy.",
        "Return factual walkthrough disclosure about current AI configuration.",
        "AI status inspection (read-only).",
        (
            "Gather provider, egress, budget, and transcript state.",
            "Include registry tools, max_iterations, and autonomy last-run fragment.",
            "Disclose residual autonomy risks without claiming production safety.",
        ),
        parameters=(),
        inputs=("Current Session AI configuration.",),
        outputs=("Dict with provider, egress, budget, registry, and autonomy info.",),
        ordering=("After ai_configure; anytime for status check.",),
        alternatives=("walkthrough for full workflow status including AI.",),
        rationale=("Transparent disclosure of AI operator state and limits.",),
        assumptions=("AI provider may or may not be configured.",),
        failures=("None; returns status even without provider configured.",),
        leakage=(
            "Status discloses egress level and budget, not API keys.",
            "Registry tools listed are the allowed tools, not all possible tools.",
        ),
        anti_patterns=("Treating ai_status as proof of production readiness.",),
        state_changes=("No state changes (read-only).",),
        result_reading=("Inspect enabled, provider, egress, budget, autonomy, and registry_tools.",),
        next_steps=("ai_configure if not enabled; ai_advisor for guidance.",),
        concepts=("ai-egress-privacy", "ai-tool-trust"),
    ),
)
