# ruff: noqa: E501, F401
"""Anomaly / fraud Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

ANOMALY_PLAN = Prerequisite(
    "anomaly-plan",
    "A train-fitted AnomalyPlan is attached to the Session.",
    check_hint="Session.anomaly_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_anomaly",
        OperationKind.MODEL,
        "Fit an anomaly / fraud detector on the train partition and store an AnomalyPlan.",
        "Learn a leakage-safe scorer with disclosed threshold and alert-rate policy.",
        "Anomaly detection fit step.",
        (
            "Require a SplitPlan and refuse fit without train.",
            "Resolve numeric columns; prefer ReducePlan component columns when present.",
            "Fit isolation_forest, lof, one_class_svm, PyOD, torch AE, or supervised scorers per mode.",
            "Calibrate a disclosed threshold; record train alert rate and score stats.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | pyod | torch",
                "Detector backend (see anomaly_capability_matrix).",
                None,
            ),
            _p(
                "method",
                "catalog method for backend or supervised scorer",
                "Detector / scorer algorithm.",
                "isolation_forest",
            ),
            _p(
                "mode",
                "unsupervised | novelty | supervised",
                "Fit regime (all-train, normal-only, or labeled binary).",
                "unsupervised",
            ),
            _p("columns", "list[str] | None", "Optional explicit numeric columns."),
            _p("random_state", "int | None", "RNG seed where applicable.", 0),
            _p("contamination", "float", "Prior alert fraction / IF-LOF contamination.", 0.05),
            _p(
                "threshold_policy",
                "contamination | quantile | score_threshold | decision_zero",
                "How the flag threshold is chosen.",
                "contamination",
            ),
            _p("score_threshold", "float | None", "Absolute threshold when policy requires it."),
            _p("quantile", "float | None", "Optional top-fraction for quantile policy."),
            _p("n_estimators", "int", "IsolationForest trees.", 100),
            _p("max_samples", "str | int | float", "IsolationForest max_samples.", "auto"),
            _p("n_neighbors", "int", "LOF neighborhood size.", 20),
            _p("nu", "float", "One-Class SVM nu.", 0.05),
            _p("kernel", "str", "One-Class SVM kernel.", "rbf"),
            _p("gamma", "str | float", "One-Class SVM gamma.", "scale"),
            _p(
                "normal_label_column",
                "str | None",
                "Novelty: column defining normal-only fit rows.",
            ),
            _p("normal_label_value", "Any", "Novelty: value treated as normal.", 0),
            _p("positive_label", "Any", "Positive / fraud class label for supervised & metrics.", 1),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer Session.reduce_dimensions component columns when available.",
                True,
            ),
            _p("flag_column", "str", "Column name used when attach=True.", "is_anomaly"),
            _p("score_column", "str", "Score column name when attach=True.", "anomaly_score"),
        ),
        inputs=("Split Session with numeric features (typically scaled; optionally PCA components).",),
        outputs=("AnomalyFitResult; AnomalyPlan stored on the Session.",),
        prerequisites=(DATASET, SPLIT),
        ordering=(
            "After split and usually after impute/scale; optional reduce_dimensions before anomaly fit.",
        ),
        alternatives=(
            "Use Session.fit for general supervised classification outside the anomaly product path.",
            "EDA IsolationForest screens remain descriptive: not this fit API.",
            "Session.handle_outliers is a preprocess fence path, not anomaly scoring.",
        ),
        rationale=(
            "Use when the goal is leakage-safe anomaly scoring with explicit thresholds/alert rates.",
        ),
        assumptions=(
            "Features are numeric and non-null; distance methods assume sensible scaling.",
            "Novelty mode has a trustworthy normal-only train subset.",
            "Supervised mode has a binary target role.",
        ),
        failures=(
            "Missing split, nulls, non-numeric columns, invalid contamination, novelty without normal labels, "
            "supervised without binary target.",
        ),
        leakage=(
            "Fitting on all rows before splitting contaminates holdout alert rates and ranking metrics.",
            "Using evaluation labels to refit unsupervised detectors breaks the holdout-score contract.",
        ),
        anti_patterns=(
            "Treating EDA IsolationForest anomaly_rate as a production AnomalyPlan.",
            "Equating ClusterPlan labels with anomaly flags.",
            "Claiming causal fraud attribution from scores.",
        ),
        state_changes=(
            "Stores anomaly_plan and anomaly_fit_result; clears prior score/eval slots.",
        ),
        result_reading=(
            "Read method, mode, threshold, threshold_policy, train_alert_rate, disclosures.",
        ),
        next_steps=("score_anomalies and/or evaluate_anomaly; optionally save_anomaly_bundle.",),
        concepts=(
            "anomaly-train-fit-holdout-score",
            "anomaly-threshold-alert-rate",
            "anomaly-novelty-vs-unsupervised",
            "anomaly-eda-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "score_anomalies",
        OperationKind.TRANSFORM,
        "Score and flag rows with a train-fitted AnomalyPlan (no refit).",
        "Apply frozen scores/threshold to a partition or the full frame.",
        "Anomaly score/flag step.",
        (
            "Require an attached AnomalyPlan.",
            "Compute higher-is-more-anomalous scores; flag score >= threshold.",
            "Optionally attach score/flag columns when partition='all'.",
        ),
        parameters=(
            _p("partition", "train | validation | test | all", "Rows to score.", "test"),
            _p(
                "attach",
                "bool",
                "Write score_column/flag_column onto the Session frame (requires partition='all').",
                False,
            ),
            _p(
                "override_threshold",
                "float | None",
                "Optional absolute threshold for this call only.",
            ),
        ),
        inputs=("Active AnomalyPlan and matching feature columns.",),
        outputs=("AnomalyScoreResult; optional mutated dataset when attach=True.",),
        prerequisites=(DATASET, ANOMALY_PLAN),
        ordering=("After fit_anomaly or load_anomaly_bundle.",),
        alternatives=("evaluate_anomaly when you need metrics rather than raw scores/flags.",),
        rationale=("Use to materialize scores and alert flags for inspection or export.",),
        assumptions=("Plan feature columns still exist; threshold disclosures are accepted.",),
        failures=("No plan, missing columns, attach=True with partition≠all, existing score/flag columns.",),
        leakage=("Refitting on the score partition would break the train-fit contract.",),
        anti_patterns=(
            "Hiding alert_rate when publishing flags.",
            "Mutating thresholds on test after peeking at labels without disclosure.",
        ),
        state_changes=("Stores anomaly_score_result; may add feature-role score/flag columns.",),
        result_reading=("Read n_flagged, alert_rate, threshold, score_stats, and disclosures.",),
        next_steps=("evaluate_anomaly; or use attached columns cautiously downstream.",),
        concepts=(
            "anomaly-train-fit-holdout-score",
            "anomaly-threshold-alert-rate",
            "leakage-boundary",
        ),
    ),
    _operation(
        "evaluate_anomaly",
        OperationKind.DIAGNOSTIC,
        "Evaluate train-fitted anomaly scores on a partition (alert rate + optional labeled metrics).",
        "Quantify operating point and ranking quality without claiming causal fraud.",
        "Anomaly evaluation step.",
        (
            "Score the requested partition with the frozen plan.",
            "Always report threshold and alert_rate.",
            "When labels exist, compute PR-AUC / ROC-AUC / precision/recall/F1 / @k with imbalance disclosures.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation falls back to test if absent).",
                "validation",
            ),
            _p(
                "label_column",
                "str | None",
                "Optional labels for ranking/classification metrics (defaults to target role).",
            ),
            _p("positive_label", "Any | None", "Positive / fraud class value.", None),
            _p("k", "int | None", "Budget for precision@k / recall@k (default ≈ positive_rate * n)."),
            _p("override_threshold", "float | None", "Optional absolute threshold for this eval only."),
        ),
        inputs=("Active AnomalyPlan and partition features (optional labels).",),
        outputs=("AnomalyEvalResult stored on the Session.",),
        prerequisites=(DATASET, ANOMALY_PLAN),
        ordering=("After fit_anomaly; prefer validation/test over train for claims.",),
        alternatives=("score_anomalies for scores/flags without labeled metrics.",),
        rationale=("Use to compare methods/thresholds under a leakage-safe scorer.",),
        assumptions=("When reporting labeled metrics, labels are honestly scoped.",),
        failures=("No plan, missing label column, null labels, empty validation without fallback.",),
        leakage=(
            "Evaluating on train only for selection overstates separation.",
            "Using labels derived from the same unsupervised fit as 'ground truth'.",
        ),
        anti_patterns=(
            "Publishing accuracy alone under rare fraud positives.",
            "Equating PR-AUC with causal fraud mechanism recovery.",
        ),
        state_changes=("Stores anomaly_eval_result.",),
        result_reading=(
            "Read alert_rate, threshold, labeled_metrics, positive_rate, disclosures, recommendations.",
        ),
        next_steps=("save_anomaly_bundle; or revise features/threshold and refit on train.",),
        concepts=(
            "anomaly-imbalance-metrics",
            "anomaly-threshold-alert-rate",
            "anomaly-train-fit-holdout-score",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "tune_anomaly_threshold",
        OperationKind.DIAGNOSTIC,
        "Choose the alert threshold that maximizes a labeled metric on a holdout partition.",
        "Turn a raw anomaly score into an operating point you can defend, using labels rather than a guessed contamination rate.",
        "Anomaly threshold selection step, between fit and evaluation.",
        (
            "Require an active AnomalyPlan and a label column.",
            "Score the tuning partition with the frozen plan (no refit).",
            "Sweep candidate thresholds and pick the one that maximizes the requested metric.",
            "Refuse Session test unless allow_test_tuning is explicitly set.",
            "Optionally write the chosen threshold back onto the plan.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test",
                "Tuning partition; validation is the honest default.",
                "validation",
            ),
            _p(
                "label_column",
                "str | None",
                "Labels used for tuning; defaults to the target role.",
                None,
            ),
            _p("positive_label", "Any | None", "Positive / anomaly class value.", None),
            _p(
                "metric",
                "f1 | fbeta | precision | recall | youden",
                "Objective maximized over candidate thresholds.",
                "f1",
            ),
            _p("fbeta", "float", "Beta for metric='fbeta'; above 1 favours recall.", 2.0),
            _p(
                "allow_test_tuning",
                "bool",
                "Dangerous opt-in to tune on Session test.",
                False,
            ),
            _p(
                "update_plan",
                "bool",
                "Write the chosen threshold back onto the active plan.",
                True,
            ),
        ),
        inputs=("Active AnomalyPlan plus labeled rows from the tuning partition.",),
        outputs=("AnomalyThresholdTuneResult with the chosen threshold and its metric curve.",),
        prerequisites=(DATASET, SPLIT, ANOMALY_PLAN),
        ordering=("After fit_anomaly; before evaluate_anomaly on test.",),
        alternatives=(
            "Setting threshold_policy at fit time when no labels exist to tune against.",
        ),
        rationale=(
            "A contamination guess is a prior, not a decision; when labels exist the operating point should be chosen against them.",
        ),
        assumptions=(
            "Tuning labels are honestly scoped and reflect the deployment cost balance.",
        ),
        failures=(
            "No plan; missing or null labels; a single label class in the partition.",
        ),
        leakage=(
            "Tuning on test contaminates the final estimate, which is why it requires allow_test_tuning.",
        ),
        anti_patterns=(
            "Tuning on test and then reporting test performance.",
            "Maximizing F1 when the real cost of a missed anomaly is far higher than a false alert.",
        ),
        state_changes=(
            "Stores the tuning result and, when update_plan is true, the plan's threshold.",
        ),
        result_reading=(
            "Read the chosen threshold together with its alert rate, not the metric alone.",
            "Inspect the metric curve for a plateau: a sharp peak usually means the threshold is fitted to noise.",
        ),
        next_steps=("evaluate_anomaly on test; save_anomaly_bundle.",),
        concepts=(
            "anomaly-threshold-alert-rate",
            "anomaly-imbalance-metrics",
            "thresholds",
            "leakage-boundary",
        ),
    ),
    _operation(
        "save_anomaly_bundle",
        OperationKind.PERSIST,
        "Persist the active AnomalyPlan as buildml.anomaly_bundle.v1.",
        "Save a reloadable detector distinct from Session checkpoints.",
        "Anomaly artifact save.",
        (
            "Require an attached AnomalyPlan.",
            "Write meta.json and anomaly_plan.joblib with compatibility disclosures.",
        ),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active AnomalyPlan (optional fit/eval summaries in meta).",),
        outputs=("Bundle directory path.",),
        prerequisites=(ANOMALY_PLAN,),
        ordering=("After fit_anomaly (and usually after evaluate_anomaly).",),
        alternatives=("Keep working inside one Session without persistence.",),
        rationale=("Use when scoring must resume without replaying the full tabular Session.",),
        assumptions=("joblib can serialize the sklearn estimator.",),
        failures=("No plan; incomplete destination permissions.",),
        leakage=("Bundles do not include the dataset; they are not a substitute for careful split hygiene.",),
        anti_patterns=(
            "Expecting checkpoint_load to restore AnomalyPlan.",
            "Treating anomaly bundles as interchangeable with Torch/RAG/unsupervised bundles.",
        ),
        state_changes=("Records save path in history; does not clear the plan.",),
        result_reading=("Confirm meta.json format == buildml.anomaly_bundle.v1.",),
        next_steps=("load_anomaly_bundle on a fresh Session when needed.",),
        concepts=("anomaly-bundle-boundary", "anomaly-train-fit-holdout-score"),
    ),
    _operation(
        "load_anomaly_bundle",
        OperationKind.PERSIST,
        "Load a buildml.anomaly_bundle.v1 AnomalyPlan into the Session.",
        "Restore a frozen anomaly detector for score/evaluate.",
        "Anomaly artifact load.",
        (
            "Validate format string.",
            "Deserialize AnomalyPlan and attach to Session slots.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Anomaly bundle directory.",),
        outputs=("Session with anomaly_plan attached.",),
        prerequisites=(),
        ordering=("Before score_anomalies / evaluate_anomaly on a restored plan.",),
        alternatives=("Refit with fit_anomaly when the feature space changed.",),
        rationale=("Use to resume scoring without refitting the detector.",),
        assumptions=("Feature columns at score time still match the plan.",),
        failures=("Missing files, wrong format, corrupt joblib payload.",),
        leakage=("Loading does not recreate SplitPlan; attach data/splits separately for holdout claims.",),
        anti_patterns=("Loading a RAG/Torch/unsupervised bundle path into load_anomaly_bundle.",),
        state_changes=("Stores anomaly_plan; clears prior fit/score/eval result slots.",),
        result_reading=("Check method, mode, threshold, columns from plan.to_dict().",),
        next_steps=("score_anomalies or evaluate_anomaly once features are available.",),
        concepts=("anomaly-bundle-boundary", "anomaly-train-fit-holdout-score"),
    ),
)
