# ruff: noqa: E501, F401
"""Causal Session operation overlays (assumptions-required teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

CAUSAL_ASSUMPTIONS = Prerequisite(
    "causal-assumptions",
    "Validated CausalAssumptions are attached (or passed) before estimation.",
    check_hint="Session.causal_assumptions is not None (or assumptions= passed).",
)

CAUSAL_PLAN = Prerequisite(
    "causal-plan",
    "A train-fitted CausalPlan is attached to the Session.",
    check_hint="Session.causal_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "declare_causal_assumptions",
        OperationKind.MODEL,
        "Declare identification assumptions required for causal estimation.",
        "Record treatment, outcome, confounders, estimand, and acknowledgements.",
        "Causal assumptions declaration.",
        (
            "Require treatment, outcome, and confounders (or empty waiver).",
            "Require acknowledge_unconfoundedness and acknowledge_positivity.",
            "Refuse instruments until an IV path exists.",
            "Store CausalAssumptions on the Session; do not infer from EDA.",
        ),
        parameters=(
            _p("treatment", "str", "Treatment column name.", required=True),
            _p("outcome", "str", "Outcome column name.", required=True),
            _p(
                "confounders",
                "sequence[str] | None",
                "Backdoor adjustment set. None is incomplete (refused).",
                required=True,
            ),
            _p("estimand", "str", "Currently only ATE.", "ATE"),
            _p("identification", "str", "Currently only backdoor.", "backdoor"),
            _p(
                "instruments",
                "sequence[str] | None",
                "Reserved; non-empty is refused (no IV yet).",
            ),
            _p(
                "acknowledge_unconfoundedness",
                "bool",
                "Caller declares no unmeasured confounding given confounders.",
                False,
            ),
            _p(
                "acknowledge_positivity",
                "bool",
                "Caller declares overlap / positivity.",
                False,
            ),
            _p(
                "allow_empty_confounders",
                "bool",
                "Permit confounders=[] under a strong no-covariate assumption.",
                False,
            ),
        ),
        inputs=("Dataset columns and domain knowledge.",),
        outputs=("Validated CausalAssumptions on the Session.",),
        prerequisites=(DATASET, ROLES),
        ordering=("Before fit_causal.",),
        alternatives=("Pass assumptions= into fit_causal.",),
        rationale=(
            "Force an explicit identification contract before any effect estimate.",
        ),
        assumptions=("Caller understands unconfoundedness and positivity.",),
        failures=(
            "Missing treatment/outcome/confounders; acknowledgements false; instruments set.",
        ),
        leakage=("None: declaration does not touch holdout fitting.",),
        anti_patterns=(
            "Treating EDA correlation / MI / importance as identification.",
            "Skipping acknowledgements.",
        ),
        state_changes=("Stores Session.causal_assumptions.",),
        result_reading=("Inspect treatment, outcome, confounders, acknowledgements.",),
        next_steps=("fit_causal.",),
        concepts=(
            "causal-assumptions",
            "causal-eda-boundary",
            "causal-ate-backdoor",
        ),
    ),
    _operation(
        "fit_causal",
        OperationKind.MODEL,
        "Fit causal models and estimate backdoor ATE.",
        "Train-only native / DoWhy / EconML under CausalAssumptions.",
        "Causal fit step.",
        (
            "Require SplitPlan and validated CausalAssumptions.",
            "Route backend=native|dowhy|econml (industry extras optional).",
            "Fit outcome and/or propensity nuisances on train only (native).",
            "Estimate ATE; optional bootstrap CI (native/econml).",
            "Never use validation/test for nuisance fitting.",
            "Refuse incomplete assumptions; never read causality from EDA.",
        ),
        parameters=(
            _p(
                "backend",
                "native | dowhy | econml | None",
                "Estimation backend; None infers from method.",
                None,
            ),
            _p(
                "method",
                "t_learner | ipw | aipw | backdoor_* | dml | causal_forest | policy_tree",
                "Estimation strategy (default AIPW on native).",
                "aipw",
            ),
            _p(
                "assumptions",
                "CausalAssumptions | mapping | None",
                "Explicit assumptions; else Session.causal_assumptions.",
            ),
            _p(
                "bootstrap_samples",
                "int",
                "Train retrain bootstrap draws (0 disables).",
                200,
            ),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p(
                "clip_propensity",
                "tuple[float, float]",
                "Propensity clip bounds for IPW/AIPW.",
                (0.01, 0.99),
            ),
            _p("outcome_model", "str", "Outcome nuisance family.", "ridge"),
            _p(
                "propensity_model",
                "str",
                "Propensity nuisance family.",
                "logistic_regression",
            ),
        ),
        inputs=("Train partition + CausalAssumptions.",),
        outputs=("CausalPlan + CausalFitResult with ATE / CI.",),
        prerequisites=(DATASET, ROLES, SPLIT, CAUSAL_ASSUMPTIONS),
        ordering=("After declare_causal_assumptions and split.",),
        alternatives=("estimate_causal after a prior fit.",),
        rationale=(
            "Estimate ATE only after an explicit identification declaration.",
        ),
        assumptions=(
            "Declared backdoor set + unconfoundedness + positivity.",
            "Binary treatment; numeric or binary outcome.",
        ),
        failures=(
            "No assumptions; incomplete acknowledgements; degenerate treatment arms.",
        ),
        leakage=(
            "Fitting nuisances on validation/test: hard-refused by train-only fit.",
        ),
        anti_patterns=(
            "Fitting without acknowledgements.",
            "Calling this causal discovery.",
            "Treating DoWhy refutation as proof of identification.",
        ),
        state_changes=(
            "Stores causal_plan and fit result; clears estimate/eval/refute slots.",
        ),
        result_reading=(
            "Read ate, ate_ci_low/high, n_treated/n_control, disclosures.",
        ),
        next_steps=(
            "evaluate_causal; refute_causal; save_causal_bundle.",
        ),
        concepts=(
            "causal-assumptions",
            "causal-aipw",
            "causal-t-learner",
            "causal-ipw",
            "causal-dowhy",
            "causal-econml",
            "causal-ate-backdoor",
            "leakage-boundary",
        ),
    ),
    _operation(
        "estimate_causal",
        OperationKind.DIAGNOSTIC,
        "Estimate ATE on a partition with fitted train nuisances.",
        "Apply T-learner / IPW / AIPW scores out-of-sample or on train.",
        "Causal estimate step.",
        (
            "Require CausalPlan.",
            "Encode treatment with plan levels; score the partition.",
            "Optional fixed-nuisance bootstrap CI on the partition.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Rows to score.",
                "train",
            ),
            _p("bootstrap_samples", "int | None", "Override bootstrap draws."),
            _p("random_state", "int | None", "Bootstrap RNG."),
        ),
        inputs=("Active CausalPlan + partition rows.",),
        outputs=("CausalEstimateResult.",),
        prerequisites=(DATASET, CAUSAL_PLAN),
        ordering=("After fit_causal or load_causal_bundle.",),
        alternatives=("evaluate_causal for nuisance metrics too.",),
        rationale=("Re-score ATE without refitting nuisances.",),
        assumptions=("Treatment levels match the plan encoding.",),
        failures=("No plan; empty/single-arm partition; missing columns.",),
        leakage=("Do not refit nuisances on the scored holdout.",),
        anti_patterns=("Treating holdout ATE as proof of identification.",),
        state_changes=("Stores causal_estimate_result.",),
        result_reading=("Read ate / CI / n_treated / disclosures.",),
        next_steps=("evaluate_causal; save_causal_bundle.",),
        concepts=("causal-ate-backdoor", "causal-aipw"),
    ),
    _operation(
        "evaluate_causal",
        OperationKind.DIAGNOSTIC,
        "Holdout nuisance checks + ATE (not proof of identification).",
        "Report outcome/propensity predictive metrics and partition ATE.",
        "Causal evaluate step.",
        (
            "Require CausalPlan.",
            "Score holdout with train-fitted nuisances only.",
            "Disclose that metrics do not prove unconfoundedness.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation→test fallback).",
                "validation",
            ),
            _p("bootstrap_samples", "int | None", "Optional CI draws."),
        ),
        inputs=("CausalPlan + holdout partition.",),
        outputs=("CausalEvalResult with metrics and ATE.",),
        prerequisites=(DATASET, CAUSAL_PLAN),
        ordering=("After fit_causal.",),
        alternatives=("estimate_causal for ATE only.",),
        rationale=(
            "Check nuisance predictive quality and report partition ATE honestly.",
        ),
        assumptions=("Feature/treatment/outcome columns match the plan.",),
        failures=("No plan; empty partition; single treatment class.",),
        leakage=("Tuning clip bounds against locked test repeatedly without protocol.",),
        anti_patterns=(
            "Advertising evaluate_causal as assumption validation.",
            "Equating propensity AUC with true confounding control.",
        ),
        state_changes=("Stores causal_eval_result.",),
        result_reading=(
            "Read metrics (outcome_rmse/r2 or accuracy, propensity_auc/brier), "
            "ate, disclosures.",
        ),
        next_steps=("refute_causal; save_causal_bundle.",),
        concepts=(
            "causal-assumptions",
            "causal-eda-boundary",
            "causal-aipw",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "refute_causal",
        OperationKind.DIAGNOSTIC,
        "Simple placebo / random-confounder sensitivity disclosure.",
        "DoWhy refutation suite when backend='dowhy'.",
        "Causal refute step.",
        (
            "Require CausalPlan.",
            "Native: shuffle treatment or append noise covariate and refit.",
            "DoWhy: placebo, random common cause, unobserved confounder, "
            "data subset, placebo outcome refuters.",
            "Report ATE shift / p-values; disclose limits.",
        ),
        parameters=(
            _p(
                "kind",
                "placebo_treatment | random_confounder | random_common_cause | "
                "add_unobserved_common_cause | data_subset | placebo_outcome",
                "Sensitivity check kind (backend-dependent).",
                "placebo_treatment",
            ),
            _p("random_state", "int | None", "RNG seed.", 0),
        ),
        inputs=("Active CausalPlan + train partition.",),
        outputs=("CausalRefuteResult.",),
        prerequisites=(DATASET, CAUSAL_PLAN),
        ordering=("After fit_causal.",),
        alternatives=("Manual domain sensitivity analyses.",),
        rationale=("Surface fragile estimates with cheap sensitivity checks.",),
        assumptions=("Train partition still available and aligned.",),
        failures=("No plan; degenerate placebo arms.",),
        leakage=("Refutation refits on train only: never on holdout.",),
        anti_patterns=(
            "Calling this a complete DoWhy suite.",
            "Treating a near-zero placebo as proof of identification.",
        ),
        state_changes=("Stores causal_refute_result.",),
        result_reading=("Compare original_ate vs refute_ate and ate_shift.",),
        next_steps=("save_causal_bundle.",),
        concepts=("causal-assumptions", "causal-ate-backdoor"),
    ),
    _operation(
        "save_causal_bundle",
        OperationKind.PERSIST,
        "Persist the active CausalPlan as buildml.causal_bundle.v1.",
        "Write a domain bundle distinct from Session checkpoints.",
        "Causal bundle save.",
        ("Require an attached plan.", "Write meta.json + causal_plan.joblib."),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active CausalPlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(CAUSAL_PLAN,),
        ordering=("After a successful fit_causal.",),
        alternatives=("Session.checkpoint_save for workflow resume without the learner.",),
        rationale=("Use when assumptions + nuisances must travel separately.",),
        assumptions=("Destination is writable.",),
        failures=("No plan attached.",),
        leakage=("Bundles do not embed holdout rows.",),
        anti_patterns=("Assuming a Session checkpoint embeds the CausalPlan.",),
        state_changes=("History records save_causal_bundle.",),
        result_reading=("Confirm meta.json format buildml.causal_bundle.v1.",),
        next_steps=("load_causal_bundle in another Session.",),
        concepts=("causal-bundle-boundary",),
    ),
    _operation(
        "load_causal_bundle",
        OperationKind.PERSIST,
        "Load a buildml.causal_bundle.v1 CausalPlan into the Session.",
        "Restore a causal plan without re-fitting.",
        "Causal bundle load.",
        (
            "Validate bundle format.",
            "Attach CausalPlan and CausalAssumptions; clear result slots.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory with meta.json + causal_plan.joblib.",),
        outputs=("Session with causal_plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest/roles/split aligned with the plan contract.",),
        alternatives=("fit_causal to learn a new plan.",),
        rationale=("Use to resume an assumption-declared causal learner.",),
        assumptions=("Columns still match the plan contract.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Do not treat load as permission to train on holdout rows.",),
        anti_patterns=("Loading a probabilistic bundle as causal.",),
        state_changes=(
            "Sets causal_plan + causal_assumptions; clears fit/estimate/eval/refute slots.",
        ),
        result_reading=("Inspect Session.causal_plan.to_dict().",),
        next_steps=("evaluate_causal / estimate_causal.",),
        concepts=("causal-bundle-boundary", "causal-assumptions"),
    ),
)
