# ruff: noqa: E501, F401
"""Case-based reasoning Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

CBR_PLAN = Prerequisite(
    "cbr-plan",
    "A train-fitted CbrPlan (case memory) is attached to the Session.",
    check_hint="Session.cbr_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_cbr",
        OperationKind.MODEL,
        "Build a tabular case memory from Session train.",
        "Each train row becomes a case (features + solution); choose metric/reuse.",
        "CBR fit / case-base compile step.",
        (
            "Require SplitPlan.",
            "Store train rows as cases; never include validation/test.",
            "Fit distance transforms (scale / ranges / cat vocab) on train only.",
            "Disclose metric definition and reuse mode.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | industry | embedding | torch | None",
                "Retrieval backend; honest default when extras installed.",
                None,
            ),
            _p(
                "task",
                "classification | regression | None",
                "Task; inferred from target when omitted.",
            ),
            _p(
                "metric",
                "euclidean | manhattan | cosine | mixed",
                "Distance metric (mixed = Gower-style).",
                "euclidean",
            ),
            _p(
                "reuse",
                "majority | distance_weighted | local_mean | local_ridge",
                "How neighbor solutions become predictions.",
                "distance_weighted",
            ),
            _p(
                "adapt",
                "none | offset",
                "Optional lite post-reuse adaptation.",
                "none",
            ),
            _p("k", "int", "Number of neighbors.", 5),
            _p("columns", "list[str] | None", "Numeric feature columns."),
            _p(
                "text_columns",
                "list[str] | None",
                "Text columns for backend='embedding' (buildml[rag|ssl]).",
            ),
            _p(
                "text_model_name",
                "str",
                "Sentence-transformer model id for embedding backend.",
                "sentence-transformers/all-MiniLM-L6-v2",
            ),
            _p(
                "categorical_columns",
                "list[str] | None",
                "Optional categoricals for metric='mixed'.",
            ),
            _p(
                "standardize",
                "bool",
                "Z-score numeric features for non-mixed metrics.",
                True,
            ),
            _p("distance_eps", "float", "ε for inverse-distance weights.", 1e-8),
            _p("random_state", "int | None", "RNG seed (reserved / disclosures).", 0),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer reduce_dimensions components when present.",
                True,
            ),
        ),
        inputs=("Train partition features + target solutions.",),
        outputs=("CbrPlan + CbrFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split / preprocess; before retrieve/predict/evaluate.",),
        alternatives=("Classical fit() for parametric models; RAG for documents.",),
        rationale=(
            "Ship leakage-safe tabular CBR with explanation traces — not RAG.",
        ),
        assumptions=("Numeric features available after encode/scale when needed.",),
        failures=("No split; null features/targets; invalid reuse for task.",),
        leakage=("Train-only case memory; holdout never enters at fit.",),
        anti_patterns=(
            "Building case memory from the full frame before split.",
            "Calling this tabular RAG.",
        ),
        state_changes=("Stores cbr_plan; clears prior CBR eval/predict/retrieve.",),
        result_reading=("Inspect n_cases, metric, reuse, train_score disclosures.",),
        next_steps=("retrieve_cases; predict_cbr; evaluate_cbr; save_cbr_bundle.",),
        concepts=(
            "cbr-case-memory",
            "cbr-retrieve-reuse",
            "cbr-vs-rag",
            "cbr-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "retrieve_cases",
        OperationKind.MODEL,
        "Retrieve k nearest cases for query rows (no reuse).",
        "Score-only neighbor lookup against the train-built case memory.",
        "CBR retrieve step.",
        (
            "Require CbrPlan.",
            "Compute distances with train-fit metric/transforms.",
            "Return CaseTrace neighbors without applying reuse.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Query rows.",
                "test",
            ),
            _p("k", "int | None", "Override plan.k."),
            _p(
                "backend",
                "sklearn | industry | embedding | torch | None",
                "Override retrieval backend for this query.",
            ),
        ),
        inputs=("CbrPlan + query partition.",),
        outputs=("CbrRetrieveResult with CaseTrace neighbors.",),
        prerequisites=(DATASET, SPLIT, CBR_PLAN),
        ordering=("After fit_cbr.",),
        alternatives=("predict_cbr to also reuse solutions.",),
        rationale=("Inspect which cases are nearest before reuse.",),
        assumptions=("Query columns match the plan.",),
        failures=("No plan; missing columns.",),
        leakage=("Retrieval does not update case memory.",),
        anti_patterns=("Treating retrieve as a fit step.",),
        state_changes=("Stores cbr_retrieve_result.",),
        result_reading=("Inspect neighbor_case_ids and distances.",),
        next_steps=("predict_cbr; evaluate_cbr.",),
        concepts=("cbr-retrieve-reuse", "cbr-case-memory", "cbr-vs-rag"),
    ),
    _operation(
        "predict_cbr",
        OperationKind.MODEL,
        "Predict via retrieve + reuse with case-influence traces.",
        "Turn the nearest cases into a prediction you can trace back to specific remembered examples, without updating the case base.",
        "CBR predict step.",
        (
            "Require CbrPlan.",
            "Retrieve k neighbors; apply reuse/adapt.",
            "Return CaseTrace when return_traces=True.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Rows to score.",
                "test",
            ),
            _p("k", "int | None", "Override plan.k."),
            _p("return_traces", "bool", "Include CaseTrace per row.", True),
            _p(
                "backend",
                "sklearn | industry | embedding | torch | None",
                "Override retrieval backend for this predict call.",
            ),
        ),
        inputs=("CbrPlan + query partition.",),
        outputs=("CbrPredictResult.",),
        prerequisites=(DATASET, SPLIT, CBR_PLAN),
        ordering=("After fit_cbr.",),
        alternatives=("retrieve_cases for neighbors only.",),
        rationale=("Supervised-style scoring with case explanations.",),
        assumptions=("Reuse mode matches task.",),
        failures=("No plan; null query features.",),
        leakage=("Predict does not retain cases.",),
        anti_patterns=("Updating memory during predict.",),
        state_changes=("Stores cbr_predict_result.",),
        result_reading=("Inspect predictions and CaseTrace weights.",),
        next_steps=("evaluate_cbr; save_cbr_bundle.",),
        concepts=("cbr-retrieve-reuse", "cbr-case-memory", "leakage-boundary"),
    ),
    _operation(
        "evaluate_cbr",
        OperationKind.MODEL,
        "Holdout metrics for CBR predictions.",
        "Accuracy/RMSE etc.; no memory update.",
        "CBR evaluate step.",
        (
            "Require CbrPlan.",
            "Score holdout with predict_cbr.",
            "Report mean_neighbor_distance when traces exist.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation→test fallback).",
                "validation",
            ),
            _p("k", "int | None", "Override plan.k."),
        ),
        inputs=("CbrPlan + holdout labels.",),
        outputs=("CbrEvalResult.",),
        prerequisites=(DATASET, SPLIT, CBR_PLAN),
        ordering=("After fit_cbr.",),
        alternatives=("predict_cbr for traces without metrics.",),
        rationale=("Quantify holdout behavior without contaminating memory.",),
        assumptions=("Non-null holdout targets.",),
        failures=("No plan; null targets.",),
        leakage=("Holdout evaluation only.",),
        anti_patterns=("Treating train_score as holdout accuracy.",),
        state_changes=("Stores cbr_eval_result.",),
        result_reading=("Inspect metrics and mean_neighbor_distance.",),
        next_steps=("save_cbr_bundle.",),
        concepts=(
            "cbr-retrieve-reuse",
            "cbr-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "retain_cbr",
        OperationKind.MODEL,
        "Retain newly labeled cases into the case memory (leakage-safe).",
        "Refuses Session validation/test indices; requires source_disclosure.",
        "CBR retain step (lite).",
        (
            "Require CbrPlan.",
            "Accept labeled_frame or row_indices.",
            "Refuse any holdout label index.",
            "Reuse train-fit distance transforms (do not refit).",
        ),
        parameters=(
            _p(
                "labeled_frame",
                "DataFrame | None",
                "New labeled rows (features + solution).",
            ),
            _p(
                "row_indices",
                "sequence | None",
                "Dataset label indices to retain (alternative to frame).",
            ),
            _p(
                "solution_column",
                "str | None",
                "Solution column; default plan.target_column.",
            ),
            _p(
                "source_disclosure",
                "str",
                "Required provenance for new labels.",
                required=True,
            ),
            _p(
                "allow_overlap_with_train",
                "bool",
                "Allow indices that overlap train (still skip duplicates).",
                True,
            ),
        ),
        inputs=("CbrPlan + newly labeled rows with disclosure.",),
        outputs=("CbrRetainResult; updated CbrPlan.",),
        prerequisites=(DATASET, CBR_PLAN),
        ordering=("After fit_cbr; typically after external labeling.",),
        alternatives=("Refit with fit_cbr to rebuild memory from train.",),
        rationale=("Lite retain without holdout contamination.",),
        assumptions=("Labels are not from Session holdout.",),
        failures=("Holdout indices; missing disclosure; missing columns.",),
        leakage=("Validation/test indices are hard-refused.",),
        anti_patterns=(
            "Retaining test rows 'to improve accuracy'.",
            "Omitting source_disclosure.",
        ),
        state_changes=("Updates cbr_plan; clears eval/predict.",),
        result_reading=("Inspect n_added / n_skipped / disclosures.",),
        next_steps=("predict_cbr; evaluate_cbr; save_cbr_bundle.",),
        concepts=(
            "cbr-retrieve-reuse",
            "cbr-case-memory",
            "leakage-boundary",
        ),
    ),
    _operation(
        "save_cbr_bundle",
        OperationKind.MODEL,
        "Persist CbrPlan as buildml.cbr_bundle.v1.",
        "Write meta.json + cbr_plan.joblib.",
        "CBR bundle save.",
        (
            "Require an active CbrPlan.",
            "Do not embed the plan in Session checkpoints.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
        ),
        inputs=("Active plan (+ optional fit/eval summaries).",),
        outputs=("Bundle directory path.",),
        prerequisites=(DATASET,),
        ordering=("After fit_cbr.",),
        alternatives=("checkpoint_save for workflow state only.",),
        rationale=("Separate learner artifact from Session checkpoint.",),
        assumptions=("Writable path.",),
        failures=("No plan attached.",),
        leakage=("None — persistence only.",),
        anti_patterns=("Expecting checkpoint_load to restore the plan.",),
        state_changes=("History record only.",),
        result_reading=("Confirm meta.json format.",),
        next_steps=("load_cbr_bundle on a new Session.",),
        concepts=("cbr-bundle-boundary",),
    ),
    _operation(
        "load_cbr_bundle",
        OperationKind.MODEL,
        "Load a CBR bundle into this Session.",
        "Restore a train-built case memory from disk so scoring can resume without rebuilding it.",
        "CBR bundle load.",
        (
            "Validate buildml.cbr_bundle.v1.",
            "Attach plan; clear fit/eval/predict/retrieve/retain slots.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
        ),
        inputs=("Bundle directory.",),
        outputs=("Session with CbrPlan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest; usually after split for scoring.",),
        alternatives=("fit_cbr to create a new plan.",),
        rationale=("Reload the case memory without rebuilding from train.",),
        assumptions=("Bundle format matches.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Load does not fit; scoring still uses holdout only.",),
        anti_patterns=("Loading into a Session with mismatched columns silently.",),
        state_changes=("Stores cbr_plan.",),
        result_reading=("Inspect plan.metric / n_cases.",),
        next_steps=("predict_cbr / evaluate_cbr.",),
        concepts=("cbr-bundle-boundary", "leakage-boundary"),
    ),
)
