# ruff: noqa: E501, F401
"""Torch / deep-learning Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    AI,
    AI_PROVIDER,
    DASHBOARD,
    DATASET,
    FIT,
    FIT_TORCH,
    RAG,
    RAG_CORPUS,
    RAG_INDEX,
    ROLES,
    SPLIT,
    TORCH,
    VIZ,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "make_torch_loaders",
        OperationKind.MODEL,
        "Build Torch DataLoaders from Session feature/target roles and split partitions.",
        "Prepare batched tensors for supervised Torch training without inventing architectures.",
        "Tabular Torch data boundary.",
        (
            "Resolve feature and target roles.",
            "Materialize numeric arrays per partition.",
            "Fit optional train-only normalize stats and freeze them on validation/test.",
            "Construct DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("batch_size", "int", "Rows per batch.", 32),
            _p("num_workers", "int", "DataLoader worker processes.", 0),
            _p("pin_memory", "bool", "Pin host memory when useful for CUDA transfers.", False),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("drop_last", "bool", "Drop the last incomplete train batch.", False),
            _p("normalize", "bool", "Fit mean/std on train and apply frozen stats elsewhere.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
            _p("task", "classification | regression | auto", "Task interpretation for labels.", "auto"),
            _p("apply_plans", "bool", "Re-apply fitted classical plans before building tensors.", False),
        ),
        inputs=("Dataset with roles, SplitPlan, and optional prior classical prep on the frame.",),
        outputs=("TorchLoaderBundle stored on the Session plus a LoaderReport summary.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split (and optional classical prep); before fit_torch.",),
        alternatives=(
            "make_text_torch_loaders for token/sequence classification.",
            "Build tensors yourself and inject only if you accept leaving the Session path.",
        ),
        rationale=("Use when moving from partition frames to batched Torch training.",),
        assumptions=("Features and targets are numeric; non-numeric columns were encoded or dropped earlier.",),
        failures=("Missing Torch extra, empty train, non-numeric columns, or NaNs in the design matrix.",),
        leakage=(
            "Fitting normalize on all rows, or shuffling validation/test into train batches, leaks evaluation signal.",
            "Ignoring group/time SplitPlan membership when building tensors outside make_torch_loaders.",
        ),
        anti_patterns=(
            "Treating loader construction as permission to skip a declared split.",
            "Expecting Polars/DuckDB zero-copy into DataLoaders in this slice.",
        ),
        state_changes=("Stores torch loaders on the Session and appends loader metadata to history.",),
        result_reading=(
            "Check n_train/n_validation/n_test, split_kind, groups_disjoint/time_order_ok, "
            "normalize flag, classical plan disclosures, and warnings for empty holdout partitions.",
        ),
        next_steps=(
            "Call fit_torch (built-in MLP when module omitted), cross_validate_torch, "
            "or nested_cv_torch / search_torch for hyperparameter selection.",
        ),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "make_text_torch_loaders",
        OperationKind.MODEL,
        "Build token-id DataLoaders for text classification (sequence modality).",
        "Fit a train-only vocabulary and pad token sequences for embedding classifiers.",
        "Text / sequence Torch data boundary.",
        (
            "Resolve a text feature column and target.",
            "Fit vocabulary on the train partition only.",
            "Encode padded token ids per partition with shuffle on train only.",
        ),
        parameters=(
            _p("text_column", "str | None", "Text feature column (inferred when unique)."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
        ),
        inputs=("Dataset with a string feature column, numeric target ids, and a SplitPlan.",),
        outputs=("TorchLoaderBundle with text_vocab / text_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch with a text classifier.",),
        alternatives=(
            "make_torch_loaders for numeric tabular tensors.",
            "make_multimodal_torch_loaders / make_image_multimodal_torch_loaders / "
            "make_audio_multimodal_torch_loaders when text must fuse with other modalities.",
        ),
        rationale=("Use when the modeling path is text/sequence rather than pure numeric tables.",),
        assumptions=("Target labels are integer class ids; vocabulary must not see validation/test text.",),
        failures=("Missing Torch extra, no text column, empty train, or non-numeric target.",),
        leakage=("Fitting vocabulary on all rows leaks holdout token identity into the model.",),
        anti_patterns=("Treating hashing RAG embeddings as a substitute for this supervised text path.",),
        state_changes=("Stores text Torch loaders on the Session.",),
        result_reading=("Check vocab size, max_len, partition sizes, and train-only vocab disclosure.",),
        next_steps=("fit_torch() without module to build the embedding text classifier.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_multimodal_torch_loaders",
        OperationKind.MODEL,
        "Build fused multimodal DataLoaders (tabular/text/image/audio) with train-only fit stats.",
        "Materialize (*modalities, y) batches for late-fusion training.",
        "Multimodal Torch data boundary (tabular ⊕ text ⊕ image ⊕ audio).",
        (
            "Resolve numeric, text, image, and/or audio feature columns (at least two modalities).",
            "Fit vocabulary on train text only when text is present.",
            "Fit numeric normalize stats on train only when enabled.",
            "Fit image channel mean/std on train only when image normalize is enabled.",
            "Fit audio amplitude mean/std on train only when audio normalize is enabled.",
            "Build per-partition DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("text_column", "str | None", "Text feature column (inferred when unique)."),
            _p("numeric_columns", "list[str] | None", "Numeric feature columns (default: numeric roles)."),
            _p("image_column", "str | None", "Image path or array feature column."),
            _p("audio_column", "str | None", "Audio path or waveform array feature column."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("normalize", "bool", "Fit numeric mean/std on train.", True),
            _p("normalize_images", "bool", "Fit image channel mean/std on train.", True),
            _p("normalize_audio", "bool", "Fit audio amplitude mean/std on train.", True),
            _p("image_size", "tuple[int, int]", "Resize height/width for image tensors.", (32, 32)),
            _p("image_channels", "int", "1 or 3 image channels.", 3),
            _p("audio_sample_rate", "int", "Target sample rate for audio tensors.", 16000),
            _p("audio_max_samples", "int", "Fixed waveform length (pad/truncate).", 16000),
            _p("audio_source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed.", 0),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
        ),
        inputs=(
            "Dataset with a valid modality mix (any two+ of tabular/text/image/audio), "
            "target, and SplitPlan.",
        ),
        outputs=("TorchLoaderBundle with multimodal_contract / text_vocab / modality metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch fusion auto-build.",),
        alternatives=(
            "make_image_multimodal_torch_loaders when an image column is required up front.",
            "make_audio_multimodal_torch_loaders when an audio column is required up front.",
            "make_torch_loaders or make_text_torch_loaders for single-modality paths.",
        ),
        rationale=("Use when modalities should share one supervised fusion head.",),
        assumptions=(
            "Text is string-like; numeric columns are numeric; image/audio cells are paths or "
            "arrays; target is encoded.",
        ),
        failures=(
            "Missing Torch extra, invalid modality mix, empty train, non-numeric target, "
            "missing Pillow for path images, or missing soundfile for path audio.",
        ),
        leakage=(
            "Fitting vocab, numeric normalize, image channel stats, or audio amplitude stats "
            "on all rows leaks holdout signal into fusion.",
        ),
        anti_patterns=(
            "Claiming Whisper-scale speech foundation-model quality from the small 1D-CNN branch.",
            "Fitting media normalize stats on the full frame outside make_multimodal_torch_loaders.",
        ),
        state_changes=("Stores multimodal Torch loaders on the Session.",),
        result_reading=(
            "Check modality, input_layout, vocab size, numeric columns, image_column, "
            "audio_column, and train-only disclosures.",
        ),
        next_steps=("fit_torch() without module to build MultimodalFusion.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_image_multimodal_torch_loaders",
        OperationKind.MODEL,
        "Build image multimodal DataLoaders (image ⊕ tabular and/or text and/or audio).",
        "Require an image column and materialize fused batches with train-only image stats.",
        "Image multimodal Torch data boundary.",
        (
            "Require image_column (path or array cells).",
            "Optionally resolve text, numeric, and audio companions.",
            "Fit image channel mean/std on train only when enabled.",
            "Fit text vocab / numeric / audio normalize on train only when present.",
            "Build per-partition DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("image_column", "str", "Image path or array feature column (required)."),
            _p("text_column", "str | None", "Optional text feature column."),
            _p("numeric_columns", "list[str] | None", "Numeric feature columns (default: numeric roles)."),
            _p("audio_column", "str | None", "Optional audio path or waveform feature column."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row when text is present.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("normalize", "bool", "Fit numeric mean/std on train.", True),
            _p("normalize_images", "bool", "Fit image channel mean/std on train.", True),
            _p("normalize_audio", "bool", "Fit audio amplitude mean/std on train.", True),
            _p("image_size", "tuple[int, int]", "Resize height/width for image tensors.", (32, 32)),
            _p("image_channels", "int", "1 or 3 image channels.", 3),
            _p("audio_sample_rate", "int", "Target sample rate for audio tensors.", 16000),
            _p("audio_max_samples", "int", "Fixed waveform length (pad/truncate).", 16000),
            _p("audio_source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed.", 0),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
        ),
        inputs=(
            "Dataset with an image feature plus tabular and/or text and/or audio, target, "
            "and SplitPlan.",
        ),
        outputs=("TorchLoaderBundle with image multimodal_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch fusion auto-build.",),
        alternatives=(
            "make_multimodal_torch_loaders with image_column= for the same path.",
            "make_audio_multimodal_torch_loaders when audio is the required media column.",
        ),
        rationale=("Use when images must fuse with tabular and/or text and/or audio under one head.",),
        assumptions=("Image cells are paths (Pillow) or arrays; companions and target are valid.",),
        failures=("Missing image_column, invalid mix, empty train, or missing Torch/Pillow.",),
        leakage=("Fitting image channel stats on holdout rows leaks evaluation signal.",),
        anti_patterns=("Treating the small CNN branch as a production vision foundation model.",),
        state_changes=("Stores image multimodal Torch loaders on the Session.",),
        result_reading=("Check modality, image_column, image_mean/std, and input_layout.",),
        next_steps=("fit_torch() without module to build the image-capable MultimodalFusion.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_audio_multimodal_torch_loaders",
        OperationKind.MODEL,
        "Build audio multimodal DataLoaders (audio ⊕ tabular and/or text and/or image).",
        "Require an audio column and materialize fused batches with train-only audio stats.",
        "Audio multimodal Torch data boundary.",
        (
            "Require audio_column (path or waveform array cells).",
            "Optionally resolve text, numeric, and image companions.",
            "Fit audio amplitude mean/std on train only when enabled.",
            "Fit text vocab / numeric / image normalize on train only when present.",
            "Build per-partition DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("audio_column", "str", "Audio path or waveform array feature column (required)."),
            _p("text_column", "str | None", "Optional text feature column."),
            _p("numeric_columns", "list[str] | None", "Numeric feature columns (default: numeric roles)."),
            _p("image_column", "str | None", "Optional image path or array feature column."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row when text is present.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("normalize", "bool", "Fit numeric mean/std on train.", True),
            _p("normalize_images", "bool", "Fit image channel mean/std on train.", True),
            _p("normalize_audio", "bool", "Fit audio amplitude mean/std on train.", True),
            _p("image_size", "tuple[int, int]", "Resize height/width for image tensors.", (32, 32)),
            _p("image_channels", "int", "1 or 3 image channels.", 3),
            _p("audio_sample_rate", "int", "Target sample rate for audio tensors.", 16000),
            _p("audio_max_samples", "int", "Fixed waveform length (pad/truncate).", 16000),
            _p("audio_source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed.", 0),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
        ),
        inputs=(
            "Dataset with an audio feature plus tabular and/or text and/or image, target, "
            "and SplitPlan.",
        ),
        outputs=("TorchLoaderBundle with audio multimodal_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch fusion auto-build.",),
        alternatives=(
            "make_multimodal_torch_loaders with audio_column= for the same path.",
            "make_image_multimodal_torch_loaders when image is the required media column.",
        ),
        rationale=("Use when waveforms must fuse with tabular and/or text and/or image under one head.",),
        assumptions=(
            "Audio cells are paths (soundfile) or waveforms; companions and target are valid.",
        ),
        failures=(
            "Missing audio_column, invalid mix, empty train, or missing Torch/soundfile.",
        ),
        leakage=("Fitting audio amplitude stats on holdout rows leaks evaluation signal.",),
        anti_patterns=(
            "Claiming Whisper-scale ASR / speech foundation-model quality from this alpha path.",
        ),
        state_changes=("Stores audio multimodal Torch loaders on the Session.",),
        result_reading=("Check modality, audio_column, audio_mean/std, and input_layout.",),
        next_steps=("fit_torch() without module to build the audio-capable MultimodalFusion.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "fit_torch",
        OperationKind.MODEL,
        "Train a Torch nn.Module (built-in MLP/text/multimodal including image/audio when omitted).",
        "Run a leakage-scoped supervised epoch loop and store a Torch TrainResult.",
        "Torch supervised training boundary.",
        (
            "Require or build Torch loaders.",
            "When module is omitted, build tabular MLP, text classifier, or multimodal fusion "
            "(tabular/text/image/audio mixes).",
            "Resolve device with explicit CPU fallback when CUDA/MPS are unavailable.",
            "Run epoch steps with optional AMP, validation loss, scheduler, grad clip, early stopping.",
            "When resume=True, restore optimizer/scheduler state from dl_train_result and append history.",
        ),
        parameters=(
            _p("module", "torch.nn.Module | None", "Optional network; built-in zoo when omitted."),
            _p("loss_fn", "callable | None", "Optional (module, xb, yb) -> loss."),
            _p("optimizer_factory", "callable | None", "Optional params -> optimizer factory."),
            _p("epochs", "int", "Epochs when config omitted; additional epochs if resume=True.", 5),
            _p("learning_rate", "float", "Adam learning rate when config is omitted.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("grad_clip_norm", "float | None", "Optional gradient-norm clip (default None=off)."),
            _p("log_every", "int", "Record history every N epochs.", 1),
            _p(
                "early_stopping_patience",
                "int | None",
                "Stop after N non-improving validation epochs (default None=off).",
            ),
            _p("early_stopping_monitor", "str", "Metric key for early stop (default val_loss).", "val_loss"),
            _p(
                "scheduler",
                "none | step | plateau | cosine",
                "LR schedule (default none).",
                "none",
            ),
            _p("resume", "bool", "Continue from dl_train_result / loaded bundle.", False),
            _p("config", "TrainConfig | None", "Optional full train config overriding scalar knobs."),
            _p("hidden", "tuple[int, ...]", "Hidden widths for built-in tabular MLP when module omitted.", (64, 32)),
            _p("dropout", "float", "Dropout for built-in models when module omitted.", 0.1),
            _p("mixed_precision", "bool", "Enable CUDA AMP when True (CPU/MPS no-op).", False),
        ),
        inputs=("TorchLoaderBundle, nn.Module, and optional loss/optimizer factories.",),
        outputs=("Session with dl_train_result (TrainResult) distinct from classical fit_result.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_torch_loaders (auto-built if missing); before evaluate_torch / save_torch_bundle.",),
        alternatives=("Use Session.fit for sklearn estimators; do not mix result slots silently.",),
        rationale=("Choose Torch when the model is an nn.Module rather than a sklearn estimator.",),
        assumptions=("Train loader rows match the intended supervised task and feature contract.",),
        failures=(
            "Missing Torch extra, empty train loader, early stop without validation, "
            "shape mismatches, or optimizer/loss errors.",
        ),
        leakage=("Training without a split, or using test batches inside the train loop, invalidates holdout claims.",),
        anti_patterns=(
            "Reporting train loss as expected production performance.",
            "Tuning stopping rules on the test partition (see early-stopping-partition).",
        ),
        state_changes=("Stores dl_train_result; classical fit_result is unchanged.",),
        result_reading=(
            "Inspect device.resolved, early_stop reason/partition, scheduler_name, "
            "training_curve disclosures, and epoch history.",
        ),
        next_steps=(
            "torch_training_curve for structured teaching data; evaluate_torch on validation or test; "
            "save_torch_bundle for weights; cross_validate_torch for fold-local estimates.",
        ),
        concepts=(
            "leakage-boundary",
            "batch-leakage",
            "early-stopping-partition",
            "training-curves",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "cross_validate_torch",
        OperationKind.DIAGNOSTIC,
        "Fold-local Torch cross-validation on numeric tabular features.",
        "Train a fresh module per fold with train-only normalize stats.",
        "Torch fold-local CV boundary.",
        (
            "Split indices into folds (optionally stratified).",
            "Fit normalize stats on each fold's train indices only.",
            "Train a fresh module (default tabular MLP) and score the held-out fold.",
            "Aggregate mean/std metrics with explicit nested-CV limitations.",
        ),
        parameters=(
            _p("n_folds", "int", "Number of folds.", 3),
            _p("epochs", "int", "Epochs per fold.", 3),
            _p("batch_size", "int", "Batch size.", 32),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Per-fold train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p(
                "module_factory",
                "callable | None",
                "Optional (n_features, task, n_classes) -> fresh nn.Module per fold.",
            ),
        ),
        inputs=("Dataset with numeric features and a target (split optional; CV makes its own folds).",),
        outputs=("TorchCVResult with per-fold and mean metrics plus limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles (and optional classical prep); beside fit_torch for a single split.",),
        alternatives=(
            "Classical Session.cross_validate for sklearn estimators.",
            "nested_cv_torch when inner hyperparameter search is required.",
        ),
        rationale=("Use when you need fold-local Torch estimates without an inner search loop.",),
        assumptions=("Features/targets are numeric; module_factory builds a fresh module each fold.",),
        failures=("Missing Torch extra, too few rows for n_folds, or non-numeric design matrix.",),
        leakage=(
            "Fitting normalize or vocab on all rows before folding leaks holdout signal.",
            "Refitting Session-global classical plans outside fold-local apply_session_plans.",
        ),
        anti_patterns=(
            "Calling this nested CV when no inner hyperparameter loop ran.",
            "Reporting mean fold accuracy as production readiness without holdout.",
        ),
        state_changes=("Stores dl_cv_result; does not replace dl_train_result.",),
        result_reading=("Read mean_metrics, limitations (not nested), and per-fold warnings.",),
        next_steps=(
            "nested_cv_torch for nested search; fit_torch on a declared split for the final trainer.",
        ),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "search_torch",
        OperationKind.DIAGNOSTIC,
        "Inner-fold Torch hyperparameter search on the Session train universe.",
        "Rank MLP knobs with fold-local normalize; never score Session test rows.",
        "Torch inner search boundary.",
        (
            "Resolve train universe (respect Session split when present).",
            "Expand grid or sample distributions.",
            "Score each trial with fold-local train-only normalize.",
            "Return ranked trials with limitations (not nested outer estimate).",
        ),
        parameters=(
            _p("param_grid", "dict | None", "Grid of searchable knobs (lr/hidden/dropout/…)."),
            _p("param_distributions", "dict | None", "Distributions for randomized search."),
            _p("inner_search", "grid | randomized | auto", "Search method.", "auto"),
            _p("n_iter", "int", "Randomized trial count.", 5),
            _p("n_folds", "int", "Inner folds.", 3),
            _p("epochs", "int", "Epochs per trial fold.", 2),
            _p("batch_size", "int", "Default batch size.", 32),
            _p("learning_rate", "float", "Default Adam LR.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Per-fold train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p("scoring_metric", "str | None", "Rank metric (default accuracy or mse)."),
            _p("module_factory", "callable | None", "(n_features, task, n_classes, params) -> module."),
        ),
        inputs=("Dataset with numeric features/target; optional SplitPlan.",),
        outputs=("TorchSearchResult with ranked trials, best_params, limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles/split; before nested_cv_torch or final fit_torch.",),
        alternatives=("nested_cv_torch for outer generalization after search.",),
        rationale=("Use to pick Torch knobs without peeking at Session test.",),
        assumptions=("Search space covers tabular MLP knobs unless module_factory overrides.",),
        failures=("Missing search space, missing Torch, or non-numeric target.",),
        leakage=("Scoring trials on Session test/validation would invalidate holdout claims.",),
        anti_patterns=("Treating search_torch ranks as a nested outer estimate.",),
        state_changes=("Stores dl_search_result.",),
        result_reading=("Read best_params, limitations, and held_out_partitions.",),
        next_steps=("nested_cv_torch for honest outer estimate; fit_torch with chosen knobs.",),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "nested_cv_torch",
        OperationKind.DIAGNOSTIC,
        "Nested Torch CV: outer evaluation after fold-local inner hyperparameter search.",
        "Estimate generalization after selection without leaking outer-eval rows into search.",
        "Torch nested CV boundary.",
        (
            "Split outer folds on the train universe.",
            "Run inner search on each outer-train subset only.",
            "Refit the winning config on outer-train with fold-local normalize.",
            "Score each outer-eval fold once and aggregate mean/std metrics.",
        ),
        parameters=(
            _p("param_grid", "dict | None", "Grid of searchable knobs."),
            _p("param_distributions", "dict | None", "Distributions for randomized search."),
            _p("inner_search", "grid | randomized | auto", "Inner search method.", "auto"),
            _p("n_iter", "int", "Randomized trial count.", 5),
            _p("outer_cv", "int", "Outer folds.", 3),
            _p("inner_cv", "int", "Inner folds.", 2),
            _p("epochs", "int", "Epochs per fit.", 2),
            _p("batch_size", "int", "Default batch size.", 32),
            _p("learning_rate", "float", "Default Adam LR.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Fold-local train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p("scoring_metric", "str | None", "Rank/eval metric (default accuracy or mse)."),
            _p("module_factory", "callable | None", "(n_features, task, n_classes, params) -> module."),
        ),
        inputs=("Dataset with numeric features/target; optional SplitPlan.",),
        outputs=("TorchNestedCVResult with outer metrics, per-fold winners, limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles/split; beside classical nested_cv_score for sklearn.",),
        alternatives=("search_torch for inner-only selection; cross_validate_torch without search.",),
        rationale=("Use when Torch hyperparameter selection needs an outer honesty estimate.",),
        assumptions=("Alpha epoch budgets make ranks noisy; refit chosen knobs on full train after.",),
        failures=("Missing search space, too few rows, or missing Torch extra.",),
        leakage=("Outer-eval rows in inner ranking, or Session test in either loop, is refused.",),
        anti_patterns=("Deploying consensus_params without an explicit final refit decision.",),
        state_changes=("Stores dl_nested_cv_result.",),
        result_reading=("Read mean_metrics, best_params_per_fold, consensus_params, limitations.",),
        next_steps=("fit_torch with an explicit chosen config; export_torch / save_torch_bundle.",),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "export_torch",
        OperationKind.PERSIST,
        "Export the last Torch trainer to TorchScript or ONNX.",
        "Produce an alpha-quality portable artifact from example train-loader inputs.",
        "Torch export escape hatch.",
        (
            "Resolve example inputs from loaders or caller.",
            "Trace/script (TorchScript) or torch.onnx.export (ONNX).",
            "Record opset/dynamic axes and honest limitations.",
        ),
        parameters=(
            _p("path", "str | Path", "Destination file path.", required=True),
            _p("format", "torchscript | onnx", "Export format.", "torchscript"),
            _p("opset", "int", "ONNX opset version.", 17),
            _p("dynamic_batch", "bool", "Mark batch dim dynamic for ONNX.", True),
            _p("example_input", "Any | None", "Optional override example tensor/tuple."),
        ),
        inputs=("Active dl_train_result and example inputs / torch loaders.",),
        outputs=("ExportResult with path, format, disclosures, limitations.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After fit_torch / evaluate_torch; beside save_torch_bundle.",),
        alternatives=("save_torch_bundle for BuildML trainer resume; serving stacks separately.",),
        rationale=("Use when another runtime needs TorchScript/ONNX, not a trainer bundle.",),
        assumptions=("Example batch shapes cover the ops you need at inference time.",),
        failures=("No trainer, export op failure, or missing Torch extra.",),
        leakage=("Exported weights can retain training-data patterns; control access.",),
        anti_patterns=(
            "Treating export alone as a full production serving stack — use serve_bundle / "
            "buildml-serve for the library-owned local server path.",
        ),
        state_changes=("Writes an artifact file; stores dl_export_result.",),
        result_reading=("Read format/opset/dynamic_axes and limitations before deploying.",),
        next_steps=(
            "Smoke-load TorchScript/ONNX in the target runtime; keep trainer bundle too; "
            "optional serve_bundle(kind='torchscript') for local HTTP.",
        ),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "fit_torch_ddp",
        OperationKind.MODEL,
        "DistributedDataParallel training via a module_factory (single-node or multi-node).",
        "Shard the train loader across ranks and return the rank-0 TrainResult.",
        "Torch DDP boundary (spawn or torchrun join).",
        (
            "Require torch loaders and a picklable module_factory (single-node spawn).",
            "Single-node: spawn one process per rank (NCCL when >=2 CUDA devices).",
            "Multi-node: multi_node=True joins torchrun env (WORLD_SIZE/RANK/LOCAL_RANK/MASTER_*).",
            "Shard train batches; collect rank-0 TrainResult.",
        ),
        parameters=(
            _p("module_factory", "callable", "Zero-arg fresh nn.Module factory per process.", required=True),
            _p("epochs", "int", "Epochs when config omitted.", 5),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("mixed_precision", "bool", "CUDA AMP when True.", False),
            _p("world_size", "int | None", "Process count for single-node (default = CUDA device count)."),
            _p("allow_cpu_ddp", "bool", "Permit gloo CPU smoke (not a perf path).", False),
            _p("multi_node", "bool", "Join torchrun multi-node rendezvous instead of local spawn.", False),
            _p("config", "TrainConfig | None", "Optional full train config."),
        ),
        inputs=("TorchLoaderBundle and a picklable module_factory (or per-rank loaders under torchrun).",),
        outputs=("DDPTrainResult; also stores dl_train_result from rank 0.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_torch_loaders; alternative to single-process fit_torch.",),
        alternatives=("fit_torch for single-process training.",),
        rationale=("Use when single-node multi-GPU or torchrun multi-node scale is needed in alpha.",),
        assumptions=(
            "Single-node datasets are picklable under spawn.",
            "Multi-node requires complete torchrun env; not a Kubernetes multi-cluster product.",
        ),
        failures=(
            "Fewer than two CUDA devices without allow_cpu_ddp (single-node).",
            "Missing WORLD_SIZE/RANK/MASTER_ADDR/MASTER_PORT when multi_node=True.",
            "Spawn/pickle errors on single-node.",
        ),
        leakage=("Same split/normalize rules as fit_torch; DDP does not invent holdouts.",),
        anti_patterns=(
            "Claiming Kubernetes multi-cluster orchestration from this torchrun helper.",
            "Enabling CPU multi-process without allow_cpu_ddp and treating it as production scale.",
        ),
        state_changes=("Stores dl_ddp_result and dl_train_result.",),
        result_reading=("Read backend, world_size, mode (single_node/multi_node), warnings, and limitations.",),
        next_steps=("evaluate_torch; export_torch / save_torch_bundle.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_speech_torch_loaders",
        OperationKind.MODEL,
        "Build speech classification DataLoaders from an audio feature column.",
        "Prepare waveforms for finetune-lite speech classification under a leakage-safe split.",
        "Speech classify loader boundary.",
        (
            "Resolve audio_column and target roles.",
            "Decode path/waveform cells to fixed-length mono tensors.",
            "Fit optional train-only amplitude mean/std.",
            "Construct DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("audio_column", "str | None", "Audio path or waveform feature column."),
            _p("batch_size", "int", "Rows per batch.", 8),
            _p("sample_rate", "int", "Target sample rate.", 16000),
            _p("max_samples", "int", "Fixed waveform length (repeat-pad short clips).", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("normalize_audio", "bool", "Fit amplitude mean/std on train.", True),
            _p("encoder_dim", "int", "Tiny encoder embedding width for fit_speech_torch.", 64),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
        ),
        inputs=("Dataset with roles, SplitPlan, and an audio feature column.",),
        outputs=("TorchLoaderBundle with modality=speech_classify.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split; before fit_speech_torch / fit_torch.",),
        alternatives=(
            "make_audio_multimodal_torch_loaders for small 1D-CNN fusion with tabular/text/image.",
            "transcribe_speech for ASR text generation without classification training.",
        ),
        rationale=("Use when fine-tuning a tiny speech encoder head on labeled audio.",),
        assumptions=("Targets are numeric class ids; audio cells are paths or waveforms.",),
        failures=("Missing Torch extra, empty train, non-numeric labels, or bad audio cells.",),
        leakage=("Fitting amp stats on all rows, or ignoring SplitPlan membership, leaks evaluation signal.",),
        anti_patterns=(
            "Calling this path 'train Whisper from scratch'.",
            "Expecting Hugging Face weights without buildml[speech] / transcribe_speech transformers backend.",
        ),
        state_changes=("Stores torch loaders on the Session.",),
        result_reading=("Check modality, n_train/n_validation/n_test, and train-only normalize disclosures.",),
        next_steps=("fit_speech_torch or fit_torch; evaluate_torch; optional transcribe_speech for ASR.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "fit_speech_torch",
        OperationKind.MODEL,
        "Fine-tune a tiny speech encoder + classifier head (finetune-lite).",
        "Train a small speech classifier under the Session split — not a foundation model from scratch.",
        "Speech finetune-lite training boundary.",
        (
            "Build speech loaders when missing.",
            "Construct tiny 1D-CNN encoder + linear head.",
            "Run the supervised train loop on train (optional freeze_encoder).",
        ),
        parameters=(
            _p("epochs", "int", "Training epochs.", 5),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Compute device.", "auto"),
            _p("freeze_encoder", "bool", "Train head only when True.", False),
            _p("audio_column", "str | None", "Audio column when loaders must be built."),
            _p("batch_size", "int", "Loader batch size when building loaders.", 8),
            _p("sample_rate", "int", "Target sample rate.", 16000),
            _p("max_samples", "int", "Fixed waveform length.", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("normalize_audio", "bool", "Train-only amplitude normalize.", True),
            _p("encoder_dim", "int", "Encoder embedding width.", 64),
            _p("seed", "int", "Loader/train seed.", 0),
        ),
        inputs=("Speech TorchLoaderBundle or roles+split+audio column.",),
        outputs=("Session with dl_train_result from speech finetune-lite.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_speech_torch_loaders (or builds them); before evaluate_torch.",),
        alternatives=("fit_torch after make_speech_torch_loaders; multimodal audio fusion for mixed modalities.",),
        rationale=("Use for labeled audio classification with a tiny encoder head.",),
        assumptions=("SplitPlan is fixed; amp stats stay train-only.",),
        failures=("Missing Torch, empty train, or non-numeric class labels.",),
        leakage=("Refitting loaders on test labels or amp stats across all rows.",),
        anti_patterns=("Marketing this as Whisper-scale foundation-model training.",),
        state_changes=("Stores dl_train_result and speech torch loaders.",),
        result_reading=("Read history, device, and disclosures that this is finetune-lite.",),
        next_steps=("evaluate_torch; save_torch_bundle; optional export_torch.",),
        concepts=("leakage-boundary", "evaluation-partitions"),
    ),
    _operation(
        "transcribe_speech",
        OperationKind.MODEL,
        "ASR transcription for an audio feature column (stub or transformers).",
        "Generate transcripts via stub (CI-safe) or Whisper-class transformers pipelines.",
        "Speech ASR inference boundary.",
        (
            "Resolve audio_column cells (optional split partition).",
            "Run stub fingerprint ASR or transformers automatic-speech-recognition pipeline.",
            "Return SpeechTranscribeResult texts + disclosures.",
        ),
        parameters=(
            _p("audio_column", "str", "Audio path or waveform feature column.", required=True),
            _p("backend", "stub | transformers", "ASR backend.", "stub"),
            _p("model_id", "str | None", "Hugging Face model id when backend=transformers."),
            _p("sample_rate", "int", "Decode sample rate.", 16000),
            _p("max_samples", "int", "Decode length cap.", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for arrays."),
            _p("partition", "train | validation | test | all", "Rows to transcribe.", "all"),
        ),
        inputs=("Dataset with an audio feature column; SplitPlan when partition != all.",),
        outputs=("SpeechTranscribeResult stored as dl_speech_result.",),
        prerequisites=(DATASET, TORCH),
        ordering=("Anytime after ingest; often beside speech classify training.",),
        alternatives=("External ASR services; make_speech_torch_loaders for classify finetune.",),
        rationale=("Use when you need ASR text from Session audio cells.",),
        assumptions=("transformers backend may download weights; stub is not real ASR quality.",),
        failures=("Missing speech extra for transformers, bad audio cells, incomplete split for partition.",),
        leakage=("Transcribing holdout audio is fine; do not refit classify stats on those texts without a plan.",),
        anti_patterns=("Treating stub transcripts as production ASR; claiming FM-from-scratch training.",),
        state_changes=("Stores dl_speech_result; does not mutate the dataset frame.",),
        result_reading=("Read backend, model_id, disclosures, and limitations before trusting texts.",),
        next_steps=("Optional: attach transcripts as a text feature and continue classical/Torch paths.",),
        concepts=("leakage-boundary", "evaluation-partitions"),
    ),
    _operation(
        "serve_bundle",
        OperationKind.EXPORT,
        "Launch BuildML managed local model serving for a pipeline or TorchScript artifact.",
        "Expose /health and /predict via a FastAPI server (localhost-oriented, no auth).",
        "Managed serving boundary.",
        (
            "Load classical pipeline bundle or TorchScript file.",
            "Bind FastAPI/uvicorn (default 127.0.0.1).",
            "Serve /health and /predict until stopped.",
        ),
        parameters=(
            _p("path", "str | Path | None", "Bundle/TorchScript path (or last save_pipeline path)."),
            _p("kind", "pipeline | torchscript", "Artifact kind.", "pipeline"),
            _p("host", "str", "Bind host (default localhost).", "127.0.0.1"),
            _p("port", "int", "Bind port.", 8080),
            _p("title", "str", "Service title.", "BuildML Serve"),
            _p("blocking", "bool", "Block current thread when True.", False),
        ),
        inputs=("Saved pipeline bundle directory or TorchScript file.",),
        outputs=("ServeHandle with url; process-local server thread.",),
        prerequisites=(),
        ordering=("After save_pipeline or export_torch TorchScript; deployment-adjacent.",),
        alternatives=("buildml-serve CLI / python -m buildml.serving; reverse-proxy in front.",),
        rationale=("Use for local/demo managed serving of BuildML artifacts.",),
        assumptions=("No authentication product claim; operator supplies reverse-proxy/TLS if exposed.",),
        failures=("Missing buildml[serve], bad bundle path, or port already in use.",),
        leakage=("Serving trained weights can retain training-data patterns; control access.",),
        anti_patterns=(
            "Exposing bare 0.0.0.0 without a reverse proxy and auth.",
            "Claiming Kubernetes multi-cluster orchestration from this local server.",
        ),
        state_changes=("Stores serve handle; starts a background (or blocking) server.",),
        result_reading=("Read url/kind; confirm /health before clients call /predict.",),
        next_steps=("PUT a reverse proxy in front for non-local use; stop() the handle when done.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "torch_training_curve",
        OperationKind.DIAGNOSTIC,
        "Return structured Torch epoch curves with interpretation and limits.",
        "Read training history as teaching evidence, not as a deployment scorecard.",
        "Torch training-curve disclosure.",
        (
            "Require dl_train_result.",
            "Build epoch/train_loss/val_loss/lr series.",
            "Attach interpretation, limitations, and early-stop/device disclosures.",
        ),
        parameters=(),
        inputs=("Active dl_train_result with epoch history.",),
        outputs=("TrainingCurveReport with series, interpretation, limitations, disclosures.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After fit_torch or load_torch_bundle; beside evaluate_torch for holdout metrics.",),
        alternatives=("Inspect TrainResult.history directly when a compact table is enough.",),
        rationale=("Curves need partition and device tags before anyone claims generalization.",),
        assumptions=("History rows were logged by fit_torch under the current TrainConfig.",),
        failures=("No Torch trainer on the Session.",),
        leakage=("Using test loss as the plotted early-stop monitor contaminates the final claim.",),
        anti_patterns=(
            "Treating the last train_loss point as expected production performance.",
            "Ignoring limitations about batch noise and validation vs test scope.",
        ),
        state_changes=("Appends a history record; trainer weights are unchanged.",),
        result_reading=(
            "Read disclosures for device and early-stop partition; treat interpretation as review cues.",
        ),
        next_steps=("evaluate_torch(partition='test') once stopping choices are frozen.",),
        concepts=("training-curves", "early-stopping-partition", "evaluation-partitions"),
    ),
    _operation(
        "evaluate_torch",
        OperationKind.DIAGNOSTIC,
        "Compute task metrics for the active Torch trainer on a named partition.",
        "Score a Torch module with partition-tagged metrics, not a single unlabeled number.",
        "Torch holdout assessment.",
        (
            "Require dl_train_result and partition DataLoader.",
            "Run batched inference.",
            "Compute classification or regression metrics.",
        ),
        parameters=(
            _p("partition", "train | validation | test", "Evaluation rows.", "test"),
            _p("device", "str | None", "Optional device override; defaults to the train device."),
        ),
        inputs=("TrainResult, Torch loaders, and a named partition.",),
        outputs=("DLEvaluateResult with metrics, row count, device, and recommendations.",),
        prerequisites=(DATASET, SPLIT, FIT_TORCH, TORCH),
        ordering=("After fit_torch or load_torch_bundle; prefer validation during iteration, test once frozen.",),
        alternatives=("Use Session.evaluate for classical sklearn FitResult scoring.",),
        rationale=("Read metrics only with their partition tag and known device.",),
        assumptions=("Loader feature contract still matches the trained module input width.",),
        failures=("No Torch trainer, missing partition loader, or Torch not installed.",),
        leakage=("Repeated test evaluation while changing architecture or stopping rules contaminates the final claim.",),
        anti_patterns=("Comparing Torch and sklearn scores without matching prep and partitions.",),
        state_changes=("Appends evaluation metadata; trainer weights are unchanged.",),
        result_reading=("Read metrics with partition and device; treat recommendations as review cues.",),
        next_steps=("save_torch_bundle when the recipe is stable enough to keep.",),
        concepts=("evaluation-partitions", "early-stopping-partition", "leakage-boundary"),
    ),
    _operation(
        "save_torch_bundle",
        OperationKind.PERSIST,
        "Persist Torch weights, optimizer state, config, history, feature contract, "
        "and optional multimodal_preprocess meta.",
        "Carry a trainer artifact without embedding Session data or splits.",
        "Torch trainer bundle persistence.",
        (
            "Write meta.json with format buildml.torch_bundle.v1.",
            "torch.save module/optimizer/config/history/multimodal_preprocess into trainer.pt.",
        ),
        parameters=(_p("path", "str | Path", "Destination trainer bundle directory.", required=True),),
        inputs=("Active dl_train_result and destination path.",),
        outputs=("Resolved bundle directory Path.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After evaluation; beside (not inside) Session checkpoint_save when both are needed.",),
        alternatives=(
            "Use checkpoint_save for data/roles/splits/history.",
            "Use save_pipeline for classical sklearn recipes.",
        ),
        rationale=("Keep weights separate from workflow data so resume and inference stay explicit.",),
        assumptions=("Loading environments trust the artifact and supply a compatible module shell.",),
        failures=("No Torch trainer, unwritable path, or missing Torch extra.",),
        leakage=("Bundles can embed learned sensitive patterns; access controls still apply.",),
        anti_patterns=(
            "Expecting Session checkpoint_load to restore Torch weights.",
            "Loading untrusted trainer.pt files (torch.load can execute code depending on version/settings).",
        ),
        state_changes=("Writes files and appends the destination to history.",),
        result_reading=("Treat the returned path as the bundle root; read meta.json format before load.",),
        next_steps=("Verify load_torch_bundle with the same module class in a clean process.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "load_torch_bundle",
        OperationKind.PERSIST,
        "Load a Torch trainer bundle into Session.dl_train_result via a module shell.",
        "Restore weights and train metadata without treating the bundle as a Session checkpoint.",
        "Torch trainer bundle restoration.",
        (
            "Validate meta.json format buildml.torch_bundle.v1.",
            "Load trainer.pt into the supplied nn.Module.",
            "Rebuild TrainResult on the Session (including multimodal_preprocess when present).",
            "Do not rebuild DataLoaders; remake multimodal/text loaders explicitly.",
        ),
        parameters=(
            _p("path", "str | Path", "Existing trainer bundle directory.", required=True),
            _p("module", "torch.nn.Module", "Compatible module shell for load_state_dict.", required=True),
            _p("map_location", "str | None", "Optional torch.load device map.", None),
        ),
        inputs=("Trusted trainer bundle path and a compatible nn.Module instance.",),
        outputs=("Session with dl_train_result restored.",),
        prerequisites=(TORCH,),
        ordering=("After attaching compatible data/split when you will evaluate; before evaluate_torch.",),
        alternatives=(
            "Use checkpoint_load for dataset/split/history.",
            "Use load_pipeline for classical sklearn bundles.",
        ),
        rationale=("Load when the module architecture matches the saved state dict.",),
        assumptions=("Artifact is trusted and feature width matches the current Session contract.",),
        failures=("Wrong format (checkpoint/pipeline), corrupt files, or state_dict mismatch.",),
        leakage=("A trainer can retain information from its original training data.",),
        anti_patterns=(
            "Passing a Session checkpoint path to load_torch_bundle.",
            "Expecting load_torch_bundle to rebuild multimodal DataLoaders or "
            "auto-apply frozen image/audio preprocess stats.",
        ),
        state_changes=("Replaces dl_train_result; classical fit_result is unchanged.",),
        result_reading=(
            "Confirm task, feature columns, epoch history, and multimodal_preprocess "
            "(when present) before scoring.",
        ),
        next_steps=(
            "Remake multimodal/text loaders when the module is non-tabular; "
            "evaluate_torch on a holdout partition; "
            "or fit_torch(..., resume=True) to continue training from the restored state.",
        ),
        concepts=("reproducibility", "feature-schema", "leakage-boundary", "training-curves"),
    ),
)
