# ruff: noqa: E501, F401
"""Torch / deep-learning Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    AI,
    AI_PROVIDER,
    DASHBOARD,
    DATASET,
    FIT,
    FIT_TORCH,
    RAG,
    RAG_CORPUS,
    RAG_INDEX,
    ROLES,
    SPLIT,
    TORCH,
    VIZ,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "make_torch_loaders",
        OperationKind.MODEL,
        "Build Torch DataLoaders from Session feature/target roles and split partitions.",
        "Prepare batched tensors for supervised Torch training without inventing architectures.",
        "Tabular Torch data boundary.",
        (
            "Resolve feature and target roles.",
            "Materialize numeric arrays per partition.",
            "Fit optional train-only normalize stats and freeze them on validation/test.",
            "Construct DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("batch_size", "int", "Rows per batch.", 32),
            _p("num_workers", "int", "DataLoader worker processes.", 0),
            _p("pin_memory", "bool", "Pin host memory when useful for CUDA transfers.", False),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("drop_last", "bool", "Drop the last incomplete train batch.", False),
            _p("normalize", "bool", "Fit mean/std on train and apply frozen stats elsewhere.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
            _p("task", "classification | regression | auto", "Task interpretation for labels.", "auto"),
            _p("apply_plans", "bool", "Re-apply fitted classical plans before building tensors.", False),
        ),
        inputs=("Dataset with roles, SplitPlan, and optional prior classical prep on the frame.",),
        outputs=("TorchLoaderBundle stored on the Session plus a LoaderReport summary.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split (and optional classical prep); before fit_torch.",),
        alternatives=(
            "make_text_torch_loaders for token/sequence classification.",
            "Build tensors yourself and inject only if you accept leaving the Session path.",
        ),
        rationale=("Use when moving from partition frames to batched Torch training.",),
        assumptions=("Features and targets are numeric; non-numeric columns were encoded or dropped earlier.",),
        failures=("Missing Torch extra, empty train, non-numeric columns, or NaNs in the design matrix.",),
        leakage=(
            "Fitting normalize on all rows, or shuffling validation/test into train batches, leaks evaluation signal.",
            "Ignoring group/time SplitPlan membership when building tensors outside make_torch_loaders.",
        ),
        anti_patterns=(
            "Treating loader construction as permission to skip a declared split.",
            "Expecting Polars/DuckDB zero-copy into DataLoaders in this slice.",
        ),
        state_changes=("Stores torch loaders on the Session and appends loader metadata to history.",),
        result_reading=(
            "Check n_train/n_validation/n_test, split_kind, groups_disjoint/time_order_ok, "
            "normalize flag, classical plan disclosures, and warnings for empty holdout partitions.",
        ),
        next_steps=("Call fit_torch (built-in MLP when module omitted) or cross_validate_torch.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "make_text_torch_loaders",
        OperationKind.MODEL,
        "Build token-id DataLoaders for text classification (sequence modality).",
        "Fit a train-only vocabulary and pad token sequences for embedding classifiers.",
        "Text / sequence Torch data boundary.",
        (
            "Resolve a text feature column and target.",
            "Fit vocabulary on the train partition only.",
            "Encode padded token ids per partition with shuffle on train only.",
        ),
        parameters=(
            _p("text_column", "str | None", "Text feature column (inferred when unique)."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
        ),
        inputs=("Dataset with a string feature column, numeric target ids, and a SplitPlan.",),
        outputs=("TorchLoaderBundle with text_vocab / text_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch with a text classifier.",),
        alternatives=("make_torch_loaders for numeric tabular tensors.",),
        rationale=("Use when the modeling path is text/sequence rather than pure numeric tables.",),
        assumptions=("Target labels are integer class ids; vocabulary must not see validation/test text.",),
        failures=("Missing Torch extra, no text column, empty train, or non-numeric target.",),
        leakage=("Fitting vocabulary on all rows leaks holdout token identity into the model.",),
        anti_patterns=("Treating hashing RAG embeddings as a substitute for this supervised text path.",),
        state_changes=("Stores text Torch loaders on the Session.",),
        result_reading=("Check vocab size, max_len, partition sizes, and train-only vocab disclosure.",),
        next_steps=("fit_torch() without module to build the embedding text classifier.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "fit_torch",
        OperationKind.MODEL,
        "Train a Torch nn.Module (built-in MLP/text classifier when module omitted).",
        "Run a leakage-scoped supervised epoch loop and store a Torch TrainResult.",
        "Torch supervised training boundary.",
        (
            "Require or build Torch loaders.",
            "When module is omitted, build tabular MLP or text classifier from the loader contract.",
            "Resolve device with explicit CPU fallback when CUDA/MPS are unavailable.",
            "Run epoch steps with optional validation loss, scheduler, grad clip, and early stopping.",
            "When resume=True, restore optimizer/scheduler state from dl_train_result and append history.",
        ),
        parameters=(
            _p("module", "torch.nn.Module | None", "Optional network; built-in zoo when omitted."),
            _p("loss_fn", "callable | None", "Optional (module, xb, yb) -> loss."),
            _p("optimizer_factory", "callable | None", "Optional params -> optimizer factory."),
            _p("epochs", "int", "Epochs when config omitted; additional epochs if resume=True.", 5),
            _p("learning_rate", "float", "Adam learning rate when config is omitted.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("grad_clip_norm", "float | None", "Optional gradient-norm clip (default None=off)."),
            _p("log_every", "int", "Record history every N epochs.", 1),
            _p(
                "early_stopping_patience",
                "int | None",
                "Stop after N non-improving validation epochs (default None=off).",
            ),
            _p("early_stopping_monitor", "str", "Metric key for early stop (default val_loss).", "val_loss"),
            _p(
                "scheduler",
                "none | step | plateau | cosine",
                "LR schedule (default none).",
                "none",
            ),
            _p("resume", "bool", "Continue from dl_train_result / loaded bundle.", False),
            _p("config", "TrainConfig | None", "Optional full train config overriding scalar knobs."),
            _p("hidden", "tuple[int, ...]", "Hidden widths for built-in tabular MLP when module omitted.", (64, 32)),
            _p("dropout", "float", "Dropout for built-in models when module omitted.", 0.1),
        ),
        inputs=("TorchLoaderBundle, nn.Module, and optional loss/optimizer factories.",),
        outputs=("Session with dl_train_result (TrainResult) distinct from classical fit_result.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_torch_loaders (auto-built if missing); before evaluate_torch / save_torch_bundle.",),
        alternatives=("Use Session.fit for sklearn estimators; do not mix result slots silently.",),
        rationale=("Choose Torch when the model is an nn.Module rather than a sklearn estimator.",),
        assumptions=("Train loader rows match the intended supervised task and feature contract.",),
        failures=(
            "Missing Torch extra, empty train loader, early stop without validation, "
            "shape mismatches, or optimizer/loss errors.",
        ),
        leakage=("Training without a split, or using test batches inside the train loop, invalidates holdout claims.",),
        anti_patterns=(
            "Reporting train loss as expected production performance.",
            "Tuning stopping rules on the test partition (see early-stopping-partition).",
        ),
        state_changes=("Stores dl_train_result; classical fit_result is unchanged.",),
        result_reading=(
            "Inspect device.resolved, early_stop reason/partition, scheduler_name, "
            "training_curve disclosures, and epoch history.",
        ),
        next_steps=(
            "torch_training_curve for structured teaching data; evaluate_torch on validation or test; "
            "save_torch_bundle for weights; cross_validate_torch for fold-local estimates.",
        ),
        concepts=(
            "leakage-boundary",
            "batch-leakage",
            "early-stopping-partition",
            "training-curves",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "cross_validate_torch",
        OperationKind.DIAGNOSTIC,
        "Fold-local Torch cross-validation on numeric tabular features.",
        "Train a fresh module per fold with train-only normalize stats.",
        "Torch fold-local CV boundary.",
        (
            "Split indices into folds (optionally stratified).",
            "Fit normalize stats on each fold's train indices only.",
            "Train a fresh module (default tabular MLP) and score the held-out fold.",
            "Aggregate mean/std metrics with explicit nested-CV limitations.",
        ),
        parameters=(
            _p("n_folds", "int", "Number of folds.", 3),
            _p("epochs", "int", "Epochs per fold.", 3),
            _p("batch_size", "int", "Batch size.", 32),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Per-fold train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p(
                "module_factory",
                "callable | None",
                "Optional (n_features, task, n_classes) -> fresh nn.Module per fold.",
            ),
        ),
        inputs=("Dataset with numeric features and a target (split optional; CV makes its own folds).",),
        outputs=("TorchCVResult with per-fold and mean metrics plus limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles (and optional classical prep); beside fit_torch for a single split.",),
        alternatives=("Classical Session.cross_validate for sklearn estimators; nested CV separately.",),
        rationale=("Use when you need fold-local Torch estimates without claiming nested search.",),
        assumptions=("Features/targets are numeric; module_factory builds a fresh module each fold.",),
        failures=("Missing Torch extra, too few rows for n_folds, or non-numeric design matrix.",),
        leakage=(
            "Fitting normalize or vocab on all rows before folding leaks holdout signal.",
            "Refitting Session-global classical plans outside fold-local apply_session_plans.",
        ),
        anti_patterns=(
            "Calling this nested CV when no inner hyperparameter loop ran.",
            "Reporting mean fold accuracy as production readiness without holdout.",
        ),
        state_changes=("Stores dl_cv_result; does not replace dl_train_result.",),
        result_reading=("Read mean_metrics, limitations (not nested), and per-fold warnings.",),
        next_steps=("fit_torch on a declared split for the final trainer; save_torch_bundle.",),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "torch_training_curve",
        OperationKind.DIAGNOSTIC,
        "Return structured Torch epoch curves with interpretation and limits.",
        "Read training history as teaching evidence, not as a deployment scorecard.",
        "Torch training-curve disclosure.",
        (
            "Require dl_train_result.",
            "Build epoch/train_loss/val_loss/lr series.",
            "Attach interpretation, limitations, and early-stop/device disclosures.",
        ),
        parameters=(),
        inputs=("Active dl_train_result with epoch history.",),
        outputs=("TrainingCurveReport with series, interpretation, limitations, disclosures.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After fit_torch or load_torch_bundle; beside evaluate_torch for holdout metrics.",),
        alternatives=("Inspect TrainResult.history directly when a compact table is enough.",),
        rationale=("Curves need partition and device tags before anyone claims generalization.",),
        assumptions=("History rows were logged by fit_torch under the current TrainConfig.",),
        failures=("No Torch trainer on the Session.",),
        leakage=("Using test loss as the plotted early-stop monitor contaminates the final claim.",),
        anti_patterns=(
            "Treating the last train_loss point as expected production performance.",
            "Ignoring limitations about batch noise and validation vs test scope.",
        ),
        state_changes=("Appends a history record; trainer weights are unchanged.",),
        result_reading=(
            "Read disclosures for device and early-stop partition; treat interpretation as review cues.",
        ),
        next_steps=("evaluate_torch(partition='test') once stopping choices are frozen.",),
        concepts=("training-curves", "early-stopping-partition", "evaluation-partitions"),
    ),
    _operation(
        "evaluate_torch",
        OperationKind.DIAGNOSTIC,
        "Compute task metrics for the active Torch trainer on a named partition.",
        "Score a Torch module with partition-tagged metrics, not a single unlabeled number.",
        "Torch holdout assessment.",
        (
            "Require dl_train_result and partition DataLoader.",
            "Run batched inference.",
            "Compute classification or regression metrics.",
        ),
        parameters=(
            _p("partition", "train | validation | test", "Evaluation rows.", "test"),
            _p("device", "str | None", "Optional device override; defaults to the train device."),
        ),
        inputs=("TrainResult, Torch loaders, and a named partition.",),
        outputs=("DLEvaluateResult with metrics, row count, device, and recommendations.",),
        prerequisites=(DATASET, SPLIT, FIT_TORCH, TORCH),
        ordering=("After fit_torch or load_torch_bundle; prefer validation during iteration, test once frozen.",),
        alternatives=("Use Session.evaluate for classical sklearn FitResult scoring.",),
        rationale=("Read metrics only with their partition tag and known device.",),
        assumptions=("Loader feature contract still matches the trained module input width.",),
        failures=("No Torch trainer, missing partition loader, or Torch not installed.",),
        leakage=("Repeated test evaluation while changing architecture or stopping rules contaminates the final claim.",),
        anti_patterns=("Comparing Torch and sklearn scores without matching prep and partitions.",),
        state_changes=("Appends evaluation metadata; trainer weights are unchanged.",),
        result_reading=("Read metrics with partition and device; treat recommendations as review cues.",),
        next_steps=("save_torch_bundle when the recipe is stable enough to keep.",),
        concepts=("evaluation-partitions", "early-stopping-partition", "leakage-boundary"),
    ),
    _operation(
        "save_torch_bundle",
        OperationKind.PERSIST,
        "Persist Torch weights, optimizer state, config, history, and feature contract.",
        "Carry a trainer artifact without embedding Session data or splits.",
        "Torch trainer bundle persistence.",
        (
            "Write meta.json with format buildml.torch_bundle.v1.",
            "torch.save module/optimizer/config/history into trainer.pt.",
        ),
        parameters=(_p("path", "str | Path", "Destination trainer bundle directory.", required=True),),
        inputs=("Active dl_train_result and destination path.",),
        outputs=("Resolved bundle directory Path.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After evaluation; beside (not inside) Session checkpoint_save when both are needed.",),
        alternatives=(
            "Use checkpoint_save for data/roles/splits/history.",
            "Use save_pipeline for classical sklearn recipes.",
        ),
        rationale=("Keep weights separate from workflow data so resume and inference stay explicit.",),
        assumptions=("Loading environments trust the artifact and supply a compatible module shell.",),
        failures=("No Torch trainer, unwritable path, or missing Torch extra.",),
        leakage=("Bundles can embed learned sensitive patterns; access controls still apply.",),
        anti_patterns=(
            "Expecting Session checkpoint_load to restore Torch weights.",
            "Loading untrusted trainer.pt files (torch.load can execute code depending on version/settings).",
        ),
        state_changes=("Writes files and appends the destination to history.",),
        result_reading=("Treat the returned path as the bundle root; read meta.json format before load.",),
        next_steps=("Verify load_torch_bundle with the same module class in a clean process.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "load_torch_bundle",
        OperationKind.PERSIST,
        "Load a Torch trainer bundle into Session.dl_train_result via a module shell.",
        "Restore weights and train metadata without treating the bundle as a Session checkpoint.",
        "Torch trainer bundle restoration.",
        (
            "Validate meta.json format buildml.torch_bundle.v1.",
            "Load trainer.pt into the supplied nn.Module.",
            "Rebuild TrainResult on the Session.",
        ),
        parameters=(
            _p("path", "str | Path", "Existing trainer bundle directory.", required=True),
            _p("module", "torch.nn.Module", "Compatible module shell for load_state_dict.", required=True),
            _p("map_location", "str | None", "Optional torch.load device map.", None),
        ),
        inputs=("Trusted trainer bundle path and a compatible nn.Module instance.",),
        outputs=("Session with dl_train_result restored.",),
        prerequisites=(TORCH,),
        ordering=("After attaching compatible data/split when you will evaluate; before evaluate_torch.",),
        alternatives=(
            "Use checkpoint_load for dataset/split/history.",
            "Use load_pipeline for classical sklearn bundles.",
        ),
        rationale=("Load when the module architecture matches the saved state dict.",),
        assumptions=("Artifact is trusted and feature width matches the current Session contract.",),
        failures=("Wrong format (checkpoint/pipeline), corrupt files, or state_dict mismatch.",),
        leakage=("A trainer can retain information from its original training data.",),
        anti_patterns=("Passing a Session checkpoint path to load_torch_bundle.",),
        state_changes=("Replaces dl_train_result; classical fit_result is unchanged.",),
        result_reading=("Confirm task, feature columns, and epoch history before scoring.",),
        next_steps=(
            "make_torch_loaders if needed; evaluate_torch on a holdout partition; "
            "or fit_torch(..., resume=True) to continue training from the restored state.",
        ),
        concepts=("reproducibility", "feature-schema", "leakage-boundary", "training-curves"),
    ),
)
