# ruff: noqa: E501, F401
"""Torch / deep-learning Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    AI,
    AI_PROVIDER,
    DASHBOARD,
    DATASET,
    FIT,
    FIT_TORCH,
    RAG,
    RAG_CORPUS,
    RAG_INDEX,
    ROLES,
    SPLIT,
    TORCH,
    VIZ,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "make_torch_loaders",
        OperationKind.MODEL,
        "Build Torch DataLoaders from Session feature/target roles and split partitions.",
        "Prepare batched tensors for supervised Torch training without inventing architectures.",
        "Tabular Torch data boundary.",
        (
            "Resolve feature and target roles.",
            "Materialize numeric arrays per partition.",
            "For classification, remap train-fit class ids to contiguous 0..K-1 "
            "(class_labels stores original ids).",
            "Fit optional train-only normalize stats and freeze them on validation/test.",
            "Construct DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("batch_size", "int", "Rows per batch.", 32),
            _p("num_workers", "int", "DataLoader worker processes.", 0),
            _p("pin_memory", "bool", "Pin host memory when useful for CUDA transfers.", False),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("drop_last", "bool", "Drop the last incomplete train batch.", False),
            _p("normalize", "bool", "Fit mean/std on train and apply frozen stats elsewhere.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
            _p("task", "classification | regression | auto", "Task interpretation for labels.", "auto"),
            _p("apply_plans", "bool", "Re-apply fitted classical plans before building tensors.", False),
        ),
        inputs=("Dataset with roles, SplitPlan, and optional prior classical prep on the frame.",),
        outputs=("TorchLoaderBundle stored on the Session plus a LoaderReport summary.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split (and optional classical prep); before fit_torch.",),
        alternatives=(
            "make_text_torch_loaders for token/sequence classification.",
            "Build tensors yourself and inject only if you accept leaving the Session path.",
        ),
        rationale=("Use when moving from partition frames to batched Torch training.",),
        assumptions=(
            "Features and targets are numeric; non-numeric columns were encoded or dropped earlier.",
            "Classification targets may be sparse integer ids — loaders remap to 0..K-1.",
        ),
        failures=("Missing Torch extra, empty train, non-numeric columns, or NaNs in the design matrix.",),
        leakage=(
            "Fitting normalize on all rows, or shuffling validation/test into train batches, leaks evaluation signal.",
            "Ignoring group/time SplitPlan membership when building tensors outside make_torch_loaders.",
        ),
        anti_patterns=(
            "Treating loader construction as permission to skip a declared split.",
            "Expecting Polars/DuckDB zero-copy into DataLoaders in this slice.",
            "Assuming n_classes = max(label)+1 without contiguous remapping.",
        ),
        state_changes=("Stores torch loaders on the Session and appends loader metadata to history.",),
        result_reading=(
            "Check n_train/n_validation/n_test, split_kind, groups_disjoint/time_order_ok, "
            "normalize flag, classical plan disclosures, and warnings for empty holdout partitions.",
        ),
        next_steps=(
            "Call fit_torch (built-in MLP when module omitted), cross_validate_torch, "
            "or nested_cv_torch / search_torch for hyperparameter selection.",
        ),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "make_text_torch_loaders",
        OperationKind.MODEL,
        "Build token-id DataLoaders for text classification (sequence modality).",
        "Fit a train-only vocabulary and pad token sequences for embedding classifiers.",
        "Text / sequence Torch data boundary.",
        (
            "Resolve a text feature column and target.",
            "Fit vocabulary on the train partition only.",
            "Remap class ids to contiguous 0..K-1 (class_labels stores original ids).",
            "Encode padded token ids per partition with shuffle on train only.",
        ),
        parameters=(
            _p("text_column", "str | None", "Text feature column (inferred when unique)."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
        ),
        inputs=("Dataset with a string feature column, numeric target ids, and a SplitPlan.",),
        outputs=("TorchLoaderBundle with text_vocab / text_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch with a text classifier.",),
        alternatives=(
            "make_torch_loaders for numeric tabular tensors.",
            "make_multimodal_torch_loaders / make_image_multimodal_torch_loaders / "
            "make_audio_multimodal_torch_loaders when text must fuse with other modalities.",
        ),
        rationale=("Use when the modeling path is text/sequence rather than pure numeric tables.",),
        assumptions=(
            "Target labels are integer class ids (sparse ids remapped to contiguous 0..K-1); "
            "vocabulary must not see validation/test text.",
        ),
        failures=("Missing Torch extra, no text column, empty train, or non-numeric target.",),
        leakage=("Fitting vocabulary on all rows leaks holdout token identity into the model.",),
        anti_patterns=("Treating hashing RAG embeddings as a substitute for this supervised text path.",),
        state_changes=("Stores text Torch loaders on the Session.",),
        result_reading=("Check vocab size, max_len, partition sizes, and train-only vocab disclosure.",),
        next_steps=("fit_torch() without module to build the embedding text classifier.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_multimodal_torch_loaders",
        OperationKind.MODEL,
        "Build fused multimodal DataLoaders (tabular/text/image/audio) with train-only fit stats.",
        "Materialize (*modalities, y) batches for late-fusion training.",
        "Multimodal Torch data boundary (tabular ⊕ text ⊕ image ⊕ audio).",
        (
            "Resolve numeric, text, image, and/or audio feature columns (at least two modalities).",
            "Fit vocabulary on train text only when text is present.",
            "Fit numeric normalize stats on train only when enabled.",
            "Fit image channel mean/std on train only when image normalize is enabled.",
            "Fit audio amplitude mean/std on train only when audio normalize is enabled.",
            "Build per-partition DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("text_column", "str | None", "Text feature column (inferred when unique)."),
            _p("numeric_columns", "list[str] | None", "Numeric feature columns (default: numeric roles)."),
            _p("image_column", "str | None", "Image path or array feature column."),
            _p("audio_column", "str | None", "Audio path or waveform array feature column."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("normalize", "bool", "Fit numeric mean/std on train.", True),
            _p("normalize_images", "bool", "Fit image channel mean/std on train.", True),
            _p("normalize_audio", "bool", "Fit audio amplitude mean/std on train.", True),
            _p("image_size", "tuple[int, int]", "Resize height/width for image tensors.", (32, 32)),
            _p("image_channels", "int", "1 or 3 image channels.", 3),
            _p("audio_sample_rate", "int", "Target sample rate for audio tensors.", 16000),
            _p("audio_max_samples", "int", "Fixed waveform length (pad/truncate).", 16000),
            _p("audio_source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed.", 0),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p(
                "preprocess",
                "MultimodalContract | dict | None",
                "Frozen multimodal fit stats to restore (mutually exclusive with use_saved_preprocess).",
            ),
            _p(
                "use_saved_preprocess",
                "bool",
                "Reuse dl_train_result.multimodal_preprocess when True.",
                False,
            ),
        ),
        inputs=(
            "Dataset with a valid modality mix (any two+ of tabular/text/image/audio), "
            "target, and SplitPlan.",
        ),
        outputs=("TorchLoaderBundle with multimodal_contract / text_vocab / modality metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch fusion auto-build.",),
        alternatives=(
            "make_image_multimodal_torch_loaders when an image column is required up front.",
            "make_audio_multimodal_torch_loaders when an audio column is required up front.",
            "make_torch_loaders or make_text_torch_loaders for single-modality paths.",
        ),
        rationale=("Use when modalities should share one supervised fusion head.",),
        assumptions=(
            "Text is string-like; numeric columns are numeric; image/audio cells are paths or "
            "arrays; target is encoded.",
        ),
        failures=(
            "Missing Torch extra, invalid modality mix, empty train, non-numeric target, "
            "missing Pillow for path images, or missing soundfile for path audio.",
        ),
        leakage=(
            "Fitting vocab, numeric normalize, image channel stats, or audio amplitude stats "
            "on all rows leaks holdout signal into fusion.",
        ),
        anti_patterns=(
            "Claiming Whisper-scale speech foundation-model quality from the small 1D-CNN branch.",
            "Fitting media normalize stats on the full frame outside make_multimodal_torch_loaders.",
        ),
        state_changes=("Stores multimodal Torch loaders on the Session.",),
        result_reading=(
            "Check modality, input_layout, vocab size, numeric columns, image_column, "
            "audio_column, and train-only disclosures.",
        ),
        next_steps=("fit_torch() without module to build MultimodalFusion.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_image_multimodal_torch_loaders",
        OperationKind.MODEL,
        "Build image multimodal DataLoaders (image ⊕ tabular and/or text and/or audio).",
        "Require an image column and materialize fused batches with train-only image stats.",
        "Image multimodal Torch data boundary.",
        (
            "Require image_column (path or array cells).",
            "Optionally resolve text, numeric, and audio companions.",
            "Fit image channel mean/std on train only when enabled.",
            "Fit text vocab / numeric / audio normalize on train only when present.",
            "Build per-partition DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("image_column", "str", "Image path or array feature column (required)."),
            _p("text_column", "str | None", "Optional text feature column."),
            _p("numeric_columns", "list[str] | None", "Numeric feature columns (default: numeric roles)."),
            _p("audio_column", "str | None", "Optional audio path or waveform feature column."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row when text is present.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("normalize", "bool", "Fit numeric mean/std on train.", True),
            _p("normalize_images", "bool", "Fit image channel mean/std on train.", True),
            _p("normalize_audio", "bool", "Fit audio amplitude mean/std on train.", True),
            _p("image_size", "tuple[int, int]", "Resize height/width for image tensors.", (32, 32)),
            _p("image_channels", "int", "1 or 3 image channels.", 3),
            _p("audio_sample_rate", "int", "Target sample rate for audio tensors.", 16000),
            _p("audio_max_samples", "int", "Fixed waveform length (pad/truncate).", 16000),
            _p("audio_source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed.", 0),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
        ),
        inputs=(
            "Dataset with an image feature plus tabular and/or text and/or audio, target, "
            "and SplitPlan.",
        ),
        outputs=("TorchLoaderBundle with image multimodal_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch fusion auto-build.",),
        alternatives=(
            "make_multimodal_torch_loaders with image_column= for the same path.",
            "make_audio_multimodal_torch_loaders when audio is the required media column.",
        ),
        rationale=("Use when images must fuse with tabular and/or text and/or audio under one head.",),
        assumptions=("Image cells are paths (Pillow) or arrays; companions and target are valid.",),
        failures=("Missing image_column, invalid mix, empty train, or missing Torch/Pillow.",),
        leakage=("Fitting image channel stats on holdout rows leaks evaluation signal.",),
        anti_patterns=("Treating the small CNN branch as a production vision foundation model.",),
        state_changes=("Stores image multimodal Torch loaders on the Session.",),
        result_reading=("Check modality, image_column, image_mean/std, and input_layout.",),
        next_steps=("fit_torch() without module to build the image-capable MultimodalFusion.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_audio_multimodal_torch_loaders",
        OperationKind.MODEL,
        "Build audio multimodal DataLoaders (audio ⊕ tabular and/or text and/or image).",
        "Require an audio column and materialize fused batches with train-only audio stats.",
        "Audio multimodal Torch data boundary.",
        (
            "Require audio_column (path or waveform array cells).",
            "Optionally resolve text, numeric, and image companions.",
            "Fit audio amplitude mean/std on train only when enabled.",
            "Fit text vocab / numeric / image normalize on train only when present.",
            "Build per-partition DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("audio_column", "str", "Audio path or waveform array feature column (required)."),
            _p("text_column", "str | None", "Optional text feature column."),
            _p("numeric_columns", "list[str] | None", "Numeric feature columns (default: numeric roles)."),
            _p("image_column", "str | None", "Optional image path or array feature column."),
            _p("batch_size", "int", "Rows per batch.", 16),
            _p("max_len", "int", "Maximum tokens per row when text is present.", 64),
            _p("max_vocab", "int", "Vocabulary cap excluding pad/unk.", 5000),
            _p("min_freq", "int", "Minimum token frequency on train.", 1),
            _p("normalize", "bool", "Fit numeric mean/std on train.", True),
            _p("normalize_images", "bool", "Fit image channel mean/std on train.", True),
            _p("normalize_audio", "bool", "Fit audio amplitude mean/std on train.", True),
            _p("image_size", "tuple[int, int]", "Resize height/width for image tensors.", (32, 32)),
            _p("image_channels", "int", "1 or 3 image channels.", 3),
            _p("audio_sample_rate", "int", "Target sample rate for audio tensors.", 16000),
            _p("audio_max_samples", "int", "Fixed waveform length (pad/truncate).", 16000),
            _p("audio_source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed.", 0),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
        ),
        inputs=(
            "Dataset with an audio feature plus tabular and/or text and/or image, target, "
            "and SplitPlan.",
        ),
        outputs=("TorchLoaderBundle with audio multimodal_contract metadata.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split / label encoding; before fit_torch fusion auto-build.",),
        alternatives=(
            "make_multimodal_torch_loaders with audio_column= for the same path.",
            "make_image_multimodal_torch_loaders when image is the required media column.",
        ),
        rationale=("Use when waveforms must fuse with tabular and/or text and/or image under one head.",),
        assumptions=(
            "Audio cells are paths (soundfile) or waveforms; companions and target are valid.",
        ),
        failures=(
            "Missing audio_column, invalid mix, empty train, or missing Torch/soundfile.",
        ),
        leakage=("Fitting audio amplitude stats on holdout rows leaks evaluation signal.",),
        anti_patterns=(
            "Claiming Whisper-scale ASR / speech foundation-model quality from this alpha path.",
        ),
        state_changes=("Stores audio multimodal Torch loaders on the Session.",),
        result_reading=("Check modality, audio_column, audio_mean/std, and input_layout.",),
        next_steps=("fit_torch() without module to build the audio-capable MultimodalFusion.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "fit_torch",
        OperationKind.MODEL,
        "Train a Torch nn.Module (built-in MLP/text/multimodal including image/audio when omitted).",
        "Run a leakage-scoped supervised epoch loop and store a Torch TrainResult.",
        "Torch supervised training boundary.",
        (
            "Require or build Torch loaders.",
            "When module is omitted, build tabular MLP, text classifier, or multimodal fusion "
            "(tabular/text/image/audio mixes).",
            "Resolve device with explicit CPU fallback when CUDA/MPS are unavailable.",
            "Run epoch steps with optional AMP, validation loss, scheduler, grad clip, early stopping.",
            "When resume=True, restore optimizer/scheduler state from dl_train_result and append history.",
        ),
        parameters=(
            _p("module", "torch.nn.Module | None", "Optional network; built-in zoo when omitted."),
            _p("loss_fn", "callable | None", "Optional (module, xb, yb) -> loss."),
            _p("optimizer_factory", "callable | None", "Optional params -> optimizer factory."),
            _p("epochs", "int", "Epochs when config omitted; additional epochs if resume=True.", 5),
            _p("learning_rate", "float", "Adam learning rate when config is omitted.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("grad_clip_norm", "float | None", "Optional gradient-norm clip (default None=off)."),
            _p("log_every", "int", "Record history every N epochs.", 1),
            _p(
                "early_stopping_patience",
                "int | None",
                "Stop after N non-improving validation epochs (default None=off).",
            ),
            _p("early_stopping_monitor", "str", "Metric key for early stop (default val_loss).", "val_loss"),
            _p(
                "scheduler",
                "none | step | plateau | cosine",
                "LR schedule (default none).",
                "none",
            ),
            _p("resume", "bool", "Continue from dl_train_result / loaded bundle.", False),
            _p("config", "TrainConfig | None", "Optional full train config overriding scalar knobs."),
            _p("hidden", "tuple[int, ...]", "Hidden widths for built-in tabular MLP when module omitted.", (64, 32)),
            _p("dropout", "float", "Dropout for built-in models when module omitted.", 0.1),
            _p("mixed_precision", "bool", "Enable CUDA AMP when True (CPU/MPS no-op).", False),
        ),
        inputs=("TorchLoaderBundle, nn.Module, and optional loss/optimizer factories.",),
        outputs=("Session with dl_train_result (TrainResult) distinct from classical fit_result.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_torch_loaders (auto-built if missing); before evaluate_torch / save_torch_bundle.",),
        alternatives=("Use Session.fit for sklearn estimators; do not mix result slots silently.",),
        rationale=("Choose Torch when the model is an nn.Module rather than a sklearn estimator.",),
        assumptions=("Train loader rows match the intended supervised task and feature contract.",),
        failures=(
            "Missing Torch extra, empty train loader, early stop without validation, "
            "shape mismatches, or optimizer/loss errors.",
        ),
        leakage=("Training without a split, or using test batches inside the train loop, invalidates holdout claims.",),
        anti_patterns=(
            "Reporting train loss as expected production performance.",
            "Tuning stopping rules on the test partition (see early-stopping-partition).",
        ),
        state_changes=("Stores dl_train_result; classical fit_result is unchanged.",),
        result_reading=(
            "Inspect device.resolved, early_stop reason/partition, scheduler_name, "
            "training_curve disclosures, and epoch history.",
        ),
        next_steps=(
            "torch_training_curve for structured teaching data; evaluate_torch on validation or test; "
            "save_torch_bundle for weights; cross_validate_torch for fold-local estimates.",
        ),
        concepts=(
            "leakage-boundary",
            "batch-leakage",
            "early-stopping-partition",
            "training-curves",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "cross_validate_torch",
        OperationKind.DIAGNOSTIC,
        "Fold-local Torch cross-validation on numeric tabular features.",
        "Train a fresh module per fold with train-only normalize stats.",
        "Torch fold-local CV boundary.",
        (
            "Split indices into folds (optionally stratified).",
            "Fit normalize stats on each fold's train indices only.",
            "Train a fresh module (default tabular MLP) and score the held-out fold.",
            "Aggregate mean/std metrics with explicit nested-CV limitations.",
        ),
        parameters=(
            _p("n_folds", "int", "Number of folds.", 3),
            _p("epochs", "int", "Epochs per fold.", 3),
            _p("batch_size", "int", "Batch size.", 32),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Per-fold train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p(
                "module_factory",
                "callable | None",
                "Optional (n_features, task, n_classes) -> fresh nn.Module per fold.",
            ),
        ),
        inputs=("Dataset with numeric features and a target (split optional; CV makes its own folds).",),
        outputs=("TorchCVResult with per-fold and mean metrics plus limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles (and optional classical prep); beside fit_torch for a single split.",),
        alternatives=(
            "Classical Session.cross_validate for sklearn estimators.",
            "nested_cv_torch when inner hyperparameter search is required.",
        ),
        rationale=("Use when you need fold-local Torch estimates without an inner search loop.",),
        assumptions=("Features/targets are numeric; module_factory builds a fresh module each fold.",),
        failures=("Missing Torch extra, too few rows for n_folds, or non-numeric design matrix.",),
        leakage=(
            "Fitting normalize or vocab on all rows before folding leaks holdout signal.",
            "Refitting Session-global classical plans outside fold-local apply_session_plans.",
        ),
        anti_patterns=(
            "Calling this nested CV when no inner hyperparameter loop ran.",
            "Reporting mean fold accuracy as production readiness without holdout.",
        ),
        state_changes=("Stores dl_cv_result; does not replace dl_train_result.",),
        result_reading=("Read mean_metrics, limitations (not nested), and per-fold warnings.",),
        next_steps=(
            "nested_cv_torch for nested search; fit_torch on a declared split for the final trainer.",
        ),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "search_torch",
        OperationKind.DIAGNOSTIC,
        "Inner-fold Torch hyperparameter search on the Session train universe.",
        "Rank MLP knobs with fold-local normalize; never score Session test rows.",
        "Torch inner search boundary.",
        (
            "Resolve train universe (respect Session split when present).",
            "Expand grid or sample distributions.",
            "Score each trial with fold-local train-only normalize.",
            "Return ranked trials with limitations (not nested outer estimate).",
        ),
        parameters=(
            _p("param_grid", "dict | None", "Grid of searchable knobs (lr/hidden/dropout/…)."),
            _p("param_distributions", "dict | None", "Distributions for randomized search."),
            _p("inner_search", "grid | randomized | auto", "Search method.", "auto"),
            _p("n_iter", "int", "Randomized trial count.", 5),
            _p("n_folds", "int", "Inner folds.", 3),
            _p("epochs", "int", "Epochs per trial fold.", 2),
            _p("batch_size", "int", "Default batch size.", 32),
            _p("learning_rate", "float", "Default Adam LR.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Per-fold train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p("scoring_metric", "str | None", "Rank metric (default accuracy or mse)."),
            _p("module_factory", "callable | None", "(n_features, task, n_classes, params) -> module."),
        ),
        inputs=("Dataset with numeric features/target; optional SplitPlan.",),
        outputs=("TorchSearchResult with ranked trials, best_params, limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles/split; before nested_cv_torch or final fit_torch.",),
        alternatives=("nested_cv_torch for outer generalization after search.",),
        rationale=("Use to pick Torch knobs without peeking at Session test.",),
        assumptions=("Search space covers tabular MLP knobs unless module_factory overrides.",),
        failures=("Missing search space, missing Torch, or non-numeric target.",),
        leakage=("Scoring trials on Session test/validation would invalidate holdout claims.",),
        anti_patterns=("Treating search_torch ranks as a nested outer estimate.",),
        state_changes=("Stores dl_search_result.",),
        result_reading=("Read best_params, limitations, and held_out_partitions.",),
        next_steps=("nested_cv_torch for honest outer estimate; fit_torch with chosen knobs.",),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "nested_cv_torch",
        OperationKind.DIAGNOSTIC,
        "Nested Torch CV: outer evaluation after fold-local inner hyperparameter search.",
        "Estimate generalization after selection without leaking outer-eval rows into search.",
        "Torch nested CV boundary.",
        (
            "Split outer folds on the train universe.",
            "Run inner search on each outer-train subset only.",
            "Refit the winning config on outer-train with fold-local normalize.",
            "Score each outer-eval fold once and aggregate mean/std metrics.",
        ),
        parameters=(
            _p("param_grid", "dict | None", "Grid of searchable knobs."),
            _p("param_distributions", "dict | None", "Distributions for randomized search."),
            _p("inner_search", "grid | randomized | auto", "Inner search method.", "auto"),
            _p("n_iter", "int", "Randomized trial count.", 5),
            _p("outer_cv", "int", "Outer folds.", 3),
            _p("inner_cv", "int", "Inner folds.", 2),
            _p("epochs", "int", "Epochs per fit.", 2),
            _p("batch_size", "int", "Default batch size.", 32),
            _p("learning_rate", "float", "Default Adam LR.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Preferred device.", "auto"),
            _p("normalize", "bool", "Fold-local train-fit mean/std.", True),
            _p("seed", "int", "RNG seed.", 0),
            _p("stratify", "bool", "Stratify classification folds when possible.", True),
            _p("task", "classification | regression | auto", "Task interpretation.", "auto"),
            _p("scoring_metric", "str | None", "Rank/eval metric (default accuracy or mse)."),
            _p("module_factory", "callable | None", "(n_features, task, n_classes, params) -> module."),
        ),
        inputs=("Dataset with numeric features/target; optional SplitPlan.",),
        outputs=("TorchNestedCVResult with outer metrics, per-fold winners, limitations.",),
        prerequisites=(DATASET, ROLES, TORCH),
        ordering=("After roles/split; beside classical nested_cv_score for sklearn.",),
        alternatives=("search_torch for inner-only selection; cross_validate_torch without search.",),
        rationale=("Use when Torch hyperparameter selection needs an outer honesty estimate.",),
        assumptions=("Alpha epoch budgets make ranks noisy; refit chosen knobs on full train after.",),
        failures=("Missing search space, too few rows, or missing Torch extra.",),
        leakage=("Outer-eval rows in inner ranking, or Session test in either loop, is refused.",),
        anti_patterns=("Deploying consensus_params without an explicit final refit decision.",),
        state_changes=("Stores dl_nested_cv_result.",),
        result_reading=("Read mean_metrics, best_params_per_fold, consensus_params, limitations.",),
        next_steps=("fit_torch with an explicit chosen config; export_torch / save_torch_bundle.",),
        concepts=("leakage-boundary", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "export_torch",
        OperationKind.PERSIST,
        "Export the last Torch trainer to TorchScript or ONNX.",
        "Produce an alpha-quality portable artifact from example train-loader inputs.",
        "Torch export escape hatch.",
        (
            "Resolve example inputs from loaders or caller.",
            "Trace/script (TorchScript) or torch.onnx.export (ONNX).",
            "Record opset/dynamic axes and honest limitations.",
        ),
        parameters=(
            _p("path", "str | Path", "Destination file path.", required=True),
            _p("format", "torchscript | onnx", "Export format.", "torchscript"),
            _p("opset", "int", "ONNX opset version.", 17),
            _p("dynamic_batch", "bool", "Mark batch dim dynamic for ONNX.", True),
            _p("example_input", "Any | None", "Optional override example tensor/tuple."),
        ),
        inputs=("Active dl_train_result and example inputs / torch loaders.",),
        outputs=("ExportResult with path, format, disclosures, limitations.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After fit_torch / evaluate_torch; beside save_torch_bundle.",),
        alternatives=("save_torch_bundle for BuildML trainer resume; serving stacks separately.",),
        rationale=("Use when another runtime needs TorchScript/ONNX, not a trainer bundle.",),
        assumptions=("Example batch shapes cover the ops you need at inference time.",),
        failures=("No trainer, export op failure, or missing Torch extra.",),
        leakage=("Exported weights can retain training-data patterns; control access.",),
        anti_patterns=(
            "Treating export alone as a full production serving stack — use serve_bundle / "
            "buildml-serve for the library-owned local server path.",
        ),
        state_changes=("Writes an artifact file; stores dl_export_result.",),
        result_reading=("Read format/opset/dynamic_axes and limitations before deploying.",),
        next_steps=(
            "Smoke-load TorchScript/ONNX in the target runtime; keep trainer bundle too; "
            "optional serve_bundle(kind='torchscript') for local HTTP.",
        ),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "fit_torch_ddp",
        OperationKind.MODEL,
        "DistributedDataParallel training via a module_factory (single-node or multi-node).",
        "Shard the train loader across ranks and return the rank-0 TrainResult.",
        "Torch DDP boundary (spawn or torchrun join).",
        (
            "Require torch loaders and a picklable module_factory (single-node spawn).",
            "Single-node: spawn one process per rank (NCCL when >=2 CUDA devices).",
            "Multi-node: multi_node=True joins torchrun env (WORLD_SIZE/RANK/LOCAL_RANK/MASTER_*).",
            "Shard train batches; collect rank-0 TrainResult.",
        ),
        parameters=(
            _p("module_factory", "callable", "Zero-arg fresh nn.Module factory per process.", required=True),
            _p("epochs", "int", "Epochs when config omitted.", 5),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("mixed_precision", "bool", "CUDA AMP when True.", False),
            _p("world_size", "int | None", "Process count for single-node (default = CUDA device count)."),
            _p("allow_cpu_ddp", "bool", "Permit gloo CPU smoke (not a perf path).", False),
            _p("multi_node", "bool", "Join torchrun multi-node rendezvous instead of local spawn.", False),
            _p("config", "TrainConfig | None", "Optional full train config."),
        ),
        inputs=("TorchLoaderBundle and a picklable module_factory (or per-rank loaders under torchrun).",),
        outputs=("DDPTrainResult; also stores dl_train_result from rank 0.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_torch_loaders; alternative to single-process fit_torch.",),
        alternatives=("fit_torch for single-process training.",),
        rationale=("Use when single-node multi-GPU or torchrun multi-node scale is needed in alpha.",),
        assumptions=(
            "Single-node datasets are picklable under spawn.",
            "Multi-node requires complete torchrun env; not a Kubernetes multi-cluster product.",
        ),
        failures=(
            "Fewer than two CUDA devices without allow_cpu_ddp (single-node).",
            "Missing WORLD_SIZE/RANK/LOCAL_RANK/MASTER_ADDR/MASTER_PORT when multi_node=True.",
            "Spawn/pickle errors on single-node.",
        ),
        leakage=("Same split/normalize rules as fit_torch; DDP does not invent holdouts.",),
        anti_patterns=(
            "Claiming Kubernetes multi-cluster orchestration from this torchrun helper.",
            "Enabling CPU multi-process without allow_cpu_ddp and treating it as production scale.",
        ),
        state_changes=("Stores dl_ddp_result and dl_train_result.",),
        result_reading=("Read backend, world_size, mode (single_node/multi_node), warnings, and limitations.",),
        next_steps=("evaluate_torch; export_torch / save_torch_bundle.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions"),
    ),
    _operation(
        "make_speech_torch_loaders",
        OperationKind.MODEL,
        "Build speech classification DataLoaders from an audio feature column.",
        "Prepare waveforms for finetune-lite speech classification under a leakage-safe split.",
        "Speech classify loader boundary.",
        (
            "Resolve audio_column and target roles.",
            "Decode path/waveform cells to fixed-length mono tensors.",
            "Fit optional train-only amplitude mean/std.",
            "Remap class ids to contiguous 0..K-1 (class_labels stores original ids).",
            "Construct DataLoaders with shuffle on train only.",
        ),
        parameters=(
            _p("audio_column", "str | None", "Audio path or waveform feature column."),
            _p("batch_size", "int", "Rows per batch.", 8),
            _p("sample_rate", "int", "Target sample rate.", 16000),
            _p("max_samples", "int", "Fixed waveform length (repeat-pad short clips).", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("normalize_audio", "bool", "Fit amplitude mean/std on train.", True),
            _p("encoder_dim", "int", "Tiny encoder embedding width for fit_speech_torch.", 64),
            _p("shuffle_train", "bool", "Shuffle the train loader only.", True),
            _p("seed", "int", "Generator seed for train shuffling.", 0),
        ),
        inputs=("Dataset with roles, SplitPlan, and an audio feature column.",),
        outputs=("TorchLoaderBundle with modality=speech_classify.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After split; before fit_speech_torch / fit_torch.",),
        alternatives=(
            "make_audio_multimodal_torch_loaders for small 1D-CNN fusion with tabular/text/image.",
            "transcribe_speech for ASR text generation without classification training.",
        ),
        rationale=("Use when fine-tuning a tiny speech encoder head on labeled audio.",),
        assumptions=(
            "Targets are numeric class ids (sparse ids remapped to contiguous 0..K-1); "
            "audio cells are paths or waveforms.",
        ),
        failures=("Missing Torch extra, empty train, non-numeric labels, or bad audio cells.",),
        leakage=("Fitting amp stats on all rows, or ignoring SplitPlan membership, leaks evaluation signal.",),
        anti_patterns=(
            "Calling this path 'train Whisper from scratch'.",
            "Expecting Hugging Face weights without buildml[speech] / transcribe_speech transformers backend.",
        ),
        state_changes=("Stores torch loaders on the Session.",),
        result_reading=("Check modality, n_train/n_validation/n_test, and train-only normalize disclosures.",),
        next_steps=("fit_speech_torch or fit_torch; evaluate_torch; optional transcribe_speech for ASR.",),
        concepts=("leakage-boundary", "batch-leakage", "evaluation-partitions", "data-splitting"),
    ),
    _operation(
        "fit_speech_torch",
        OperationKind.MODEL,
        "Fine-tune a tiny speech encoder + classifier head (finetune-lite).",
        "Train a small speech classifier under the Session split — not a foundation model from scratch.",
        "Speech finetune-lite training boundary.",
        (
            "Build speech loaders when missing.",
            "Construct tiny 1D-CNN encoder + linear head.",
            "Run the supervised train loop on train (optional freeze_encoder).",
        ),
        parameters=(
            _p("epochs", "int", "Training epochs.", 5),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Compute device.", "auto"),
            _p("freeze_encoder", "bool", "Train head only when True.", False),
            _p("audio_column", "str | None", "Audio column when loaders must be built."),
            _p("batch_size", "int", "Loader batch size when building loaders.", 8),
            _p("sample_rate", "int", "Target sample rate.", 16000),
            _p("max_samples", "int", "Fixed waveform length.", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("normalize_audio", "bool", "Train-only amplitude normalize.", True),
            _p("encoder_dim", "int", "Encoder embedding width.", 64),
            _p("seed", "int", "Loader/train seed.", 0),
        ),
        inputs=("Speech TorchLoaderBundle or roles+split+audio column.",),
        outputs=("Session with dl_train_result from speech finetune-lite.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_speech_torch_loaders (or builds them); before evaluate_torch.",),
        alternatives=("fit_torch after make_speech_torch_loaders; multimodal audio fusion for mixed modalities.",),
        rationale=("Use for labeled audio classification with a tiny encoder head.",),
        assumptions=("SplitPlan is fixed; amp stats stay train-only.",),
        failures=("Missing Torch, empty train, or non-numeric class labels.",),
        leakage=("Refitting loaders on test labels or amp stats across all rows.",),
        anti_patterns=("Marketing this as Whisper-scale foundation-model training.",),
        state_changes=("Stores dl_train_result and speech torch loaders.",),
        result_reading=("Read history, device, and disclosures that this is finetune-lite.",),
        next_steps=("evaluate_torch; save_torch_bundle; optional export_torch.",),
        concepts=("leakage-boundary", "evaluation-partitions"),
    ),
    _operation(
        "transcribe_speech",
        OperationKind.MODEL,
        "ASR transcription for an audio feature column (stub or transformers).",
        "Generate transcripts via stub (CI-safe) or Whisper-class transformers pipelines.",
        "Speech ASR inference boundary.",
        (
            "Resolve audio_column cells (optional split partition).",
            "Run stub fingerprint ASR or transformers automatic-speech-recognition pipeline.",
            "Return SpeechTranscribeResult texts + disclosures.",
        ),
        parameters=(
            _p("audio_column", "str", "Audio path or waveform feature column.", required=True),
            _p("backend", "stub | transformers", "ASR backend.", "stub"),
            _p("model_id", "str | None", "Hugging Face model id when backend=transformers."),
            _p("sample_rate", "int", "Decode sample rate.", 16000),
            _p("max_samples", "int", "Decode length cap.", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for arrays."),
            _p("partition", "train | validation | test | all", "Rows to transcribe.", "all"),
        ),
        inputs=("Dataset with an audio feature column; SplitPlan when partition != all.",),
        outputs=("SpeechTranscribeResult stored as dl_speech_result.",),
        prerequisites=(DATASET,),
        ordering=("Anytime after ingest; often beside speech classify training.",),
        alternatives=("External ASR services; make_speech_torch_loaders for classify finetune.",),
        rationale=("Use when you need ASR text from Session audio cells.",),
        assumptions=(
            "stub backend needs no Torch/transformers; transformers backend needs buildml[speech] "
            "and may download weights; stub is not real ASR quality.",
        ),
        failures=("Missing speech extra for transformers, bad audio cells, incomplete split for partition.",),
        leakage=("Transcribing holdout audio is fine; do not refit classify stats on those texts without a plan.",),
        anti_patterns=("Treating stub transcripts as production ASR; claiming FM-from-scratch training.",),
        state_changes=("Stores dl_speech_result; does not mutate the dataset frame.",),
        result_reading=("Read backend, model_id, disclosures, and limitations before trusting texts.",),
        next_steps=("Optional: attach transcripts as a text feature and continue classical/Torch paths.",),
        concepts=("leakage-boundary", "evaluation-partitions"),
    ),
    _operation(
        "serve_bundle",
        OperationKind.EXPORT,
        "Launch BuildML managed local model serving for a pipeline or TorchScript artifact.",
        "Expose /health and /predict via FastAPI (optional API-key/Bearer middleware).",
        "Managed serving boundary (CLI/Session-primary; intentionally not an AI tool).",
        (
            "Load classical pipeline bundle or TorchScript file.",
            "Optionally attach API-key/Bearer middleware when api_keys is set.",
            "Refuse non-loopback binds without api_keys unless allow_insecure_public_bind.",
            "Bind FastAPI/uvicorn (default 127.0.0.1).",
            "Serve /health and /predict until stopped.",
        ),
        parameters=(
            _p("path", "str | Path | None", "Bundle/TorchScript path (or last save_pipeline path)."),
            _p("kind", "pipeline | torchscript", "Artifact kind.", "pipeline"),
            _p("host", "str", "Bind host (default localhost).", "127.0.0.1"),
            _p("port", "int", "Bind port.", 8080),
            _p("title", "str", "Service title.", "BuildML Serve"),
            _p("blocking", "bool", "Block current thread when True.", False),
            _p("api_keys", "str | list[str] | None", "API key(s) for Bearer / X-API-Key; required off-loopback."),
            _p(
                "allow_insecure_public_bind",
                "bool",
                "Dangerous override to bind non-loopback without api_keys.",
                False,
            ),
            _p("ssl_certfile", "str | Path | None", "Optional local TLS certificate path."),
            _p("ssl_keyfile", "str | Path | None", "Optional local TLS private key path."),
            _p(
                "trusted",
                "bool",
                "Required True to deserialize pickle/joblib/TorchScript payloads.",
                False,
            ),
        ),
        inputs=("Saved pipeline bundle directory or TorchScript file.",),
        outputs=("ServeHandle with url; process-local server thread.",),
        prerequisites=(),
        ordering=("After save_pipeline or export_torch TorchScript; deployment-adjacent.",),
        alternatives=("buildml-serve CLI / python -m buildml.serving; reverse-proxy in front.",),
        rationale=(
            "Use for local/demo managed serving of BuildML artifacts. "
            "Not registered in the AI tool allowlist (network listener / CLI-primary)."
        ,),
        assumptions=(
            "Optional API-key middleware is library-local auth — not managed IAM/cloud identity.",
            "Prefer TLS termination at a reverse proxy for non-local exposure.",
            "trusted=True means you accept pickle/TorchScript execution risk for this artifact.",
            "Localhost defaults stay open-with-honesty; public binds need keys or a loud override.",
        ),
        failures=(
            "Missing buildml[serve], bad bundle path, port in use, or non-loopback bind "
            "without api_keys / allow_insecure_public_bind.",
        ),
        leakage=("Serving trained weights can retain training-data patterns; control access.",),
        anti_patterns=(
            "Exposing bare 0.0.0.0 without api_keys or a reverse proxy.",
            "Using allow_insecure_public_bind in production.",
            "Claiming a managed cloud product from this local server.",
            "Claiming Kubernetes multi-cluster orchestration from this local server.",
            "Expecting the AI operator to call serve_bundle — use CLI/Session instead.",
        ),
        state_changes=("Stores serve handle; starts a background (or blocking) server.",),
        result_reading=("Read url/kind and /health auth flag before clients call /predict.",),
        next_steps=("PUT a reverse proxy (TLS) in front for non-local use; stop() the handle when done.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "load_pretrained_backbone",
        OperationKind.MODEL,
        "Load a curated vision/audio/speech pretrained backbone hook.",
        "Integration load of ResNet/ViT, Wav2Vec2, or Whisper-encoder with freeze/finetune controls.",
        "Pretrained backbone boundary.",
        (
            "Resolve modality + architecture.",
            "Construct backbone with weights=none|mock|pretrained.",
            "Optionally freeze parameters for linear-probe / head finetune.",
        ),
        parameters=(
            _p("modality", "vision | audio | speech", "Backbone modality.", required=True),
            _p("architecture", "str | None", "Optional architecture id (defaults per modality)."),
            _p("weights", "none | mock | pretrained", "Weight mode (mock is CI-safe default).", "mock"),
            _p("freeze", "bool", "Freeze backbone parameters when True.", True),
            _p("seed", "int", "Seed for mock weight init.", 0),
            _p("model_id", "str | None", "Optional Hugging Face model id for audio/speech."),
        ),
        inputs=("Optional Torch / torchvision / transformers extras depending on modality.",),
        outputs=("PretrainedBackbone stored as dl_backbone.",),
        prerequisites=(TORCH,),
        ordering=("Before attaching a custom head / fit_torch; beside speech/vision loaders.",),
        alternatives=("Caller-supplied nn.Module; built-in tiny speech encoder via fit_speech_torch.",),
        rationale=("Use when you need a real backbone hook without claiming a full zoo product.",),
        assumptions=("mock/none avoid large downloads; pretrained may fetch weights.",),
        failures=("Missing torchvision/transformers extras, unknown architecture.",),
        leakage=("Pretrained weights encode upstream data; disclose when claiming domain fit.",),
        anti_patterns=(
            "Calling this a full Hugging Face / TorchVision zoo product.",
            "Claiming foundation-model training from scratch.",
        ),
        state_changes=("Stores dl_backbone on the Session.",),
        result_reading=("Read weight_mode, frozen, feature_dim, disclosures, limitations.",),
        next_steps=("attach_backbone_head then fit_torch, or export_torch for serving packs.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "pack_torchserve",
        OperationKind.PERSIST,
        "Pack a TorchScript file into a TorchServe-ready model directory.",
        "Write model.pt, handler, config.properties, and manifest — does not run TorchServe.",
        "TorchServe packaging boundary.",
        (
            "Resolve TorchScript path (explicit or last export_torch).",
            "Copy artifact and write handler/config/manifest + archive hints.",
        ),
        parameters=(
            _p("output_dir", "str | Path", "Destination directory.", required=True),
            _p("torchscript_path", "str | Path | None", "TorchScript file (or last export)."),
            _p("model_name", "str", "TorchServe model name.", "buildml_model"),
        ),
        inputs=("TorchScript artifact from export_torch or an external .pt.",),
        outputs=("PackagingResult with files list and honesty limitations.",),
        prerequisites=(TORCH,),
        ordering=("After export_torch(format='torchscript'); deployment-adjacent.",),
        alternatives=("serve_bundle for the library-owned FastAPI path.",),
        rationale=("Use when an operator will run TorchServe themselves.",),
        assumptions=("TorchServe / torch-model-archiver are operator-installed.",),
        failures=("Missing TorchScript path / prior export.",),
        leakage=("Packaged weights can retain training-data patterns; control access.",),
        anti_patterns=("Claiming BuildML runs a TorchServe cloud or managed inference product.",),
        state_changes=("Writes a directory; stores dl_packaging_result.",),
        result_reading=("Read files + ARCHIVE.txt hints before archiving with torch-model-archiver.",),
        next_steps=("Run torch-model-archiver / torchserve outside BuildML; or use serve_bundle.",),
        concepts=("reproducibility",),
    ),
    _operation(
        "prepare_tensorrt_export",
        OperationKind.PERSIST,
        "Write a TensorRT trtexec plan next to a validated ONNX artifact.",
        "Validate ONNX when possible and emit a recipe — does not build TensorRT engines.",
        "TensorRT plan boundary.",
        (
            "Resolve ONNX path (explicit or last export_torch).",
            "Optional onnx.checker validation.",
            "Write tensorrt_plan.json + TENSORRT.md (+ ONNX copy).",
        ),
        parameters=(
            _p("output_dir", "str | Path", "Destination directory.", required=True),
            _p("onnx_path", "str | Path | None", "ONNX file (or last export)."),
            _p("engine_name", "str", "Suggested engine filename.", "model.engine"),
            _p("fp16", "bool", "Include --fp16 in the example trtexec command.", True),
        ),
        inputs=("ONNX artifact from export_torch or an external .onnx.",),
        outputs=("PackagingResult describing the plan directory.",),
        prerequisites=(TORCH,),
        ordering=("After export_torch(format='onnx'); deployment-adjacent.",),
        alternatives=("Run TensorRT tooling directly on an ONNX file.",),
        rationale=("Use when an operator will build TensorRT engines themselves.",),
        assumptions=("TensorRT / trtexec are operator-installed; BuildML does not ship them.",),
        failures=("Missing ONNX path / prior export.",),
        leakage=("Exported engines inherit model memorization risks; control access.",),
        anti_patterns=("Claiming TensorRT-as-a-platform or a managed GPU cloud from this helper.",),
        state_changes=("Writes a directory; stores dl_packaging_result.",),
        result_reading=("Read tensorrt_plan.json trtexec_example and limitations.",),
        next_steps=("Run trtexec on target hardware; validate accuracy/latency.",),
        concepts=("reproducibility",),
    ),
    _operation(
        "emit_k8s_ddp_job",
        OperationKind.EXPORT,
        "Emit a Kubernetes Job YAML for torchrun multi-node DDP.",
        "Render an Indexed Job + Service (+ optional ConfigMap) template — not live multi-cluster orchestration.",
        "K8s torchrun template boundary.",
        (
            "Render Job+Service YAML with nnodes / nproc_per_node / image / script_path.",
            "Optionally include a ConfigMap and GPU/CPU resource knobs.",
            "Write the YAML to the requested path.",
        ),
        parameters=(
            _p("path", "str | Path", "Output YAML path.", required=True),
            _p("job_name", "str", "Kubernetes Job name.", "buildml-torchrun-ddp"),
            _p("namespace", "str", "Kubernetes namespace.", "default"),
            _p("image", "str", "Container image."),
            _p("nnodes", "int", "Number of nodes / Job completions.", 2),
            _p("nproc_per_node", "int", "Processes per node.", 2),
            _p("script_path", "str", "Training script path inside the container.", "/workspace/train.py"),
            _p("cpu_request", "str", "CPU request.", "2"),
            _p("memory_request", "str", "Memory request.", "4Gi"),
            _p("gpu_limit", "int", "nvidia.com/gpu limit.", 1),
            _p("gpu_request", "int | None", "Optional nvidia.com/gpu request."),
            _p("service_account", "str | None", "Optional serviceAccountName."),
            _p("include_configmap", "bool", "Include companion ConfigMap document.", True),
        ),
        inputs=("Operator-chosen image/script; optional prior fit_torch_ddp knowledge.",),
        outputs=("K8sJobRenderResult with yaml path and honesty limitations.",),
        prerequisites=(),
        ordering=("Deployment-adjacent; pairs with fit_torch_ddp(multi_node=True).",),
        alternatives=("Hand-written torchrun manifests; Kubeflow / cloud trainers outside BuildML.",),
        rationale=("Use when you need a starter K8s Job for torchrun DDP.",),
        assumptions=("Cluster networking, GPUs, storage, and RBAC are operator-owned.",),
        failures=("Invalid job_name / nnodes / nproc_per_node.",),
        leakage=("N/A for YAML emit; training data access remains operator-controlled.",),
        anti_patterns=(
            "Claiming live multi-cluster orchestration or a Helm product from this emitter.",
            "Assuming the example Service DNS works unmodified on every cluster.",
        ),
        state_changes=("Writes a YAML file; stores dl_k8s_result.",),
        result_reading=("Read disclosures/limitations; adapt DNS/selectors for your cluster.",),
        next_steps=("kubectl apply; launch with fit_torch_ddp(multi_node=True) inside the script.",),
        concepts=("reproducibility",),
    ),
    _operation(
        "domain_adapt_speech_torch",
        OperationKind.MODEL,
        "Domain-adapt / finetune-lite speech classification on a small Session corpus.",
        "Alias of fit_speech_torch with stronger naming that this is not FM continued pretrain.",
        "Speech domain-adapt boundary.",
        (
            "Delegate to fit_speech_torch (tiny encoder + head).",
            "Record domain-adapt disclosures that refuse FM-from-scratch claims.",
        ),
        parameters=(
            _p("epochs", "int", "Training epochs.", 5),
            _p("learning_rate", "float", "Adam learning rate.", 1e-3),
            _p("device", "cpu | cuda | mps | auto", "Compute device.", "auto"),
            _p("freeze_encoder", "bool", "Train head only when True (default for domain adapt).", True),
            _p("audio_column", "str | None", "Audio column when loaders must be built."),
            _p("batch_size", "int", "Loader batch size when building loaders.", 8),
            _p("sample_rate", "int", "Target sample rate.", 16000),
            _p("max_samples", "int", "Fixed waveform length.", 16000),
            _p("source_sample_rate", "int | None", "Optional source rate for array waveforms."),
            _p("normalize_audio", "bool", "Train-only amplitude normalize.", True),
            _p("encoder_dim", "int", "Encoder embedding width.", 64),
            _p("seed", "int", "Loader/train seed.", 0),
        ),
        inputs=("Speech TorchLoaderBundle or roles+split+audio column.",),
        outputs=("Session with dl_train_result from finetune-lite domain adapt.",),
        prerequisites=(DATASET, ROLES, SPLIT, TORCH),
        ordering=("After make_speech_torch_loaders (or builds them); before evaluate_torch.",),
        alternatives=("fit_speech_torch; refuse_speech_foundation_pretrain for explicit refusal.",),
        rationale=("Use when you want domain-adapt naming without implying FM continued pretrain.",),
        assumptions=("Small labeled corpus under Session splits; not web-scale audio pretrain.",),
        failures=("Missing Torch, empty train, or non-numeric class labels.",),
        leakage=("Same as fit_speech_torch — keep amp stats train-only.",),
        anti_patterns=(
            "Calling this continued pretrain of Whisper/Wav2Vec at foundation scale.",
            "Marketing domain adapt as training a foundation model from scratch.",
        ),
        state_changes=("Stores dl_train_result; appends domain-adapt history disclosures.",),
        result_reading=("Read disclosures that this is finetune-lite / domain adapt only.",),
        next_steps=("evaluate_torch; optional load_pretrained_backbone for real Whisper encoders.",),
        concepts=("leakage-boundary", "evaluation-partitions"),
    ),
    _operation(
        "refuse_speech_foundation_pretrain",
        OperationKind.DIAGNOSTIC,
        "Explicitly refuse foundation-model / large continued-pretrain speech requests.",
        "Raise a ValidationError explaining why FM-from-scratch is not a library feature.",
        "Speech honesty refuse boundary.",
        (
            "Record the refuse request on Session history.",
            "Raise ValidationError with pointers to finetune-lite / pretrained hooks.",
        ),
        parameters=(),
        inputs=(
            "A caller request for Whisper-scale / foundation speech pretrain or "
            "large continued pretrain (no dataset mutation required).",
        ),
        outputs=("Always raises ValidationError after recording history.",),
        prerequisites=(),
        ordering=("Anytime a caller asks for FM-from-scratch / large continued pretrain.",),
        alternatives=("domain_adapt_speech_torch / fit_speech_torch; load_pretrained_backbone.",),
        rationale=("Use to keep product claims honest when automation asks for impossible pretrain.",),
        assumptions=("Whisper-scale pretrain needs data/compute outside a pip package.",),
        failures=("Always fails by design with a clear ValidationError.",),
        leakage=("N/A — no training occurs.",),
        anti_patterns=("Catching the error and silently claiming pretrain succeeded.",),
        state_changes=("Appends a history record, then raises.",),
        result_reading=("Read the ValidationError message for the honest alternative APIs.",),
        next_steps=("Call domain_adapt_speech_torch or load_pretrained_backbone instead.",),
        concepts=("reproducibility",),
    ),
    _operation(
        "attach_backbone_head",
        OperationKind.MODEL,
        "Attach a classification head to the Session pretrained backbone.",
        "Build a linear (or small) head on frozen/unfrozen backbone features for finetune/probe.",
        "Pretrained backbone head boundary.",
        (
            "Require a prior load_pretrained_backbone result on the Session.",
            "Attach an n_classes head; optionally override backbone freeze.",
            "Store the combined module as dl_backbone_head.",
        ),
        parameters=(
            _p("n_classes", "int", "Number of classification classes (>= 2).", required=True),
            _p(
                "freeze_backbone",
                "bool | None",
                "Override backbone freeze; None keeps the loaded freeze state.",
            ),
        ),
        inputs=("Session with dl_backbone from load_pretrained_backbone.",),
        outputs=("Backbone+head module stored as dl_backbone_head.",),
        prerequisites=(TORCH,),
        ordering=("After load_pretrained_backbone; before fit_torch / export.",),
        alternatives=("Caller-built nn.Module head; fit_speech_torch tiny encoder path.",),
        rationale=("Use when moving from a curated backbone hook to a trainable classify head.",),
        assumptions=("Backbone exposes a feature_dim compatible with a linear head.",),
        failures=("Missing dl_backbone, n_classes < 2, missing Torch extras.",),
        leakage=("Pretrained features encode upstream data; disclose when claiming domain fit.",),
        anti_patterns=(
            "Calling this foundation-model training from scratch.",
            "Skipping load_pretrained_backbone and attaching to an empty Session slot.",
        ),
        state_changes=("Stores dl_backbone_head on the Session.",),
        result_reading=("Confirm n_classes, freeze state, and module type before fit_torch.",),
        next_steps=("fit_torch / evaluate_torch; optional export_torch and serve packs.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "evaluate_asr",
        OperationKind.DIAGNOSTIC,
        "Score ASR hypotheses against references with WER/CER.",
        "Cheap transcript metrics for stub or transformers ASR outputs — not FM pretrain.",
        "ASR evaluation boundary.",
        (
            "Resolve hypotheses (explicit or last transcribe_speech texts).",
            "Normalize optionally via lowercase.",
            "Compute word and character error rates.",
        ),
        parameters=(
            _p("hypotheses", "list[str] | None", "Hypothesis transcripts; default last ASR texts."),
            _p("references", "list[str]", "Reference transcripts.", required=True),
            _p("lowercase", "bool", "Lowercase before scoring.", True),
        ),
        inputs=("Hypothesis/reference string lists, or Session dl_speech_result.texts.",),
        outputs=("AsrEvalResult with wer/cer stored as dl_asr_eval.",),
        prerequisites=(),
        ordering=("After transcribe_speech when reusing Session texts; anytime with explicit hyps.",),
        alternatives=("External ASR eval toolkits; human transcript review.",),
        rationale=("Use to quantify stub/transformers ASR quality without large downloads.",),
        assumptions=("References align 1:1 with hypotheses; tokenization is whitespace-based WER.",),
        failures=("Missing hypotheses and no prior transcription; length mismatch.",),
        leakage=("N/A for metrics; do not tune ASR prompts on held-out eval transcripts casually.",),
        anti_patterns=("Treating WER/CER as proof of foundation-model training quality.",),
        state_changes=("Stores dl_asr_eval on the Session.",),
        result_reading=("Read wer, cer, n_pairs, and any disclosures/warnings.",),
        next_steps=("Iterate stub/transformers backend or domain-adapt speech classify path.",),
        concepts=("evaluation-partitions", "reproducibility"),
    ),
    _operation(
        "emit_k8s_serve_deployment",
        OperationKind.EXPORT,
        "Emit a Kubernetes Deployment+Service YAML for managed BuildML serve.",
        "Render a starter serve Deployment template — not live multi-cluster orchestration.",
        "K8s serve template boundary.",
        (
            "Render Deployment+Service YAML with image/replicas/port/resources.",
            "Write the YAML to the requested path.",
        ),
        parameters=(
            _p("path", "str | Path", "Output YAML path.", required=True),
            _p("name", "str", "Deployment / Service name.", "buildml-serve"),
            _p("namespace", "str", "Kubernetes namespace.", "default"),
            _p("image", "str", "Container image."),
            _p("replicas", "int", "Deployment replicas.", 1),
            _p("port", "int", "Container / Service port.", 8080),
            _p("cpu_request", "str", "CPU request.", "1"),
            _p("memory_request", "str", "Memory request.", "2Gi"),
            _p("gpu_limit", "int | None", "Optional nvidia.com/gpu limit."),
            _p("service_account", "str | None", "Optional serviceAccountName."),
        ),
        inputs=("Operator-chosen image and bundle mount story for buildml-serve.",),
        outputs=("K8s render result with yaml path and honesty limitations.",),
        prerequisites=(),
        ordering=("Deployment-adjacent; pairs with serve_bundle / pack_torchserve recipes.",),
        alternatives=("Hand-written Deployment manifests; cloud managed endpoints outside BuildML.",),
        rationale=("Use when you need a starter K8s Deployment for local/library-owned serve.",),
        assumptions=("Cluster networking, volumes, TLS, and RBAC are operator-owned.",),
        failures=("Invalid name / replicas / port.",),
        leakage=("N/A for YAML emit; model artifact access remains operator-controlled.",),
        anti_patterns=(
            "Claiming live multi-cluster orchestration or a Helm/control-plane product.",
            "Assuming the example Service exposes a managed IAM / cloud endpoint.",
        ),
        state_changes=("Writes a YAML file; stores dl_k8s_result.",),
        result_reading=("Read disclosures/limitations; wire volumes/TLS for your cluster.",),
        next_steps=("kubectl apply; point the container at a pipeline/TorchScript bundle.",),
        concepts=("reproducibility",),
    ),
    _operation(
        "torch_training_curve",
        OperationKind.DIAGNOSTIC,
        "Return structured Torch epoch curves with interpretation and limits.",
        "Read training history as teaching evidence, not as a deployment scorecard.",
        "Torch training-curve disclosure.",
        (
            "Require dl_train_result.",
            "Build epoch/train_loss/val_loss/lr series.",
            "Attach interpretation, limitations, and early-stop/device disclosures.",
        ),
        parameters=(),
        inputs=("Active dl_train_result with epoch history.",),
        outputs=("TrainingCurveReport with series, interpretation, limitations, disclosures.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After fit_torch or load_torch_bundle; beside evaluate_torch for holdout metrics.",),
        alternatives=("Inspect TrainResult.history directly when a compact table is enough.",),
        rationale=("Curves need partition and device tags before anyone claims generalization.",),
        assumptions=("History rows were logged by fit_torch under the current TrainConfig.",),
        failures=("No Torch trainer on the Session.",),
        leakage=("Using test loss as the plotted early-stop monitor contaminates the final claim.",),
        anti_patterns=(
            "Treating the last train_loss point as expected production performance.",
            "Ignoring limitations about batch noise and validation vs test scope.",
        ),
        state_changes=("Appends a history record; trainer weights are unchanged.",),
        result_reading=(
            "Read disclosures for device and early-stop partition; treat interpretation as review cues.",
        ),
        next_steps=("evaluate_torch(partition='test') once stopping choices are frozen.",),
        concepts=("training-curves", "early-stopping-partition", "evaluation-partitions"),
    ),
    _operation(
        "evaluate_torch",
        OperationKind.DIAGNOSTIC,
        "Compute task metrics for the active Torch trainer on a named partition.",
        "Score a Torch module with partition-tagged metrics, not a single unlabeled number.",
        "Torch holdout assessment.",
        (
            "Require dl_train_result and partition DataLoader.",
            "Run batched inference.",
            "Compute classification or regression metrics.",
        ),
        parameters=(
            _p("partition", "train | validation | test", "Evaluation rows.", "test"),
            _p("device", "str | None", "Optional device override; defaults to the train device."),
        ),
        inputs=("TrainResult, Torch loaders, and a named partition.",),
        outputs=("DLEvaluateResult with metrics, row count, device, and recommendations.",),
        prerequisites=(DATASET, SPLIT, FIT_TORCH, TORCH),
        ordering=("After fit_torch or load_torch_bundle; prefer validation during iteration, test once frozen.",),
        alternatives=("Use Session.evaluate for classical sklearn FitResult scoring.",),
        rationale=("Read metrics only with their partition tag and known device.",),
        assumptions=("Loader feature contract still matches the trained module input width.",),
        failures=("No Torch trainer, missing partition loader, or Torch not installed.",),
        leakage=("Repeated test evaluation while changing architecture or stopping rules contaminates the final claim.",),
        anti_patterns=("Comparing Torch and sklearn scores without matching prep and partitions.",),
        state_changes=("Appends evaluation metadata; trainer weights are unchanged.",),
        result_reading=("Read metrics with partition and device; treat recommendations as review cues.",),
        next_steps=("save_torch_bundle when the recipe is stable enough to keep.",),
        concepts=("evaluation-partitions", "early-stopping-partition", "leakage-boundary"),
    ),
    _operation(
        "save_torch_bundle",
        OperationKind.PERSIST,
        "Persist Torch weights, optimizer state, config, history, feature contract, "
        "and optional multimodal_preprocess meta.",
        "Carry a trainer artifact without embedding Session data or splits.",
        "Torch trainer bundle persistence.",
        (
            "Write meta.json with format buildml.torch_bundle.v1.",
            "torch.save module/optimizer/config/history/multimodal_preprocess into trainer.pt.",
        ),
        parameters=(_p("path", "str | Path", "Destination trainer bundle directory.", required=True),),
        inputs=("Active dl_train_result and destination path.",),
        outputs=("Resolved bundle directory Path.",),
        prerequisites=(FIT_TORCH, TORCH),
        ordering=("After evaluation; beside (not inside) Session checkpoint_save when both are needed.",),
        alternatives=(
            "Use checkpoint_save for data/roles/splits/history.",
            "Use save_pipeline for classical sklearn recipes.",
        ),
        rationale=("Keep weights separate from workflow data so resume and inference stay explicit.",),
        assumptions=("Loading environments trust the artifact and supply a compatible module shell.",),
        failures=("No Torch trainer, unwritable path, or missing Torch extra.",),
        leakage=("Bundles can embed learned sensitive patterns; access controls still apply.",),
        anti_patterns=(
            "Expecting Session checkpoint_load to restore Torch weights.",
            "Loading untrusted trainer.pt files (torch.load can execute code depending on version/settings).",
        ),
        state_changes=("Writes files and appends the destination to history.",),
        result_reading=("Treat the returned path as the bundle root; read meta.json format before load.",),
        next_steps=("Verify load_torch_bundle with the same module class in a clean process.",),
        concepts=("reproducibility", "leakage-boundary"),
    ),
    _operation(
        "load_torch_bundle",
        OperationKind.PERSIST,
        "Load a Torch trainer bundle into Session.dl_train_result via a module shell.",
        "Restore weights and train metadata without treating the bundle as a Session checkpoint.",
        "Torch trainer bundle restoration.",
        (
            "Validate meta.json format buildml.torch_bundle.v1.",
            "Load trainer.pt into the supplied nn.Module.",
            "Rebuild TrainResult on the Session (including multimodal_preprocess when present).",
            "Do not rebuild DataLoaders; remake multimodal/text loaders explicitly.",
        ),
        parameters=(
            _p("path", "str | Path", "Existing trainer bundle directory.", required=True),
            _p("module", "torch.nn.Module", "Compatible module shell for load_state_dict.", required=True),
            _p("map_location", "str | None", "Optional torch.load device map.", None),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize trainer.pt (default False).",
                required=False,
            ),
        ),
        inputs=("Trusted trainer bundle path and a compatible nn.Module instance.",),
        outputs=("Session with dl_train_result restored.",),
        prerequisites=(TORCH,),
        ordering=("After attaching compatible data/split when you will evaluate; before evaluate_torch.",),
        alternatives=(
            "Use checkpoint_load for dataset/split/history.",
            "Use load_pipeline for classical sklearn bundles.",
        ),
        rationale=("Load when the module architecture matches the saved state dict.",),
        assumptions=("Artifact is trusted and feature width matches the current Session contract.",),
        failures=("Wrong format (checkpoint/pipeline), corrupt files, or state_dict mismatch.",),
        leakage=("A trainer can retain information from its original training data.",),
        anti_patterns=(
            "Passing a Session checkpoint path to load_torch_bundle.",
            "Expecting load_torch_bundle to rebuild multimodal DataLoaders or "
            "auto-apply frozen image/audio preprocess stats.",
        ),
        state_changes=("Replaces dl_train_result; classical fit_result is unchanged.",),
        result_reading=(
            "Confirm task, feature columns, epoch history, and multimodal_preprocess "
            "(when present) before scoring.",
        ),
        next_steps=(
            "Remake multimodal/text loaders when the module is non-tabular; "
            "evaluate_torch on a holdout partition; "
            "or fit_torch(..., resume=True) to continue training from the restored state.",
        ),
        concepts=("reproducibility", "feature-schema", "leakage-boundary", "training-curves"),
    ),
)
