# ruff: noqa: E501, F401
"""Native ensemble Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    FIT,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

ENSEMBLE_PLAN = Prerequisite(
    "ensemble-plan",
    "A train-fitted EnsemblePlan is attached to the Session.",
    check_hint="Session.ensemble_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_voting",
        OperationKind.MODEL,
        "Fit a VotingClassifier / VotingRegressor on the train partition.",
        "Combine heterogeneous base learners with hard/soft voting without test leakage.",
        "Native voting ensemble fit.",
        (
            "Require a SplitPlan and refuse fit without train.",
            "Build VotingClassifier or VotingRegressor from named estimators.",
            "Fit on train only; store EnsemblePlan and classical FitResult.",
        ),
        parameters=(
            _p("estimators", "dict[str, estimator] | sequence", "Named base estimators."),
            _p("voting", "hard | soft", "Voting mode (classification).", "hard"),
            _p("weights", "sequence[float] | None", "Optional per-base weights."),
            _p("task", "classification | regression | auto", "Task type.", "auto"),
        ),
        inputs=("Split Session with features + target.",),
        outputs=("EnsembleFitResult; EnsemblePlan + FitResult stored on the Session.",),
        prerequisites=(DATASET, SPLIT),
        ordering=("After split and usual prep (impute/encode/scale).",),
        alternatives=(
            "fit_stacking for CV meta-learner; fit_blending for holdout blend.",
            "Session.fit(RandomForest) remains a single estimator, not native voting.",
        ),
        rationale=("Use when combining diverse base learners with simple aggregation.",),
        assumptions=(
            "At least two named estimators.",
            "Soft voting requires predict_proba on every base.",
        ),
        failures=(
            "Missing split, one estimator, soft voting without predict_proba, weight length mismatch.",
        ),
        leakage=(
            "Fitting voting on all rows before splitting contaminates holdout metrics.",
        ),
        anti_patterns=(
            "Calling this 'done' after only Session.fit(RandomForestClassifier).",
        ),
        state_changes=(
            "Stores ensemble_plan, ensemble_fit_result, and fit_result.",
        ),
        result_reading=(
            "Read strategy, estimator_names, voting, disclosures.",
        ),
        next_steps=("evaluate_ensemble or evaluate; optionally save_ensemble_bundle / save_pipeline.",),
        concepts=(
            "ensemble-voting-vs-single-tree",
            "leakage-boundary",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "fit_stacking",
        OperationKind.MODEL,
        "Fit a StackingClassifier / StackingRegressor on the train partition.",
        "Train a meta-learner on out-of-fold base predictions inside train.",
        "Native stacking ensemble fit.",
        (
            "Require a SplitPlan.",
            "Build sklearn Stacking* with cv folds inside train.",
            "Fit on train only; store EnsemblePlan and FitResult.",
        ),
        parameters=(
            _p("estimators", "dict[str, estimator] | sequence", "Named base estimators."),
            _p("final_estimator", "estimator | None", "Meta-learner (task default if None)."),
            _p("cv", "int", "Out-of-fold folds inside train.", 5),
            _p("passthrough", "bool", "Concatenate original features with meta features.", False),
            _p("stack_method", "str", "Stacking method (classification).", "auto"),
            _p("task", "classification | regression | auto", "Task type.", "auto"),
        ),
        inputs=("Split Session with features + target.",),
        outputs=("EnsembleFitResult; EnsemblePlan + FitResult stored on the Session.",),
        prerequisites=(DATASET, SPLIT),
        ordering=("After split and usual prep.",),
        alternatives=(
            "fit_blending for a single train-inner holdout instead of CV OOF.",
            "fit_voting when no meta-learner is needed.",
        ),
        rationale=("Use when a learned combiner should correct base learner mistakes.",),
        assumptions=("Train large enough for cv; bases match task type.",),
        failures=("cv < 2, missing split, incompatible final_estimator.",),
        leakage=(
            "Using Session test rows to build stacking meta features is leakage.",
            "Session-global preprocess before CV can still poison fold honesty — see leakage guides.",
        ),
        anti_patterns=(
            "Scoring meta features on the evaluation partition during fit.",
        ),
        state_changes=(
            "Stores ensemble_plan, ensemble_fit_result, and fit_result.",
        ),
        result_reading=("Read strategy, cv, final_estimator_name, disclosures.",),
        next_steps=("evaluate_ensemble; save_ensemble_bundle or save_pipeline.",),
        concepts=(
            "ensemble-stacking-oof",
            "cross-validation",
            "leakage-boundary",
        ),
    ),
    _operation(
        "fit_blending",
        OperationKind.MODEL,
        "Fit a holdout-blend ensemble on the train partition.",
        "Carve an inner train holdout for the meta-learner; never use Session test.",
        "Native blending ensemble fit.",
        (
            "Require a SplitPlan.",
            "Carve holdout_fraction from train; fit bases on blend-train.",
            "Fit meta-learner on holdout predictions; optionally refit bases on full train.",
        ),
        parameters=(
            _p("estimators", "dict[str, estimator] | sequence", "Named base estimators."),
            _p("final_estimator", "estimator | None", "Meta-learner (task default if None)."),
            _p("holdout_fraction", "float", "Fraction of train reserved for meta fit.", 0.2),
            _p("blend_method", "predict | predict_proba", "Meta feature construction.", "predict_proba"),
            _p("random_state", "int | None", "Holdout split seed.", 0),
            _p(
                "refit_bases_on_full_train",
                "bool",
                "Refit bases on full train after meta fit.",
                True,
            ),
            _p("passthrough", "bool", "Concatenate original features with meta features.", False),
            _p("task", "classification | regression | auto", "Task type.", "auto"),
        ),
        inputs=("Split Session with features + target.",),
        outputs=("EnsembleFitResult; EnsemblePlan + FitResult stored on the Session.",),
        prerequisites=(DATASET, SPLIT),
        ordering=("After split and usual prep.",),
        alternatives=("fit_stacking for CV OOF meta features (usually preferred).",),
        rationale=("Use when a simple train-inner holdout blend is explicitly desired.",),
        assumptions=("holdout_fraction in [0.05, 0.5); train large enough after carve.",),
        failures=("Missing split, tiny holdout, <2 estimators.",),
        leakage=(
            "Using Session validation/test as the blend holdout leaks evaluation labels.",
        ),
        anti_patterns=(
            "Reporting blend-holdout accuracy as final test performance.",
        ),
        state_changes=(
            "Stores ensemble_plan, ensemble_fit_result, and fit_result.",
        ),
        result_reading=(
            "Read holdout_fraction, blend_method, refit_bases_on_full_train, disclosures.",
        ),
        next_steps=("evaluate_ensemble; save_ensemble_bundle or save_pipeline.",),
        concepts=(
            "ensemble-blending-holdout",
            "ensemble-stacking-oof",
            "leakage-boundary",
        ),
    ),
    _operation(
        "evaluate_ensemble",
        OperationKind.DIAGNOSTIC,
        "Evaluate the last native ensemble with classical supervised metrics.",
        "Score the fitted ensemble on a holdout partition with strategy disclosures.",
        "Ensemble evaluation step.",
        (
            "Require FitResult (from fit_voting / fit_stacking / fit_blending / load).",
            "Delegate to classical evaluate_estimator metrics.",
            "Attach EnsemblePlan disclosures to recommendations/diagnostics.",
        ),
        parameters=(
            _p("partition", "train | validation | test", "Partition to score.", "test"),
        ),
        inputs=("Fitted ensemble on the Session.",),
        outputs=("EvaluateResult with ensemble diagnostics when EnsemblePlan is present.",),
        prerequisites=(DATASET, SPLIT, FIT),
        ordering=("After fit_voting / fit_stacking / fit_blending or load_ensemble_bundle.",),
        alternatives=("Session.evaluate — same metrics without ensemble-specific tips.",),
        rationale=("Use to read supervised metrics beside ensemble strategy disclosures.",),
        assumptions=("Feature columns match the fitted contract.",),
        failures=("No fit_result; missing partition.",),
        leakage=("Train-partition scores are optimistic for model selection.",),
        anti_patterns=("Treating train metrics as final generalization.",),
        state_changes=("Records evaluate_ensemble in history; does not mutate the estimator.",),
        result_reading=("Read metrics, diagnostics.ensemble, recommendations.",),
        next_steps=("save_ensemble_bundle and/or save_pipeline.",),
        concepts=(
            "evaluation-partitions",
            "ensemble-voting-vs-single-tree",
            "ensemble-stacking-oof",
        ),
    ),
    _operation(
        "save_ensemble_bundle",
        OperationKind.PERSIST,
        "Persist the active EnsemblePlan as buildml.ensemble_bundle.v1.",
        "Save strategy disclosures and the fitted ensemble separately from checkpoints.",
        "Ensemble bundle save.",
        (
            "Require an attached EnsemblePlan.",
            "Write meta.json + ensemble_plan.joblib.",
        ),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("Active EnsemblePlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(ENSEMBLE_PLAN,),
        ordering=("After a successful ensemble fit.",),
        alternatives=(
            "save_pipeline when preprocess plans must travel with the estimator.",
            "save_model for estimator-only without ensemble disclosures.",
        ),
        rationale=("Use when EnsemblePlan disclosures must round-trip.",),
        assumptions=("Destination is writable.",),
        failures=("No ensemble plan attached.",),
        leakage=("Bundles do not embed Session test labels.",),
        anti_patterns=("Treating the bundle as a Session checkpoint.",),
        state_changes=("Writes files; records history.",),
        result_reading=("Confirm format=buildml.ensemble_bundle.v1 in meta.json.",),
        next_steps=("load_ensemble_bundle in a fresh Session, then evaluate_ensemble.",),
        concepts=("ensemble-bundle-boundary",),
    ),
    _operation(
        "load_ensemble_bundle",
        OperationKind.PERSIST,
        "Load a buildml.ensemble_bundle.v1 EnsemblePlan into the Session.",
        "Restore a fitted native ensemble and feature contract.",
        "Ensemble bundle load.",
        (
            "Validate bundle format.",
            "Attach EnsemblePlan and FitResult.",
        ),
        parameters=(_p("path", "str | Path", "Bundle directory."),),
        inputs=("Ensemble bundle directory.",),
        outputs=("Session with ensemble_plan and fit_result attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingesting a frame with matching feature columns.",),
        alternatives=("load_model / load_pipeline for classical artifacts.",),
        rationale=("Use to restore ensemble strategy + estimator without a full checkpoint.",),
        assumptions=("Feature columns match the saved contract.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Loading does not re-open Session test for refitting.",),
        anti_patterns=("Expecting preprocess plans inside an ensemble bundle.",),
        state_changes=("Sets ensemble_plan and fit_result; clears ensemble_fit_result.",),
        result_reading=("Read strategy and estimator_names from ensemble_plan.",),
        next_steps=("evaluate_ensemble or predict.",),
        concepts=("ensemble-bundle-boundary",),
    ),
)
