# ruff: noqa: E501, F401
"""Graph Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

GRAPH_SPEC = Prerequisite(
    "graph-spec",
    "An edge list GraphSpec is attached via set_graph.",
    check_hint="Session.graph_spec is not None.",
)

GRAPH_PLAN = Prerequisite(
    "graph-plan",
    "A train-fitted GraphPlan is attached to the Session.",
    check_hint="Session.graph_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "set_graph",
        OperationKind.MODEL,
        "Attach an edge list; Session rows are nodes.",
        "Normalize edges and store GraphSpec on the Session.",
        "Graph structure declaration.",
        (
            "Require an ingested dataset.",
            "Normalize edge endpoints; drop self-loops; dedupe.",
            "Validate node_id_col uniqueness against the node table.",
            "Clear any prior GraphPlan.",
        ),
        parameters=(
            _p("edges", "DataFrame | sequence", "Edge list.", required=True),
            _p("source_col", "str", "Source endpoint column.", "source"),
            _p("target_col", "str", "Target endpoint column.", "target"),
            _p("node_id_col", "str", "Unique node id column in the dataset.", "node_id"),
            _p("directed", "bool", "Treat edges as directed.", False),
        ),
        inputs=("Node table + edge list.",),
        outputs=("Validated GraphSpec on the Session.",),
        prerequisites=(DATASET,),
        ordering=("Before fit_graph; usually after set_roles.",),
        alternatives=("Reload via load_graph_bundle (restores GraphSpec too).",),
        rationale=("Separate structure from the node feature table explicitly.",),
        assumptions=("Edge endpoints match node_id values.",),
        failures=("Empty edges; missing columns; duplicate node ids.",),
        leakage=("None — declaration does not fit models.",),
        anti_patterns=(
            "Using row positions as edge endpoints without a stable id.",
            "Treating this as a Neo4j/KG store.",
        ),
        state_changes=("Stores graph_spec; clears prior graph plan/results.",),
        result_reading=("Inspect n_edges, node_id_col, disclosures.",),
        next_steps=("split (if needed); fit_graph.",),
        concepts=(
            "graph-data-model",
            "graph-inductive-transductive",
            "graph-bundle-boundary",
        ),
    ),
    _operation(
        "fit_graph",
        OperationKind.MODEL,
        "Fit graph node classification (classical, pure-Torch GCN, or PyG).",
        "Train-only labels; inductive train-induced subgraph by default.",
        "Graph fit step.",
        (
            "Require SplitPlan and GraphSpec.",
            "Classical: NetworkX metrics + sklearn (buildml[graph]).",
            "GCN: pure-Torch 1–2 layer GCN (buildml[torch]).",
            "PyG: GCNConv / SAGEConv / GATConv (buildml[graph-pyg]).",
            "Inductive fit uses train–train edges only.",
            "Never use validation/test labels for fitting.",
        ),
        parameters=(
            _p("method", "classical | gcn | pyg", "Learning path.", "classical"),
            _p("task", "node_classification", "Currently only node_classification.", "node_classification"),
            _p(
                "mode",
                "inductive | transductive",
                "Topology leakage mode (default inductive).",
                "inductive",
            ),
            _p("columns", "sequence[str] | None", "Optional tabular feature columns."),
            _p(
                "classical_estimator",
                "logistic_regression | random_forest",
                "Sklearn head for classical.",
                "logistic_regression",
            ),
            _p("pyg_model", "gcn | graphsage | gat", "PyG conv when method=pyg.", "gcn"),
            _p("hidden_dim", "int", "GNN hidden size.", 32),
            _p("n_layers", "int", "GNN layers in {1,2}.", 2),
            _p("heads", "int", "GAT attention heads.", 4),
            _p("epochs", "int", "GNN training epochs.", 80),
            _p("learning_rate", "float", "GCN Adam lr.", 0.01),
            _p("weight_decay", "float", "GCN Adam weight decay.", 5e-4),
            _p("dropout", "float", "GCN dropout.", 0.1),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p(
                "include_graph_metrics",
                "bool",
                "Classical: compute NetworkX metrics.",
                True,
            ),
        ),
        inputs=("Train nodes + GraphSpec edges.",),
        outputs=("GraphPlan + GraphFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT, GRAPH_SPEC),
        ordering=("After set_graph and split.",),
        alternatives=("load_graph_bundle.",),
        rationale=(
            "Ship classical, pure-Torch, and PyG node-classification paths "
            "with explicit leakage modes.",
        ),
        assumptions=("Binary/multiclass node labels; numeric features for GNN paths.",),
        failures=(
            "No GraphSpec; no train–train edges (inductive); missing extras.",
        ),
        leakage=(
            "Fitting with holdout labels — refused.",
            "Inductive fit using holdout–holdout edges — filtered out.",
        ),
        anti_patterns=(
            "Treating this as a full PyG algorithm zoo or Neo4j product.",
            "Ignoring mode disclosures when comparing to papers.",
        ),
        state_changes=("Stores graph_plan and fit result; clears predict/eval.",),
        result_reading=("Read train_accuracy, n_edges_fit, mode, disclosures.",),
        next_steps=("evaluate_graph; predict_graph; save_graph_bundle.",),
        concepts=(
            "graph-classical-features",
            "graph-gcn",
            "graph-pyg",
            "graph-inductive-transductive",
            "leakage-boundary",
        ),
    ),
    _operation(
        "predict_graph",
        OperationKind.DIAGNOSTIC,
        "Predict node labels with the fitted GraphPlan.",
        "Score a partition under the plan's inductive/transductive edge filter.",
        "Graph predict step.",
        (
            "Require GraphPlan.",
            "Rebuild mode-filtered features / adjacency.",
            "Do not update the learner.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Nodes to score.",
                "validation",
            ),
        ),
        inputs=("Active GraphPlan + partition nodes.",),
        outputs=("GraphPredictResult.",),
        prerequisites=(DATASET, GRAPH_PLAN),
        ordering=("After fit_graph or load_graph_bundle.",),
        alternatives=("evaluate_graph for metrics.",),
        rationale=("Score nodes without refitting.",),
        assumptions=("Feature columns and node ids match the plan.",),
        failures=("No plan; empty partition.",),
        leakage=("Do not refit on the scored holdout.",),
        anti_patterns=("Treating probabilities as calibrated without checks.",),
        state_changes=("Stores graph_predict_result.",),
        result_reading=("Read predictions / probabilities / disclosures.",),
        next_steps=("evaluate_graph; save_graph_bundle.",),
        concepts=("graph-inductive-transductive", "graph-gcn"),
    ),
    _operation(
        "evaluate_graph",
        OperationKind.DIAGNOSTIC,
        "Holdout node-classification metrics.",
        "Accuracy / macro-F1 (and ROC-AUC when binary) on a frozen plan.",
        "Graph evaluate step.",
        (
            "Require GraphPlan.",
            "Score holdout with frozen estimator/GCN.",
            "Validation→test fallback when validation absent.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition.",
                "validation",
            ),
        ),
        inputs=("GraphPlan + holdout nodes.",),
        outputs=("GraphEvalResult with metrics.",),
        prerequisites=(DATASET, GRAPH_PLAN),
        ordering=("After fit_graph.",),
        alternatives=("predict_graph for raw labels.",),
        rationale=("Report honest holdout quality under the chosen mode.",),
        assumptions=("Target column still present on the partition.",),
        failures=("No plan; empty partition.",),
        leakage=("Repeated test peeking without a protocol.",),
        anti_patterns=("Comparing inductive and transductive numbers blindly.",),
        state_changes=("Stores graph_eval_result.",),
        result_reading=("Read metrics accuracy / f1_macro / roc_auc.",),
        next_steps=("save_graph_bundle.",),
        concepts=("graph-inductive-transductive", "leakage-boundary"),
    ),
    _operation(
        "save_graph_bundle",
        OperationKind.PERSIST,
        "Persist the active GraphPlan as buildml.graph_bundle.v1.",
        "Write meta.json + graph_plan.joblib.",
        "Graph bundle save.",
        (
            "Require an attached plan.",
            "Write meta.json + graph_plan.joblib.",
        ),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active GraphPlan.",),
        outputs=("Bundle directory.",),
        prerequisites=(GRAPH_PLAN,),
        ordering=("After a successful fit_graph.",),
        alternatives=("Session checkpoint for tabular workflow only.",),
        rationale=("Keep graph learner artifacts distinct from checkpoints.",),
        assumptions=("Writable path.",),
        failures=("No plan.",),
        leakage=("None.",),
        anti_patterns=("Expecting checkpoint_save to embed GraphPlan.",),
        state_changes=("None beyond history.",),
        result_reading=("Confirm meta.json format buildml.graph_bundle.v1.",),
        next_steps=("load_graph_bundle in another Session.",),
        concepts=("graph-bundle-boundary",),
    ),
    _operation(
        "load_graph_bundle",
        OperationKind.PERSIST,
        "Load a buildml.graph_bundle.v1 GraphPlan into the Session.",
        "Restore GraphPlan (+ GraphSpec) from disk.",
        "Graph bundle load.",
        (
            "Read meta.json + graph_plan.joblib.",
            "Attach plan and graph_spec; clear fit/predict/eval slots.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory with meta.json + graph_plan.joblib.",),
        outputs=("Session with graph_plan attached.",),
        prerequisites=(DATASET,),
        ordering=("Before predict_graph / evaluate_graph on reloaded plans.",),
        alternatives=("fit_graph to train fresh.",),
        rationale=("Reload the learner without a full Session checkpoint.",),
        assumptions=("Bundle format matches buildml.graph_bundle.v1.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("None.",),
        anti_patterns=("Loading into a Session whose node ids no longer align.",),
        state_changes=("Sets graph_plan and graph_spec; clears result slots.",),
        result_reading=("Inspect Session.graph_plan.to_dict().",),
        next_steps=("predict_graph; evaluate_graph.",),
        concepts=("graph-bundle-boundary",),
    ),
)
