# ruff: noqa: E501, F401
"""Knowledge-graph Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

KG_PLAN = Prerequisite(
    "kg-plan",
    "A train-fitted KgPlan is attached.",
    check_hint="Session.kg_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_kg",
        OperationKind.MODEL,
        "Fit a knowledge-graph embedding model on train triples.",
        "native: numpy TransE/DistMult; pykeen: RotatE/ComplEx when installed.",
        "KG fit step.",
        (
            "Require SplitPlan.",
            "Resolve head_column / relation_column / tail_column.",
            "Materialize unique train triples; build entity/relation vocab.",
            "Train embeddings via native or PyKEEN backend; store train adjacency.",
        ),
        parameters=(
            _p(
                "backend",
                "native | pykeen",
                "Embedding backend (pykeen requires buildml[kg-industry]).",
                "native",
            ),
            _p(
                "method",
                "transe | distmult | rotate | complex",
                "Embedding model family.",
                "transe",
            ),
            _p("head_column", "str", "Head entity column (required)."),
            _p("relation_column", "str", "Relation column (required)."),
            _p("tail_column", "str", "Tail entity column (required)."),
            _p("embedding_dim", "int", "Embedding dimensionality.", 50),
            _p("epochs", "int", "Training epochs.", 40),
            _p("batch_size", "int", "Mini-batch size.", 256),
            _p("learning_rate", "float", "SGD step size.", 0.01),
            _p("margin", "float", "Margin ranking loss margin.", 1.0),
            _p(
                "neg_ratio",
                "int",
                "Negatives per positive (uniform head/tail corruption).",
                1,
            ),
            _p("norm", "l1 | l2", "TransE distance norm.", "l1"),
            _p("random_state", "int | None", "RNG seed.", 0),
        ),
        inputs=("Train partition (head, relation, tail) rows.",),
        outputs=("KgPlan + KgFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split; before score_triples / predict_links / evaluate_kg / query_kg."),
        alternatives=(
            "Graph ML set_graph/fit_graph for node classification; "
            "RAG for document retrieve; recommenders for user–item CF.",
        ),
        rationale=("Ship leakage-safe Session KG embeddings + symbolic query."),
        assumptions=("≥2 train entities; ≥1 relation; triples present."),
        failures=("No split; missing triple columns; single-entity graph."),
        leakage=(
            "Train-only vocab/embeddings/adjacency; never trains on holdout triples.",
        ),
        anti_patterns=(
            "Fitting on the full frame before split.",
            "Calling this Neo4j or a graph-DB product.",
            "Confusing with set_graph / fit_graph node classification.",
            "Confusing with RAG.",
        ),
        state_changes=("Stores kg_plan; clears prior score/predict/query/eval results."),
        result_reading=("Inspect n_train_triples, n_entities, n_relations, disclosures."),
        next_steps=("predict_links; query_kg; evaluate_kg; save_kg_bundle."),
        concepts=(
            "kg-triples",
            "kg-transe-distmult",
            "kg-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "score_triples",
        OperationKind.MODEL,
        "Score full (head, relation, tail) triples.",
        "Higher is better under the frozen embedding model.",
        "KG scoring.",
        (
            "Require KgPlan.",
            "Encode triples against train vocab (OOV → -inf).",
            "Score with TransE or DistMult.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all | None",
                "Score all triples in a partition when triples omitted.",
                "test",
            ),
            _p(
                "triples",
                "DataFrame | list[tuple] | None",
                "Explicit triples to score (mutually exclusive with partition).",
            ),
        ),
        inputs=("Frozen KgPlan + triples.",),
        outputs=("ScoreTriplesResult.",),
        prerequisites=(KG_PLAN,),
        ordering=("After fit_kg."),
        alternatives=("predict_links for incomplete triples."),
        rationale=("Direct plausibility scores for complete facts."),
        assumptions=("Triples use train vocab where possible."),
        failures=("No KgPlan; both partition and triples provided."),
        leakage=("Uses frozen train embeddings only."),
        anti_patterns=("Refitting on holdout before scoring."),
        state_changes=("Stores last ScoreTriplesResult."),
        result_reading=("scores parallel to input triples; unknown_* counts."),
        next_steps=("evaluate_kg; save_kg_bundle."),
        concepts=("kg-link-prediction", "kg-transe-distmult"),
    ),
    _operation(
        "predict_links",
        OperationKind.MODEL,
        "Predict missing link components.",
        "Rank candidate tails, heads, or relations for incomplete triples.",
        "KG link prediction.",
        (
            "Require KgPlan.",
            "Score all catalog candidates for each query.",
            "Optionally filter other train-known true triples.",
        ),
        parameters=(
            _p(
                "mode",
                "tail | head | relation",
                "Which component to predict.",
                "tail",
            ),
            _p("heads", "list | None", "Head ids (tail/relation modes)."),
            _p("relations", "list | None", "Relation ids (tail/head modes)."),
            _p("tails", "list | None", "Tail ids (head/relation modes)."),
            _p("k", "int", "Top-K cut-off.", 10),
            _p(
                "filtered",
                "bool",
                "Remove other train-known true triples from candidates.",
                True,
            ),
        ),
        inputs=("Frozen KgPlan + incomplete triple queries.",),
        outputs=("PredictLinksResult.",),
        prerequisites=(KG_PLAN,),
        ordering=("After fit_kg."),
        alternatives=("evaluate_kg for holdout metrics; query_kg for exact structure."),
        rationale=("Complete missing facts against the train catalog."),
        assumptions=("Query entities/relations in train vocab."),
        failures=("No KgPlan; mismatched list lengths; wrong mode args."),
        leakage=("Catalog and filter set are train-only."),
        anti_patterns=("Treating predictions as Neo4j writes."),
        state_changes=("Stores last PredictLinksResult."),
        result_reading=("predictions / scores parallel to queries."),
        next_steps=("evaluate_kg; save_kg_bundle."),
        concepts=("kg-link-prediction", "kg-transe-distmult"),
    ),
    _operation(
        "query_kg",
        OperationKind.DIAGNOSTIC,
        "Symbolic neighbors / path / typed query over the train KG.",
        "BFS / adjacency — not an LLM, not Neo4j/Cypher, not RAG.",
        "KG structure query.",
        (
            "Require KgPlan with train adjacency.",
            "neighbors: 1-hop; typed: (entity, relation, ?); path: shortest BFS.",
        ),
        parameters=(
            _p(
                "mode",
                "neighbors | path | typed",
                "Query family.",
                "neighbors",
            ),
            _p("entity", "Any | None", "Entity for neighbors/typed."),
            _p("source", "Any | None", "Path source entity."),
            _p("target", "Any | None", "Path target entity."),
            _p("relation", "Any | None", "Optional/required relation filter."),
            _p(
                "direction",
                "out | in | both",
                "Edge direction for neighbors/typed.",
                "out",
            ),
            _p("max_hops", "int", "Path BFS depth cap.", 3),
        ),
        inputs=("Frozen KgPlan train adjacency.",),
        outputs=("KgQueryResult.",),
        prerequisites=(KG_PLAN,),
        ordering=("After fit_kg."),
        alternatives=("predict_links for scored completions."),
        rationale=("Exact structure queries complement embedding scores."),
        assumptions=("Entities exist in train vocab for non-empty results."),
        failures=("No KgPlan; missing mode-required args."),
        leakage=("Train adjacency only — holdout edges invisible."),
        anti_patterns=(
            "Calling this Cypher/Neo4j or RAG retrieve.",
            "Expecting holdout edges in the query graph.",
        ),
        state_changes=("Stores last KgQueryResult."),
        result_reading=("results list; n_results; warnings for missing paths."),
        next_steps=("predict_links; evaluate_kg."),
        concepts=("kg-symbolic-query", "kg-triples"),
    ),
    _operation(
        "evaluate_kg",
        OperationKind.DIAGNOSTIC,
        "Evaluate holdout filtered link-prediction metrics.",
        "MRR and Hits@1/3/K averaged over head+tail rankings.",
        "KG evaluation.",
        (
            "Require KgPlan.",
            "Encode holdout triples in train vocab (skip OOV).",
            "Filtered rank true head/tail; aggregate MRR / Hits.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Holdout partition.",
                "test",
            ),
            _p("k", "int", "Hits@K cut-off.", 10),
        ),
        inputs=("Frozen KgPlan + labeled holdout triples.",),
        outputs=("KgEvalResult.",),
        prerequisites=(KG_PLAN, SPLIT),
        ordering=("After fit_kg."),
        alternatives=("predict_links for explicit candidate lists."),
        rationale=("Honest KG ranking quality under a disclosed split."),
        assumptions=("Holdout triples mostly in train vocab."),
        failures=("No KgPlan; empty holdout."),
        leakage=("No refit; OOV disclosed and skipped."),
        anti_patterns=(
            "Equating with Graph ML evaluate_graph or RAG rag_evaluate.",
        ),
        state_changes=("Stores last KgEvalResult."),
        result_reading=("mrr / hits_at_1 / hits_at_3 / hits_at_k."),
        next_steps=("save_kg_bundle; compare transe vs distmult."),
        concepts=("kg-link-prediction", "leakage-boundary"),
    ),
    _operation(
        "save_kg_bundle",
        OperationKind.PERSIST,
        "Persist KgPlan as buildml.kg_bundle.v1.",
        "Writes meta.json + kg_plan.joblib.",
        "KG bundle save.",
        ("Require KgPlan.", "Write bundle directory."),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("KgPlan (+ optional fit/eval/score/predict/query summaries).",),
        outputs=("Bundle directory path.",),
        prerequisites=(KG_PLAN,),
        ordering=("After fit_kg."),
        alternatives=("Session checkpoint for workflow resume (no KG weights)."),
        rationale=("Deployable KG artifact separate from checkpoints."),
        assumptions=("Writable path."),
        failures=("No KgPlan."),
        leakage=("Bundle contains train-fitted embeddings/adjacency only."),
        anti_patterns=("Expecting Neo4j dump semantics."),
        state_changes=("History record only."),
        result_reading=("Path + format buildml.kg_bundle.v1."),
        next_steps=("load_kg_bundle on another Session."),
        concepts=("kg-bundle-boundary",),
    ),
    _operation(
        "load_kg_bundle",
        OperationKind.PERSIST,
        "Load a buildml.kg_bundle.v1 plan into the Session.",
        "Restores KgPlan; clears prior fit/eval/score/predict/query results.",
        "KG bundle load.",
        ("Read meta + joblib.", "Attach KgPlan."),
        parameters=(_p("path", "str | Path", "Bundle directory."),),
        inputs=("KG bundle directory.",),
        outputs=("Session with kg_plan."),
        prerequisites=(DATASET,),
        ordering=("Before score_triples / predict_links / evaluate_kg / query_kg."),
        alternatives=("Refit with fit_kg."),
        rationale=("Reload frozen KG without refitting."),
        assumptions=("Valid bundle format."),
        failures=("Missing meta.json / kg_plan.joblib; wrong format."),
        leakage=("Loaded plan remains train-fitted; do not mix with holdout refit."),
        anti_patterns=("Loading a Graph ML or RAG bundle here."),
        state_changes=("Sets kg_plan; clears result caches."),
        result_reading=("Session.kg_plan is not None."),
        next_steps=("predict_links; query_kg; evaluate_kg."),
        concepts=("kg-bundle-boundary",),
    ),
)
