# ruff: noqa: E501, F401
"""Natural-language processing Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite, PrerequisiteStatus

NLP_TEXT_PLAN = Prerequisite(
    "nlp-text-plan",
    "A train-fitted NlpTextPlan (normalization + representation + head) is attached to the Session.",
    check_hint="Session.nlp_text_plan is not None.",
)
NLP_TOPIC_PLAN = Prerequisite(
    "nlp-topic-plan",
    "A train-fitted NlpTopicPlan (vectorizer + decomposition) is attached to the Session.",
    check_hint="Session.nlp_topic_plan is not None.",
)
NLP_TEXT_COLUMN = Prerequisite(
    "nlp-text-column",
    "The dataset exposes an unambiguous text column, or one is named explicitly.",
    check_hint="Pass text_column=... when more than one string column could be the documents.",
)
NLP_EXTRA = Prerequisite(
    "nlp-extra",
    "Optional NLP dependencies are installed for embedding, transformer, langdetect, or NLTK paths.",
    status=PrerequisiteStatus.OPTIONAL,
    check_hint="Install buildml[nlp]; spaCy NER additionally needs buildml[nlp-industry] plus a downloaded model.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "profile_text_corpus",
        OperationKind.DIAGNOSTIC,
        "Profile a text column and screen the split for text contamination.",
        "Find the corpus problems that would otherwise show up as an inflated holdout score.",
        "NLP data-quality gate, before any text model is fitted.",
        (
            "Resolve the text column, refusing ambiguity.",
            "Measure length distributions, vocabulary size, hapax rate, and type-token ratio.",
            "Fingerprint documents to count exact duplicate groups.",
            "When a split exists, count holdout documents that exactly match train, and near-duplicates above a character n-gram cosine threshold.",
            "Report the holdout out-of-vocabulary token rate as the complementary drift signal.",
            "Detect the dominant language so language-specific defaults can be reconsidered.",
        ),
        parameters=(
            _p(
                "text_column",
                "str | None",
                "Text column to profile; inferred when unambiguous.",
                None,
            ),
            _p("top_tokens", "int", "How many frequent tokens to report.", 25),
            _p(
                "near_duplicate_threshold",
                "float",
                "Cosine similarity on character n-grams above which a holdout document counts as a near-duplicate of train.",
                0.9,
            ),
            _p(
                "detect_languages",
                "bool",
                "Run language identification as part of the profile.",
                True,
            ),
            _p(
                "stopword_language",
                "str | None",
                "Stopword list applied before token statistics; None keeps every token.",
                None,
            ),
        ),
        inputs=("A text column on the Session dataset; a SplitPlan when contamination is to be measured.",),
        outputs=("NlpCorpusProfile with findings, disclosures, and warnings.",),
        prerequisites=(DATASET, NLP_TEXT_COLUMN),
        ordering=("After split; before fit_text_classifier or fit_topics.",),
        alternatives=(
            "eda() for tabular profiling; detect_language alone when only the language matters.",
        ),
        rationale=(
            "Duplicate and near-duplicate documents are the most common reason a text model's holdout score does not survive deployment.",
        ),
        assumptions=(
            "Documents are string-like; character n-grams are an adequate similarity proxy for this genre.",
        ),
        failures=(
            "No text-like column, or several equally plausible ones (refused rather than guessed).",
            "Very large corpora making the near-duplicate scan expensive.",
        ),
        leakage=(
            "Read-only: measures contamination and reports it; nothing is removed and no vocabulary is fitted for reuse.",
        ),
        anti_patterns=(
            "Deduplicating automatically and reporting a clean score.",
            "Quoting a near-duplicate count without the threshold that produced it.",
        ),
        state_changes=("Stores nlp_profile_result; adds a history record.",),
        result_reading=(
            "Read findings first; a non-zero train_holdout_exact_overlap invalidates the holdout estimate for those rows.",
            "A very low holdout_oov_token_rate next to high near-duplicate counts is the classic contamination signature.",
        ),
        next_steps=("detect_language; fit_text_classifier; fit_topics.",),
        concepts=(
            "nlp-corpus-contamination",
            "nlp-text-normalization",
            "nlp-language-identification",
            "leakage-boundary",
        ),
    ),
    _operation(
        "detect_language",
        OperationKind.DIAGNOSTIC,
        "Identify the language of every document in a partition.",
        "Confirm the corpus language before applying language-specific stopwords, stemming, or sentiment lexicons.",
        "NLP diagnostic; usually run once on the whole dataset.",
        (
            "Measure Unicode script shares to settle non-Latin scripts directly.",
            "Within Latin script, score discriminative function words with shared-marker down-weighting.",
            "Return 'und' below the minimum character count or the minimum score, instead of guessing.",
            "With backend='langdetect', delegate to the trained n-gram model from buildml[nlp].",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to classify; 'all' needs no split.",
                "all",
            ),
            _p(
                "backend",
                "native | langdetect | None",
                "Shipped script and function-word scorer, or langdetect (buildml[nlp]).",
                "native",
            ),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p(
                "min_characters",
                "int",
                "Below this length a document is reported as 'und'.",
                12,
            ),
        ),
        inputs=("A text column on the Session dataset.",),
        outputs=("NlpLanguageResult with per-document codes, counts, dominant language, and undetermined rate.",),
        prerequisites=(DATASET, NLP_TEXT_COLUMN, NLP_EXTRA),
        ordering=("Early: before choosing stopword_language or a sentiment backend.",),
        alternatives=("profile_text_corpus runs detection as part of a wider corpus screen.",),
        rationale=(
            "Language-specific resources silently degrade on mixed corpora, so the check has to come before the choice.",
        ),
        assumptions=("Documents are predominantly single-language.",),
        failures=(
            "Code, identifiers, or URLs dominating the token stream.",
            "backend='langdetect' requested without buildml[nlp].",
        ),
        leakage=("Read-only description; nothing is fitted.",),
        anti_patterns=(
            "Forcing a label on documents below the character threshold.",
            "Running English stopwords and stemming after detection flagged a mixed corpus.",
        ),
        state_changes=("Stores nlp_language_result; adds a history record.",),
        result_reading=(
            "'und' means below the evidence threshold, not 'unknown language'.",
            "Confidence is a relative marker score, not a calibrated probability.",
        ),
        next_steps=("profile_text_corpus; fit_text_classifier; analyze_sentiment.",),
        concepts=(
            "nlp-language-identification",
            "nlp-lexicon-sentiment",
            "nlp-text-normalization",
        ),
    ),
    _operation(
        "fit_text_classifier",
        OperationKind.MODEL,
        "Fit a single-label document classifier on Session train.",
        "Predict a row label from the row's text, with a representation you can choose and, for linear heads, explain.",
        "NLP model fit step.",
        (
            "Require a SplitPlan; refuse to fit on anything but train.",
            "Resolve one normalization plan and embed it in the fitted artifact.",
            "Fit the representation on train only: vocabulary, document frequencies, and idf never see holdout.",
            "Fit the chosen head and record whether it supports calibrated probabilities.",
            "Store feature names when the representation has an invertible vocabulary, so attribution stays possible.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | embedding | transformer | None",
                "Train-fitted bag-of-n-grams, frozen sentence-transformer vectors, or a frozen pooled encoder; None picks sklearn.",
                None,
            ),
            _p(
                "estimator",
                "logistic | linear_svm | sgd | complement_nb | multinomial_nb | None",
                "Classifier head; linear heads permit exact token attribution.",
                None,
            ),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p(
                "vectorizer",
                "tfidf | count | hashing",
                "Bag-of-n-grams weighting; hashing stores no vocabulary.",
                "tfidf",
            ),
            _p(
                "analyzer",
                "word | char | char_wb",
                "Token unit; character n-grams survive typos and morphology.",
                "word",
            ),
            _p("ngram_range", "tuple[int, int]", "Inclusive (min_n, max_n) n-gram sizes.", (1, 2)),
            _p("max_features", "int | None", "Vocabulary cap by corpus frequency.", 20000),
            _p("min_df", "int | float", "Drop terms below this document frequency.", 1),
            _p("max_df", "int | float", "Drop terms above this document frequency.", 1.0),
            _p("sublinear_tf", "bool", "Damp repeated terms with 1 + log(tf).", True),
            _p("binary", "bool", "Use presence instead of counts.", False),
            _p("n_hash_features", "int", "Output width for vectorizer='hashing'.", 2**18),
            _p(
                "normalize_steps",
                "list[str] | None",
                "Ordered character-level steps; None uses the honest default set.",
                None,
            ),
            _p("stopwords", "list[str] | None", "Extra stopwords added to any language list.", None),
            _p(
                "stopword_language",
                "str | None",
                "Built-in stopword list; None keeps every token, which usually helps classification.",
                None,
            ),
            _p("min_token_length", "int", "Discard shorter tokens.", 1),
            _p("max_token_length", "int", "Discard longer tokens.", 40),
            _p("stem", "bool", "Apply Porter stemming (NLTK) or built-in suffix rules.", False),
            _p("lemmatize", "bool", "Apply WordNet lemmatization (requires buildml[nlp]).", False),
            _p("class_weight", "str | None", "Pass 'balanced' to reweight imbalanced classes.", None),
            _p("C", "float", "Inverse regularization strength for logistic and linear SVM.", 1.0),
            _p("alpha", "float", "Additive smoothing for naive Bayes; penalty for SGD.", 1.0),
            _p(
                "embedding_model_name",
                "str",
                "Sentence-transformer id for backend='embedding'.",
                "sentence-transformers/all-MiniLM-L6-v2",
            ),
            _p("max_seq_tokens", "int", "Truncation length for backend='transformer'.", 256),
            _p("device", "str", "Device for embedding / transformer encoding.", "cpu"),
            _p("random_state", "int | None", "RNG seed where the head uses one.", 0),
        ),
        inputs=("Train documents plus the Session target column.",),
        outputs=("NlpTextPlan on the Session plus an NlpFitResult summary.",),
        prerequisites=(DATASET, ROLES, SPLIT, NLP_TEXT_COLUMN, NLP_EXTRA),
        ordering=("After split and profile_text_corpus; before predict / evaluate / interpret.",),
        alternatives=(
            "text_features + fit() when text is one signal among many tabular columns; the Torch text path when weights must be updated; RAG when the answer lives in a document to retrieve and cite.",
        ),
        rationale=(
            "A train-fitted linear model over TF-IDF is a strong, cheap, and explainable baseline that any heavier text model has to beat.",
        ),
        assumptions=(
            "One label per document; holdout documents resemble train in language and register.",
        ),
        failures=(
            "No split, or too few train documents to fit a vocabulary.",
            "A single target class, or null targets.",
            "backend='embedding' or 'transformer' without buildml[nlp].",
        ),
        leakage=(
            "Normalization, vocabulary, document frequencies, and the head are fitted on train only; validation and test are transform-and-score.",
        ),
        anti_patterns=(
            "Fitting the vectorizer on the whole frame before splitting.",
            "Choosing embeddings for a task where TF-IDF is both stronger and readable.",
            "Expecting token attribution after choosing vectorizer='hashing'.",
        ),
        state_changes=(
            "Stores nlp_text_plan and nlp_fit_result; clears prior NLP eval, predict, and interpret results.",
        ),
        result_reading=(
            "train_score is in-sample; read evaluate_text_classifier for an honest number.",
            "vocabulary_size is 0 for hashing because nothing is stored.",
        ),
        next_steps=(
            "evaluate_text_classifier; interpret_text_prediction; predict_text; save_nlp_bundle.",
        ),
        concepts=(
            "nlp-document-representation",
            "nlp-text-normalization",
            "nlp-token-attribution",
            "nlp-vs-rag",
            "leakage-boundary",
        ),
    ),
    _operation(
        "predict_text",
        OperationKind.MODEL,
        "Score a partition with the train-fitted text plan.",
        "Produce labels, and probabilities where the head genuinely supports them.",
        "NLP predict step.",
        (
            "Require an NlpTextPlan.",
            "Transform documents with the stored vectorizer; never refit.",
            "Return probabilities only when the head exposes calibrated ones.",
            "Report the out-of-vocabulary token rate for the scored partition.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to score.",
                "test",
            ),
            _p(
                "return_probabilities",
                "bool",
                "Include class probabilities when the head supports them.",
                True,
            ),
        ),
        inputs=("NlpTextPlan plus the requested partition's documents.",),
        outputs=("NlpPredictResult with predictions, optional probabilities, and OOV rate.",),
        prerequisites=(DATASET, NLP_TEXT_PLAN),
        ordering=("After fit_text_classifier or load_nlp_bundle.",),
        alternatives=("evaluate_text_classifier when labels exist and metrics are wanted.",),
        rationale=("Scoring is separate from evaluation so unlabeled text can still be classified.",),
        assumptions=("The partition exposes the plan's text column.",),
        failures=("No plan attached; the text column missing from the frame.",),
        leakage=("Transform-and-score only; no vocabulary or head update.",),
        anti_patterns=(
            "Treating LinearSVC margins as probabilities.",
            "Refitting the vectorizer on the scoring partition.",
        ),
        state_changes=("Stores nlp_predict_result; adds a history record.",),
        result_reading=(
            "An empty probabilities tuple means the head is margin-only, which is stated as a warning.",
            "A high oov_rate means the fitted vocabulary cannot see much of this partition's text.",
        ),
        next_steps=("evaluate_text_classifier; interpret_text_prediction.",),
        concepts=(
            "nlp-document-representation",
            "nlp-text-normalization",
            "probability-calibration",
        ),
    ),
    _operation(
        "evaluate_text_classifier",
        OperationKind.MODEL,
        "Evaluate the text classifier on a holdout partition.",
        "Get an honest classification report for documents the model never saw.",
        "NLP evaluate step.",
        (
            "Require an NlpTextPlan.",
            "Resolve validation, falling back to test when no validation partition exists.",
            "Report accuracy, balanced accuracy, macro and weighted F1, plus log loss and ROC AUC where probabilities exist.",
            "Return a per-class report and a confusion matrix alongside the holdout OOV rate.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition; validation falls back to test when absent.",
                "validation",
            ),
        ),
        inputs=("NlpTextPlan plus holdout documents and labels.",),
        outputs=("NlpEvalResult with metrics, per-class report, and confusion matrix.",),
        prerequisites=(DATASET, SPLIT, NLP_TEXT_PLAN),
        ordering=("After fit_text_classifier; before reporting any score.",),
        alternatives=("predict_text when labels are unavailable.",),
        rationale=(
            "Accuracy alone hides class imbalance, so balanced accuracy and a per-class report ship with it.",
        ),
        assumptions=("Non-null holdout labels drawn from the fitted classes.",),
        failures=("No plan; an empty partition; holdout labels unseen at fit time.",),
        leakage=(
            "Holdout scoring only. Read profile_text_corpus first: duplicate documents across the split make even a correct score meaningless.",
        ),
        anti_patterns=(
            "Reporting the fit result's train_score as holdout performance.",
            "Tuning against test because no validation partition was created.",
        ),
        state_changes=("Stores nlp_eval_result; adds a history record.",),
        result_reading=(
            "Compare accuracy with balanced_accuracy: a large gap means the majority class is carrying the score.",
            "log_loss and roc_auc appear only when the head produced probabilities.",
        ),
        next_steps=("interpret_text_prediction; save_nlp_bundle.",),
        concepts=(
            "nlp-document-representation",
            "nlp-corpus-contamination",
            "evaluation-partitions",
            "class-imbalance",
        ),
    ),
    _operation(
        "interpret_text_prediction",
        OperationKind.DIAGNOSTIC,
        "Explain document decisions with per-token contributions.",
        "See exactly which tokens moved a document toward or away from a class.",
        "NLP explanation step.",
        (
            "Require an invertible vocabulary; refuse hashing, embedding, and encoder representations.",
            "Read the head's coefficients, expanding binary linear heads into two signed rows.",
            "Multiply coefficients by the document's own feature values to get exact contributions.",
            "Rank per-document contributions by magnitude and, separately, rank global class weights.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to explain.",
                "test",
            ),
            _p(
                "target_class",
                "Any",
                "Class whose score is decomposed; defaults to the positive class for binary problems.",
                None,
            ),
            _p("top_k", "int", "Tokens to report per document and per class.", 12),
            _p("max_documents", "int", "Cap on explained documents.", 10),
            _p("include_global", "bool", "Also rank the head's global class weights.", True),
        ),
        inputs=("NlpTextPlan with feature names plus the partition's documents.",),
        outputs=("NlpInterpretResult with per-document TokenAttribution rows and global top tokens.",),
        prerequisites=(DATASET, NLP_TEXT_PLAN),
        ordering=("After fit_text_classifier and evaluate_text_classifier.",),
        alternatives=(
            "extract_keyphrases for unsupervised description; feature_importance for tabular models.",
        ),
        rationale=(
            "For a linear head the decomposition is an identity, so attribution can be exact instead of approximate.",
        ),
        assumptions=("The head is linear or naive Bayes and the plan carries feature names.",),
        failures=(
            "vectorizer='hashing' (refused: no invertible vocabulary).",
            "backend='embedding' or 'transformer' (refused: latent dense vectors).",
            "target_class not among the fitted classes.",
        ),
        leakage=("Read-only inspection of a fitted model.",),
        anti_patterns=(
            "Approximating attributions for a non-invertible representation to avoid an error.",
            "Presenting global coefficient rankings as an explanation of one prediction.",
            "Reading coefficients as causal effects of words.",
        ),
        state_changes=("Stores nlp_interpret_result; adds a history record.",),
        result_reading=(
            "A positive contribution pushes the document toward the target class.",
            "A large weight with value 0 contributes nothing, because the token did not occur.",
            "Global top tokens ignore frequency, so a high-weight token may be rare and practically irrelevant.",
        ),
        next_steps=("save_nlp_bundle; extract_keyphrases for a corpus-level view.",),
        concepts=(
            "nlp-token-attribution",
            "nlp-document-representation",
            "feature-importance",
        ),
    ),
    _operation(
        "fit_topics",
        OperationKind.MODEL,
        "Fit an unsupervised topic model on Session train documents.",
        "Discover the recurring vocabulary patterns in a corpus, with a coherence number attached.",
        "NLP unsupervised structure step.",
        (
            "Require a SplitPlan; fit on train documents only.",
            "Vectorize with TF-IDF for NMF or counts for LDA.",
            "Decompose into n_topics components and rank each topic's terms.",
            "Compute NPMI coherence per topic from train co-occurrence, and report train mass.",
        ),
        parameters=(
            _p(
                "method",
                "nmf | lda",
                "Deterministic TF-IDF factorization, or a probabilistic count mixture.",
                "nmf",
            ),
            _p("n_topics", "int", "Number of components to fit.", 6),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p("top_terms", "int", "Terms reported per topic.", 10),
            _p("max_features", "int | None", "Vocabulary cap by corpus frequency.", 20000),
            _p("min_df", "int | float", "Drop terms below this document frequency.", 2),
            _p("max_df", "int | float", "Drop near-universal boilerplate terms.", 0.95),
            _p("ngram_range", "tuple[int, int]", "Inclusive (min_n, max_n) n-gram sizes.", (1, 1)),
            _p("normalize_steps", "list[str] | None", "Ordered character-level steps.", None),
            _p("stopwords", "list[str] | None", "Extra stopwords added to the language list.", None),
            _p(
                "stopword_language",
                "str | None",
                "Built-in stopword list; topics are usually unreadable without one.",
                "en",
            ),
            _p("stem", "bool", "Collapse morphological variants before counting.", False),
            _p("max_iter", "int", "Solver iterations.", 300),
            _p("random_state", "int | None", "RNG seed for reproducible components.", 0),
        ),
        inputs=("Train documents from the Session dataset.",),
        outputs=("NlpTopicPlan on the Session plus an NlpTopicResult summary.",),
        prerequisites=(DATASET, SPLIT, NLP_TEXT_COLUMN),
        ordering=("After split and profile_text_corpus; before assign_topics.",),
        alternatives=(
            "fit_clusters for tabular structure; extract_keyphrases for per-document description without a fitted model.",
        ),
        rationale=(
            "Fitting on train only makes assign_topics on holdout a pure transform, so topic weights stay usable as honest features.",
        ),
        assumptions=(
            "Enough documents to estimate term co-occurrence; min_df and max_df have removed one-off tokens and boilerplate.",
        ),
        failures=(
            "Too few train documents for the requested topic count.",
            "An empty vocabulary after min_df / max_df filtering.",
        ),
        leakage=("Vectorizer and decomposition are fitted on train only.",),
        anti_patterns=(
            "Fitting topics on the full corpus and then using topic weights as model inputs.",
            "Presenting the auto-generated top-term label as a validated category name.",
            "Comparing coherence across different vectorizer settings as an absolute scale.",
        ),
        state_changes=(
            "Stores nlp_topic_plan and nlp_topic_result; clears any prior topic assignment.",
        ),
        result_reading=(
            "Read terms and weights rather than the generated label when deciding what a topic is.",
            "Low or negative coherence means the top terms rarely co-occur; treat the topic as noise.",
            "A tiny train_mass usually marks an artifact rather than a theme.",
        ),
        next_steps=("assign_topics; extract_keyphrases; save_nlp_bundle.",),
        concepts=(
            "nlp-topic-models",
            "nlp-document-representation",
            "cluster-validity-not-truth",
            "leakage-boundary",
        ),
    ),
    _operation(
        "assign_topics",
        OperationKind.MODEL,
        "Transform a partition into per-document topic weights.",
        "Apply the train-fitted topic model to new documents without refitting it.",
        "NLP topic assignment step.",
        (
            "Require an NlpTopicPlan.",
            "Transform documents with the stored vectorizer and decomposition.",
            "Report each document's dominant topic and the partition's topic share.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to transform.",
                "test",
            ),
        ),
        inputs=("NlpTopicPlan plus the requested partition's documents.",),
        outputs=("NlpTopicAssignResult with topic weights, dominant topics, and topic share.",),
        prerequisites=(DATASET, NLP_TOPIC_PLAN),
        ordering=("After fit_topics or load_nlp_bundle.",),
        alternatives=("fit_topics again on a different partition, which produces a different model.",),
        rationale=("Separating transform from fit is what keeps holdout topic weights honest.",),
        assumptions=("The partition exposes the plan's text column.",),
        failures=("No topic plan attached; an empty partition.",),
        leakage=("Transform only; the decomposition is never updated.",),
        anti_patterns=("Refitting on holdout and calling the result an assignment.",),
        state_changes=("Stores nlp_topic_assign_result; adds a history record.",),
        result_reading=(
            "topic_share shows how the partition distributes across topics; a share far from the train mass suggests drift.",
        ),
        next_steps=("save_nlp_bundle; extract_keyphrases for a term-level cross-check.",),
        concepts=(
            "nlp-topic-models",
            "unsupervised-train-fit-holdout-assign",
            "dataset-drift",
        ),
    ),
    _operation(
        "extract_keyphrases",
        OperationKind.DIAGNOSTIC,
        "Rank keyphrases for a partition with an unsupervised scorer.",
        "Describe what a corpus and its individual documents are about, with no labels required.",
        "NLP description step.",
        (
            "Normalize documents, then build candidate phrases delimited by stopwords and punctuation.",
            "Score with corpus-weighted TF-IDF, RAKE degree-over-frequency, or TextRank word centrality.",
            "Exclude bare numbers and punctuation so candidates are alphabetic content words.",
            "Return corpus-level and per-document rankings with document frequencies.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to describe.",
                "train",
            ),
            _p(
                "method",
                "tfidf | rake | textrank",
                "Corpus-weighted n-grams, degree-over-frequency phrases, or word-graph centrality.",
                "tfidf",
            ),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p("top_n", "int", "Phrases returned per ranking.", 15),
            _p("max_phrase_words", "int", "Longest candidate phrase in content words.", 3),
            _p("per_document", "bool", "Also return per-document rankings.", True),
            _p("max_documents", "int", "Cap on per-document rankings.", 25),
            _p("stopword_language", "str | None", "Built-in stopword list used as a phrase delimiter.", "en"),
            _p("stopwords", "list[str] | None", "Extra stopwords added to the language list.", None),
            _p("min_df", "int | float", "TF-IDF minimum document frequency.", 1),
            _p("max_df", "int | float", "TF-IDF maximum document frequency.", 1.0),
            _p("window", "int", "TextRank co-occurrence window in tokens.", 4),
            _p("random_state", "int | None", "Reserved for reproducibility disclosures.", 0),
        ),
        inputs=("A text column on the Session dataset.",),
        outputs=("NlpKeyphraseResult with corpus and per-document Keyphrase rankings.",),
        prerequisites=(DATASET, NLP_TEXT_COLUMN),
        ordering=("Any time after ingest; commonly alongside profile_text_corpus.",),
        alternatives=(
            "fit_topics for corpus-level themes; interpret_text_prediction for supervised token evidence.",
        ),
        rationale=(
            "Keyphrases are the cheapest honest summary of a corpus, and they need no labels or fitted state.",
        ),
        assumptions=(
            "The stopword list matches the corpus language; documents are long enough for candidates to exist.",
        ),
        failures=(
            "An empty ranking when stopwords, min_df, and max_phrase_words are jointly too strict.",
            "Boilerplate phrases dominating the corpus ranking.",
        ),
        leakage=(
            "Nothing is fitted or persisted. Running on holdout is description, and the result says so, because reading holdout text still informs the analyst.",
        ),
        anti_patterns=(
            "Claiming keyphrase precision or recall with no annotated reference.",
            "Using holdout keyphrases to choose features or hyperparameters.",
        ),
        state_changes=("Stores nlp_keyphrase_result; adds a history record.",),
        result_reading=(
            "Scores are comparable within one call, never across methods or corpora.",
            "A high corpus score with document_frequency of 1 is a single-document quirk.",
        ),
        next_steps=("fit_topics; summarize_text; fit_text_classifier.",),
        concepts=(
            "nlp-keyphrases-vs-topics",
            "nlp-text-normalization",
            "nlp-topic-models",
        ),
    ),
    _operation(
        "analyze_sentiment",
        OperationKind.DIAGNOSTIC,
        "Score a partition's documents for sentiment.",
        "Get a polarity read on text with no labels, or reuse your own fitted classifier when you have them.",
        "NLP sentiment step.",
        (
            "With backend='lexicon', sum shipped valence scores and apply negation, intensifier, contrast, punctuation, and capitalisation rules.",
            "Squash the sum into a bounded compound score and threshold it into positive, negative, or neutral.",
            "Report the matched-term rate so a neutral verdict can be distinguished from ignorance.",
            "With backend='supervised', reuse the fitted text classifier's own labels instead of inventing a second scorer.",
            "With backend='transformer', delegate to a sentiment checkpoint from buildml[nlp].",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to score.",
                "test",
            ),
            _p(
                "backend",
                "lexicon | supervised | transformer",
                "Shipped rule scorer, the fitted text classifier, or a transformer checkpoint.",
                "lexicon",
            ),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p("threshold", "float", "Compound magnitude above which a document leaves neutral.", 0.05),
            _p(
                "compare_to_target",
                "bool",
                "Report agreement when the dataset target looks like sentiment labels.",
                False,
            ),
            _p(
                "transformer_model",
                "str",
                "Hugging Face sentiment checkpoint for backend='transformer'.",
                "distilbert-base-uncased-finetuned-sst-2-english",
            ),
            _p("device", "str", "Device for the transformer backend.", "cpu"),
        ),
        inputs=("A text column; for backend='supervised', a fitted NlpTextPlan.",),
        outputs=("NlpSentimentResult with labels, scores, rates, and matched-term rate.",),
        prerequisites=(DATASET, NLP_TEXT_COLUMN, NLP_EXTRA),
        ordering=("Any time after ingest; run detect_language first on unfamiliar corpora.",),
        alternatives=(
            "fit_text_classifier on your own sentiment labels, which almost always beats a generic lexicon.",
        ),
        rationale=(
            "A transparent rule scorer works on day one with no labels, which makes it the right baseline before any supervised sentiment model.",
        ),
        assumptions=("Documents are English for the lexicon backend; the threshold suits the register.",),
        failures=(
            "backend='supervised' without a fitted text plan.",
            "backend='transformer' without buildml[nlp].",
            "Domain jargon, sarcasm, and rhetorical questions scored at face value.",
        ),
        leakage=("Read-only scoring; the lexicon backend fits nothing at all.",),
        anti_patterns=(
            "Reporting lexicon sentiment as ground truth rather than as a baseline.",
            "Applying the English lexicon to a multilingual corpus without running detect_language.",
            "Ignoring matched_term_rate when explaining a large neutral share.",
        ),
        state_changes=("Stores nlp_sentiment_result; adds a history record.",),
        result_reading=(
            "matched_term_rate near zero means the neutral share is ignorance, not balance.",
            "Compound scores are bounded and ordinal, not probabilities.",
        ),
        next_steps=("fit_text_classifier; interpret_text_prediction; extract_keyphrases.",),
        concepts=(
            "nlp-lexicon-sentiment",
            "nlp-language-identification",
            "nlp-document-representation",
        ),
    ),
    _operation(
        "extract_entities",
        OperationKind.DIAGNOSTIC,
        "Extract entity mentions from a partition's documents.",
        "Pull typed spans such as dates, money, contacts, and your own domain terms out of free text.",
        "NLP extraction step.",
        (
            "With backend='rules', apply precision-first regular expressions plus caller gazetteers matched on whole words.",
            "Resolve overlapping spans deterministically by span length and pattern priority.",
            "Record the rule or gazetteer that produced each span, so false positives are fixable.",
            "With backend='spacy', run a trained statistical model and normalize its labels to BuildML's set.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to scan.",
                "test",
            ),
            _p(
                "backend",
                "rules | spacy | None",
                "Precision-first regular expressions, or statistical NER via buildml[nlp-industry].",
                "rules",
            ),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p("labels", "list[str] | None", "Restrict output to these labels.", None),
            _p(
                "gazetteers",
                "dict[str, list[str]] | None",
                "Label to term list, matched case-insensitively on whole words.",
                None,
            ),
            _p("spacy_model", "str", "spaCy model name for backend='spacy'.", "en_core_web_sm"),
            _p("max_documents", "int", "Cap on documents scanned for spans.", 25),
            _p("batch_size", "int", "spaCy pipe batch size.", 32),
        ),
        inputs=("A text column on the Session dataset.",),
        outputs=("NlpEntityResult with per-document Entity spans, label counts, and top mentions.",),
        prerequisites=(DATASET, NLP_TEXT_COLUMN, NLP_EXTRA),
        ordering=("Any time after ingest.",),
        alternatives=(
            "text_features for tabular expansion; the Torch text path when a span model must be trained.",
        ),
        rationale=(
            "Extraction feeding an automated decision usually needs precision, so rules are often the correct engineering answer rather than a fallback.",
        ),
        assumptions=(
            "Documents are plain text with meaningful character offsets; gazetteer terms are whole words.",
        ),
        failures=(
            "Gazetteer terms that are common words, producing floods of matches.",
            "Locale-specific date and phone formats outside the shipped patterns.",
            "backend='spacy' without buildml[nlp-industry] or without the model downloaded.",
        ),
        leakage=("Read-only extraction; nothing is fitted.",),
        anti_patterns=(
            "Presenting rule output as trained NER performance.",
            "Adding a rule so broad that precision is lost, which defeats the backend's purpose.",
        ),
        state_changes=("Stores nlp_entity_result; adds a history record.",),
        result_reading=(
            "source names the rule or gazetteer behind each span.",
            "A label count of zero means no pattern covers that type, not that the corpus lacks it.",
            "start and end are character offsets into the raw document, so spans can be highlighted exactly.",
        ),
        next_steps=("summarize_text; extract_keyphrases; fit_text_classifier.",),
        concepts=(
            "nlp-rule-vs-statistical-ner",
            "nlp-text-normalization",
            "nlp-vs-rag",
        ),
    ),
    _operation(
        "summarize_text",
        OperationKind.DIAGNOSTIC,
        "Build extractive summaries for a partition's documents.",
        "Shorten long documents using only sentences their authors actually wrote.",
        "NLP summarization step.",
        (
            "Split documents into sentences with abbreviation-aware boundaries.",
            "Score sentences by graph centrality: token overlap for TextRank, TF-IDF cosine with a similarity floor for LexRank.",
            "Select the top k and emit them in original document order.",
            "Offer 'lead' as the honest baseline that graph methods have to beat.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Documents to summarize.",
                "test",
            ),
            _p(
                "method",
                "textrank | lexrank | lead",
                "Token-overlap graph, TF-IDF cosine graph, or the first k sentences.",
                "textrank",
            ),
            _p("text_column", "str | None", "Text column; inferred when unambiguous.", None),
            _p("n_sentences", "int", "Sentences per summary.", 3),
            _p("max_documents", "int", "Cap on summarized documents.", 25),
            _p("max_input_sentences", "int", "Bound the sentence graph on very long documents.", 200),
            _p("stopword_language", "str | None", "Stopword list used when comparing sentences.", "en"),
            _p("stopwords", "list[str] | None", "Extra stopwords added to the language list.", None),
        ),
        inputs=("A text column on the Session dataset.",),
        outputs=("NlpSummaryResult with summaries, selected sentence indices, and mean compression.",),
        prerequisites=(DATASET, NLP_TEXT_COLUMN),
        ordering=("Any time after ingest.",),
        alternatives=(
            "extract_keyphrases for phrase-level description; RAG plus a provider when generated prose is genuinely required.",
        ),
        rationale=(
            "Extractive selection cannot state a fact the document does not contain, which matters more than fluency for most analysis work.",
        ),
        assumptions=(
            "Documents contain multiple sentences with detectable boundaries; sentence similarity proxies importance in this genre.",
        ),
        failures=(
            "Single-sentence documents, where every method returns the input.",
            "Lists and tables, where sentence boundaries are meaningless.",
            "Redundant near-identical sentences all scoring highly.",
        ),
        leakage=("Read-only; nothing is fitted.",),
        anti_patterns=(
            "Calling extractive output 'generated' or 'abstractive'.",
            "Reporting ROUGE without reference summaries.",
            "Skipping the lead baseline and asserting the graph method is better.",
        ),
        state_changes=("Stores nlp_summary_result; adds a history record.",),
        result_reading=(
            "selected_sentence_indices lets you highlight the summary inside the original document.",
            "mean_compression near 1.0 means the document was already about as short as the request.",
        ),
        next_steps=("extract_keyphrases; extract_entities.",),
        concepts=(
            "nlp-extractive-summarization",
            "nlp-keyphrases-vs-topics",
            "nlp-vs-rag",
        ),
    ),
    _operation(
        "save_nlp_bundle",
        OperationKind.MODEL,
        "Persist the active NLP plan(s) as buildml.nlp_bundle.v1.",
        "Keep the fitted vectorizer, head, topic model, and normalization plan together on disk.",
        "NLP bundle save.",
        (
            "Require at least one active plan (text or topic).",
            "Write meta.json plus joblib payloads for each present plan.",
            "Do not embed the plans in Session checkpoints.",
        ),
        parameters=(_p("path", "str | Path", "Bundle directory.", required=True),),
        inputs=("Active NlpTextPlan and/or NlpTopicPlan, plus optional fit and eval summaries.",),
        outputs=("Bundle directory path.",),
        prerequisites=(DATASET,),
        ordering=("After fit_text_classifier or fit_topics.",),
        alternatives=("checkpoint_save for workflow state only.",),
        rationale=(
            "The normalization plan travels with the vectorizer, so a reloaded model preprocesses text exactly as it was fitted.",
        ),
        assumptions=("Writable path.",),
        failures=("No NLP plan attached.",),
        leakage=("Persistence only.",),
        anti_patterns=(
            "Expecting checkpoint_load to restore an NLP plan.",
            "Shipping a fitted vectorizer without its normalization plan.",
        ),
        state_changes=("History record only.",),
        result_reading=("Confirm meta.json format is buildml.nlp_bundle.v1.",),
        next_steps=("load_nlp_bundle on a new Session.",),
        concepts=("nlp-bundle-boundary", "nlp-text-normalization", "checkpoint-integrity"),
    ),
    _operation(
        "load_nlp_bundle",
        OperationKind.MODEL,
        "Load an NLP bundle into this Session.",
        "Restore a fitted text classifier and/or topic model from disk.",
        "NLP bundle load.",
        (
            "Validate the buildml.nlp_bundle.v1 format tag.",
            "Attach whichever plans the bundle carries.",
            "Clear stale fit, eval, predict, interpret, and topic results so nothing misattributes to the new plan.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory.",),
        outputs=("Session with NlpTextPlan and/or NlpTopicPlan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest; usually after split so holdout scoring is available.",),
        alternatives=("fit_text_classifier or fit_topics to create new plans.",),
        rationale=("Reload a fitted vocabulary rather than rebuilding it from train.",),
        assumptions=("Bundle format matches; the Session exposes the same text column name.",),
        failures=(
            "Incomplete or wrong-format bundle.",
            "A text column named differently in this Session.",
        ),
        leakage=("Load does not fit; scoring still uses holdout only.",),
        anti_patterns=("Treating RAG bundles and NLP bundles as interchangeable.",),
        state_changes=("Stores nlp_text_plan and/or nlp_topic_plan; clears dependent results.",),
        result_reading=("Inspect plan.estimator, plan.text_column, and plan.n_features after load.",),
        next_steps=("evaluate_text_classifier; predict_text; assign_topics.",),
        concepts=("nlp-bundle-boundary", "nlp-vs-rag", "leakage-boundary"),
    ),
)
