# ruff: noqa: E501, F401
"""Online / continual Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

ONLINE_PLAN = Prerequisite(
    "online-plan",
    "A warm-started OnlinePlan is attached to the Session.",
    check_hint="Session.online_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_online",
        OperationKind.MODEL,
        "Warm-start an incremental partial_fit estimator on a train chunk.",
        "Fit the first train chunk; freeze feature contract, classes, and cursor.",
        "Online / continual init step.",
        (
            "Require a SplitPlan and a target role.",
            "Carve an initial train chunk (n_init or chunk_size).",
            "For classifiers, set classes= or discover from full train targets (labels only).",
            "Call partial_fit (refuse silent full refit unless allow_refit_fallback).",
            "Never use validation/test for the init update.",
        ),
        parameters=(
            _p("backend", "sklearn | industry | torch | None", "Online backend; honest default when installed."),
            _p(
                "estimator",
                "Backend-specific estimator name (see online_capability_matrix).",
                "sgd_classifier",
            ),
            _p("task", "classification | regression | None", "Optional task override."),
            _p("columns", "list[str] | None", "Optional explicit numeric columns."),
            _p("random_state", "int | None", "RNG seed where applicable.", 0),
            _p("chunk_size", "int", "Default subsequent update chunk size.", 50),
            _p("n_init", "int | None", "Initial chunk size (defaults to chunk_size)."),
            _p("indices", "list | tuple | None", "Optional explicit train indices for init."),
            _p(
                "classes",
                "list | tuple | None",
                "Classifier label vocabulary; else discovered from train targets.",
            ),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer Session.reduce_dimensions component columns when available.",
                True,
            ),
            _p(
                "allow_refit_fallback",
                "bool",
                "Permit disclosed full refit when partial_fit is missing.",
                False,
            ),
            _p(
                "drift_disclose",
                "bool",
                "Emit lite drift notes on updates/evaluate.",
                True,
            ),
            _p(
                "drift_detector",
                "mean_shift | adwin | page_hinkley | none",
                "Drift disclosure mode (River detectors need backend=industry).",
                "mean_shift",
            ),
            _p("buffer_size", "int", "Torch replay buffer capacity.", 512),
            _p("epochs_per_update", "int", "Torch training epochs per partial_fit.", 5),
            _p("device", "str", "Torch device string.", "cpu"),
        ),
        inputs=("Split Session with numeric features and a labeled train target.",),
        outputs=("OnlineFitResult; OnlinePlan stored on the Session.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split and usually after impute/scale.",),
        alternatives=(
            "Session.fit for a single full-batch classical fit.",
            "Session.fit_active_learner when labels arrive via human queries.",
        ),
        rationale=(
            "Use when data arrives (or is carved) in chunks and the estimator supports partial_fit.",
        ),
        assumptions=(
            "Estimator is in the sklearn partial_fit family (or fallback is explicit).",
            "Features are numeric and non-null.",
        ),
        failures=(
            "Missing split/target, null features, unknown estimator, missing classes, "
            "estimator without partial_fit when fallback is False.",
        ),
        leakage=(
            "Using validation/test rows as the init chunk.",
            "Fitting before split contaminates holdout metrics.",
        ),
        anti_patterns=(
            "Silent full .fit each round while claiming online learning.",
            "Treating this as a distributed streaming platform.",
        ),
        state_changes=(
            "Stores online_plan and fit result; clears prior update/eval/predict slots.",
        ),
        result_reading=(
            "Read n_init_rows, n_remaining_train, classes, disclosures, used_refit_fallback.",
        ),
        next_steps=(
            "partial_fit_online → evaluate_online; optionally save_online_bundle.",
        ),
        concepts=(
            "online-partial-fit",
            "online-class-discovery",
            "leakage-boundary",
        ),
    ),
    _operation(
        "partial_fit_online",
        OperationKind.MODEL,
        "Incremental partial_fit update on the next train chunk or frame.",
        "Advance the train cursor (or accept indices/frame); update without holdout leakage.",
        "Online / continual update step.",
        (
            "Require an attached OnlinePlan.",
            "Carve next train chunk, explicit train indices, or a role-aligned frame.",
            "Refuse validation/test indices.",
            "Call partial_fit (or disclosed refit fallback).",
            "Optionally disclose chunk vs init mean-shift notes.",
        ),
        parameters=(
            _p("n_rows", "int | None", "Rows to take from the train cursor (default chunk_size)."),
            _p("indices", "list | tuple | None", "Explicit train-partition dataset indices."),
            _p(
                "frame",
                "DataFrame | None",
                "User-provided incremental frame with aligned feature/target columns.",
            ),
        ),
        inputs=("Active OnlinePlan and a train chunk source.",),
        outputs=("OnlineUpdateResult; updated OnlinePlan on the Session.",),
        prerequisites=(DATASET, ONLINE_PLAN),
        ordering=("After fit_online or load_online_bundle.",),
        alternatives=("fit_online again to restart the stream contract.",),
        rationale=("Use to apply subsequent incremental updates without full refits.",),
        assumptions=("Chunk targets are non-null; columns match the plan contract.",),
        failures=(
            "No plan; exhausted train cursor; non-train indices; new unseen classes; "
            "null features/targets.",
        ),
        leakage=("Passing validation/test indices as the update chunk.",),
        anti_patterns=("Silent full refit without allow_refit_fallback disclosure.",),
        state_changes=("Updates online_plan and online_update_result.",),
        result_reading=(
            "Read n_chunk_rows, n_seen_rows, update_mode, drift_notes, disclosures.",
        ),
        next_steps=("More partial_fit_online, or evaluate_online / save_online_bundle.",),
        concepts=(
            "online-partial-fit",
            "online-drift-disclose",
            "online-class-discovery",
            "leakage-boundary",
        ),
    ),
    _operation(
        "evaluate_online",
        OperationKind.DIAGNOSTIC,
        "Evaluate the online learner on a holdout partition (never for updates).",
        "Score accuracy/F1 or MAE/RMSE/R²; disclose incremental state.",
        "Online / continual evaluation step.",
        (
            "Predict with the frozen incremental estimator.",
            "Score a holdout partition that was never used for partial_fit.",
            "Report task-appropriate metrics with n_seen_rows / n_updates disclosures.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation falls back to test if absent).",
                "validation",
            ),
            _p(
                "drift_check",
                "bool",
                "Surface River or mean-shift drift notes without model update.",
                True,
            ),
        ),
        inputs=("Active OnlinePlan and a labeled evaluation partition.",),
        outputs=("OnlineEvalResult.",),
        prerequisites=(DATASET, ONLINE_PLAN),
        ordering=("After fit_online / partial_fit_online.",),
        alternatives=("Classical Session.evaluate when using a full-batch FitResult.",),
        rationale=("Use to quantify holdout quality as chunks are consumed.",),
        assumptions=("Holdout has labeled rows for the metrics you care about.",),
        failures=("No plan; empty/null evaluation partition.",),
        leakage=("Using evaluate_online metrics to choose which train chunks to replay.",),
        anti_patterns=("Reporting train chunk accuracy as holdout performance.",),
        state_changes=("Stores online_eval_result.",),
        result_reading=("Read n_rows, n_seen_rows, n_updates, metrics, disclosures.",),
        next_steps=("save_online_bundle; or continue partial_fit_online.",),
        concepts=(
            "online-partial-fit",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "predict_online",
        OperationKind.DIAGNOSTIC,
        "Predict with the incremental online estimator (no update).",
        "Score a partition without advancing the online state.",
        "Online / continual predict step.",
        (
            "Require an attached OnlinePlan.",
            "Predict without calling partial_fit.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Prediction partition.",
                "test",
            ),
        ),
        inputs=("Active OnlinePlan.",),
        outputs=("OnlinePredictResult.",),
        prerequisites=(DATASET, ONLINE_PLAN),
        ordering=("After fit_online / partial_fit_online.",),
        alternatives=("evaluate_online when you also need metrics.",),
        rationale=("Use for inference snapshots without mutating the stream state.",),
        assumptions=("Feature columns match the plan contract.",),
        failures=("No plan; missing columns; null features.",),
        leakage=("None inherent — still do not train on predictions.",),
        anti_patterns=("Feeding predictions back as unlabeled update rows without disclosure.",),
        state_changes=("Stores online_predict_result.",),
        result_reading=("Read n_rows / n_predictions and disclosures.",),
        next_steps=("evaluate_online or save_online_bundle.",),
        concepts=("online-partial-fit",),
    ),
    _operation(
        "save_online_bundle",
        OperationKind.PERSIST,
        "Persist the active OnlinePlan as buildml.online_bundle.v1.",
        "Write a domain bundle distinct from Session checkpoints.",
        "Online-learning bundle save.",
        ("Require an attached plan.", "Write meta.json + online_plan.joblib."),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active OnlinePlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(ONLINE_PLAN,),
        ordering=("After a successful fit_online / update round.",),
        alternatives=("Session.checkpoint_save for workflow resume without the learner.",),
        rationale=("Use when the incremental model + update ledger must travel separately.",),
        assumptions=("Destination is writable.",),
        failures=("No plan attached.",),
        leakage=("Bundles do not embed holdout rows.",),
        anti_patterns=("Assuming a Session checkpoint embeds the OnlinePlan.",),
        state_changes=("History records save_online_bundle.",),
        result_reading=("Confirm meta.json format buildml.online_bundle.v1.",),
        next_steps=("load_online_bundle in another Session.",),
        concepts=("online-bundle-boundary",),
    ),
    _operation(
        "load_online_bundle",
        OperationKind.PERSIST,
        "Load a buildml.online_bundle.v1 OnlinePlan into the Session.",
        "Restore an incremental learner + update history without refitting.",
        "Online-learning bundle load.",
        ("Validate bundle format.", "Attach OnlinePlan; clear fit/update/eval/predict slots."),
        parameters=(_p("path", "str | Path", "Bundle directory.", required=True),),
        inputs=("Bundle directory with meta.json + online_plan.joblib.",),
        outputs=("Session with online_plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest/roles/split aligned with the plan feature contract.",),
        alternatives=("fit_online to learn a new plan.",),
        rationale=("Use to resume an incremental update ledger.",),
        assumptions=("Feature columns and target role still match the plan contract.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Do not treat load as permission to update on holdout rows.",),
        anti_patterns=("Loading into a Session whose features drifted from the plan.",),
        state_changes=("Sets online_plan; clears fit/update/eval/predict result slots.",),
        result_reading=("Inspect Session.online_plan.to_dict().",),
        next_steps=("partial_fit_online / evaluate_online / predict_online.",),
        concepts=("online-bundle-boundary",),
    ),
)
