# ruff: noqa: E501, F401
"""RAG Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    AI,
    AI_PROVIDER,
    DASHBOARD,
    DATASET,
    FIT,
    FIT_TORCH,
    RAG,
    RAG_CORPUS,
    RAG_INDEX,
    ROLES,
    SPLIT,
    TORCH,
    VIZ,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "rag_ingest_corpus",
        OperationKind.INGEST,
        "Load text files, in-memory documents, or a tabular text column into a RAG corpus.",
        "Attach an explicit corpus handle without silently indexing the whole Session frame.",
        "RAG corpus ingest boundary.",
        (
            "Accept a path/directory, document sequence, or text_column bridge.",
            "Assign document roles (index vs eval_only).",
            "Store a CorpusHandle on the Session.",
        ),
        parameters=(
            _p("source", "str | Path | sequence | None", "File, directory, or document sequence."),
            _p("text_column", "str | None", "Optional Session-frame text column to bridge."),
            _p("id_column", "str | None", "Optional id column when bridging a frame."),
            _p("glob", "str", "Filename pattern for directories.", "*.txt"),
            _p("encoding", "str", "Text encoding for files.", "utf-8"),
            _p("role", "index | eval_only", "Document role for hygiene checks.", "index"),
        ),
        inputs=("Text files, document mappings, or a Session frame text column.",),
        outputs=("Session with an attached RAG corpus handle.",),
        prerequisites=(RAG,),
        ordering=("Before rag_chunk / rag_embed_and_index; separate from classical ingest.",),
        alternatives=("Build a CorpusHandle via buildml.rag.corpus and stay outside Session.",),
        rationale=("Use when retrieval needs a document corpus rather than a supervised design matrix.",),
        assumptions=("UTF-8 (or declared encoding) text is readable; role labels are honest.",),
        failures=("Missing path matches, decode errors, empty text column, or missing RAG extra.",),
        leakage=(
            "Labeling eval answers as index documents contaminates later retrieval metrics.",
            "Silently indexing every Session column would mix identifiers and labels into the corpus.",
        ),
        anti_patterns=(
            "Expecting rag_ingest_corpus to replace Session.ingest for tabular ML.",
            "Putting labeled eval answers into the index role without disclosure.",
        ),
        state_changes=("Stores rag corpus; clears prior RAG index/retrieve/eval slots.",),
        result_reading=("Check n_documents, source, doc_ids, and roles in the history summary.",),
        next_steps=("rag_chunk, then rag_embed_and_index on index-role documents only.",),
        concepts=("rag-eval-contamination", "rag-chunk-index-boundary", "leakage-boundary"),
    ),
    _operation(
        "rag_chunk",
        OperationKind.TRANSFORM,
        "Split the active RAG corpus into overlapping character chunks with stable ids.",
        "Choose the retrieval unit before embedding and indexing.",
        "RAG chunking step.",
        (
            "Require an ingested corpus.",
            "Apply size/overlap chunking.",
            "Emit deterministic chunk ids of the form {doc_id}::c{ordinal}.",
        ),
        parameters=(
            _p("size", "int", "Chunk character size.", 512),
            _p("overlap", "int", "Overlap between adjacent chunks.", 64),
        ),
        inputs=("Active RAG corpus.",),
        outputs=("ChunkResult stored on the Session.",),
        prerequisites=(RAG_CORPUS, RAG),
        ordering=("After rag_ingest_corpus; before or inside rag_embed_and_index.",),
        alternatives=("Pass chunk_size/chunk_overlap directly to rag_embed_and_index.",),
        rationale=("Stable chunk ids support audit, bundle reload, and later upsert work.",),
        assumptions=("Chunk size exceeds overlap; document text is already decoded.",),
        failures=("No corpus, invalid size/overlap, or missing RAG extra.",),
        leakage=("Chunking eval_only text that later enters the index contaminates retrieval eval.",),
        anti_patterns=("Changing chunk size between index build and evaluation without rebuilding.",),
        state_changes=("Stores chunk snapshot for the next index build.",),
        result_reading=("Read n_chunks, n_documents, and the size/overlap config.",),
        next_steps=("rag_embed_and_index.",),
        concepts=("rag-chunk-index-boundary", "rag-eval-contamination"),
    ),
    _operation(
        "rag_embed_and_index",
        OperationKind.MODEL,
        "Embed chunks and build the default NumPy cosine vector index.",
        "Construct a dense retrieval index with typed IndexResult disclosures.",
        "RAG index build boundary.",
        (
            "Refuse corpora that contain eval_only documents.",
            "Chunk if needed, encode texts, build NumpyCosineStore.",
            "Store RagIndex and IndexResult on the Session.",
        ),
        parameters=(
            _p("embedder", "str | callable | Embedder | None", "Default hashing; callable or ST override."),
            _p("chunk_size", "int | None", "Optional chunk size when chunking inside this call."),
            _p("chunk_overlap", "int | None", "Optional chunk overlap when chunking inside this call."),
        ),
        inputs=("RAG corpus and optional prior ChunkResult.",),
        outputs=("Session with rag_index_result (IndexResult) distinct from fit_result / dl_train_result.",),
        prerequisites=(RAG_CORPUS, RAG),
        ordering=("After corpus ingest (and optional rag_chunk); before rag_retrieve / rag_evaluate.",),
        alternatives=("Use classical Session.fit for tabular estimators; use fit_torch for nn.Module training.",),
        rationale=("Choose RAG indexing when the task is retrieve-then-read rather than supervised fit.",),
        assumptions=("Index-role documents only; embedder dim matches later query encoding.",),
        failures=("eval_only contamination, empty corpus, embedder errors, or missing RAG extra.",),
        leakage=(
            "Indexing labeled eval answers invalidates recall@k / MRR generalization claims.",
        ),
        anti_patterns=(
            "Treating hashing-embedder demos as semantic retrieval quality without disclosure.",
            "Expecting Session.checkpoint_save to persist the vector index.",
        ),
        state_changes=("Stores rag_index / rag_index_result; classical and Torch slots unchanged.",),
        result_reading=(
            "Read n_chunks, embedder_id, dim, store_backend, and disclosures "
            "(hashing is lexical/hashed, not semantic).",
        ),
        next_steps=("rag_retrieve; rag_evaluate with held-out qrels; save_rag_bundle.",),
        concepts=(
            "rag-chunk-index-boundary",
            "rag-eval-contamination",
            "rag-retrieval-metrics",
            "leakage-boundary",
        ),
    ),
    _operation(
        "rag_retrieve",
        OperationKind.DIAGNOSTIC,
        "Top-k retrieve against the active RAG index (dense, BM25, or hybrid).",
        "Return ranked chunk hits with scores, mode, and embedder disclosures.",
        "RAG retrieval (dense / BM25 / hybrid).",
        (
            "Require an active RagIndex.",
            "Run dense cosine, BM25, or fused hybrid retrieval.",
            "Optionally filter by chunk metadata and rerank with a cross-encoder.",
        ),
        parameters=(
            _p("query", "str", "Query text.", required=True),
            _p("k", "int", "Number of hits to return.", 5),
            _p("mode", "str", "dense (default), bm25, or hybrid.", "dense"),
            _p("fusion", "str | None", "Hybrid fusion: rrf (default) or weighted.", None),
            _p("filters", "dict | None", "Equality filters on chunk metadata.", None),
            _p("rerank", "bool | str", "False (default), True/'cross-encoder', or model id.", False),
        ),
        inputs=("Active RagIndex and a non-empty query string.",),
        outputs=("RetrieveResult with ranked hits, mode, and optional fusion/rerank notes.",),
        prerequisites=(RAG_INDEX, RAG),
        ordering=("After rag_embed_and_index or load_rag_bundle; before or beside rag_evaluate.",),
        alternatives=("Call buildml.rag.retrieve directly on a RagIndex.",),
        rationale=("Use when you need ranked evidence passages for a query.",),
        assumptions=("Query embedder is compatible with the stored embedding dim for dense/hybrid.",),
        failures=("No index, empty query, invalid mode, or missing RAG extra for cross-encoder rerank.",),
        leakage=("Retrieving from an index that includes eval answers is not a fair eval setup.",),
        anti_patterns=("Calling retrieval success 'accuracy' without qrels and k.",),
        state_changes=("Stores rag_retrieve_result; index weights unchanged.",),
        result_reading=(
            "Inspect hit doc_ids, scores, k, mode, filters, rerank, and embedder_id disclosures.",
        ),
        next_steps=(
            "rag_generate for grounded answers with citations; "
            "rag_evaluate for aggregate metrics; save_rag_bundle when the index is stable.",
        ),
        concepts=("rag-retrieval-metrics", "rag-chunk-index-boundary", "rag-eval-contamination"),
    ),
    _operation(
        "rag_generate",
        OperationKind.MODEL,
        "Retrieve context and generate a grounded answer with citations.",
        "Assemble CONTEXT from ranked chunks, call a chat provider, and return citations.",
        "Retrieval-augmented generation boundary.",
        (
            "Require an active RagIndex and a chat provider.",
            "Retrieve top-k chunks (or reuse the last retrieve).",
            "Assemble grounded prompt with [source:N] labels.",
            "Call the provider and return GenerateResult with citations.",
        ),
        parameters=(
            _p("query", "str", "Question to answer from retrieved context.", required=True),
            _p("k", "int", "Retrieval depth for grounding.", 5),
            _p("provider", "ChatProvider | None", "Optional provider; else Session AI provider."),
            _p("mode", "str | None", "Optional retrieve mode override (dense/bm25/hybrid)."),
            _p("fusion", "str | None", "Optional hybrid fusion strategy override."),
            _p("filters", "dict | None", "Optional metadata filters for retrieval."),
            _p("rerank", "bool | str | None", "Optional rerank toggle or strategy."),
            _p("retrieve_config", "RetrieveConfig | None", "Optional full retrieve config."),
            _p("config", "GenerateConfig | None", "Optional generation config (prompt/budget knobs)."),
            _p("use_last_retrieve", "bool", "Reuse rag_retrieve_result instead of retrieving again.", False),
        ),
        inputs=("Active RagIndex, non-empty query, and a chat provider (or ai_configure).",),
        outputs=("GenerateResult with answer, citations, and retrieve provenance.",),
        prerequisites=(RAG_INDEX, RAG),
        ordering=("After rag_embed_and_index; optionally after rag_retrieve.",),
        alternatives=("rag_retrieve alone when you only need ranked evidence passages.",),
        rationale=("Use when the product path is retrieve-then-generate, not retrieve-only.",),
        assumptions=("Provider answers are constrained by CONTEXT; users still verify citations.",),
        failures=(
            "No index, empty query, empty retrieval, missing provider, or provider errors.",
        ),
        leakage=("Generating from an index that includes eval answers is not a fair RAG eval setup.",),
        anti_patterns=(
            "Treating grounded generate as infallible; citations must be checked against source text.",
            "Calling generate without a provider and assuming OpenAI is embedded in core.",
        ),
        state_changes=("Stores rag_generate_result and updates rag_retrieve_result when retrieving.",),
        result_reading=(
            "Read answer, n_citations, citation doc/chunk ids, provider_model, and disclosures.",
        ),
        next_steps=("save_ai_transcript for the grounded exchange; save_rag_bundle for the index.",),
        concepts=("rag-retrieval-metrics", "rag-chunk-index-boundary", "rag-eval-contamination"),
    ),
    _operation(
        "rag_evaluate",
        OperationKind.DIAGNOSTIC,
        "Score retrieval with gold qrels using recall@k, MRR, nDCG@k, and hit-rate@k.",
        "Measure ranking quality with document- or chunk-level relevance modes.",
        "RAG retrieval evaluation.",
        (
            "Require an active RagIndex.",
            "Run retrieve per eval query under the chosen mode.",
            "Aggregate recall@k, MRR, nDCG@k, and hit-rate@k.",
        ),
        parameters=(
            _p("qrels", "mapping | sequence", "Gold query → relevant doc or chunk ids.", required=True),
            _p("k", "int", "Cutoff for ranking metrics.", 5),
            _p("relevance_mode", "str", "document (default) or chunk.", "document"),
            _p("mode", "str | None", "Optional retrieve mode override (dense/bm25/hybrid).", None),
        ),
        inputs=("Active RagIndex and gold qrels.",),
        outputs=("RagEvalResult with recall_at_k, mrr, ndcg_at_k, hit_rate_at_k, per-query rows.",),
        prerequisites=(RAG_INDEX, RAG),
        ordering=("After index build; use held-out queries whose answers were not indexed.",),
        alternatives=(
            "Inspect rag_retrieve hits manually for a single debugging query.",
            "Use buildml.rag.compare_retrieval_configs for side-by-side chunk/embed trials.",
            "rag_generate for grounded answers (generation quality is separate from ranking metrics).",
        ),
        rationale=("Use when you need quantitative retrieval ranking quality.",),
        assumptions=("Qrels ids match the claimed relevance_mode (doc_id vs chunk_id).",),
        failures=("No index, empty qrels, or missing RAG extra.",),
        leakage=("Evaluating against answers that were indexed contaminates the metric.",),
        anti_patterns=(
            "Calling recall@k 'accuracy'.",
            "Tuning chunk/embed choices on the same eval queries repeatedly without disclosure.",
        ),
        state_changes=("Stores rag_eval_result; index unchanged.",),
        result_reading=(
            "Read recall_at_k, mrr, ndcg_at_k, hit_rate_at_k with k, relevance_mode, and retrieve_mode.",
        ),
        next_steps=(
            "rag_generate for grounded answers; save_rag_bundle; iterate chunk/embed configs "
            "only with clear experiment notes.",
        ),
        concepts=("rag-retrieval-metrics", "rag-eval-contamination", "evaluation-partitions"),
    ),
    _operation(
        "rag_upsert",
        OperationKind.TRANSFORM,
        "Upsert documents or chunks into the active RAG index without a full rebuild.",
        "Replace or append by chunk_id and re-embed only new or changed text.",
        "RAG index update.",
        (
            "Require an active RagIndex.",
            "Chunk documents when requested.",
            "Replace matching chunk_ids and encode only upserted rows.",
        ),
        parameters=(
            _p("documents", "sequence | None", "Documents to chunk and upsert.", None),
            _p("chunks", "sequence | None", "Pre-chunked Chunk objects to upsert.", None),
            _p("chunk", "bool", "Chunk documents with the index ChunkConfig.", True),
        ),
        inputs=("Active RagIndex and documents or chunks.",),
        outputs=("Updated IndexResult on Session.rag_index_result.",),
        prerequisites=(RAG_INDEX, RAG),
        ordering=("After rag_embed_and_index; before retrieve/evaluate on the updated index.",),
        alternatives=("Rebuild with rag_embed_and_index when embedder or chunk config changes.",),
        rationale=("Use for incremental corpus updates without re-encoding the full index.",),
        assumptions=("Upserted text uses the same embedder dim as the existing index.",),
        failures=("No index, empty payload, dim mismatch, or eval_only documents.",),
        leakage=("Upserting eval answers into the index contaminates later rag_evaluate runs.",),
        anti_patterns=("Silent full-frame upsert from Session tabular data without text_column.",),
        state_changes=("Updates rag_index / rag_index_result / rag_chunks.",),
        result_reading=("Confirm n_chunks and disclosures noting upserted/replaced counts.",),
        next_steps=("rag_retrieve; rag_evaluate; save_rag_bundle.",),
        concepts=("rag-chunk-index-boundary", "rag-eval-contamination", "leakage-boundary"),
    ),
    _operation(
        "rag_delete",
        OperationKind.TRANSFORM,
        "Delete chunks by chunk_id and/or parent doc_id from the active RAG index.",
        "Drop dense rows for removed ids without re-embedding survivors.",
        "RAG index deletion.",
        (
            "Require an active RagIndex.",
            "Remove matching chunk or document ids from the store.",
        ),
        parameters=(
            _p("chunk_ids", "sequence[str] | None", "Chunk ids to remove.", None),
            _p("doc_ids", "sequence[str] | None", "Parent document ids to remove.", None),
        ),
        inputs=("Active RagIndex and at least one id list.",),
        outputs=("Updated IndexResult on Session.rag_index_result.",),
        prerequisites=(RAG_INDEX, RAG),
        ordering=("After an index exists; before retrieve/evaluate when stale docs must leave.",),
        alternatives=("Rebuild the index from a cleaned corpus.",),
        rationale=("Use when documents leave the index corpus and a full rebuild is unnecessary.",),
        assumptions=("Ids refer to currently indexed chunks or documents.",),
        failures=("No index, or neither chunk_ids nor doc_ids provided.",),
        leakage=(
            "Deleting answer documents after a contaminated index build does not undo "
            "metric-driven tuning already done on those scores; re-run rag_evaluate on a clean index.",
            "Removing only some chunk_ids for an eval answer while sibling chunks remain "
            "leaves answer text searchable and still contaminates retrieval metrics.",
            "Choosing which documents to drop after inspecting per-query qrel failures "
            "is label-informed corpus editing and invalidates held-out retrieval claims.",
        ),
        anti_patterns=("Deleting eval evidence after contaminating metrics without re-running eval.",),
        state_changes=("Updates rag_index / rag_index_result / rag_chunks.",),
        result_reading=("Confirm n_chunks decreased and deleted_chunks disclosure.",),
        next_steps=("rag_retrieve; rag_evaluate; save_rag_bundle.",),
        concepts=("rag-chunk-index-boundary", "rag-eval-contamination", "leakage-boundary"),
    ),
    _operation(
        "save_rag_bundle",
        OperationKind.PERSIST,
        "Persist chunk config, embedder metadata, chunks, and embeddings as a RAG bundle.",
        "Carry a retrieval artifact without embedding Session data or Torch weights.",
        "RAG bundle persistence.",
        (
            "Write meta.json with format buildml.rag_bundle.v1.",
            "Write chunks.jsonl and embeddings.npy.",
        ),
        parameters=(_p("path", "str | Path", "Destination RAG bundle directory.", required=True),),
        inputs=("Active RagIndex and destination path.",),
        outputs=("Resolved bundle directory Path.",),
        prerequisites=(RAG_INDEX, RAG),
        ordering=("After evaluation; beside (not inside) Session checkpoint_save when both are needed.",),
        alternatives=(
            "Use checkpoint_save for data/roles/splits/history.",
            "Use save_torch_bundle for Torch trainer weights.",
        ),
        rationale=("Keep the vector index separate so resume and teaching stay explicit.",),
        assumptions=("Loading environments trust the artifact and supply a compatible embedder.",),
        failures=("No RAG index, unwritable path, or missing RAG extra.",),
        leakage=("Bundles can embed sensitive corpus text; access controls still apply.",),
        anti_patterns=(
            "Expecting Session checkpoint_load to restore the vector index.",
            "Passing a Torch trainer bundle path to load_rag_bundle.",
        ),
        state_changes=("Writes files and appends the destination to history.",),
        result_reading=("Treat the returned path as the bundle root; read meta.json format before load.",),
        next_steps=("Verify load_rag_bundle in a clean process; rag_retrieve a smoke query.",),
        concepts=("rag-chunk-index-boundary", "reproducibility", "leakage-boundary"),
    ),
    _operation(
        "load_rag_bundle",
        OperationKind.PERSIST,
        "Load a RAG bundle into Session rag_index_result.",
        "Restore chunks/embeddings without treating the bundle as a Session checkpoint.",
        "RAG bundle restoration.",
        (
            "Validate meta.json format buildml.rag_bundle.v1.",
            "Load chunks.jsonl and embeddings.npy.",
            "Rebuild RagIndex on the Session.",
        ),
        parameters=(_p("path", "str | Path", "Existing RAG bundle directory.", required=True),),
        inputs=("Trusted RAG bundle path.",),
        outputs=("Session with rag_index_result restored.",),
        prerequisites=(RAG,),
        ordering=("Before rag_retrieve / rag_evaluate on the restored index.",),
        alternatives=(
            "Use checkpoint_load for dataset/split/history.",
            "Use load_torch_bundle for Torch trainers.",
        ),
        rationale=("Load when you need the same index bytes and chunk metadata in a new process.",),
        assumptions=("Artifact is trusted; query embedder remains compatible with recorded dim.",),
        failures=("Wrong format (checkpoint/torch bundle), corrupt files, or dim mismatch.",),
        leakage=("A bundle retains the indexed corpus text and any sensitive content it held.",),
        anti_patterns=("Passing a Session checkpoint path to load_rag_bundle.",),
        state_changes=("Replaces rag index slots; classical fit_result and dl_train_result unchanged.",),
        result_reading=("Confirm n_chunks, embedder_id, and dim before scoring.",),
        next_steps=("rag_retrieve; rag_evaluate with held-out qrels.",),
        concepts=("rag-chunk-index-boundary", "reproducibility", "leakage-boundary"),
    ),
)
