# ruff: noqa: E501, F401
"""LTR / tabular ranking Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

RANKER_PLAN = Prerequisite(
    "ranker-plan",
    "A train-fitted RankerPlan is attached.",
    check_hint="Session.ranker_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_ranker",
        OperationKind.MODEL,
        "Fit a tabular learning-to-rank model on train judgments.",
        "Sklearn pointwise/pairwise fallback; industry GBDT rankers; torch listwise-lite.",
        "LTR fit step.",
        (
            "Require SplitPlan.",
            "Resolve backend/method via ranking_capability_matrix defaults.",
            "Resolve query_column / item_column / relevance / features.",
            "Disclose query-group split honesty (prefer group_split).",
            "Standardize features on train; fit selected ranker.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | industry | torch | None",
                "LTR backend; industry default when installed.",
                None,
            ),
            _p(
                "method",
                "pointwise | pairwise | lambdarank_lgbm | rank_ndcg_xgb | "
                "yetirank_catboost | listwise_lite | None",
                "Method for the backend; None uses installed default.",
                None,
            ),
            _p("query_column", "str", "Query id column (required)."),
            _p("item_column", "str", "Item/document id column (required)."),
            _p(
                "relevance_column",
                "str | None",
                "Relevance label column; defaults to Session target.",
            ),
            _p(
                "feature_columns",
                "list[str] | None",
                "Numeric feature columns; defaults to feature roles.",
            ),
            _p(
                "pointwise_estimator",
                "ridge | hgb",
                "Regressor for method='pointwise'.",
                "ridge",
            ),
            _p(
                "pairwise_estimator",
                "ranksvm",
                "Pairwise learner for method='pairwise'.",
                "ranksvm",
            ),
            _p(
                "max_pairs_per_query",
                "int",
                "Pair budget per query for RankSVM-lite.",
                80,
            ),
            _p(
                "relevance_threshold",
                "float",
                "Grade threshold for binary MAP/MRR relevance.",
                0.0,
            ),
            _p("alpha", "float", "Ridge regularization.", 1.0),
            _p("C", "float", "LinearSVC C for RankSVM-lite.", 1.0),
            _p("n_estimators", "int", "GBDT boosting rounds for industry backends.", 120),
            _p("learning_rate", "float", "GBDT/torch learning rate.", 0.08),
            _p("hidden_dim", "int", "Torch listwise-lite hidden width.", 64),
            _p("epochs", "int", "Torch listwise-lite epochs.", 40),
            _p("device", "str", "Torch device for listwise_lite.", "cpu"),
            _p("random_state", "int | None", "RNG seed.", 0),
        ),
        inputs=("Train partition query–item feature rows + relevance labels.",),
        outputs=("RankerPlan + RankerFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split (prefer group_split); before rank / evaluate_ranker.",),
        alternatives=(
            "Classical supervised fit on engineered features; "
            "recommenders for user–item CF; RAG for document retrieve.",
        ),
        rationale=("Ship leakage-safe Session LTR with real ranking metrics.",),
        assumptions=(
            "≥2 train queries; numeric features; graded/binary relevance present.",
        ),
        failures=(
            "No split; missing query/item columns; pairwise without distinct-grade pairs.",
        ),
        leakage=(
            "Train-only fit; prefer group_split so test query labels never enter train.",
        ),
        anti_patterns=(
            "Fitting on the full frame before split.",
            "Calling this a search-engine product or RAG.",
            "Confusing with fit_recommender CF.",
        ),
        state_changes=("Stores ranker_plan; clears prior rank/eval results.",),
        result_reading=("Inspect n_train_queries, n_features, method, disclosures.",),
        next_steps=("rank; evaluate_ranker; save_ranker_bundle.",),
        concepts=(
            "ltr-tabular-ranking",
            "ltr-pointwise",
            "ltr-pairwise",
            "ltr-industry-rankers",
            "ltr-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "rank",
        OperationKind.MODEL,
        "Order items for queries with the frozen ranker.",
        "Score candidates per query; return top-K item ids and scores.",
        "LTR inference.",
        (
            "Require RankerPlan.",
            "Resolve queries from partition or query_ids.",
            "Score rows; sort descending within each query.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all | None",
                "Source partition when query_ids omitted.",
                "test",
            ),
            _p("query_ids", "list | None", "Optional explicit query id list."),
            _p("k", "int", "Cut-off per query.", 10),
            _p(
                "backend",
                "sklearn | industry | torch | None",
                "Optional backend guard; must match frozen plan.",
                None,
            ),
        ),
        inputs=("Frozen RankerPlan + candidate judgment rows.",),
        outputs=("RankResult.",),
        prerequisites=(RANKER_PLAN,),
        ordering=("After fit_ranker.",),
        alternatives=("evaluate_ranker for metric summary.",),
        rationale=("Produce ordered item lists for queries.",),
        assumptions=("Candidate rows exist for requested queries.",),
        failures=("No RankerPlan; empty partition.",),
        leakage=("Uses frozen train standardization/weights only.",),
        anti_patterns=("Refitting on holdout before ranking.",),
        state_changes=("Stores last RankResult.",),
        result_reading=("rankings / scores parallel to query_ids.",),
        next_steps=("evaluate_ranker; save_ranker_bundle.",),
        concepts=("ltr-tabular-ranking", "ltr-ranking-metrics"),
    ),
    _operation(
        "evaluate_ranker",
        OperationKind.DIAGNOSTIC,
        "Evaluate holdout ranking metrics per query.",
        "Graded nDCG@K, MAP@K, MRR@K on frozen RankerPlan.",
        "LTR evaluation.",
        (
            "Require RankerPlan.",
            "Score holdout rows; sort within each query.",
            "Macro-average metrics over queries with ≥1 relevant item.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Holdout partition.",
                "test",
            ),
            _p("k", "int", "Cut-off for metrics.", 10),
            _p(
                "backend",
                "sklearn | industry | torch | None",
                "Optional backend guard; must match frozen plan.",
                None,
            ),
        ),
        inputs=("Frozen RankerPlan + labeled holdout judgments.",),
        outputs=("RankerEvalResult.",),
        prerequisites=(RANKER_PLAN, SPLIT),
        ordering=("After fit_ranker.",),
        alternatives=("rank for explicit lists.",),
        rationale=("Honest ranking quality under a disclosed split.",),
        assumptions=("Holdout queries with relevant items.",),
        failures=("No RankerPlan; empty holdout.",),
        leakage=("No refit; warn if queries overlap partitions.",),
        anti_patterns=(
            "Equating with RAG rag_evaluate or recommender evaluate_recommender.",
        ),
        state_changes=("Stores last RankerEvalResult.",),
        result_reading=("ndcg_at_k / map_at_k / mrr_at_k.",),
        next_steps=("save_ranker_bundle; compare pointwise vs pairwise.",),
        concepts=("ltr-ranking-metrics", "leakage-boundary"),
    ),
    _operation(
        "save_ranker_bundle",
        OperationKind.PERSIST,
        "Persist RankerPlan as buildml.ranker_bundle.v1.",
        "Writes meta.json + ranker_plan.joblib.",
        "LTR bundle save.",
        ("Require RankerPlan.", "Write bundle directory."),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("RankerPlan (+ optional fit/eval/rank summaries).",),
        outputs=("Bundle directory path.",),
        prerequisites=(RANKER_PLAN,),
        ordering=("After fit_ranker.",),
        alternatives=("Session checkpoint for workflow resume (no ranker weights).",),
        rationale=("Deployable LTR artifact separate from checkpoints.",),
        assumptions=("Writable path.",),
        failures=("No RankerPlan.",),
        leakage=("Bundle contains train-fitted weights only.",),
        anti_patterns=("Expecting dataset rows inside the bundle.",),
        state_changes=("History record only.",),
        result_reading=("Path + format buildml.ranker_bundle.v1.",),
        next_steps=("load_ranker_bundle on another Session.",),
        concepts=("ltr-bundle-boundary",),
    ),
    _operation(
        "load_ranker_bundle",
        OperationKind.PERSIST,
        "Load a buildml.ranker_bundle.v1 plan into the Session.",
        "Restores RankerPlan; clears prior fit/eval/rank result objects.",
        "LTR bundle load.",
        ("Read meta + joblib.", "Attach RankerPlan."),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Ranker bundle directory.",),
        outputs=("Session with ranker_plan.",),
        prerequisites=(DATASET,),
        ordering=("Before rank / evaluate_ranker on reloaded plan.",),
        alternatives=("Refit with fit_ranker.",),
        rationale=("Reload frozen LTR without refitting.",),
        assumptions=("Valid bundle format.",),
        failures=("Missing meta.json / ranker_plan.joblib; wrong format.",),
        leakage=("Loaded plan remains train-fitted; do not mix with holdout refit.",),
        anti_patterns=("Loading a recommender or RAG bundle here.",),
        state_changes=("Sets ranker_plan; clears fit/eval/rank result caches.",),
        result_reading=("Session.ranker_plan is not None.",),
        next_steps=("rank; evaluate_ranker.",),
        concepts=("ltr-bundle-boundary",),
    ),
)
