# ruff: noqa: E501, F401
"""Recommender Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

RECOMMENDER_PLAN = Prerequisite(
    "recommender-plan",
    "A train-fitted RecommenderPlan is attached.",
    check_hint="Session.recommender_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_recommender",
        OperationKind.MODEL,
        "Fit a recommender on train user–item interactions.",
        "Neighborhood CF, SVD/NMF, or content profiles — train only.",
        "Recommender fit step.",
        (
            "Require SplitPlan.",
            "Resolve user_column / item_column / rating (or implicit).",
            "Build train interaction matrix; fit similarities or factors.",
            "Disclose known-item protocol and cold-start policy.",
        ),
        parameters=(
            _p(
                "method",
                "item_knn | user_knn | svd | nmf | content | als | bpr | lightfm | None",
                "Recommender algorithm; None applies feedback-aware default.",
                None,
            ),
            _p(
                "backend",
                "sklearn | implicit | lightfm | None",
                "Backend routing; inferred from method when omitted.",
                None,
            ),
            _p("user_column", "str", "User id column (required)."),
            _p("item_column", "str", "Item id column (required)."),
            _p(
                "rating_column",
                "str | None",
                "Rating column; defaults to Session target for explicit feedback.",
            ),
            _p("feedback", "explicit | implicit", "Rating vs presence.", "explicit"),
            _p("n_neighbors", "int", "kNN neighborhood size.", 40),
            _p("n_factors", "int", "SVD/NMF latent factors.", 32),
            _p("min_rating", "float | None", "Optional rating threshold.", None),
            _p(
                "item_feature_columns",
                "list[str] | None",
                "Numeric item features for method='content' or LightFM hybrid.",
            ),
            _p(
                "user_feature_columns",
                "list[str] | None",
                "Numeric user features for LightFM hybrid.",
            ),
            _p("n_iterations", "int", "implicit ALS/BPR iterations.", 15),
            _p("lightfm_epochs", "int", "LightFM training epochs.", 10),
            _p(
                "cold_start",
                "popularity | skip",
                "Policy for users absent from train.",
                "popularity",
            ),
            _p("random_state", "int | None", "RNG seed for factorization.", 0),
        ),
        inputs=("Train partition interactions (+ optional item features).",),
        outputs=("RecommenderPlan + RecommenderFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split; before recommend / evaluate_recommender.",),
        alternatives=("Classical supervised fit on engineered features; RAG for documents.",),
        rationale=("Ship leakage-safe Session recommenders with real ranking metrics.",),
        assumptions=("≥2 train users and ≥2 train items; entity columns present.",),
        failures=("No split; missing user/item columns; content without features.",),
        leakage=("Train-only matrix/similarities/factors; holdout never enters at fit.",),
        anti_patterns=(
            "Fitting on the full frame before split.",
            "Calling this Netflix-scale recsys or RAG.",
            "Confusing with EDA Recommendation Findings.",
        ),
        state_changes=("Stores recommender_plan; clears prior recommend/eval results.",),
        result_reading=("Inspect n_users, n_items, method, disclosures.",),
        next_steps=("recommend; evaluate_recommender; save_recommender_bundle.",),
        concepts=(
            "recommender-collaborative-filtering",
            "recommender-content-based",
            "recommender-industry-backends",
            "recommender-cold-start",
            "recommender-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "recommend",
        OperationKind.MODEL,
        "Top-K item recommendations for users.",
        "Score train-catalog items; exclude train history by default.",
        "Recommender inference.",
        (
            "Require RecommenderPlan.",
            "Resolve users from partition or user_ids.",
            "Score candidates; apply cold-start policy.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all | None",
                "Users from this partition when user_ids omitted.",
                "test",
            ),
            _p("user_ids", "sequence | None", "Explicit user ids (mutually exclusive)."),
            _p("k", "int", "List length.", 10),
            _p(
                "exclude_train_items",
                "bool",
                "Hide items already in the user's train history.",
                True,
            ),
        ),
        inputs=("User ids + frozen RecommenderPlan.",),
        outputs=("RecommendResult (items + scores).",),
        prerequisites=(DATASET, RECOMMENDER_PLAN),
        ordering=("After fit_recommender.",),
        alternatives=("evaluate_recommender for aggregate ranking metrics.",),
        rationale=("Separate inference lists from holdout metric computation.",),
        assumptions=("Train item catalog is the candidate set.",),
        failures=("Missing plan; empty user list.",),
        leakage=("Inference only; no refit on holdout interactions.",),
        anti_patterns=("Treating recommendations as labels to refit without disclosure.",),
        state_changes=("Stores recommender_recommend_result.",),
        result_reading=("Inspect recommendations per user and cold_start_users.",),
        next_steps=("evaluate_recommender; save_recommender_bundle."),
        concepts=("recommender-collaborative-filtering", "recommender-cold-start"),
    ),
    _operation(
        "evaluate_recommender",
        OperationKind.DIAGNOSTIC,
        "Holdout ranking metrics for the frozen recommender.",
        "Precision@K, Recall@K, nDCG@K, MAP@K under known-item protocol.",
        "Recommender evaluation.",
        (
            "Require RecommenderPlan.",
            "Build holdout relevant sets (warm users, known items).",
            "Recommend top-K excluding train history; score metrics.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition.",
                "test",
            ),
            _p("k", "int", "Cutoff for ranking metrics.", 10),
        ),
        inputs=("Holdout interactions + frozen plan.",),
        outputs=("RecommenderEvalResult metrics.",),
        prerequisites=(DATASET, RECOMMENDER_PLAN),
        ordering=("After fit_recommender.",),
        alternatives=("Classical evaluate() is not a ranking substitute.",),
        rationale=("Honest holdout ranking quality with cold-start disclosure.",),
        assumptions=("Some warm users with known holdout items.",),
        failures=("Missing plan.",),
        leakage=("No fit updates from the evaluation partition.",),
        anti_patterns=("Reporting train reconstruction as holdout ranking quality.",),
        state_changes=("Stores recommender_eval_result.",),
        result_reading=("precision_at_k / recall_at_k / ndcg_at_k / map_at_k.",),
        next_steps=("save_recommender_bundle; compare methods.",),
        concepts=("recommender-ranking-metrics", "recommender-cold-start"),
    ),
    _operation(
        "save_recommender_bundle",
        OperationKind.PERSIST,
        "Persist RecommenderPlan as buildml.recommender_bundle.v1.",
        "Write meta.json + recommender_plan.joblib.",
        "Recommender bundle save.",
        ("Require RecommenderPlan.", "Serialize bundle directory."),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("Active RecommenderPlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(RECOMMENDER_PLAN,),
        ordering=("After fit_recommender.",),
        alternatives=("Session checkpoint for workflow state (does not embed recommender).",),
        rationale=("Distinct persistence boundary from checkpoints / RAG.",),
        assumptions=("Writable path.",),
        failures=("Missing plan.",),
        leakage=("N/A (serialization).",),
        anti_patterns=("Expecting checkpoint_save to include RecommenderPlan.",),
        state_changes=("None beyond history record.",),
        result_reading=("Confirm format buildml.recommender_bundle.v1 in meta.json.",),
        next_steps=("load_recommender_bundle in another Session."),
        concepts=("recommender-bundle-boundary",),
    ),
    _operation(
        "load_recommender_bundle",
        OperationKind.PERSIST,
        "Load a recommender bundle into this Session.",
        "Restore RecommenderPlan from buildml.recommender_bundle.v1.",
        "Recommender bundle load.",
        ("Read meta.json + recommender_plan.joblib.", "Attach plan; clear live results."),
        parameters=(_p("path", "str | Path", "Bundle directory."),),
        inputs=("Bundle directory.",),
        outputs=("Session with recommender_plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest; typically after checkpoint_load.",),
        alternatives=("Refit with fit_recommender.",),
        rationale=("Reload CF/content plan without refitting.",),
        assumptions=("Bundle format matches buildml.recommender_bundle.v1.",),
        failures=("Incomplete / wrong-format bundle.",),
        leakage=("Loaded plan remains train-fitted; do not treat as refit on current frame.",),
        anti_patterns=("Loading a recommender bundle into a mismatched schema Session.",),
        state_changes=("Sets recommender_plan; clears fit/eval/recommend results.",),
        result_reading=("Inspect Session.recommender_plan.to_dict().",),
        next_steps=("recommend; evaluate_recommender."),
        concepts=("recommender-bundle-boundary",),
    ),
)
