# ruff: noqa: E501, F401
"""Imitation + RL Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

IMITATION_PLAN = Prerequisite(
    "imitation-plan",
    "A train-fitted ImitationPlan (behavioral cloning policy) is attached.",
    check_hint="Session.imitation_plan is not None.",
)
RL_PLAN = Prerequisite(
    "rl-plan",
    "A fitted RlPlan (bandit or gym policy) is attached.",
    check_hint="Session.rl_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_imitation",
        OperationKind.MODEL,
        "Fit behavioral cloning from Session train demonstrations.",
        "Supervised state→action policy on train only; action defaults to target.",
        "Imitation / BC fit step.",
        (
            "Require SplitPlan.",
            "Resolve state feature columns (exclude action column).",
            "Fit classifier or regressor on train demonstrations only.",
            "Disclose BC honesty boundary (not inverse RL / robotics).",
        ),
        parameters=(
            _p("task", "classification | regression | None", "Inferred from action dtype when omitted."),
            _p(
                "estimator",
                "logistic_regression | hist_gradient_boosting | ridge | hist_gradient_boosting_regressor | None",
                "BC estimator; defaults by task.",
            ),
            _p("columns", "list[str] | None", "State feature columns."),
            _p("action_column", "str | None", "Demonstrated action; defaults to target."),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer reduce_dimensions components when present.",
                True,
            ),
        ),
        inputs=("Train partition state features + demonstrated actions.",),
        outputs=("ImitationPlan + ImitationFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split / preprocess; before predict/evaluate imitation.",),
        alternatives=("Classical fit() when the target is a standard label, not an action.",),
        rationale=("Ship leakage-safe BC for Session demo tables.",),
        assumptions=("Non-null features/actions on train.",),
        failures=("No split; null features; estimator/task mismatch.",),
        leakage=("Train-only policy fit; holdout never enters at fit.",),
        anti_patterns=(
            "Fitting BC on the full frame before split.",
            "Calling this a robotics stack.",
        ),
        state_changes=("Stores imitation_plan; clears prior imitation eval/predict.",),
        result_reading=("Inspect train_score, task, estimator, action_column.",),
        next_steps=("predict_imitation_action; evaluate_imitation; save_imitation_bundle.",),
        concepts=(
            "imitation-behavioral-cloning",
            "imitation-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "predict_imitation_action",
        OperationKind.MODEL,
        "Predict actions under the fitted BC policy.",
        "Apply the train-fitted cloning policy to a partition.",
        "Imitation action inference.",
        ("Require ImitationPlan.", "Score partition features → actions."),
        parameters=(
            _p("partition", "train | validation | test | all", "Rows to score.", "test"),
        ),
        inputs=("Partition state features.",),
        outputs=("ImitationPredictResult.",),
        prerequisites=(DATASET, IMITATION_PLAN),
        ordering=("After fit_imitation.",),
        alternatives=("act_rl for bandit/gym policies.",),
        rationale=("Expose action predictions separately from evaluation.",),
        assumptions=("Feature columns match the plan contract.",),
        failures=("Missing plan; null features.",),
        leakage=("Inference only; no fit on holdout.",),
        anti_patterns=("Treating predicted actions as new expert demos without disclosure.",),
        state_changes=("Stores imitation_predict_result.",),
        result_reading=("Inspect actions length vs partition size.",),
        next_steps=("evaluate_imitation; save_imitation_bundle.",),
        concepts=("imitation-behavioral-cloning",),
    ),
    _operation(
        "evaluate_imitation",
        OperationKind.DIAGNOSTIC,
        "Compare predicted actions to held-out demonstration actions.",
        "Holdout imitation metrics (accuracy/F1 or rmse/mae/r2).",
        "Imitation evaluation.",
        (
            "Require ImitationPlan.",
            "Predict actions on partition.",
            "Score against demonstration action column.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition.",
                "validation",
            ),
        ),
        inputs=("Partition state features + demonstration actions.",),
        outputs=("ImitationEvalResult.",),
        prerequisites=(DATASET, SPLIT, IMITATION_PLAN),
        ordering=("After fit_imitation.",),
        alternatives=("evaluate_rl for bandit/gym policies.",),
        rationale=("Honest holdout imitation metrics.",),
        assumptions=("Demonstration actions present on the partition.",),
        failures=("Missing plan; null actions.",),
        leakage=("Holdout never updates the policy.",),
        anti_patterns=("Reporting train_score as generalization.",),
        state_changes=("Stores imitation_eval_result.",),
        result_reading=("Inspect metrics dict and disclosures.",),
        next_steps=("save_imitation_bundle.",),
        concepts=("imitation-behavioral-cloning", "leakage-boundary"),
    ),
    _operation(
        "save_imitation_bundle",
        OperationKind.PERSIST,
        "Persist ImitationPlan as buildml.imitation_bundle.v1.",
        "Write meta.json + imitation_plan.joblib.",
        "Imitation bundle save.",
        ("Require ImitationPlan.", "Write bundle directory."),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("ImitationPlan.",),
        outputs=("Path to bundle directory.",),
        prerequisites=(IMITATION_PLAN,),
        ordering=("After fit_imitation.",),
        alternatives=("save_rl_bundle for RL policies.",),
        rationale=("Policy persistence distinct from Session checkpoints.",),
        assumptions=("Writable path.",),
        failures=("Missing plan.",),
        leakage=("N/A: artifact write.",),
        anti_patterns=("Expecting checkpoints to embed the BC policy.",),
        state_changes=("None beyond history record.",),
        result_reading=("Confirm meta.json format string.",),
        next_steps=("load_imitation_bundle on a fresh Session.",),
        concepts=("imitation-bundle-boundary",),
    ),
    _operation(
        "load_imitation_bundle",
        OperationKind.PERSIST,
        "Load an imitation bundle into the Session.",
        "Restore ImitationPlan from buildml.imitation_bundle.v1.",
        "Imitation bundle load.",
        ("Read meta + joblib.", "Attach plan; clear prior imitation results."),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Imitation bundle directory.",),
        outputs=("Session with imitation_plan attached.",),
        prerequisites=(),
        ordering=("Anytime; typically after checkpoint_load.",),
        alternatives=("fit_imitation to create a new plan.",),
        rationale=("Reload BC policy without refitting.",),
        assumptions=("Valid bundle format.",),
        failures=("Incomplete/unsupported bundle.",),
        leakage=("N/A: artifact read.",),
        anti_patterns=("Loading an RL bundle via load_imitation_bundle.",),
        state_changes=("Sets imitation_plan; clears fit/eval/predict results.",),
        result_reading=("Inspect Session.imitation_plan.",),
        next_steps=("predict_imitation_action; evaluate_imitation.",),
        concepts=("imitation-bundle-boundary",),
    ),
    _operation(
        "fit_rl",
        OperationKind.MODEL,
        "Fit a contextual bandit (core) or a Gymnasium env policy.",
        "Bandit: train logged (context, action, reward). Gym: optional env loop.",
        "RL fit step.",
        (
            "Branch on backend/mode.",
            "contextual_bandit: require split; fit LinUCB / reward-model policy on train.",
            "gym_reinforce: require buildml[rl]; train linear softmax REINFORCE.",
            "tabular_q: require buildml[rl]; discretize states and run TD control "
            "(Q-learning / SARSA / Expected SARSA / Double Q-learning).",
            "gym_sb3: require buildml[rl-industry]; train SB3 PPO/DQN/A2C.",
            "Disclose offline vs env-loop honesty boundaries.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | native | industry | None",
                "Bandit (sklearn), env loops (native), SB3 (industry).",
            ),
            _p(
                "mode",
                "contextual_bandit | gym_reinforce | tabular_q | gym_sb3",
                "RL path.",
                "contextual_bandit",
            ),
            _p(
                "algorithm",
                "linucb | epsilon_greedy | softmax | q_learning | sarsa | "
                "expected_sarsa | double_q_learning | ppo | dqn | a2c",
                "Algorithm within the resolved mode.",
                "linucb",
            ),
            _p("columns", "list[str] | None", "Context feature columns."),
            _p("action_column", "str | None", "Logged arm column; defaults to target."),
            _p("reward_column", "str | None", "Numeric reward column (or 'reward')."),
            _p("alpha", "float", "LinUCB exploration scale.", 1.0),
            _p(
                "epsilon",
                "float",
                "Epsilon-greedy exploration rate (bandit; tabular_q start value).",
                0.1,
            ),
            _p("temperature", "float", "Softmax temperature.", 1.0),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p("prefer_reduce_components", "bool", "Prefer reduce components.", True),
            _p("env_id", "str", "Gymnasium env id.", "CartPole-v1"),
            _p("n_episodes", "int", "REINFORCE / tabular training episodes.", 200),
            _p("max_steps", "int", "Max steps per episode.", 500),
            _p("learning_rate", "float", "REINFORCE lr / tabular TD step size.", 0.01),
            _p("gamma", "float", "Discount factor.", 0.99),
            _p("total_timesteps", "int", "SB3 training timesteps.", 20_000),
            _p("n_bins", "int", "tabular_q bins per Box observation dimension.", 8),
            _p("epsilon_min", "float", "tabular_q exploration floor.", 0.01),
            _p("epsilon_decay", "float", "tabular_q per-episode epsilon decay.", 0.995),
        ),
        inputs=("Train logged table (bandit) or Gymnasium env (gym / tabular modes).",),
        outputs=("RlPlan + RlFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split for bandits; env modes may host policy without tabular fit.",),
        alternatives=("fit_imitation for demonstration cloning without rewards.",),
        rationale=("Ship practical Session bandits + optional small-env RL.",),
        assumptions=("Discrete arms + numeric rewards for bandits; gymnasium for env modes.",),
        failures=("Missing reward_column; MissingExtraError without buildml[rl].",),
        leakage=("Bandit updates train-only; holdout never updates the policy.",),
        anti_patterns=(
            "Calling offline IPS online A/B.",
            "Calling off-policy tabular_q 'offline RL'.",
            "Claiming MuJoCo/robotics scope.",
        ),
        state_changes=("Stores rl_plan; clears prior RL eval/act.",),
        result_reading=("Inspect mode, algorithm, train_metrics, disclosures.",),
        next_steps=("act_rl; evaluate_rl; save_rl_bundle.",),
        concepts=(
            "rl-contextual-bandit",
            "rl-offline-metrics",
            "rl-gym-reinforce",
            "rl-tabular-q-learning",
            "rl-sarsa-on-policy",
            "rl-state-discretization",
            "rl-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "act_rl",
        OperationKind.MODEL,
        "Choose actions under the fitted RL policy.",
        "Bandit: score a partition. Env modes: score observation vectors.",
        "RL action selection.",
        ("Require RlPlan.", "Select arms / env actions; optional scores."),
        parameters=(
            _p("partition", "train | validation | test | all", "Bandit contexts.", "test"),
            _p("observations", "array | sequence | None", "Gym observations."),
            _p("deterministic", "bool", "Greedy vs stochastic action.", True),
            _p("random_state", "int | None", "RNG seed.", 0),
        ),
        inputs=("Partition contexts or observation vectors.",),
        outputs=("RlActResult.",),
        prerequisites=(RL_PLAN,),
        ordering=("After fit_rl.",),
        alternatives=("predict_imitation_action for BC.",),
        rationale=("Expose policy actions for inspection / deployment-lite.",),
        assumptions=("Plan columns/obs_dim match inputs.",),
        failures=("Missing plan; gym without observations.",),
        leakage=("Inference only.",),
        anti_patterns=("Using holdout actions to refit without a new fit_rl call.",),
        state_changes=("Stores rl_act_result.",),
        result_reading=(
            "Inspect actions and optional per-arm scores "
            "(UCB / predicted reward / action probabilities / Q-values)."
        ,),
        next_steps=("evaluate_rl; save_rl_bundle.",),
        concepts=(
            "rl-contextual-bandit",
            "rl-gym-reinforce",
            "rl-tabular-q-learning",
        ),
    ),
    _operation(
        "evaluate_rl",
        OperationKind.DIAGNOSTIC,
        "Evaluate RL (offline bandit metrics or Gymnasium returns).",
        "Bandit: DM/IPS/match-rate with offline=True. Gym: mean episode return.",
        "RL evaluation.",
        (
            "Require RlPlan.",
            "Bandit: act on holdout + offline estimators.",
            "Gym: roll out episodes in the env.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Bandit eval partition.",
                "validation",
            ),
            _p("n_episodes", "int | None", "Gym eval episodes."),
            _p("max_steps", "int | None", "Gym max steps."),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p("deterministic", "bool", "Greedy actions when True.", True),
        ),
        inputs=("Holdout logged table or Gymnasium env.",),
        outputs=("RlEvalResult.",),
        prerequisites=(RL_PLAN,),
        ordering=("After fit_rl.",),
        alternatives=("evaluate_imitation for BC.",),
        rationale=("Disclose offline vs online eval semantics.",),
        assumptions=("Logged action/reward columns for bandits; gymnasium for gym.",),
        failures=("Missing plan; MissingExtraError for gym without extra.",),
        leakage=("Holdout never updates bandit parameters.",),
        anti_patterns=("Reporting IPS as online lift.",),
        state_changes=("Stores rl_eval_result.",),
        result_reading=(
            "Inspect offline flag + metrics disclosures "
            "(tabular_q also reports unseen_state_rate)."
        ,),
        next_steps=("save_rl_bundle.",),
        concepts=(
            "rl-offline-metrics",
            "rl-contextual-bandit",
            "rl-gym-reinforce",
            "rl-tabular-q-learning",
        ),
    ),
    _operation(
        "save_rl_bundle",
        OperationKind.PERSIST,
        "Persist RlPlan as buildml.rl_bundle.v1.",
        "Write meta.json + rl_plan.joblib.",
        "RL bundle save.",
        ("Require RlPlan.", "Write bundle directory."),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("RlPlan.",),
        outputs=("Path to bundle directory.",),
        prerequisites=(RL_PLAN,),
        ordering=("After fit_rl.",),
        alternatives=("save_imitation_bundle for BC.",),
        rationale=("Policy persistence distinct from Session checkpoints.",),
        assumptions=("Writable path.",),
        failures=("Missing plan.",),
        leakage=("N/A: artifact write.",),
        anti_patterns=("Expecting checkpoints to embed the RL policy.",),
        state_changes=("None beyond history record.",),
        result_reading=("Confirm meta.json format string.",),
        next_steps=("load_rl_bundle on a fresh Session.",),
        concepts=("rl-bundle-boundary",),
    ),
    _operation(
        "load_rl_bundle",
        OperationKind.PERSIST,
        "Load an RL bundle into the Session.",
        "Restore RlPlan from buildml.rl_bundle.v1.",
        "RL bundle load.",
        ("Read meta + joblib.", "Attach plan; clear prior RL results."),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("RL bundle directory.",),
        outputs=("Session with rl_plan attached.",),
        prerequisites=(),
        ordering=("Anytime; typically after checkpoint_load.",),
        alternatives=("fit_rl to create a new plan.",),
        rationale=("Reload RL policy without refitting.",),
        assumptions=("Valid bundle format.",),
        failures=("Incomplete/unsupported bundle.",),
        leakage=("N/A: artifact read.",),
        anti_patterns=("Loading an imitation bundle via load_rl_bundle.",),
        state_changes=("Sets rl_plan; clears fit/eval/act results.",),
        result_reading=("Inspect Session.rl_plan.",),
        next_steps=("act_rl; evaluate_rl.",),
        concepts=("rl-bundle-boundary",),
    ),
)
