# ruff: noqa: E501, F401
"""Self-supervised Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

SSL_PLAN = Prerequisite(
    "ssl-plan",
    "A train-fitted SelfSupervisedPlan is attached to the Session.",
    check_hint="session.ssl.plan is not None.",
)
SSL_HEAD = Prerequisite(
    "ssl-head",
    "An SSLHeadPlan has been fitted on labeled train representations.",
    check_hint="session.ssl.head_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_ssl_pretext",
        OperationKind.MODEL,
        "Fit a self-supervised tabular pretext encoder on the train partition only.",
        "Learn masked-reconstruction representations; freeze a SelfSupervisedPlan.",
        "Self-supervised pretext fit.",
        (
            "Require a SplitPlan.",
            "Fit masked tabular autoencoder lite on train features (labels ignored).",
            "Record latent width, reconstruction MAE diagnostic, and disclosures.",
        ),
        parameters=(
            _p("method", "masked_tabular", "Pretext algorithm (complete small surface).", "masked_tabular"),
            _p("columns", "list[str] | None", "Optional explicit numeric columns."),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p("latent_dim", "int", "Bottleneck / representation width.", 16),
            _p("hidden", "tuple[int, ...] | list[int]", "MLP hidden widths before latent.", (64,)),
            _p("mask_ratio", "float", "Fraction of features masked per view.", 0.15),
            _p("n_mask_views", "int", "Augmented masked views per train row.", 3),
            _p("max_iter", "int", "MLPRegressor max iterations.", 200),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer Session.reduce_dimensions component columns when available.",
                True,
            ),
            _p("representation_prefix", "str", "Prefix for exported embedding columns.", "ssl_emb"),
        ),
        inputs=("Split Session with numeric features (typically scaled).",),
        outputs=("SelfSupervisedFitResult; SelfSupervisedPlan stored on the Session.",),
        prerequisites=(DATASET, SPLIT),
        ordering=("After split and usually after impute/scale; optional reduce_dimensions.",),
        alternatives=(
            "session.semisupervised.fit when labels (even scarce) should drive learning.",
            "session.dl.load_backbone for vision/audio/speech transfer (torch/speech).",
        ),
        rationale=(
            "Use to learn train-only tabular representations before a supervised/semi-supervised head.",
        ),
        assumptions=("Features are numeric and non-null; enough train rows for an MLP pretext.",),
        failures=("Missing split, null/non-numeric features, invalid mask_ratio/latent_dim.",),
        leakage=(
            "Fitting pretext on all rows before splitting contaminates holdout representations.",
        ),
        anti_patterns=(
            "Claiming BERT/SimCLR-from-scratch coverage.",
            "Using holdout labels during pretext fitting.",
        ),
        state_changes=(
            "Stores session.ssl.plan and session.ssl.fit_result; clears transform/head/eval slots.",
        ),
        result_reading=(
            "Read latent_dim, reconstruction_mae, representation_columns, disclosures.",
        ),
        next_steps=("session.ssl.transform and/or session.ssl.finetune_head; optionally session.ssl.save_bundle.",),
        concepts=(
            "ssl-pretext-then-head",
            "ssl-masked-tabular",
            "ssl-vs-backbone-transfer",
            "leakage-boundary",
        ),
    ),
    _operation(
        "transform_ssl",
        OperationKind.TRANSFORM,
        "Export SSL representations with a train-fitted SelfSupervisedPlan (no refit).",
        "Project features through the frozen encoder; optionally attach embedding columns.",
        "Self-supervised transform step.",
        (
            "Require an attached SelfSupervisedPlan.",
            "Compute bottleneck activations for the partition.",
            "Optionally attach representation columns when partition='all'.",
        ),
        parameters=(
            _p("partition", "train | validation | test | all", "Rows to transform.", "train"),
            _p(
                "attach",
                "bool",
                "Write embedding columns onto the Session frame (requires partition='all').",
                False,
            ),
        ),
        inputs=("Active SelfSupervisedPlan and matching feature columns.",),
        outputs=("SelfSupervisedTransformResult; optional mutated dataset when attach=True.",),
        prerequisites=(DATASET, SSL_PLAN),
        ordering=("After session.ssl.fit_pretext or session.ssl.load_bundle.",),
        alternatives=("session.ssl.finetune_head when you want an in-plan supervised head without attach.",),
        rationale=("Use to materialize embeddings for classical fit or inspection.",),
        assumptions=("Plan feature columns still exist.",),
        failures=("No plan, missing columns, attach=True with partition≠all, name collisions.",),
        leakage=("Refitting the encoder on the transform partition breaks the contract.",),
        anti_patterns=("Treating reconstructions as the exported representation.",),
        state_changes=("Stores session.ssl.transform_result; may add feature-role embedding columns.",),
        result_reading=("Read n_rows, representation_columns, attached, disclosures.",),
        next_steps=("session.ssl.finetune_head, or Session.fit on attached embeddings + labels.",),
        concepts=("ssl-pretext-then-head", "leakage-boundary"),
    ),
    _operation(
        "finetune_ssl_head",
        OperationKind.MODEL,
        "Fit a supervised head on frozen SSL embeddings using labeled train rows only.",
        "Attach a classifier head without updating the pretext encoder.",
        "Self-supervised head fine-tune.",
        (
            "Require SelfSupervisedPlan and a target role.",
            "Skip unlabeled train targets (NaN by default).",
            "Fit logistic_regression or hist_gradient_boosting on embeddings.",
        ),
        parameters=(
            _p(
                "estimator",
                "logistic_regression | hist_gradient_boosting",
                "Supervised head family.",
                "logistic_regression",
            ),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p(
                "unlabeled_marker",
                "Any | None",
                "Extra unlabeled sentinel; default None uses NaN missingness.",
            ),
        ),
        inputs=("Active SelfSupervisedPlan and a partially or fully labeled train target.",),
        outputs=("SSLHeadFitResult; SSLHeadPlan stored on the Session.",),
        prerequisites=(DATASET, ROLES, SPLIT, SSL_PLAN),
        ordering=("After session.ssl.fit_pretext.",),
        alternatives=(
            "session.ssl.transform(attach=True) then Session.fit / session.semisupervised.fit on embeddings.",
            "session.dl.attach_head for vision/audio/speech zoo transfer.",
        ),
        rationale=("Use to transfer tabular SSL representations into a supervised predictor.",),
        assumptions=("At least two labeled train rows spanning ≥2 classes.",),
        failures=("No SSL plan, <2 labeled rows, single class.",),
        leakage=(
            "Using holdout labels to update the head during selection without disclosure.",
        ),
        anti_patterns=(
            "Updating the pretext encoder on labeled holdout during 'fine-tune'.",
        ),
        state_changes=("Stores session.ssl.head_plan and session.ssl.head_fit_result; clears eval slot.",),
        result_reading=("Read n_labeled_train, n_unlabeled_skipped, classes, disclosures.",),
        next_steps=("session.ssl.evaluate; optionally session.ssl.save_bundle.",),
        concepts=("ssl-pretext-then-head", "semisupervised-label-missingness", "leakage-boundary"),
    ),
    _operation(
        "evaluate_ssl",
        OperationKind.DIAGNOSTIC,
        "Evaluate frozen SSL pretext + head on labeled partition rows.",
        "Report accuracy/F1 on ground-truth labels; disclose unlabeled holdout rows.",
        "Self-supervised evaluation step.",
        (
            "Transform with frozen encoder; predict with frozen head.",
            "Score only labeled rows.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation falls back to test if absent).",
                "validation",
            ),
            _p("unlabeled_marker", "Any | None", "Optional unlabeled sentinel override."),
        ),
        inputs=("SelfSupervisedPlan, SSLHeadPlan, and a partition with some labels.",),
        outputs=("SelfSupervisedEvalResult.",),
        prerequisites=(DATASET, SSL_PLAN, SSL_HEAD),
        ordering=("After session.ssl.finetune_head.",),
        alternatives=("Classical evaluate after attaching embeddings and Session.fit.",),
        rationale=("Use to quantify transfer quality under a frozen pretext + head.",),
        assumptions=("Holdout has labeled rows for the metrics you care about.",),
        failures=("Missing plan/head; no labeled eval rows.",),
        leakage=("Inventing labels on unlabeled holdout for selection.",),
        anti_patterns=("Reporting train reconstruction MAE as predictive utility.",),
        state_changes=("Stores session.ssl.eval_result.",),
        result_reading=("Read n_labeled_eval, metrics, disclosures.",),
        next_steps=("session.ssl.save_bundle; or iterate latent_dim / head on train only.",),
        concepts=("ssl-pretext-then-head", "evaluation-partitions"),
    ),
    _operation(
        "save_ssl_bundle",
        OperationKind.PERSIST,
        "Persist the active SSL plan (+ optional head) as buildml.selfsupervised_bundle.v1.",
        "Write a domain bundle distinct from Session checkpoints and Torch trainer bundles.",
        "Self-supervised bundle save.",
        ("Require an attached SelfSupervisedPlan.", "Write meta.json + ssl_plan.joblib."),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active SelfSupervisedPlan (optional SSLHeadPlan).",),
        outputs=("Bundle directory path.",),
        prerequisites=(SSL_PLAN,),
        ordering=("After session.ssl.fit_pretext (and optionally session.ssl.finetune_head).",),
        alternatives=("Session.checkpoint_save for workflow resume without the encoder.",),
        rationale=("Use when the SSL encoder/head must travel separately from data.",),
        assumptions=("Destination is writable.",),
        failures=("No SSL plan attached.",),
        leakage=("Bundles do not embed holdout labels for silent rescoring claims.",),
        anti_patterns=("Assuming a Session checkpoint embeds the SelfSupervisedPlan.",),
        state_changes=("History records session.ssl.save_bundle.",),
        result_reading=("Confirm meta.json format buildml.selfsupervised_bundle.v1.",),
        next_steps=("session.ssl.load_bundle in another Session.",),
        concepts=("ssl-bundle-boundary",),
    ),
    _operation(
        "load_ssl_bundle",
        OperationKind.PERSIST,
        "Load a buildml.selfsupervised_bundle.v1 plan (+ optional head) into the Session.",
        "Restore a train-fitted SSL encoder without refitting the pretext.",
        "Self-supervised bundle load.",
        ("Validate bundle format.", "Attach plans; clear transient result slots."),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory with meta.json + ssl_plan.joblib.",),
        outputs=("Session with session.ssl.plan (and optional session.ssl.head_plan) attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest/roles/split aligned with the plan feature contract.",),
        alternatives=("session.ssl.fit_pretext to learn a new encoder.",),
        rationale=("Use to reuse a frozen tabular SSL encoder/head.",),
        assumptions=("Feature columns still match the plan contract.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Do not treat load as permission to resplit using prior holdout knowledge.",),
        anti_patterns=("Loading into a Session whose features drifted from the plan.",),
        state_changes=("Sets session.ssl.plan / optional head; clears fit/transform/eval slots.",),
        result_reading=("Inspect session.ssl.plan.to_dict().",),
        next_steps=("session.ssl.transform / session.ssl.finetune_head / session.ssl.evaluate.",),
        concepts=("ssl-bundle-boundary",),
    ),
)
