# ruff: noqa: E501, F401
"""Semi-supervised Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

SEMISUPERVISED_PLAN = Prerequisite(
    "semisupervised-plan",
    "A train-fitted SemiSupervisedPlan is attached to the Session.",
    check_hint="Session.semisupervised_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_semisupervised",
        OperationKind.MODEL,
        "Fit a semi-supervised classifier on scarce labeled + unlabeled train rows.",
        "Propagate or self-train labels on the train partition only; freeze a SemiSupervisedPlan.",
        "Semi-supervised fit step.",
        (
            "Require a SplitPlan and a target role.",
            "Treat target NaNs (default) as unlabeled; map to sklearn -1 internally.",
            "Fit label_propagation, label_spreading, or self_training on train only.",
            "Never invent labels from validation/test for selection.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | industry | torch | hf",
                "Semi-supervised backend; sklearn when extras missing.",
                None,
            ),
            _p(
                "method",
                "label_propagation | label_spreading | self_training | "
                "pseudo_label_xgb | pseudo_label_lgbm | fixmatch_tabular | "
                "mixmatch_tabular | text_pseudo_label",
                "Semi-supervised algorithm within the backend.",
                "label_propagation",
            ),
            _p("columns", "list[str] | None", "Optional explicit numeric columns."),
            _p("random_state", "int | None", "RNG seed where applicable.", 0),
            _p("kernel", "str", "Graph kernel for propagation/spreading.", "knn"),
            _p("n_neighbors", "int", "Graph neighborhood size.", 7),
            _p("max_iter", "int", "Graph solver max iterations.", 1000),
            _p("alpha", "float", "LabelSpreading clamping factor.", 0.2),
            _p(
                "base_estimator",
                "logistic_regression | hist_gradient_boosting",
                "Self-training base classifier.",
                "logistic_regression",
            ),
            _p(
                "threshold",
                "float",
                "Self-training / pseudo-label confidence threshold.",
                0.75,
            ),
            _p("criterion", "str", "Self-training selection criterion.", "threshold"),
            _p("k_best", "int", "Self-training k_best when criterion requires it.", 10),
            _p("max_self_train_iter", "int", "Self-training / pseudo-label outer iterations.", 10),
            _p("epochs", "int", "Torch consistency training epochs.", 40),
            _p("batch_size", "int", "Torch mini-batch size.", 64),
            _p("text_column", "str | None", "Text feature column for hf backend.", None),
            _p("text_model_name", "str", "Sentence-transformer model for hf backend.", "sentence-transformers/all-MiniLM-L6-v2"),
            _p(
                "unlabeled_marker",
                "Any | None",
                "Extra unlabeled sentinel; default None uses NaN missingness.",
            ),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer Session.reduce_dimensions component columns when available.",
                True,
            ),
        ),
        inputs=("Split Session with numeric features and a partially labeled target.",),
        outputs=("SemiSupervisedFitResult; SemiSupervisedPlan stored on the Session.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split and usually after impute/scale; optional reduce_dimensions.",),
        alternatives=(
            "Session.fit for fully labeled supervised learning.",
            "Session.fit_ssl_pretext + transform_ssl + fit_semisupervised for SSL embeddings.",
            "Session.finetune_ssl_head when only labeled train rows matter.",
            "Anomaly novelty mode is normal-only detection: not this API.",
        ),
        rationale=(
            "Use when labels are scarce on train but unlabeled feature rows are abundant.",
        ),
        assumptions=(
            "At least two labeled train rows spanning ≥2 classes.",
            "Features are numeric and non-null.",
        ),
        failures=(
            "Missing split/target, <2 labeled rows, single class, null features, unknown method.",
        ),
        leakage=(
            "Using validation/test unlabeled rows to invent labels for selection.",
            "Fitting before split contaminates holdout metrics.",
        ),
        anti_patterns=(
            "Treating pseudo-labels as ground truth on holdout.",
            "Stratifying a split on a mostly-NaN target without a labeled-first strategy.",
        ),
        state_changes=(
            "Stores semisupervised_plan and fit result; clears prior predict/eval slots.",
        ),
        result_reading=(
            "Read n_labeled_train, n_unlabeled_train, method, classes, disclosures.",
        ),
        next_steps=(
            "predict_semisupervised / evaluate_semisupervised; optionally save_semisupervised_bundle.",
        ),
        concepts=(
            "semisupervised-label-missingness",
            "semisupervised-train-only-fit",
            "semisupervised-vs-novelty",
            "semisupervised-ssl-pipeline",
            "leakage-boundary",
        ),
    ),
    _operation(
        "predict_semisupervised",
        OperationKind.TRANSFORM,
        "Predict with a train-fitted SemiSupervisedPlan (no refit).",
        "Apply the frozen estimator to a partition or the full frame.",
        "Semi-supervised predict step.",
        (
            "Require an attached SemiSupervisedPlan.",
            "Predict labels for the partition without updating the plan.",
            "Optionally attach a prediction column when partition='all'.",
        ),
        parameters=(
            _p("partition", "train | validation | test | all", "Rows to score.", "test"),
            _p(
                "attach",
                "bool",
                "Write prediction_column onto the Session frame (requires partition='all').",
                False,
            ),
            _p(
                "prediction_column",
                "str",
                "Column name used when attach=True.",
                "semisupervised_prediction",
            ),
        ),
        inputs=("Active SemiSupervisedPlan and matching feature columns.",),
        outputs=("SemiSupervisedPredictResult; optional mutated dataset when attach=True.",),
        prerequisites=(DATASET, SEMISUPERVISED_PLAN),
        ordering=("After fit_semisupervised or load_semisupervised_bundle.",),
        alternatives=("evaluate_semisupervised when you need labeled metrics.",),
        rationale=("Use to materialize predictions for inspection or export.",),
        assumptions=("Plan feature columns still exist.",),
        failures=("No plan, missing columns, attach=True with partition≠all.",),
        leakage=("Refitting on the predict partition would break the train-fit contract.",),
        anti_patterns=("Writing predictions into the target role silently.",),
        state_changes=("Stores semisupervised_predict_result; may add a feature-role column.",),
        result_reading=("Read n_rows, method, attached, disclosures.",),
        next_steps=("evaluate_semisupervised; or use attached columns cautiously.",),
        concepts=("semisupervised-train-only-fit", "leakage-boundary"),
    ),
    _operation(
        "evaluate_semisupervised",
        OperationKind.DIAGNOSTIC,
        "Evaluate semi-supervised predictions on labeled partition rows only.",
        "Score accuracy/F1 on ground-truth labels; disclose unlabeled holdout rows.",
        "Semi-supervised evaluation step.",
        (
            "Predict with the frozen plan.",
            "Exclude unlabeled rows from metrics.",
            "Report accuracy / macro and weighted F1 with label-mix disclosures.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation falls back to test if absent).",
                "validation",
            ),
            _p(
                "unlabeled_marker",
                "Any | None",
                "Optional unlabeled sentinel override for eval missingness.",
            ),
        ),
        inputs=("Active SemiSupervisedPlan and a partition with some labeled targets.",),
        outputs=("SemiSupervisedEvalResult.",),
        prerequisites=(DATASET, SEMISUPERVISED_PLAN),
        ordering=("After fit_semisupervised.",),
        alternatives=("predict_semisupervised for raw labels without metrics.",),
        rationale=("Use to quantify holdout quality without treating unlabeled rows as truth.",),
        assumptions=("Holdout has labeled rows for the metrics you care about.",),
        failures=("No plan; no labeled eval rows (empty metrics with warning).",),
        leakage=(
            "Using unlabeled holdout rows as invented truths for model selection.",
        ),
        anti_patterns=("Reporting train pseudo-label accuracy as holdout performance.",),
        state_changes=("Stores semisupervised_eval_result.",),
        result_reading=(
            "Read n_labeled_eval, n_unlabeled_eval, metrics, disclosures.",
        ),
        next_steps=("save_semisupervised_bundle; or iterate method/base_estimator on train only.",),
        concepts=(
            "semisupervised-label-missingness",
            "semisupervised-train-only-fit",
            "evaluation-partitions",
        ),
    ),
    _operation(
        "save_semisupervised_bundle",
        OperationKind.PERSIST,
        "Persist the active SemiSupervisedPlan as buildml.semisupervised_bundle.v1.",
        "Write a domain bundle distinct from Session checkpoints.",
        "Semi-supervised bundle save.",
        ("Require an attached plan.", "Write meta.json + semisupervised_plan.joblib."),
        parameters=(_p("path", "str | Path", "Destination directory.", required=True),),
        inputs=("Active SemiSupervisedPlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(SEMISUPERVISED_PLAN,),
        ordering=("After a successful fit_semisupervised.",),
        alternatives=("Session.checkpoint_save for workflow resume without the estimator.",),
        rationale=("Use when the semi-supervised estimator must travel separately from data.",),
        assumptions=("Destination is writable.",),
        failures=("No plan attached.",),
        leakage=("Bundles do not embed holdout labels for silent rescoring claims.",),
        anti_patterns=("Assuming a Session checkpoint embeds the SemiSupervisedPlan.",),
        state_changes=("History records save_semisupervised_bundle.",),
        result_reading=("Confirm meta.json format buildml.semisupervised_bundle.v1.",),
        next_steps=("load_semisupervised_bundle in another Session.",),
        concepts=("semisupervised-bundle-boundary",),
    ),
    _operation(
        "load_semisupervised_bundle",
        OperationKind.PERSIST,
        "Load a buildml.semisupervised_bundle.v1 SemiSupervisedPlan into the Session.",
        "Restore a train-fitted semi-supervised estimator without refitting.",
        "Semi-supervised bundle load.",
        ("Validate bundle format.", "Attach SemiSupervisedPlan; clear fit/predict/eval slots."),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory with meta.json + semisupervised_plan.joblib.",),
        outputs=("Session with semisupervised_plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest/roles/split aligned with the plan feature contract.",),
        alternatives=("fit_semisupervised to learn a new plan.",),
        rationale=("Use to reuse a frozen semi-supervised estimator.",),
        assumptions=("Feature columns still match the plan contract.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Do not treat load as permission to resplit using prior holdout knowledge.",),
        anti_patterns=("Loading into a Session whose features drifted from the plan.",),
        state_changes=("Sets semisupervised_plan; clears fit/predict/eval result slots.",),
        result_reading=("Inspect Session.semisupervised_plan.to_dict().",),
        next_steps=("predict_semisupervised / evaluate_semisupervised.",),
        concepts=("semisupervised-bundle-boundary",),
    ),
)
