# ruff: noqa: E501, F401
"""Symbolic / neuro-symbolic Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

SYMBOLIC_PLAN = Prerequisite(
    "symbolic-plan",
    "A train-fitted SymbolicPlan is attached to the Session.",
    check_hint="session.symbolic.plan is not None.",
)

NEURO_SYMBOLIC_PLAN = Prerequisite(
    "neuro-symbolic-plan",
    "A train-fitted NeuroSymbolicPlan is attached to the Session.",
    check_hint="session.symbolic.neuro_plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_symbolic",
        OperationKind.MODEL,
        "Compile or induce a symbolic if-then rule base on train.",
        "Declared rules, DecisionTree path export, or decision-list covering.",
        "Symbolic fit / compile step.",
        (
            "Require SplitPlan.",
            "declared: compile caller rules (not learned).",
            "decision_tree: fit shallow sklearn tree on train; export paths.",
            "decision_list: sequential covering on train (RIPPER-lite).",
            "Never induce on validation/test.",
            "Disclose provenance (declared vs induced_*).",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | industry",
                "Rule induction backend; industry when extras installed.",
            ),
            _p(
                "source",
                "declared | decision_tree | decision_list",
                "Rule origin when backend='sklearn'.",
                "decision_tree",
            ),
            _p(
                "method",
                "skope_rules | rulefit | boosted_rules",
                "Industry rule export when backend='industry'.",
            ),
            _p(
                "verify_constraints",
                "bool",
                "Optional Z3 lite SAT check on hard constraints.",
                False,
            ),
            _p(
                "task",
                "classification | regression | None",
                "Task; inferred from target when omitted.",
            ),
            _p(
                "rules",
                "sequence[mapping] | None",
                "Required for source='declared'; optional otherwise.",
            ),
            _p("columns", "list[str] | None", "Feature columns; default role features."),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p("max_depth", "int", "Tree / stump depth.", 4),
            _p("min_samples_leaf", "int", "Minimum leaf support.", 5),
            _p("max_rules", "int", "Cap on exported / covered rules.", 32),
            _p(
                "default_consequent",
                "Any | None",
                "Fallback when no rule fires.",
            ),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer reduce_dimensions components when present.",
                True,
            ),
        ),
        inputs=("Train partition (+ optional declared rules).",),
        outputs=("SymbolicPlan + SymbolicFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split / preprocess; before session.symbolic.evaluate.",),
        alternatives=("session.symbolic.fit_neuro for sklearn + rule hybrid.",),
        rationale=(
            "Ship readable tabular rules with traces: not Prolog/Z3/AGI.",
        ),
        assumptions=("Numeric features available after encode/scale when inducing.",),
        failures=("Empty declared rules; missing columns; too-small train.",),
        leakage=("Train-only induction; holdout never used to learn rules.",),
        anti_patterns=(
            "Calling this an AGI symbolic reasoner.",
            "Inducing rules on the full dataset before split.",
        ),
        state_changes=("Stores session.symbolic.plan; clears prior symbolic eval/predict.",),
        result_reading=("Inspect n_rules, provenance, train_accuracy, disclosures.",),
        next_steps=("session.symbolic.predict; session.symbolic.evaluate; session.symbolic.save_bundle.",),
        concepts=(
            "symbolic-rules",
            "symbolic-induction",
            "symbolic-traces",
            "symbolic-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "predict_symbolic",
        OperationKind.MODEL,
        "Predict with the symbolic rule base and explanation traces.",
        "Decision-list inference; no refit.",
        "Symbolic predict step.",
        (
            "Require SymbolicPlan.",
            "Fire rules in priority order; first match wins.",
            "Return RuleTrace per row when return_traces=True.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Rows to score.",
                "test",
            ),
            _p("return_traces", "bool", "Include rule-firing traces.", True),
        ),
        inputs=("SymbolicPlan + partition rows.",),
        outputs=("SymbolicPredictResult with predictions/traces.",),
        prerequisites=(DATASET, SPLIT, SYMBOLIC_PLAN),
        ordering=("After session.symbolic.fit.",),
        alternatives=("session.symbolic.evaluate for metrics + coverage.",),
        rationale=("Make rule firings inspectable.",),
        assumptions=("Rule columns exist on the scored frame.",),
        failures=("No SymbolicPlan; missing predicate columns.",),
        leakage=("Score-only; does not update the rule base.",),
        anti_patterns=("Ignoring traces when auditing decisions.",),
        state_changes=("Stores session.symbolic.predict_result.",),
        result_reading=("Inspect predictions and traces[*].chosen_rule_id.",),
        next_steps=("session.symbolic.evaluate; session.symbolic.save_bundle.",),
        concepts=("symbolic-rules", "symbolic-traces", "leakage-boundary"),
    ),
    _operation(
        "evaluate_symbolic",
        OperationKind.MODEL,
        "Holdout metrics and rule coverage for the symbolic plan.",
        "Accuracy / RMSE plus rule_coverage; no refit.",
        "Symbolic evaluate step.",
        (
            "Require SymbolicPlan.",
            "Score holdout; report metrics and mean rules fired.",
            "Never re-induce rules on the evaluation partition.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation→test fallback).",
                "validation",
            ),
        ),
        inputs=("SymbolicPlan + holdout labels.",),
        outputs=("SymbolicEvalResult.",),
        prerequisites=(DATASET, SPLIT, SYMBOLIC_PLAN),
        ordering=("After session.symbolic.fit.",),
        alternatives=("session.symbolic.predict for raw traces.",),
        rationale=("Quantify holdout fidelity of the rule list.",),
        assumptions=("Non-null holdout targets.",),
        failures=("No plan; null targets.",),
        leakage=("Holdout evaluation only.",),
        anti_patterns=("Reporting train accuracy as holdout performance.",),
        state_changes=("Stores session.symbolic.eval_result.",),
        result_reading=("Inspect metrics, rule_coverage, mean_rules_fired.",),
        next_steps=("session.symbolic.save_bundle.",),
        concepts=(
            "symbolic-rules",
            "symbolic-traces",
            "symbolic-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "fit_neuro_symbolic",
        OperationKind.MODEL,
        "Fit a sklearn + symbolic hybrid in one Session API.",
        "Overlay, rules-as-features, or constraint-repair modes.",
        "Neuro-symbolic fit step.",
        (
            "Require SplitPlan.",
            "Fit base estimator on train (and induced rules when requested).",
            "Modes: constraint_overlay, rules_as_features, constraint_repair.",
            "Disclose rule provenance (declared vs induced).",
            "Not a disconnected fit-then-rules pair without Session state.",
        ),
        parameters=(
            _p(
                "backend",
                "sklearn | torch",
                "Hybrid base backend; torch for concept-bottleneck / NAM lite.",
            ),
            _p(
                "mode",
                "constraint_overlay | rules_as_features | constraint_repair",
                "Hybrid integration mode.",
                "constraint_overlay",
            ),
            _p(
                "base_estimator",
                "logistic_regression | ridge | random_forest | decision_tree | "
                "concept_bottleneck_lite | neural_additive_lite",
                "sklearn or torch lite base family.",
                "logistic_regression",
            ),
            _p(
                "torch_method",
                "concept_bottleneck_lite | neural_additive_lite",
                "Torch base when backend='torch'.",
            ),
            _p(
                "task",
                "classification | regression | None",
                "Task; inferred when omitted.",
            ),
            _p(
                "rules",
                "sequence[mapping] | None",
                "Declared rules / constraints (required when rule_source='declared').",
            ),
            _p(
                "rule_source",
                "declared | decision_tree | decision_list",
                "How the symbolic component is obtained.",
                "decision_tree",
            ),
            _p("columns", "list[str] | None", "Feature columns."),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p(
                "soft_strength",
                "float",
                "Global soft-rule blend / prefer strength in [0,1].",
                0.5,
            ),
            _p("max_depth", "int", "Induction depth when rule_source induces.", 3),
            _p("min_samples_leaf", "int", "Induction leaf support.", 5),
            _p("max_rules", "int", "Induction rule cap.", 24),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer reduce_dimensions components when present.",
                True,
            ),
        ),
        inputs=("Train partition + rules / induction config.",),
        outputs=("NeuroSymbolicPlan + NeuroSymbolicFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split / preprocess; before session.symbolic.evaluate_neuro.",),
        alternatives=("session.symbolic.fit for pure rules; classical fit for pure sklearn.",),
        rationale=(
            "Real neural↔symbolic integration with shared Session state and traces.",
        ),
        assumptions=("Base estimator matches task; rule columns exist.",),
        failures=("Missing declared rules; incompatible base_estimator/task.",),
        leakage=("Train-only fit/induction; holdout for score only.",),
        anti_patterns=(
            "Manual fit() + separate rule script without Session API.",
            "Claiming LTN / deep logic-tensor research depth.",
        ),
        state_changes=(
            "Stores session.symbolic.neuro_plan; clears prior symbolic eval / neuro predict.",
        ),
        result_reading=("Inspect mode, n_rules, rule_provenance, train_score.",),
        next_steps=(
            "session.symbolic.predict_neuro; session.symbolic.evaluate_neuro; session.symbolic.save_bundle.",
        ),
        concepts=(
            "neuro-symbolic-hybrid",
            "symbolic-rules",
            "symbolic-induction",
            "symbolic-traces",
            "symbolic-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "predict_neuro_symbolic",
        OperationKind.MODEL,
        "Hybrid predict with neural outputs and rule traces.",
        "Apply overlay / features / repair; no refit.",
        "Neuro-symbolic predict step.",
        (
            "Require NeuroSymbolicPlan.",
            "Run base estimator; apply mode-specific symbolic component.",
            "Return traces including neural_prediction and repaired flags.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Rows to score.",
                "test",
            ),
            _p("return_traces", "bool", "Include hybrid traces.", True),
        ),
        inputs=("NeuroSymbolicPlan + partition rows.",),
        outputs=("SymbolicPredictResult (path=neuro_symbolic).",),
        prerequisites=(DATASET, SPLIT, NEURO_SYMBOLIC_PLAN),
        ordering=("After session.symbolic.fit_neuro.",),
        alternatives=("session.symbolic.evaluate_neuro for metrics + repair_rate.",),
        rationale=("Expose neural vs final decisions.",),
        assumptions=("Plan columns present on the scored frame.",),
        failures=("No NeuroSymbolicPlan.",),
        leakage=("Score-only.",),
        anti_patterns=("Ignoring n_repaired / neural_predictions.",),
        state_changes=("Stores session.symbolic.neuro_predict_result.",),
        result_reading=("Compare neural_predictions vs predictions; read traces.",),
        next_steps=("session.symbolic.evaluate_neuro; session.symbolic.save_bundle.",),
        concepts=("neuro-symbolic-hybrid", "symbolic-traces", "leakage-boundary"),
    ),
    _operation(
        "evaluate_neuro_symbolic",
        OperationKind.MODEL,
        "Holdout metrics for the neuro-symbolic hybrid.",
        "Accuracy/RMSE, rule coverage, repair_rate; no refit.",
        "Neuro-symbolic evaluate step.",
        (
            "Require NeuroSymbolicPlan.",
            "Score holdout with the hybrid path.",
            "Report neural_final_agreement when neural preds exist.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition (validation→test fallback).",
                "validation",
            ),
        ),
        inputs=("NeuroSymbolicPlan + holdout labels.",),
        outputs=("SymbolicEvalResult (path=neuro_symbolic).",),
        prerequisites=(DATASET, SPLIT, NEURO_SYMBOLIC_PLAN),
        ordering=("After session.symbolic.fit_neuro.",),
        alternatives=("session.symbolic.predict_neuro for traces.",),
        rationale=("Quantify hybrid holdout behavior and repair pressure.",),
        assumptions=("Non-null holdout targets.",),
        failures=("No plan; null targets.",),
        leakage=("Holdout evaluation only.",),
        anti_patterns=("Treating repair_rate as proof of correctness.",),
        state_changes=("Stores session.symbolic.eval_result.",),
        result_reading=("Inspect metrics, repair_rate, rule_coverage.",),
        next_steps=("session.symbolic.save_bundle.",),
        concepts=(
            "neuro-symbolic-hybrid",
            "symbolic-traces",
            "symbolic-bundle-boundary",
            "leakage-boundary",
        ),
    ),
    _operation(
        "save_symbolic_bundle",
        OperationKind.MODEL,
        "Persist SymbolicPlan or NeuroSymbolicPlan as buildml.symbolic_bundle.v1.",
        "Write meta.json + symbolic_plan.joblib.",
        "Symbolic bundle save.",
        (
            "Require an active symbolic or neuro-symbolic plan.",
            "Prefer NeuroSymbolicPlan when both are present.",
            "Do not embed the plan in Session checkpoints.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
        ),
        inputs=("Active plan (+ optional fit/eval summaries).",),
        outputs=("Bundle directory path.",),
        prerequisites=(DATASET,),
        ordering=("After session.symbolic.fit or session.symbolic.fit_neuro.",),
        alternatives=("checkpoint_save for workflow state only.",),
        rationale=("Separate learner artifact from Session checkpoint.",),
        assumptions=("Writable path.",),
        failures=("No plan attached.",),
        leakage=("None: persistence only.",),
        anti_patterns=("Expecting checkpoint_load to restore the plan.",),
        state_changes=("History record only.",),
        result_reading=("Confirm meta.json format and kind.",),
        next_steps=("session.symbolic.load_bundle on a new Session.",),
        concepts=("symbolic-bundle-boundary",),
    ),
    _operation(
        "load_symbolic_bundle",
        OperationKind.MODEL,
        "Load a symbolic / neuro-symbolic bundle into this Session.",
        "Restore SymbolicPlan or NeuroSymbolicPlan from disk.",
        "Symbolic bundle load.",
        (
            "Validate buildml.symbolic_bundle.v1.",
            "Attach plan; clear fit/eval/predict result slots.",
        ),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory.",),
        outputs=("Session with plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest; usually after split for scoring.",),
        alternatives=("session.symbolic.fit / session.symbolic.fit_neuro to create a new plan.",),
        rationale=("Reload the learner without re-induction.",),
        assumptions=("Bundle format matches.",),
        failures=("Incomplete or wrong-format bundle.",),
        leakage=("Load does not fit; scoring still uses holdout only.",),
        anti_patterns=("Loading into a Session with mismatched columns silently.",),
        state_changes=("Stores symbolic or neuro-symbolic plan.",),
        result_reading=("Inspect plan kind/source/mode.",),
        next_steps=("predict_* / evaluate_*.",),
        concepts=("symbolic-bundle-boundary", "leakage-boundary"),
    ),
)
