# ruff: noqa: E501, F401
"""TDA Session operation overlays."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    DATASET,
    ROLES,
    SPLIT,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec, Prerequisite

TDA_PLAN = Prerequisite(
    "tda-plan",
    "A train-fitted TdaPlan (PH vectorizer ± head) is attached.",
    check_hint="session.tda.plan is not None.",
)

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "fit_tda",
        OperationKind.MODEL,
        "Fit topological features (+ optional sklearn head) on train.",
        "Local Vietoris–Rips (native) or giotto-tda (industry) → vectorize on train only.",
        "TDA fit step.",
        (
            "Require SplitPlan and buildml[tda] (native) or buildml[tda-industry] (giotto).",
            "Resolve numeric feature columns; optional train standardization.",
            "Optional train subsample when above max_points_guard.",
            "Fit NN index on train; compute local VR diagrams per train row.",
            "Fit vectorizer ranges from train diagrams; optionally fit sklearn head.",
            "Disclose PH honesty boundary (not full Mapper suite).",
        ),
        parameters=(
            _p("backend", "native | giotto", "PH/vectorization backend.", "native"),
            _p(
                "vectorization",
                "persistence_image | landscape | silhouette | betti_curve | persistence_landscape",
                "Diagram → vector map.",
                "persistence_image",
            ),
            _p("homology_dims", "sequence[int]", "Homology dimensions to keep.", "(0, 1)"),
            _p("knn", "int", "Local train-neighborhood size.", 16),
            _p("maxdim", "int", "ripser maxdim.", 1),
            _p("thresh", "float | None", "Optional ripser thresh.", None),
            _p("n_bins", "int", "Grid / image resolution control.", 20),
            _p("n_layers", "int", "Landscape layers.", 3),
            _p("pixel_size", "float | None", "Override PI pixel size.", None),
            _p("standardize", "bool", "Train mean/scale before PH.", True),
            _p(
                "head",
                "logistic_regression | random_forest | ridge | hist_gradient_boosting | none",
                "Optional supervised head.",
                "logistic_regression",
            ),
            _p("task", "classification | regression | None", "Inferred when omitted."),
            _p("columns", "list[str] | None", "Numeric feature columns."),
            _p("random_state", "int | None", "RNG seed.", 0),
            _p(
                "prefer_reduce_components",
                "bool",
                "Prefer reduce_dimensions components when present.",
                True,
            ),
            _p("max_points_guard", "int", "Train row cap before subsample/error.", 4000),
            _p(
                "subsample_strategy",
                "error | random | stratified",
                "Behavior when train exceeds max_points_guard.",
                "error",
            ),
            _p(
                "mapper",
                "bool",
                "Optional KeplerMapper train summary (giotto backend only).",
                False,
            ),
        ),
        inputs=("Train partition numeric features + target (if head).",),
        outputs=("TdaPlan + TdaFitResult.",),
        prerequisites=(DATASET, ROLES, SPLIT),
        ordering=("After split / preprocess; before transform/evaluate TDA.",),
        alternatives=("Classical fit() on raw features; unsupervised clustering.",),
        rationale=("Ship leakage-safe PH features for Session tabular workflows.",),
        assumptions=("≥2 numeric features; buildml[tda] installed.",),
        failures=("No split; MissingExtraError; knn<2; oversized train.",),
        leakage=("Train-only NN/vectorizer/head; holdout never enters at fit.",),
        anti_patterns=(
            "Fitting TDA on the full frame before split.",
            "Calling this a Mapper research platform.",
        ),
        state_changes=("Stores session.tda.plan; clears prior TDA eval/transform/predict.",),
        result_reading=("Inspect feature_dim, train_score, vectorization, disclosures.",),
        next_steps=("session.tda.transform; session.tda.predict; session.tda.evaluate; session.tda.save_bundle.",),
        concepts=(
            "tda-persistent-homology",
            "tda-vectorization",
            "tda-supervised-head",
            "tda-extra-boundary",
            "tda-giotto-backend",
            "leakage-boundary",
        ),
    ),
    _operation(
        "transform_tda",
        OperationKind.TRANSFORM,
        "Transform a partition with the frozen TDA pipeline.",
        "Local VR + vectorize using train NN index and frozen ranges.",
        "TDA feature transform.",
        ("Require TdaPlan.", "Score partition → topological feature matrix."),
        parameters=(
            _p("partition", "train | validation | test | all", "Rows to transform.", "test"),
        ),
        inputs=("Partition numeric features.",),
        outputs=("TdaTransformResult (features matrix).",),
        prerequisites=(DATASET, TDA_PLAN),
        ordering=("After session.tda.fit.",),
        alternatives=("session.tda.predict when a head is attached.",),
        rationale=("Expose topological features for custom downstream models.",),
        assumptions=("Feature columns match the plan contract.",),
        failures=("Missing plan; null features; MissingExtraError.",),
        leakage=("Inference only; no refit on holdout.",),
        anti_patterns=("Re-estimating vectorizer ranges on the transformed partition.",),
        state_changes=("Stores session.tda.transform_result.",),
        result_reading=("Inspect features shape vs feature_dim.",),
        next_steps=("session.tda.predict; session.tda.evaluate; or feed features to Session.fit.",),
        concepts=("tda-persistent-homology", "tda-vectorization"),
    ),
    _operation(
        "predict_tda",
        OperationKind.MODEL,
        "Predict with the optional TDA supervised head.",
        "Frozen transformer + train-fitted head → predictions.",
        "TDA head inference.",
        ("Require TdaPlan with head.", "Transform then predict."),
        parameters=(
            _p("partition", "train | validation | test | all", "Rows to score.", "test"),
        ),
        inputs=("Partition features.",),
        outputs=("TdaPredictResult.",),
        prerequisites=(DATASET, TDA_PLAN),
        ordering=("After session.tda.fit with head!='none'.",),
        alternatives=("session.tda.transform for feature-only workflows.",),
        rationale=("Separate inference from evaluation metrics.",),
        assumptions=("head_estimator_ present.",),
        failures=("head='none'; missing plan.",),
        leakage=("Inference only.",),
        anti_patterns=("Treating predictions as labels for refitting TDA without disclosure.",),
        state_changes=("Stores session.tda.predict_result.",),
        result_reading=("Inspect predictions length vs partition size.",),
        next_steps=("session.tda.evaluate; session.tda.save_bundle.",),
        concepts=("tda-supervised-head",),
    ),
    _operation(
        "evaluate_tda",
        OperationKind.DIAGNOSTIC,
        "Score the TDA head on a holdout partition.",
        "Frozen train pipeline; classification or regression metrics.",
        "TDA evaluation.",
        (
            "Require TdaPlan with head.",
            "Predict on partition.",
            "Compare to target labels.",
        ),
        parameters=(
            _p(
                "partition",
                "train | validation | test | all",
                "Evaluation partition.",
                "validation",
            ),
        ),
        inputs=("Partition features + target.",),
        outputs=("TdaEvalResult metrics.",),
        prerequisites=(DATASET, TDA_PLAN),
        ordering=("After session.tda.fit.",),
        alternatives=("Classical evaluate() on raw features for a baseline.",),
        rationale=("Honest holdout scoring of topological + head pipeline.",),
        assumptions=("Non-null targets on the partition.",),
        failures=("head='none'; missing plan; null targets.",),
        leakage=("No fit updates from the evaluation partition.",),
        anti_patterns=("Reporting train_score as holdout performance.",),
        state_changes=("Stores session.tda.eval_result.",),
        result_reading=("accuracy/macro_f1 or rmse/mae/r2 plus disclosures.",),
        next_steps=("session.tda.save_bundle; compare to classical fit baseline.",),
        concepts=("tda-supervised-head", "tda-persistent-homology"),
    ),
    _operation(
        "save_tda_bundle",
        OperationKind.PERSIST,
        "Persist TdaPlan as buildml.tda_bundle.v2 (v1 loadable).",
        "Write meta.json + tda_plan.joblib.",
        "TDA bundle save.",
        ("Require TdaPlan.", "Serialize bundle directory."),
        parameters=(_p("path", "str | Path", "Destination directory."),),
        inputs=("Active TdaPlan.",),
        outputs=("Bundle directory path.",),
        prerequisites=(TDA_PLAN,),
        ordering=("After session.tda.fit.",),
        alternatives=("Session checkpoint for workflow state (does not embed TDA).",),
        rationale=("Distinct persistence boundary from checkpoints.",),
        assumptions=("Writable path.",),
        failures=("Missing plan.",),
        leakage=("N/A (serialization).",),
        anti_patterns=("Expecting checkpoint_save to include TdaPlan.",),
        state_changes=("None beyond history record.",),
        result_reading=("Confirm format buildml.tda_bundle.v2 in meta.json.",),
        next_steps=("session.tda.load_bundle in another Session.",),
        concepts=("tda-bundle-boundary",),
    ),
    _operation(
        "load_tda_bundle",
        OperationKind.PERSIST,
        "Load a TDA bundle into this Session.",
        "Restore TdaPlan from buildml.tda_bundle.v2 (v1 compatible).",
        "TDA bundle load.",
        ("Read meta.json + tda_plan.joblib.", "Attach plan; clear live eval/transform."),
        parameters=(
            _p("path", "str | Path", "Bundle directory.", required=True),
            _p(
                "trusted",
                "bool",
                "Must be True to deserialize pickle/joblib/torch payloads (default False).",
                False,
            ),
        ),
        inputs=("Bundle directory.",),
        outputs=("Session with session.tda.plan attached.",),
        prerequisites=(DATASET,),
        ordering=("After ingest; typically after checkpoint_load.",),
        alternatives=("Refit with session.tda.fit.",),
        rationale=("Reload PH pipeline without refitting.",),
        assumptions=("Bundle format matches buildml.tda_bundle.v2 or v1.",),
        failures=("Incomplete / wrong-format bundle.",),
        leakage=("Loaded plan remains train-fitted; do not treat as refit on current frame.",),
        anti_patterns=("Loading a TDA bundle into a Session with mismatched feature columns.",),
        state_changes=("Sets session.tda.plan; clears fit/eval/transform/predict results.",),
        result_reading=("Inspect session.tda.plan.to_dict().",),
        next_steps=("session.tda.transform; session.tda.evaluate.",),
        concepts=("tda-bundle-boundary",),
    ),
)
