# ruff: noqa: E501, F401
"""Workflow / teaching Session operation overlays (human teaching prose)."""

from __future__ import annotations

from buildml.explain.overlays._common import (
    AI,
    AI_PROVIDER,
    DASHBOARD,
    DATASET,
    FIT,
    FIT_TORCH,
    RAG,
    RAG_CORPUS,
    RAG_INDEX,
    ROLES,
    SPLIT,
    TORCH,
    VIZ,
    OperationKind,
    _operation,
    _p,
)
from buildml.explain.schemas import OperationSpec

_OPERATIONS: tuple[OperationSpec, ...] = (
    _operation(
        "register_transform",
        OperationKind.CONFIGURE,
        "Register a named custom fit/transform pair for later Session application.",
        "Extend preparation with domain callables while keeping an explicit train-fit contract.",
        "Process-local transform registry configuration.",
        (
            "Store fit and transform callables under a unique name.",
            "Record serialization and output-column contract metadata.",
        ),
        parameters=(
            _p("name", "str", "Registry key used by apply_custom_transform.", required=True),
            _p("fit", "callable", "fit(train_frame, params) -> artifact.", required=True),
            _p("transform", "callable", "transform(frame, artifact) -> DataFrame.", required=True),
            _p("description", "str", "Human-readable contract note.", ""),
            _p("drop_input_columns", "bool", "Drop inputs after transform by default.", False),
            _p("serializable", "bool", "Whether fitted artifacts should be joblib-picklable.", True),
            _p("overwrite", "bool", "Replace an existing registration.", False),
        ),
        inputs=("Caller-supplied fit/transform callables.",),
        outputs=("CustomTransformSpec stored in the process registry.",),
        ordering=("Register before apply_custom_transform and before scoring reloaded pipelines that need it.",),
        alternatives=("Express the step with built-in prep APIs when they already cover the need.",),
        rationale=("Use for domain logic that must still honor train-only fit scope.",),
        assumptions=("The fit callable will not read holdout rows or undeclared globals.",),
        failures=("Empty names, non-callables, or duplicate names without overwrite=True.",),
        leakage=("A fit callable that peeks at holdout data bypasses BuildML's partition guard.",),
        anti_patterns=("Closing over mutable globals that change between fit and score.",),
        state_changes=("Updates the process-local registry only; Session dataset is unchanged.",),
        result_reading=("Call list_transforms() to confirm the name, description, and flags.",),
        next_steps=("apply_custom_transform after split with the registered name.",),
        concepts=("custom-transforms", "leakage-boundary", "reproducibility"),
    ),
    _operation(
        "list_transforms",
        OperationKind.INSPECT,
        "List custom transforms registered in the current process.",
        "Confirm which escape-hatch transforms are available for apply or reload.",
        "Read-only registry inspection.",
        ("Return registered CustomTransformSpec objects in name order.",),
        inputs=("Process-local transform registry.",),
        outputs=("Tuple of CustomTransformSpec objects.",),
        ordering=("Use before apply_custom_transform or after re-registering for pipeline reload.",),
        alternatives=("Track registrations in application code outside BuildML.",),
        rationale=("Make the registry inspectable before score-time replay depends on it.",),
        assumptions=("Registrations in other processes are not visible.",),
        failures=("None for an empty registry; returns an empty tuple.",),
        leakage=("Listing transforms does not move data; misuse of the callables can still leak later.",),
        anti_patterns=("Assuming a checkpoint restores registry callables automatically.",),
        state_changes=("None.",),
        result_reading=("Check name, serializable, and description fields.",),
        next_steps=("Register missing transforms before apply_custom_transform or predict_from_pipeline.",),
        concepts=("custom-transforms", "reproducibility"),
    ),
    _operation(
        "eda",
        OperationKind.DIAGNOSTIC,
        "Profile quality, distributions, associations, target patterns, outliers, and drift.",
        "Surface data risks and modeling questions before and during model development.",
        "Broad exploratory diagnostic.",
        ("Run adaptive analyzers.", "Generate narrative and recommendations.", "Optionally render/export figures."),
        parameters=(
            _p("sample_rows", "int | None", "Analysis sample cap."),
            _p("max_columns", "int", "Detailed-analysis column cap.", 100),
            _p("max_plots", "int", "Maximum planned figures.", 36),
            _p("include_plots", "bool", "Render optional figures.", False),
            _p("show", "bool", "Print narrative summary.", False),
            _p(
                "export_html",
                "str | Path | None",
                "Optional HTML path (Teaching Studio offline by default).",
            ),
            _p("export_figures", "str | Path | None", "Optional matplotlib figure directory."),
            _p(
                "html_format",
                "studio | research",
                "studio=offline Teaching Studio; research=layered report shell.",
                "studio",
            ),
        ),
        inputs=("Dataset, roles, optional SplitPlan and viz/dashboard dependencies.",),
        outputs=("EDAReport with structured analyses, findings, recommendations, and optional artifacts.",),
        prerequisites=(DATASET, VIZ),
        ordering=("After role assignment; repeat after major schema changes without mining final test outcomes.",),
        alternatives=(
            "session.eda_app() for the live Teaching Studio.",
            "html_format='research' for the layered research HTML shell.",
        ),
        rationale=("Sample only when full analysis is too costly and record what the sample misses.",),
        assumptions=("Statistical flags are screening evidence, not domain conclusions.",),
        failures=("Unsupported dtypes, too few observations, optional plotting errors, or costly wide data.",),
        leakage=("Target/test-aware exploration can influence features and choices; isolate final test review.",),
        anti_patterns=("Applying every recommendation automatically or treating correlation as causation.",),
        state_changes=("Does not transform data; records report summary and exported paths.",),
        result_reading=("Prioritize severe, well-evidenced findings and read analyzer limitations.",),
        next_steps=("Validate important findings, adjust roles/schema, and define a leakage-safe experiment.",),
        concepts=("column-roles", "diagnostic-uncertainty", "data-splitting", "dataset-drift"),
    ),
    _operation(
        "eda_app",
        OperationKind.EXPORT,
        "Serve a local Teaching Studio app over the current EDA report.",
        "Inspect domain boards, teaching studios, Concept Academy, and export PDF/CSV evidence.",
        "Interactive local product surface for EDA teaching and review.",
        (
            "Reuse or compute an EDAReport.",
            "Start a local FastAPI server with Plotly boards and searchable concepts.",
            "Optionally open the system browser.",
        ),
        parameters=(
            _p("report", "EDAReport | None", "Optional existing EDA report."),
            _p("host", "str", "Local bind host.", "127.0.0.1"),
            _p("port", "int", "Local bind port.", 8765),
            _p("open_browser", "bool", "Open the default browser.", True),
            _p("title", "str", "App header title.", "BuildML EDA Studio"),
            _p("sample_rows", "int | None", "Fresh-EDA sample cap when needed."),
            _p("max_columns", "int", "Fresh-EDA column cap.", 100),
            _p("blocking", "bool", "Run the server on the calling thread.", False),
        ),
        inputs=("Dataset with an EDAReport, plus buildml[dashboard] dependencies.",),
        outputs=("EDAAppHandle with local URL and stop() control.",),
        prerequisites=(DATASET, DASHBOARD),
        ordering=("After eda() or when a fresh exploratory review is needed before modeling.",),
        alternatives=(
            "session.eda(export_html=..., html_format='studio') for an offline Teaching Studio snapshot.",
            "session.eda(export_html=..., html_format='research') for the layered research HTML shell.",
        ),
        rationale=(
            "Use the live Teaching Studio for interactive review; offline HTML is the same product "
            "surface without a server.",
        ),
        assumptions=("The app binds to a local loopback port and serves one Session report payload.",),
        failures=("Missing dashboard extra, port already in use, or no materialized dataset.",),
        leakage=("The app presents full-dataset EDA; it does not fit transforms or models.",),
        anti_patterns=("Treating the local app as a deployment dashboard or causal discovery tool.",),
        state_changes=("Records launch metadata; does not mutate the dataset.",),
        result_reading=("Start at the cockpit, open Teaching Studio for each domain, then Concept Academy links.",),
        next_steps=(
            "Export PDF (tables + chart stills), Offline HTML, or CSV for the current view, "
            "then apply cited Session operations on train only.",
        ),
        concepts=(
            "column-roles",
            "diagnostic-uncertainty",
            "mutual-information",
            "variance-inflation",
            "dataset-drift",
            "normality-screens",
        ),
    ),
    _operation(
        "head",
        OperationKind.INSPECT,
        "Return a copy of the first rows of the current dataset.",
        "Quickly verify parsing, column names, and obvious value issues.",
        "Lightweight data preview.",
        ("Delegate to the Dataset preview without exposing mutable state.",),
        parameters=(_p("n", "int", "Number of rows.", 5),),
        inputs=("Current Dataset.",),
        outputs=("Pandas DataFrame preview.",),
        prerequisites=(DATASET,),
        ordering=("Use immediately after ingest and after schema-changing transforms.",),
        alternatives=("Use EDA for systematic checks or partition for split-scoped inspection.",),
        rationale=("Preview for orientation, not distributional inference.",),
        assumptions=("Source order has meaning only if established by the data contract.",),
        failures=("Invalid row count.",),
        leakage=("First rows can include test data; do not use them for iterative test-driven choices.",),
        anti_patterns=("Inferring data quality or class balance from five rows.",),
        state_changes=("Returns a preview and records the access; dataset state is unchanged.",),
        result_reading=("Check names, parse quality, dtypes, and suspicious identifiers.",),
        next_steps=("Inspect metadata/EDA and assign roles.",),
        concepts=("column-roles", "diagnostic-uncertainty"),
    ),
    _operation(
        "metadata",
        OperationKind.INSPECT,
        "Return a JSON-oriented snapshot of Session and Dataset state.",
        "Support audit, debugging, and report headers without exposing internal objects.",
        "Read-only workflow introspection.",
        ("Assemble ingest, split, history, reattach, and dataset metadata into a dictionary.",),
        inputs=("Current Session state; dataset is optional.",),
        outputs=("Dictionary snapshot suitable for serialization after normal value handling.",),
        ordering=("Inspect at workflow boundaries and before persistence or handoff.",),
        alternatives=("Use focused properties for typed runtime objects.",),
        rationale=("Use metadata for state summaries, not as a control API.",),
        assumptions=("History records calls but does not prove semantic correctness or source provenance.",),
        failures=("Unexpected non-serializable values in third-party metadata.",),
        leakage=("Metadata may reveal paths, schema, target names, and history; classify it with the project.",),
        anti_patterns=("Mutating the returned dictionary and expecting Session state to change.",),
        state_changes=("None.",),
        result_reading=("Check dataset presence, split, reattach status, roles, mode, engine, and history.",),
        next_steps=("Resolve warnings or missing state before the next fit-capable operation.",),
        concepts=("reproducibility", "checkpoint-integrity"),
    ),
    _operation(
        "workflow",
        OperationKind.INSPECT,
        "Resolve every catalog operation against the Session's live state and versioned history.",
        "Show which workflow operations are done, available, blocked, or intentionally skipped.",
        "Read-only workflow navigation and prerequisite diagnosis.",
        (
            "Inspect dataset, role, split, fitted-model, optional dependency, and history state.",
            "Resolve prerequisites and alternative paths into precise statuses and reasons.",
        ),
        inputs=("Current Session state, operation catalog, and normalized operation history.",),
        outputs=("Stable tuple of WorkflowStep records covering every public Session operation.",),
        ordering=("Use at any decision boundary, especially after loading or transforming state.",),
        alternatives=("Call explain for richer before/after detail about one operation.",),
        rationale=("Use the resolver to identify valid next actions without mutating the workflow.",),
        assumptions=("Catalog prerequisites represent the supported Session contract.",),
        failures=("An unknown custom state cannot be inferred beyond the catalog and recorded history.",),
        leakage=("Resolution is read-only, but suggested availability does not validate domain split design.",),
        anti_patterns=("Treating available as automatically appropriate without reading risks and assumptions.",),
        state_changes=("None; resolution reads state and history only.",),
        result_reading=("Read status, exact reasons, blockers, and prerequisite chains together.",),
        next_steps=("Inspect a candidate with explain(..., moment='before') before executing it.",),
        concepts=("leakage-boundary", "reproducibility"),
    ),
    _operation(
        "explain",
        OperationKind.INSPECT,
        "Explain one operation before or after execution, or return the full resolved workflow.",
        "Connect catalog guidance to the actual Session state, choices, transition, and observed result.",
        "Read-only interpretation layer over Session operations.",
        (
            "Resolve current prerequisites and workflow status for a before explanation.",
            "Join the latest v2 history record to catalog guidance for an after explanation.",
        ),
        parameters=(
            _p("operation", "str | None", "Catalog operation ID, or None for the workflow."),
            _p("moment", "before | after", "Explanation perspective.", "before"),
            _p(
                "level",
                "beginner | intermediate | advanced",
                "How much teaching depth to render around the expert sections.",
                "beginner",
                choices=("beginner", "intermediate", "advanced"),
            ),
        ),
        inputs=("Operation catalog, concept notes, Session state, and normalized history.",),
        outputs=("BeforeOperationExplanation, AfterOperationExplanation, or WorkflowStep tuple.",),
        ordering=("Use before a choice and after a result that needs interpretation.",),
        alternatives=("Use workflow for status-only navigation or get_operation for static guidance.",),
        rationale=("Prefer contextual explanation when prerequisites, choices, or limitations matter.",),
        assumptions=("Recorded parameters summarize the public call without retaining opaque objects.",),
        failures=("Unknown operation ID, invalid moment value, or unknown reading level.",),
        leakage=("Explanation identifies leakage risks but cannot prove data provenance or independence.",),
        anti_patterns=("Reading after guidance as evidence when the operation has not actually run.",),
        state_changes=("None; explanation never appends history or changes Session state.",),
        result_reading=("Distinguish observed record fields from catalog interpretation and limitations.",),
        next_steps=("Choose only among valid operations whose assumptions fit the data-generating process.",),
        concepts=("reproducibility", "diagnostic-uncertainty", "explain-learning-levels"),
        plain=(
            "Ask BuildML what a step does before you run it, and what actually happened after. "
            "The 'before' answer is grounded in your session: it knows whether you have loaded data, "
            "assigned roles, or split yet, so it tells you what is still missing rather than reciting "
            "a manual page."
        ),
        analogy=(
            "A recipe step read aloud by someone standing in your kitchen. They can see you have not "
            "preheated the oven yet, so that is the part they mention."
        ),
        beginner_steps=(
            "Name the operation you are curious about, or pass nothing to see the whole workflow.",
            "Read the plain-language primer first: what it is, why it exists, and the steps in order.",
            "Check the prerequisites section for anything not yet satisfied in this session.",
            "Run the operation, then call explain again with moment='after' to interpret the result.",
        ),
        when_to_use=(
            "You are about to call something and want to know what it will change.",
            "A result came back and you are not sure how to read it.",
            "An operation is blocked and you want the exact reason.",
        ),
        when_not_to_use=(
            "You want the concept behind the operation rather than its effect here: use learn instead.",
            "You want to see the effect on real rows without committing: use dry_run.",
        ),
        mini_example=(
            "before = session.explain('split')",
            "print(before.beginner.plain_summary)",
            "for step in before.beginner.steps: print('-', step)",
            "session.split()",
            "print(session.explain('split', moment='after').what_happened)",
        ),
    ),
    _operation(
        "learn",
        OperationKind.INSPECT,
        "Resolve a concept key, operation name, or glossary term into layered teaching material.",
        "Answer 'what is this and what should I understand first' independently of session state.",
        "Read-only teaching entry point over concept notes, the operation catalog, and the glossary.",
        (
            "Match the topic against concept keys, catalog operation names, and glossary aliases in that order.",
            "Render the resolved subject at the requested reading level.",
            "Attach prerequisite concepts as read_first and follow-on concepts as read_next.",
        ),
        parameters=(
            _p("topic", "str | None", "Concept key, operation name, or glossary term; None returns the foundation reading list."),
            _p(
                "level",
                "beginner | intermediate | advanced",
                "How much depth to render.",
                "beginner",
                choices=("beginner", "intermediate", "advanced"),
            ),
        ),
        inputs=("Concept notes, operation catalog, and the BuildML glossary.",),
        outputs=("LearningBrief with the subject, a reading order, and related operations.",),
        ordering=("Use before explain when the vocabulary itself is unfamiliar; use at any time.",),
        alternatives=("Use explain for state-aware guidance about a specific call, or workflow for status.",),
        rationale=("Prefer learn when the question is conceptual rather than about this session's state.",),
        assumptions=("Concept notes and the glossary are the single source of teaching truth.",),
        failures=("No concept, operation, or term matches the topic; close matches are suggested.",),
        leakage=("Teaching material describes leakage risks generally; it inspects no data.",),
        anti_patterns=("Treating a concept note as a substitute for checking assumptions against your own data.",),
        state_changes=("None; learn reads static teaching content and never touches the session.",),
        result_reading=("Read read_first before the subject itself when a topic depends on earlier ideas.",),
        next_steps=("Follow read_next, or explain one of the related operations in your session.",),
        concepts=("explain-learning-levels", "reproducibility"),
        plain=(
            "A dictionary that knows what order things should be learned in. Give it a word you did not "
            "understand: 'leakage', 'stratified', 'ROC AUC': or the name of an operation, and it "
            "explains the idea from scratch, then tells you which two or three ideas come before it and "
            "which come after."
        ),
        analogy=(
            "A textbook index that also says 'you will want to read chapter 3 first'. An index alone "
            "tells you where a topic is; this tells you whether you are ready for it."
        ),
        beginner_steps=(
            "Call learn() with no topic to see where to start.",
            "Read the plain-language summary and the analogy for the topic itself.",
            "If read_first is not empty, read those concepts before going further.",
            "Follow read_next when the idea has settled, or explain a related operation to see it applied.",
        ),
        when_to_use=(
            "A word in an explanation or an error message meant nothing to you.",
            "You are new to machine learning and want a reading order rather than an index.",
            "You want the idea behind an operation, separate from your current session.",
        ),
        when_not_to_use=(
            "You want to know why an operation is blocked right now: that is explain or workflow.",
            "You need to see the effect on your actual rows: that is dry_run.",
        ),
        mini_example=(
            "brief = session.learn('leakage-boundary')",
            "print(brief.concept.plain_summary)",
            "print([note.key for note in brief.read_first])",
            "session.learn('stratified')  # a glossary term resolves to its concept",
        ),
    ),
    _operation(
        "dry_run",
        OperationKind.INSPECT,
        "Preview intended operations, prerequisites, and leakage notes without mutation.",
        "Inspect what would run next before fitting or transforming state.",
        "Read-only plan preview over the operation catalog and workflow resolver.",
        (
            "Resolve one operation, a sequence, or a focused default next-step set.",
            "Report availability, blockers, estimated effects, and catalog leakage risks.",
            "Rank unresolved risks, summarize the prerequisite graph, and suggest next ops.",
        ),
        parameters=(
            _p("operation", "str | sequence[str] | None", "Operation name(s) or None for a default preview."),
            _p("parameters", "mapping | None", "Optional parameters attached to a single-operation preview."),
        ),
        inputs=("Current Session state, operation catalog, and normalized history.",),
        outputs=(
            "DryRunReport with ranked_risks, prerequisite_graph, and suggested_next_ops; "
            "Session data and history are unchanged.",
        ),
        ordering=("Use before irreversible prep, fit, or export decisions.",),
        alternatives=("Use explain(moment='before') for one operation or walkthrough for a full audit.",),
        rationale=("Preview blockers and leakage notes before spending compute or mutating partitions.",),
        assumptions=("Catalog definitions match the installed Session surface.",),
        failures=("Unknown operation names appear as blocked unknown steps.",),
        leakage=("Dry-run surfaces catalog leakage risks but does not prove row independence.",),
        anti_patterns=("Treating available as recommended, or expecting simulated metric outputs.",),
        state_changes=("Stores last_dry_run in memory only; no history append and no dataset mutation.",),
        result_reading=(
            "Read blocked_reasons, ranked_risks, prerequisite_graph.missing_required, "
            "and suggested_next_ops together.",
        ),
        next_steps=("Resolve blockers, then execute the operation or summarize_history after a run.",),
        concepts=("dry-run-plans", "leakage-boundary", "operation-history"),
    ),
    _operation(
        "summarize_history",
        OperationKind.INSPECT,
        "Summarize versioned operation history and list unresolved risks.",
        "Give a compact audit view of what ran and which review cues remain open.",
        "Read-only history aggregation for teaching and debugging.",
        (
            "Count operations and decision origins.",
            "Collect recent operation ids and warning totals.",
            "Rank unresolved risks, summarize prerequisites for suggested next ops, and list follow-ups.",
        ),
        inputs=("Normalized Session history and current plan/fit state.",),
        outputs=(
            "HistorySummary with ranked_risks, prerequisite_graph, and suggested_next_ops.",
        ),
        ordering=("Use after prep/fit sequences, before handoff, or beside walkthrough.",),
        alternatives=("Use walkthrough for narrative status or explain for one operation.",),
        rationale=("Compact counts and risks are faster to scan than raw history JSON.",),
        assumptions=("State-changing work went through Session methods that append history.",),
        failures=("Empty history returns zero counts; risks may still exist from current state.",),
        leakage=("History cannot prove source provenance; unresolved risks are review cues only.",),
        anti_patterns=("Clearing history to hide experimental paths before review.",),
        state_changes=("Stores last_history_summary in memory; does not append a history record.",),
        result_reading=(
            "Inspect operation_counts, ranked_risks, suggested_next_ops, and prerequisite_graph before export.",
        ),
        next_steps=("dry_run or explain a candidate fix, then execute the needed Session method.",),
        concepts=("operation-history", "reproducibility", "diagnostic-uncertainty"),
    ),
    _operation(
        "walkthrough",
        OperationKind.INSPECT,
        "Build a workflow report from resolver state and versioned history.",
        "Teach what happened, what can happen next, what is blocked, and which risks remain.",
        "Read-only workflow reporting and audit layer.",
        (
            "Resolve every catalog operation against current state.",
            "Join statuses to sequenced history, state transitions, and decision origins.",
            "Render an optional offline report with shared reporting components.",
        ),
        parameters=(
            _p("export_html", "str | Path | None", "Optional self-contained walkthrough report path."),
        ),
        inputs=("Current Session state, normalized history, operation catalog, and concept notes.",),
        outputs=("WorkflowWalkthroughReport and optional self-contained HTML artifact.",),
        ordering=("Use at decision, handoff, checkpoint, and review boundaries.",),
        alternatives=("Use workflow for status-only output, dry_run for previews, or explain for one operation.",),
        rationale=("Use when one view must show sequence, choice origins, unresolved risks, and next actions.",),
        assumptions=(
            "Session history records state-changing calls plus deliberate data access, materialization, and export calls.",
            "Resolver/reporting introspection (metadata, workflow, explain, dry_run, summarize_history, and walkthrough) is intentionally not recorded to avoid recursive audit noise.",
        ),
        failures=("An unwritable export path or external work absent from Session history.",),
        leakage=("The report identifies catalog leakage risks but cannot prove row independence or source provenance.",),
        anti_patterns=("Treating an available operation as automatically appropriate without reading its assumptions.",),
        state_changes=("Stores last_walkthrough in memory; workflow data and fitted artifacts are unchanged.",),
        result_reading=("Read timeline evidence, status reasons, unresolved risks, and linked API actions together.",),
        next_steps=("Resolve material risks and explain a candidate operation before executing it.",),
        concepts=("reproducibility", "leakage-boundary", "diagnostic-uncertainty", "operation-history"),
    ),
)
