"""Kubernetes Job / torchrun helpers for multi-node DDP (spec emitters).

Emits YAML Job templates and documents torchrun/elastic launch. This is **not**
live multi-cluster orchestration, a Helm product, or a managed training cloud.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from buildml.core.errors import ValidationError


@dataclass(slots=True)
class K8sJobRenderResult:
    """Rendered Kubernetes Job YAML for a torchrun DDP launch."""

    yaml_text: str
    path: Path | None
    nnodes: int
    nproc_per_node: int
    disclosures: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    meta: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": None if self.path is None else str(self.path),
            "nnodes": self.nnodes,
            "nproc_per_node": self.nproc_per_node,
            "disclosures": list(self.disclosures),
            "limitations": list(self.limitations),
            "meta": dict(self.meta),
            "yaml_chars": len(self.yaml_text),
        }


def render_torchrun_ddp_job(
    *,
    job_name: str = "buildml-torchrun-ddp",
    namespace: str = "default",
    image: str = "pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime",
    nnodes: int = 2,
    nproc_per_node: int = 2,
    script_path: str = "/workspace/train.py",
    master_port: int = 29500,
    cpu_request: str = "2",
    memory_request: str = "4Gi",
    gpu_limit: int = 1,
    service_account: str | None = None,
) -> str:
    """Render a multi-pod Kubernetes Job YAML that runs ``torchrun``.

    Uses a simple indexed Job pattern. Operators must wire shared storage,
    network, and RDZV endpoints for their cluster — BuildML only emits the
    starter manifest.
    """
    if nnodes < 1:
        raise ValidationError("nnodes must be >= 1")
    if nproc_per_node < 1:
        raise ValidationError("nproc_per_node must be >= 1")
    if not job_name or not job_name.replace("-", "").isalnum():
        raise ValidationError("job_name must be a simple DNS-1123 label")
    # Placeholder kept indent-aligned with sibling pod-spec keys so textwrap.dedent
    # cannot be poisoned by a shorter injected serviceAccountName line.
    sa_placeholder = "__BUILDML_SERVICE_ACCOUNT_LINE__"
    # Indexed job: each pod gets JOB_COMPLETION_INDEX as node rank.
    yaml_text = textwrap.dedent(
        f"""\
        # Generated by buildml.dl.k8s.render_torchrun_ddp_job
        # Honesty: example Job template for torchrun multi-node DDP.
        # Not live multi-cluster orchestration. Not a Helm chart product.
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {job_name}
          namespace: {namespace}
          labels:
            app.kubernetes.io/name: buildml-torchrun-ddp
            app.kubernetes.io/part-of: buildml
        spec:
          completionMode: Indexed
          completions: {nnodes}
          parallelism: {nnodes}
          backoffLimit: 1
          template:
            metadata:
              labels:
                app.kubernetes.io/name: buildml-torchrun-ddp
            spec:
              {sa_placeholder}
              restartPolicy: Never
              containers:
                - name: trainer
                  image: {image}
                  resources:
                    requests:
                      cpu: "{cpu_request}"
                      memory: "{memory_request}"
                    limits:
                      nvidia.com/gpu: {gpu_limit}
                  env:
                    - name: MASTER_ADDR
                      value: {job_name}-0.{job_name}
                    - name: MASTER_PORT
                      value: "{master_port}"
                    - name: PET_NNODES
                      value: "{nnodes}"
                    - name: PET_NPROC_PER_NODE
                      value: "{nproc_per_node}"
                  command:
                    - bash
                    - -lc
                    - |
                      set -euo pipefail
                      NODE_RANK="${{JOB_COMPLETION_INDEX:-0}}"
                      torchrun \\
                        --nnodes={nnodes} \\
                        --nproc_per_node={nproc_per_node} \\
                        --node_rank="$NODE_RANK" \\
                        --master_addr="$MASTER_ADDR" \\
                        --master_port="$MASTER_PORT" \\
                        {script_path}
        ---
        # Optional headless Service so pods can resolve MASTER_ADDR.
        # Adjust selectors / DNS for your cluster networking model.
        apiVersion: v1
        kind: Service
        metadata:
          name: {job_name}
          namespace: {namespace}
        spec:
          clusterIP: None
          selector:
            app.kubernetes.io/name: buildml-torchrun-ddp
            job-name: {job_name}
          ports:
            - name: rdzv
              port: {master_port}
              targetPort: {master_port}
        """
    )
    if service_account:
        yaml_text = yaml_text.replace(sa_placeholder, f"serviceAccountName: {service_account}")
    else:
        # Drop the whole placeholder line (indent + marker + newline).
        yaml_text = "\n".join(
            line for line in yaml_text.splitlines() if sa_placeholder not in line
        ) + ("\n" if yaml_text.endswith("\n") else "")
    return yaml_text


def write_torchrun_ddp_job(
    path: str | Path,
    **kwargs: Any,
) -> K8sJobRenderResult:
    """Render and write a torchrun DDP Job YAML to ``path``."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    yaml_text = render_torchrun_ddp_job(**kwargs)
    destination.write_text(yaml_text, encoding="utf-8")
    nnodes = int(kwargs.get("nnodes", 2))
    nproc = int(kwargs.get("nproc_per_node", 2))
    return K8sJobRenderResult(
        yaml_text=yaml_text,
        path=destination,
        nnodes=nnodes,
        nproc_per_node=nproc,
        disclosures=(
            f"Wrote Kubernetes Job+Service YAML to {destination}.",
            "Uses Indexed Job + torchrun for multi-node DDP rendezvous.",
        ),
        limitations=(
            "Example template only — not live multi-cluster orchestration.",
            "Operator must provide GPU nodes, networking, shared data, and RBAC.",
            "Not a Helm chart product or managed training cloud.",
        ),
        meta={
            "job_name": kwargs.get("job_name", "buildml-torchrun-ddp"),
            "namespace": kwargs.get("namespace", "default"),
            "image": kwargs.get("image", "pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime"),
        },
    )
