"""Kubernetes Job / Service / ConfigMap helpers for torchrun DDP and local serve.

Emits YAML templates. This is **not** live multi-cluster orchestration, a Helm
product, or a managed training cloud. Shipped emitters are real YAML writers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from buildml.core.errors import ValidationError


@dataclass(slots=True)
class K8sJobRenderResult:
    """Rendered Kubernetes YAML result."""

    yaml_text: str
    path: Path | None
    nnodes: int
    nproc_per_node: int
    disclosures: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    meta: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": None if self.path is None else str(self.path),
            "nnodes": self.nnodes,
            "nproc_per_node": self.nproc_per_node,
            "disclosures": list(self.disclosures),
            "limitations": list(self.limitations),
            "meta": dict(self.meta),
            "yaml_chars": len(self.yaml_text),
        }


def _validate_dns_label(name: str, *, field_name: str = "name") -> None:
    if not name or not str(name).replace("-", "").isalnum():
        raise ValidationError(f"{field_name} must be a simple DNS-1123 label")


def render_torchrun_ddp_job(
    *,
    job_name: str = "buildml-torchrun-ddp",
    namespace: str = "default",
    image: str = "pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime",
    nnodes: int = 2,
    nproc_per_node: int = 2,
    script_path: str = "/workspace/train.py",
    master_port: int = 29500,
    cpu_request: str = "2",
    memory_request: str = "4Gi",
    gpu_limit: int = 1,
    gpu_request: int | None = None,
    service_account: str | None = None,
    include_configmap: bool = True,
) -> str:
    """Render Indexed Job + Service (+ optional ConfigMap) for torchrun DDP."""
    if nnodes < 1:
        raise ValidationError("nnodes must be >= 1")
    if nproc_per_node < 1:
        raise ValidationError("nproc_per_node must be >= 1")
    _validate_dns_label(job_name, field_name="job_name")
    if gpu_limit < 0:
        raise ValidationError("gpu_limit must be >= 0")
    resolved_gpu_request = gpu_limit if gpu_request is None else int(gpu_request)
    cm_name = f"{job_name}-config"
    sa_line = f"      serviceAccountName: {service_account}\n" if service_account else ""
    gpu_req = (
        f'\n              nvidia.com/gpu: "{resolved_gpu_request}"'
        if resolved_gpu_request > 0
        else ""
    )
    gpu_lim = f"\n              nvidia.com/gpu: {gpu_limit}" if gpu_limit > 0 else ""
    env_from = (
        (
            "          envFrom:\n"
            "            - configMapRef:\n"
            f"                name: {cm_name}\n"
        )
        if include_configmap
        else ""
    )
    body = (
        "# Generated by buildml.dl.k8s.render_torchrun_ddp_job\n"
        "# Honesty: template only — not live multi-cluster orchestration.\n"
        "apiVersion: batch/v1\n"
        "kind: Job\n"
        "metadata:\n"
        f"  name: {job_name}\n"
        f"  namespace: {namespace}\n"
        "  labels:\n"
        "    app.kubernetes.io/name: buildml-torchrun-ddp\n"
        "    app.kubernetes.io/part-of: buildml\n"
        "spec:\n"
        "  completionMode: Indexed\n"
        f"  completions: {nnodes}\n"
        f"  parallelism: {nnodes}\n"
        "  backoffLimit: 1\n"
        "  template:\n"
        "    metadata:\n"
        "      labels:\n"
        "        app.kubernetes.io/name: buildml-torchrun-ddp\n"
        "    spec:\n"
        f"{sa_line}"
        "      restartPolicy: Never\n"
        "      containers:\n"
        "        - name: trainer\n"
        f"          image: {image}\n"
        "          resources:\n"
        "            requests:\n"
        f'              cpu: "{cpu_request}"\n'
        f'              memory: "{memory_request}"{gpu_req}\n'
        "            limits:\n"
        f'              memory: "{memory_request}"{gpu_lim}\n'
        f"{env_from}"
        "          env:\n"
        "            - name: MASTER_ADDR\n"
        f"              value: {job_name}-0.{job_name}\n"
        "            - name: MASTER_PORT\n"
        f'              value: "{master_port}"\n'
        "            - name: PET_NNODES\n"
        f'              value: "{nnodes}"\n'
        "            - name: PET_NPROC_PER_NODE\n"
        f'              value: "{nproc_per_node}"\n'
        "          command:\n"
        "            - bash\n"
        "            - -lc\n"
        "            - |\n"
        "              set -euo pipefail\n"
        '              NODE_RANK="${JOB_COMPLETION_INDEX:-0}"\n'
        "              torchrun \\\n"
        f"                --nnodes={nnodes} \\\n"
        f"                --nproc_per_node={nproc_per_node} \\\n"
        '                --node_rank="$NODE_RANK" \\\n'
        '                --master_addr="$MASTER_ADDR" \\\n'
        '                --master_port="$MASTER_PORT" \\\n'
        f"                {script_path}\n"
        "---\n"
        "apiVersion: v1\n"
        "kind: Service\n"
        "metadata:\n"
        f"  name: {job_name}\n"
        f"  namespace: {namespace}\n"
        "spec:\n"
        "  clusterIP: None\n"
        "  selector:\n"
        "    app.kubernetes.io/name: buildml-torchrun-ddp\n"
        f"    job-name: {job_name}\n"
        "  ports:\n"
        "    - name: rdzv\n"
        f"      port: {master_port}\n"
        f"      targetPort: {master_port}\n"
    )
    if include_configmap:
        body += (
            "---\n"
            "apiVersion: v1\n"
            "kind: ConfigMap\n"
            "metadata:\n"
            f"  name: {cm_name}\n"
            f"  namespace: {namespace}\n"
            "  labels:\n"
            "    app.kubernetes.io/name: buildml-torchrun-ddp\n"
            "    app.kubernetes.io/part-of: buildml\n"
            "data:\n"
            f'  PET_NNODES: "{nnodes}"\n'
            f'  PET_NPROC_PER_NODE: "{nproc_per_node}"\n'
            f'  BUILDML_SCRIPT: "{script_path}"\n'
            '  BUILDML_NOTE: "Template ConfigMap — not a live control plane."\n'
        )
    return body


def write_torchrun_ddp_job(path: str | Path, **kwargs: Any) -> K8sJobRenderResult:
    """Render and write a torchrun DDP Job YAML to ``path``."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    yaml_text = render_torchrun_ddp_job(**kwargs)
    destination.write_text(yaml_text, encoding="utf-8")
    return K8sJobRenderResult(
        yaml_text=yaml_text,
        path=destination,
        nnodes=int(kwargs.get("nnodes", 2)),
        nproc_per_node=int(kwargs.get("nproc_per_node", 2)),
        disclosures=(
            "Wrote Kubernetes Job+Service"
            + ("+ConfigMap" if kwargs.get("include_configmap", True) else "")
            + f" YAML to {destination}.",
        ),
        limitations=(
            "Example template only — not live multi-cluster orchestration.",
            "Operator must provide GPU nodes, networking, shared data, and RBAC.",
            "Not a Helm chart product or managed training cloud.",
        ),
        meta={
            "job_name": kwargs.get("job_name", "buildml-torchrun-ddp"),
            "namespace": kwargs.get("namespace", "default"),
            "include_configmap": kwargs.get("include_configmap", True),
            "gpu_limit": kwargs.get("gpu_limit", 1),
        },
    )


def render_serve_deployment(
    *,
    name: str = "buildml-serve",
    namespace: str = "default",
    image: str = "python:3.12-slim",
    replicas: int = 1,
    port: int = 8080,
    cpu_request: str = "1",
    memory_request: str = "2Gi",
    gpu_limit: int | None = None,
    service_account: str | None = None,
    bundle_path: str = "/models/bundle",
    kind: str = "pipeline",
) -> str:
    """Render a serve Deployment + Service template (not a control plane)."""
    _validate_dns_label(name, field_name="name")
    if replicas < 1:
        raise ValidationError("replicas must be >= 1")
    sa_line = f"      serviceAccountName: {service_account}\n" if service_account else ""
    gpu_lim = f"\n              nvidia.com/gpu: {int(gpu_limit)}" if gpu_limit else ""
    return (
        "# Generated by buildml.dl.k8s.render_serve_deployment\n"
        "# Honesty: template only — not live multi-cluster / managed IAM.\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        f"  name: {name}\n"
        f"  namespace: {namespace}\n"
        "  labels:\n"
        "    app.kubernetes.io/name: buildml-serve\n"
        "    app.kubernetes.io/part-of: buildml\n"
        "spec:\n"
        f"  replicas: {replicas}\n"
        "  selector:\n"
        "    matchLabels:\n"
        "      app.kubernetes.io/name: buildml-serve\n"
        "  template:\n"
        "    metadata:\n"
        "      labels:\n"
        "        app.kubernetes.io/name: buildml-serve\n"
        "    spec:\n"
        f"{sa_line}"
        "      containers:\n"
        "        - name: serve\n"
        f"          image: {image}\n"
        "          args:\n"
        '            - "--bundle"\n'
        f'            - "{bundle_path}"\n'
        '            - "--kind"\n'
        f'            - "{kind}"\n'
        '            - "--host"\n'
        '            - "0.0.0.0"\n'
        '            - "--port"\n'
        f'            - "{port}"\n'
        "          ports:\n"
        "            - name: http\n"
        f"              containerPort: {port}\n"
        "          resources:\n"
        "            requests:\n"
        f'              cpu: "{cpu_request}"\n'
        f'              memory: "{memory_request}"\n'
        "            limits:\n"
        f'              memory: "{memory_request}"{gpu_lim}\n'
        "          readinessProbe:\n"
        "            httpGet:\n"
        "              path: /health\n"
        "              port: http\n"
        "            initialDelaySeconds: 5\n"
        "            periodSeconds: 10\n"
        "          livenessProbe:\n"
        "            httpGet:\n"
        "              path: /health\n"
        "              port: http\n"
        "            initialDelaySeconds: 15\n"
        "            periodSeconds: 20\n"
        "---\n"
        "apiVersion: v1\n"
        "kind: Service\n"
        "metadata:\n"
        f"  name: {name}\n"
        f"  namespace: {namespace}\n"
        "spec:\n"
        "  type: ClusterIP\n"
        "  selector:\n"
        "    app.kubernetes.io/name: buildml-serve\n"
        "  ports:\n"
        "    - name: http\n"
        f"      port: {port}\n"
        "      targetPort: http\n"
    )


def write_serve_deployment(path: str | Path, **kwargs: Any) -> K8sJobRenderResult:
    """Write a serve Deployment+Service YAML template."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    yaml_text = render_serve_deployment(**kwargs)
    destination.write_text(yaml_text, encoding="utf-8")
    return K8sJobRenderResult(
        yaml_text=yaml_text,
        path=destination,
        nnodes=int(kwargs.get("replicas", 1)),
        nproc_per_node=1,
        disclosures=(f"Wrote serve Deployment+Service YAML to {destination}.",),
        limitations=(
            "Example template only — not live multi-cluster orchestration.",
            "Not a managed IAM / Ingress / cert product.",
        ),
        meta={
            "name": kwargs.get("name", "buildml-serve"),
            "namespace": kwargs.get("namespace", "default"),
        },
    )
