"""TorchServe packaging and TensorRT export-plan helpers (library recipes).

These helpers write on-disk layouts and validation reports. They do **not**
run a managed cloud, operate a TorchServe cluster, or ship a TensorRT runtime.
"""

from __future__ import annotations

import json
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from buildml.core.errors import ValidationError

PackKind = Literal["torchserve", "tensorrt_plan"]

TORCHSERVE_COMPOSE_EXAMPLE = (
    Path(__file__).resolve().parents[2]
    / "deploy"
    / "torchserve"
    / "docker-compose.example.yml"
)


@dataclass(slots=True)
class PackagingResult:
    """Outcome of a packaging / export-plan helper."""

    kind: PackKind
    path: Path
    files: tuple[str, ...]
    disclosures: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    warnings: tuple[str, ...] = ()
    meta: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "path": str(self.path),
            "files": list(self.files),
            "disclosures": list(self.disclosures),
            "limitations": list(self.limitations),
            "warnings": list(self.warnings),
            "meta": dict(self.meta),
        }


_TORCHSERVE_HANDLER = '''\
"""Minimal TorchServe handler for a TorchScript BuildML export.

Install torchserve separately. This file is generated by BuildML packaging
helpers — it is not a managed cloud product.
"""

from __future__ import annotations

import json
from typing import Any

import torch
from ts.torch_handler.base_handler import BaseHandler


class BuildMLTorchScriptHandler(BaseHandler):
    def initialize(self, context: Any) -> None:
        properties = context.system_properties
        model_dir = properties.get("model_dir")
        self.device = torch.device(
            "cuda:" + str(properties.get("gpu_id"))
            if torch.cuda.is_available() and properties.get("gpu_id") is not None
            else "cpu"
        )
        self.model = torch.jit.load(f"{model_dir}/model.pt", map_location=self.device)
        self.model.eval()
        self.initialized = True

    def preprocess(self, data: list[Any]) -> torch.Tensor:
        body = data[0].get("body") or data[0].get("data")
        if isinstance(body, (bytes, bytearray)):
            body = body.decode("utf-8")
        if isinstance(body, str):
            payload = json.loads(body)
        else:
            payload = body
        rows = payload.get("instances") or payload.get("inputs")
        if rows is None:
            raise ValueError('JSON body must include "instances" or "inputs"')
        return torch.tensor(rows, dtype=torch.float32, device=self.device)

    def inference(self, data: torch.Tensor, *args: Any, **kwargs: Any) -> torch.Tensor:
        with torch.no_grad():
            return self.model(data)

    def postprocess(self, data: torch.Tensor) -> list[Any]:
        return data.detach().cpu().tolist()
'''


def pack_torchserve_model(
    torchscript_path: str | Path,
    output_dir: str | Path,
    *,
    model_name: str = "buildml_model",
    handler_name: str = "handler.py",
) -> PackagingResult:
    """Pack a TorchScript file into a TorchServe-ready model directory.

    Writes ``model.pt``, ``handler.py``, ``config.properties``, and
    ``manifest.json``. Optionally reminds the operator to run
    ``torch-model-archiver`` if installed — BuildML does not bundle TorchServe.
    """
    src = Path(torchscript_path)
    if not src.is_file():
        raise ValidationError(f"TorchScript file not found: {src}")
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    model_pt = root / "model.pt"
    model_pt.write_bytes(src.read_bytes())
    handler = root / handler_name
    handler.write_text(_TORCHSERVE_HANDLER, encoding="utf-8")
    config = root / "config.properties"
    config.write_text(
        textwrap.dedent(
            f"""\
            inference_address=http://127.0.0.1:8080
            management_address=http://127.0.0.1:8081
            metrics_address=http://127.0.0.1:8082
            model_store={root.resolve().as_posix()}
            load_models={model_name}.mar
            """
        ),
        encoding="utf-8",
    )
    manifest = {
        "model": {
            "modelName": model_name,
            "handler": handler_name,
            "modelFile": "model.pt",
            "modelVersion": "1.0",
            "runtime": "python",
        },
        "buildml": {
            "packager": "buildml.dl.packaging.pack_torchserve_model",
            "honesty": (
                "Directory layout for TorchServe; not a managed cloud. "
                "Run torch-model-archiver + torchserve yourself."
            ),
        },
    }
    manifest_path = root / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    archive_hint = root / "ARCHIVE.txt"
    archive_hint.write_text(
        textwrap.dedent(
            f"""\
            # Optional: create a .mar with the TorchServe archiver (separate install)
            torch-model-archiver --model-name {model_name} --version 1.0 \\
              --serialized-file {model_pt.name} --handler {handler_name} \\
              --export-path . --force
            torchserve --start --model-store . --models {model_name}.mar \\
              --ts-config config.properties
            """
        ),
        encoding="utf-8",
    )
    files = (
        model_pt.name,
        handler.name,
        config.name,
        manifest_path.name,
        archive_hint.name,
    )
    return PackagingResult(
        kind="torchserve",
        path=root,
        files=files,
        disclosures=(
            f"TorchServe model directory written to {root}.",
            "Includes TorchScript copy, handler, config.properties, manifest.json.",
        ),
        limitations=(
            "BuildML does not install or run TorchServe / torch-model-archiver.",
            "Not a managed inference cloud or multi-cluster product.",
            "Validate the handler against your TorchServe major version.",
        ),
        warnings=(),
        meta={"model_name": model_name, "source": str(src)},
    )


def prepare_tensorrt_export_plan(
    onnx_path: str | Path,
    output_dir: str | Path,
    *,
    engine_name: str = "model.engine",
    fp16: bool = True,
    workspace_mib: int = 1024,
) -> PackagingResult:
    """Validate an ONNX artifact and write a TensorRT ``trtexec`` recipe.

    Does **not** invoke TensorRT. Operators run ``trtexec`` (or their platform
    builder) themselves.
    """
    onnx_file = Path(onnx_path)
    if not onnx_file.is_file():
        raise ValidationError(f"ONNX file not found: {onnx_file}")
    # Soft validate with onnx checker when available.
    warnings: list[str] = []
    try:
        import onnx as onnx_lib  # type: ignore[import-untyped]

        model = onnx_lib.load(str(onnx_file))
        onnx_lib.checker.check_model(model)
    except ImportError:
        warnings.append(
            "onnx package not installed; skipped checker "
            "(pip install 'buildml[onnx]')."
        )
    except Exception as exc:  # noqa: BLE001
        warnings.append(f"onnx.checker reported issues: {exc}")

    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    plan = {
        "format": "tensorrt_export_plan",
        "onnx_path": str(onnx_file.resolve()),
        "engine_name": engine_name,
        "fp16": bool(fp16),
        "workspace_mib": int(workspace_mib),
        "trtexec_example": (
            f"trtexec --onnx={onnx_file.name} --saveEngine={engine_name}"
            + (" --fp16" if fp16 else "")
            + f" --memPoolSize=workspace:{int(workspace_mib)}MiB"
        ),
        "honesty": (
            "BuildML writes a plan/recipe only. TensorRT runtime, GPU drivers, "
            "and engine builds are operator-owned — not a BuildML cloud product."
        ),
    }
    plan_path = root / "tensorrt_plan.json"
    plan_path.write_text(json.dumps(plan, indent=2), encoding="utf-8")
    readme = root / "TENSORRT.md"
    readme.write_text(
        textwrap.dedent(
            f"""\
            # TensorRT export plan (BuildML)

            ONNX source: `{onnx_file}`

            Example (NVIDIA `trtexec`, installed separately):

            ```
            {plan["trtexec_example"]}
            ```

            BuildML does **not** ship TensorRT, build engines, or host a
            managed inference platform. Validate precision/latency on your hardware.
            """
        ),
        encoding="utf-8",
    )
    # Copy ONNX next to the plan for a self-contained folder.
    dest_onnx = root / onnx_file.name
    if dest_onnx.resolve() != onnx_file.resolve():
        dest_onnx.write_bytes(onnx_file.read_bytes())
    files = (plan_path.name, readme.name, dest_onnx.name)
    return PackagingResult(
        kind="tensorrt_plan",
        path=root,
        files=files,
        disclosures=(
            f"TensorRT export plan written under {root}.",
            "ONNX validated when the onnx package is available.",
        ),
        limitations=(
            "No TensorRT engine is built by BuildML.",
            "Not a TensorRT-as-a-platform / managed cloud product.",
        ),
        warnings=tuple(warnings),
        meta={"onnx": str(onnx_file), "engine_name": engine_name, "fp16": fp16},
    )
